dynamix/force-app/main/default/objects/Opportunity/fields/EOI_CA__c.field-meta.xml
<CustomField>
    <fullName>EOI_CA__c</fullName>
    <label>EOI/CA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/EOI_CA_Form_Sent_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>EOI_CA_Form_Sent_Date_Time__c</fullName>
    <label>EOI/CA Form Sent Date&amp;Time</label>
    <type>DateTime</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/EOI_CA_Form_Submission_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>EOI_CA_Form_Submission_Date_and_Time__c</fullName>
    <label>EOI/CA Form Submission Date and Time</label>
    <type>DateTime</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/EOI_CA_stage__c.field-meta.xml
<CustomField>
    <fullName>EOI_CA_stage__c</fullName>
    <label>EOI/CA stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/classes/EOICALinkExpirationController.cls
public class EOICALinkExpirationController{
    
    @AuraEnabled
    public static String EOICALinkExpirationMethod(String recordId){
        string status = '';
       
        Opportunity  thisOpportunity =  [SELECT ID,EOI_CA_Form_Sent_Date_Time__c,EOI_CA_Form_Submission_Date_and_Time__c,EOI_CA_stage__c, EOI_CA__c
                                         FROM Opportunity
                                         WHERE ID =: recordId
                                         LIMIT 1];
        
        system.debug('thisOpportunity------>'+thisOpportunity.EOI_CA_Form_Sent_Date_Time__c);
      
        if(thisOpportunity.EOI_CA_Form_Submission_Date_and_Time__c != null)
        {
            status = thisOpportunity.EOI_CA__c+' Form  is Submitted.';
        }
        else if(thisOpportunity.EOI_CA_Form_Sent_Date_Time__c != null )
        {
            if(thisOpportunity.EOI_CA_Form_Sent_Date_Time__c.addHours(24) < system.now())
            { 
                System.debug('true');
                status = 'Expired';
            }
            else
            {
                System.debug('false');
                status = thisOpportunity.EOI_CA__c+' Form Link is Activated.';
            }
        }
        return status;
    }
}