dynamix/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit No.</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/Suggested_Property__c.object-meta.xml
<CustomObject>
    <label>Suggested Property</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Suggestion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suggested Property</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Suggested Property</relationshipLabel>
    <relationshipName>Suggested_Property</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Short Listed</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Send for Cost-Sheet Approval</fullName>
            </value>
            <value>
                <fullName>Custom Payment Plan Approved</fullName>
            </value>
            <value>
                <fullName>Custom Payment Plan Reject</fullName>
            </value>
            <value>
                <fullName>Send for Cost-Sheet Discount Approval</fullName>
            </value>
            <value>
                <fullName>Discount Approved</fullName>
            </value>
            <value>
                <fullName>Discount Reject</fullName>
            </value>
            <value>
                <fullName>Send for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Confirmed Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Suggested Property</relationshipLabel>
    <relationshipName>Suggested_Property</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/classes/SuggestedPropertyTrigger_Test.cls
@isTest
public class SuggestedPropertyTrigger_Test 
{   
    @isTest
    public static void statusChangedToShortListed()
    {
        
        Property__c prop1 = new Property__c(Name='Testing property1',Floor__c='1');
        insert prop1;
        
        Account accountObject = new Account();
        accountObject.Name= 'Test Account';
        insert accountObject; 
        
        Opportunity opp1 = new Opportunity(Name='Opp 1', CloseDate=Date.today()+45,stageName='Site Visit', AccountId = accountObject.Id);
        insert opp1;
        
        Suggested_Property__c sp1 = new Suggested_Property__c(Opportunity__c=opp1.id,Status__c='Unavailable',Unit__c=prop1.id);
        insert sp1;
        Suggested_Property__c sp2 = new Suggested_Property__c(Opportunity__c=opp1.id,Status__c='Unavailable',Unit__c=prop1.id);
        insert sp2;
        Suggested_Property__c sp3 = new Suggested_Property__c(Opportunity__c=opp1.id,Status__c='Unavailable',Unit__c=prop1.id);
        insert sp3;
        
        Test.startTest();
           sp3.Status__c='Short Listed';
           update sp3;
        Test.stopTest();
    }
    
    @isTest
    public static void statusChangedToReserved()
    {
        Property__c prop1 = new Property__c(Name='Testing property1',Floor__c='1');
        insert prop1;
        
        Account accountObject = new Account();
        accountObject.Name= 'Test Account';
        insert accountObject;
        
        Opportunity opp1 = new Opportunity(Name='Opp 1', CloseDate=Date.today()+45,stageName='Site Visit',AccountId = accountObject.Id);
        insert opp1;
        
        Suggested_Property__c sp1 = new Suggested_Property__c(Opportunity__c=opp1.id,Status__c='Short Listed',Unit__c=prop1.id);
        insert sp1;
        Suggested_Property__c sp2 = new Suggested_Property__c(Opportunity__c=opp1.id,Status__c='Short Listed',Unit__c=prop1.id);
        insert sp2;
        Suggested_Property__c sp3 = new Suggested_Property__c(Opportunity__c=opp1.id,Status__c='Short Listed',Unit__c=prop1.id);
        insert sp3;
        
        Test.startTest();
           sp3.Status__c = 'Reserved';
           update sp3;
        Test.stopTest();
    }
    
    @isTest
    public static void statusChangedToInProgress()
    {
        Property__c prop1 = new Property__c(Name='Testing property1',Floor__c='1');
        insert prop1;
        
        Account accountObject = new Account();
        accountObject.Name= 'Test Account';
        insert accountObject;
        
        Opportunity opp1 = new Opportunity(Name='Opp 1', CloseDate=Date.today()+45,stageName='Site Visit',AccountId = accountObject.Id);
        insert opp1;
        
        Suggested_Property__c sp1 = new Suggested_Property__c(Opportunity__c=opp1.id,Status__c='Short Listed',Unit__c=prop1.id);
        insert sp1;
        Suggested_Property__c sp2 = new Suggested_Property__c(Opportunity__c=opp1.id,Status__c='Short Listed',Unit__c=prop1.id);
        insert sp2;
        Suggested_Property__c sp3 = new Suggested_Property__c(Opportunity__c=opp1.id,Status__c='Short Listed',Unit__c=prop1.id);
        insert sp3;
        
        Test.startTest();
           sp3.Status__c = 'In Progress';
          // update sp3;
        Test.stopTest();
    }
    
    @isTest
    public static void statusChangedToBooked()
    {
        Property__c prop1 = new Property__c(Name='Testing property1',Floor__c='1');
        insert prop1;
        
        Account accountObject = new Account();
        accountObject.Name= 'Test Account';
        insert accountObject; 
        
        Opportunity opp1 = new Opportunity(Name='Opp 1', CloseDate=Date.today()+45,stageName='Site Visit',AccountId = accountObject.Id);
        insert opp1;
        
        Suggested_Property__c sp1 = new Suggested_Property__c(Opportunity__c=opp1.id,Status__c='Short Listed',Unit__c=prop1.id);
        insert sp1;
        Suggested_Property__c sp2 = new Suggested_Property__c(Opportunity__c=opp1.id,Status__c='Short Listed',Unit__c=prop1.id);
        insert sp2;
        Suggested_Property__c sp3 = new Suggested_Property__c(Opportunity__c=opp1.id,Status__c='Short Listed',Unit__c=prop1.id);
        insert sp3;
        Suggested_Property__c sp4 = new Suggested_Property__c(Opportunity__c=opp1.id,Status__c='Unavailable',Unit__c=prop1.id);
        insert sp4;
        Test.startTest();
           sp3.Status__c = 'Booked';
           update sp3;
        Test.stopTest();
    }
}