dynamix/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>Pay-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Receipt_No__c.field-meta.xml
<CustomField>
    <fullName>Receipt_No__c</fullName>
    <description>RA0000001</description>
    <label>Receipt No:</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/ReceiptNumber__c/ReceiptNumber__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payment Receipt Number</label>
</CustomObject>

dynamix/force-app/main/default/objects/ReceiptNumber__c/fields/LastReceiptNumber__c.field-meta.xml
<CustomField>
    <fullName>LastReceiptNumber__c</fullName>
    <defaultValue>40000</defaultValue>
    <label>LastReceiptNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/classes/PaymentTriggerHandler.cls
public class PaymentTriggerHandler {
    public static void updateReceiptNumber(List<Payment__c> payList){
        if(!payList.isEmpty()){
            List<Payment__c> paymentToUpdateList = new List<Payment__c>();
            ReceiptNumber__c ct = ReceiptNumber__c.getOrgDefaults();
            for(Payment__c pay:payList){
                if(pay.Receipt_No__c == null){
                    Payment__c payToUpdate = new Payment__c();
                    payToUpdate.Id = pay.Id;
                    payToUpdate.Receipt_No__c = String.valueOf(ct.LastReceiptNumber__c.setscale(0));
                    ct.LastReceiptNumber__c += 1;
                    update ct;
                    paymentToUpdateList.add(payToUpdate);
                }
            }
            if(!paymentToUpdateList.isEmpty()){
                update paymentToUpdateList;
            }
        }
    }
}