dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Budgets__c.field-meta.xml
<CustomField>
    <fullName>Budgets__c</fullName>
    <label>Budgets</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Budget</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Project_Carpet_Area__c</fullName>
    <label>Project Carpet Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Carpet_Area</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <label>Project Email</label>
    <type>Email</type>
</CustomField>

dynamix/force-app/main/default/globalValueSets/Budget.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Under 75 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 0.7 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.7  - 0.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.8  - 0.9 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.9  - 1 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 - 1.1 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 - 1.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.2 - 1.3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.3 - 1.4 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.4 - 1.6 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.6 - 1.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.8 - 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2 - 2.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.2 - 2.4 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.4 - 2.6 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.6 - 2.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.8 - 3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3 Cr &amp; Above</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2 – 2.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.2 – 2.5 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.5 – 2.75 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.75 – 3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3 – 3.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3.2 – 3.5 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3.5 – 3.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>4 Cr and Above</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 1.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.8 – 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 – 1.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>above 3.5 crs</fullName>
    </customValue>
    <masterLabel>Budget</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/globalValueSets/Carpet_Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>475 - 1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>600 - 2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>900 - 3 BHk</fullName>
    </customValue>
    <customValue>
        <fullName>375 - 400 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>400 – 450 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>450 – 500 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>500 – 550 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>550 – 600 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>600 – 650 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>650 – 700 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>700 – 800 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>700 – 750 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>750 sq.ft. and Above</fullName>
    </customValue>
    <customValue>
        <fullName>750 – 800 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>750 – 850 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>800 – 900 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>850 -- 900 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>900 – 1000 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1000 – 1100 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1100 – 1200 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1200 sq.ft. &amp; Above</fullName>
    </customValue>
    <customValue>
        <fullName>1200 – 1300 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1300 sq.ft and above</fullName>
    </customValue>
    <masterLabel>Carpet Area</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/globalValueSets/Configuration.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Studio</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK (G)</fullName>
    </customValue>
    <customValue>
        <fullName>1 BHK Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK Jodi</fullName>
    </customValue>
    <masterLabel>Configuration</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/classes/ProjectTriggerHandler_Test.cls
@isTest
public class ProjectTriggerHandler_Test {
    @isTest  
    public static void generateCIFFormLink_Method(){
        Project__c projectObject = new Project__c();
        projectObject.Name = 'Test Project';
        projectObject.Project_Email__c= 'nishi@manras.com';
        projectObject.Budgets__c = 'above 3.5 crs';
        projectObject.Configuration__c = '1 BHK;2.5 BHK';
        projectObject.Project_Carpet_Area__c = '475 - 1 BHK;600 - 2 BHK;900 - 3 BHk	';
        insert projectObject;
    }
}