dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/CA__c.field-meta.xml
<CustomField>
    <fullName>CA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CA</label>
    <type>Checkbox</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Launch_CA_Period_s_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Launch_CA_Period_s_End_Date__c</fullName>
    <label>Launch CA Period&apos;s End Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Launch_CA_Period_s_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Launch_CA_Period_s_Start_Date__c</fullName>
    <label>Launch CA Period&apos;s Start Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Launch_EOI_Period_s_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Launch_EOI_Period_s_End_Date__c</fullName>
    <label>Launch EOI Period&apos;s End Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Launch_EOI_Period_s_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Launch_EOI_Period_s_Start_Date__c</fullName>
    <label>Launch EOI Period&apos;s Start Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Minimum_amount_for_CA__c.field-meta.xml
<CustomField>
    <fullName>Minimum_amount_for_CA__c</fullName>
    <label>Minimum amount for CA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Minimum_amount_for_EOI__c.field-meta.xml
<CustomField>
    <fullName>Minimum_amount_for_EOI__c</fullName>
    <label>Minimum amount for EOI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <label>Project Email</label>
    <type>Email</type>
</CustomField>

dynamix/force-app/main/default/classes/BatchForActiveEOICA.cls
public class BatchForActiveEOICA implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([SELECT Id, Name,Launch_CA_Period_s_Start_Date__c,Launch_CA_Period_s_End_Date__c,Minimum_amount_for_CA__c,Project_Email__c,
                                         Launch_EOI_Period_s_Start_Date__c,Launch_EOI_Period_s_End_Date__c,Minimum_amount_for_EOI__c
                                         FROM Project__c WHERE Launch_EOI_Period_s_End_Date__c  <: System.today() OR Launch_CA_Period_s_End_Date__c <: System.today()
                                        OR  Launch_EOI_Period_s_Start_Date__c  =: System.today() OR Launch_CA_Period_s_Start_Date__c =: System.today()]);
    }
    
    public void execute(Database.BatchableContext bc, List<Project__c> projectList)
    {       
        System.debug('projectList'+projectList);
        List<Project__c>  updateProjectList = New  List<Project__c> ();
        for(Project__c thisProject: projectList){
          Project__c Project = New Project__c();
            Project.id = thisProject.id;
            if(thisProject.Launch_EOI_Period_s_End_Date__c < system.today())
            {
                Project.EOI__c = false;
            }
            if(thisProject.Launch_CA_Period_s_End_Date__c < system.today())
            {
                Project.CA__c = false;
            }
            if(thisProject.Launch_EOI_Period_s_Start_Date__c == system.today())
            {
                Project.EOI__c = true;
            }
            if(thisProject.Launch_CA_Period_s_Start_Date__c == system.today())
            {
                Project.CA__c = true;
            }
            updateProjectList.add(Project);
        }
        if(!updateProjectList.isEmpty())
        {
            update updateProjectList;
        }
    }
        
        
      
    
    public void finish(Database.BatchableContext bc)
    {
    }
}