dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/Project_Add_On_Charges__c.object-meta.xml
<CustomObject>
    <label>Project Add On Charges</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Add On Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Add_On_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/recordTypes/Charges.recordType-meta.xml
<RecordType>
    <fullName>Charges</fullName>
    <active>true</active>
    <label>Charges</label>
</RecordType>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/recordTypes/Parking.recordType-meta.xml
<RecordType>
    <fullName>Parking</fullName>
    <active>true</active>
    <label>Parking</label>
</RecordType>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Pricing_Plan_Detail__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Plan_Detail__c</fullName>
    <label>Pricing Plan Detail</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/classes/GetCharges_Test.cls
@isTest
public class GetCharges_Test {
	 @isTest public static void GetChargesMethod()
     {
         Property__c propertyObject = new Property__c();
         propertyObject.Pricing_Plan_Detail__c = '{"components":[{"type":"Charges","pricePerSQFT":null,"priceLumpSum":15000.00,"name":"Floor Rise","gst":"Standard"},{"type":"Charges","pricePerSQFT":null,"priceLumpSum":300000.00,"name":"Club Membership Charges","gst":"Standard"},{"type":"Charges","pricePerSQFT":null,"priceLumpSum":4000000.00,"name":"Basic Price","gst":"Standard"},{"type":"Charges","pricePerSQFT":null,"priceLumpSum":45000.00,"name":"Registration","gst":"Standard"},{"type":"Parking","pricePerSQFT":null,"priceLumpSum":95000.00,"name":"Basement Parking","gst":"Standard"},{"type":"Preferred Location","pricePerSQFT":null,"priceLumpSum":175000.00,"name":"Garden view","gst":"Standard"},{"type":"Preferred Location","pricePerSQFT":null,"priceLumpSum":125000.00,"name":"Podium View","gst":"Standard"}]}';
	     insert propertyObject;
         
         Project__c projectObject = new Project__c();
         projectObject.Name = 'Test Project ';
         insert projectObject;
         
         Project_Add_On_Charges__c projectAddOn = new Project_Add_On_Charges__c();
         projectAddOn.Name = 'Test Add On';
         projectAddOn.Project__c = projectObject.Id;
         insert projectAddOn;
         
         GetCharges.Requests request = new GetCharges.Requests();
         request.chargeName = 'Test';
         request.chargeType = 'Preferred Location';
         request.propertyId = propertyObject.Id;
         
         List<GetCharges.Requests> reqList = new List<GetCharges.Requests>();
         reqList.add(request);
         GetCharges.execute(reqList);
     }
}