dynamix/force-app/main/default/objects/ContentVersion/fields/BookingId__c.field-meta.xml
<CustomField>
    <fullName>BookingId__c</fullName>
    <description>BookingId For Backend.</description>
    <label>BookingId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/classes/FileOrganiserHandler.cls
public with sharing class FileOrganiserHandler {
    
    @AuraEnabled(cacheable=true)
    public static List<FileWrap> getFiles(Id recordId){
        
        List<FileWrap> filesLst = new List<FileWrap>();

        for(ContentDocumentLink cDL: [SELECT Id, ContentDocumentId, ContentDocument.Title, ContentDocument.ContentModifiedDate, 
                                        ContentDocument.LatestPublishedVersion.Document_Type__c, ContentDocument.LatestPublishedVersionId,
                                        ContentDocument.LatestPublishedVersion.ContentModifiedBy.Name
                                        FROM ContentDocumentLink WHERE LinkedEntityId =: recordId]){
            
            FileWrap fWrap = new FileWrap();

            fWrap.id = cDL.ContentDocumentId;
            fWrap.title = cDL.ContentDocument.Title;
            fWrap.documentType = cDL.ContentDocument.LatestPublishedVersion.Document_Type__c;
            fWrap.uploadedBy = cDL.ContentDocument.LatestPublishedVersion.ContentModifiedBy.Name;
            fWrap.uploadedDate = cDL.ContentDocument.ContentModifiedDate;
            
            filesLst.add(fWrap);
        }

        return filesLst;                    
    }

    @AuraEnabled
    public static void updateFile(Id Temp ,Id recordId, String objType, String documentType){
        
        ContentVersion file = [SELECT Id, Title, SObjectType__c, Document_Type__c,BookingId__c 
                                FROM ContentVersion 
                                WHERE ContentDocumentId =: recordId
                                AND IsLatest = true];
        System.debug('file.BookingId__c'+Temp);
        System.debug('filec'+file.Id);
        file.SObjectType__c = objType;
        file.Document_Type__c = documentType;
        file.BookingId__c = Temp;
        update file;
    }

    public class FileWrap{

        @AuraEnabled
        public String id;

        @AuraEnabled
        public String title;

        @AuraEnabled
        public String documentType;

        @AuraEnabled
        public Datetime uploadedDate;

        @AuraEnabled
        public String uploadedBy;
    }
}