dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
            <value>
                <fullName>Annexures</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Annexures__c.field-meta.xml
<CustomField>
    <fullName>Annexures__c</fullName>
    <label>Annexures</label>
    <type>Url</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Terms_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_Conditions__c</fullName>
    <label>Terms &amp; Conditions</label>
    <type>Url</type>
</CustomField>

dynamix/force-app/main/default/classes/GeneratePublicURL.cls
public class GeneratePublicURL {
   public static void generatePublicLink(Id contentDocumentId){
       system.debug('Trigger Hit');
        /* Getting ContentVersion file using ContentDocument Id */
       if(contentDocumentID!=null){
           
       List<ContentVersion> cvlst = [SELECT Id, Title, Document_Type__c, SObjectType__c,FirstPublishLocationId FROM ContentVersion WHERE ContentDocumentId = :contentDocumentId order by CreatedDate desc limit 1 ];
       Set<Id> projectIds = new Set<Id>();
       Set<Id> propertyIds = new Set<Id>();
       
       system.debug('Cvlst>>' + cvlst);
       List<ContentDistribution> conDisList = new List<ContentDistribution>();
       for(ContentVersion cv:cvlst){
           system.debug('cv Found>>' + cv.Document_Type__c);
           if(cv.Document_Type__c=='Terms & Conditions' && cv.SObjectType__c == 'Project__c'){
               
               projectIds.add(cv.FirstPublishLocationId);
               system.debug('Proj Id>>' + projectIds);
               ContentDistribution conDis = new ContentDistribution();
               conDis.Name = cv.Title;
               conDis.ContentVersionId = cv.Id;
               conDis.PreferencesAllowViewInBrowser= true;
               conDisList.add(conDis);
           }
           if(cv.Document_Type__c=='Annexures' && cv.SObjectType__c=='Property__c'){
               propertyIds.add(cv.FirstPublishLocationId);
               system.debug('Prop Id>>' + propertyIds);
               
               ContentDistribution conDis = new ContentDistribution();
               conDis.Name = cv.Title;
               conDis.ContentVersionId = cv.Id;
               conDis.PreferencesAllowViewInBrowser= true;
               conDisList.add(conDis);
       }
           else{
               system.debug('Different File Uploaded');
           }
       }
       insert conDisList;
       List<ContentDistribution> ContentDistributionList =[SELECT id, Name , DistributionPublicUrl FROM ContentDistribution Where id In :conDisList];
       
       if (!projectIds.isEmpty()){
           Project__c proj = [Select Id, Name, Terms_Conditions__c From Project__c Where Id IN :projectIds];
           system.debug('Proj Found>>' + proj.Id);
           proj.Terms_Conditions__c = ContentDistributionList[0].DistributionPublicUrl;
           update proj;
       }
       
       if(!propertyIds.isEmpty()){
           Property__c prop = [Select Id, Name, Annexures__c From Property__c Where ID IN :propertyIds];
           system.debug('Proj Found>>' + prop.Id);
           prop.Annexures__c = ContentDistributionList[0].DistributionPublicUrl;
           update prop;
       }
       }
       
    }
}