dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
            <value>
                <fullName>Annexures</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Budgets__c.field-meta.xml
<CustomField>
    <fullName>Budgets__c</fullName>
    <label>Budgets</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Budget</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Project_Carpet_Area__c</fullName>
    <label>Project Carpet Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Carpet_Area</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Annexures__c.field-meta.xml
<CustomField>
    <fullName>Annexures__c</fullName>
    <label>Annexures</label>
    <type>Url</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Terms_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_Conditions__c</fullName>
    <label>Terms &amp; Conditions</label>
    <type>Url</type>
</CustomField>

dynamix/force-app/main/default/globalValueSets/Budget.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Under 75 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 0.7 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.7  - 0.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.8  - 0.9 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.9  - 1 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 - 1.1 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 - 1.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.2 - 1.3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.3 - 1.4 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.4 - 1.6 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.6 - 1.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.8 - 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2 - 2.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.2 - 2.4 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.4 - 2.6 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.6 - 2.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.8 - 3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3 Cr &amp; Above</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2 – 2.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.2 – 2.5 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.5 – 2.75 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.75 – 3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3 – 3.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3.2 – 3.5 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3.5 – 3.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>4 Cr and Above</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 1.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.8 – 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 – 1.2 Cr</fullName>
    </customValue>
    <masterLabel>Budget</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/globalValueSets/Carpet_Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>475 - 1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>600 - 2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>900 - 3 BHk</fullName>
    </customValue>
    <customValue>
        <fullName>375 - 400 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>400 – 450 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>450 – 500 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>500 – 550 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>550 – 600 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>600 – 650 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>650 – 700 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>700 – 800 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>700 – 750 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>750 sq.ft. and Above</fullName>
    </customValue>
    <customValue>
        <fullName>750 – 800 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>750 – 850 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>800 – 900 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>850 -- 900 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>900 – 1000 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1000 – 1100 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1100 – 1200 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1200 sq.ft. &amp; Above</fullName>
    </customValue>
    <customValue>
        <fullName>1200 – 1300 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1300 sq.ft and above</fullName>
    </customValue>
    <masterLabel>Carpet Area</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/globalValueSets/Configuration.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Studio</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK (G)</fullName>
    </customValue>
    <customValue>
        <fullName>1 BHK Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK Jodi</fullName>
    </customValue>
    <masterLabel>Configuration</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/classes/GeneratePublicURLTest.cls
@isTest
private class GeneratePublicURLTest {

    @isTest
    static void testGeneratePublicLinkTC() {
        // Create test data - ContentDocument, ContentVersion, and Project__c records
        List<ContentVersion> cvList = new List<ContentVersion>();
        Project__c testProject = new Project__c();
        testProject.Name = 'Test Project';
        testProject.Budgets__c = 'Under 75 lakhs';
        testProject.Configuration__c = '1 BHK';
        testProject.Project_Carpet_Area__c = '475 - 1 BHK';
        insert testProject;
        ContentVersion testContentVersion = new ContentVersion();
        testContentVersion.Title = 'Test Document';
        testContentVersion.Document_Type__c = 'Terms & Conditions';
        testContentVersion.SObjectType__c = 'Project__c';
        testContentVersion.PathOnClient = 'Test Path';
        testContentVersion.VersionData = Blob.valueof('Testdata');
        testContentVersion.FirstPublishLocationId = testProject.Id;
        insert testContentVersion;
        cvList.add(testContentVersion);

        testProject.Terms_Conditions__c = null; // Ensure the field is initially empty

        Test.startTest();
        GeneratePublicURL.generatePublicLink(testContentVersion.ContentDocumentId);
        Test.stopTest();

        testProject = [SELECT Id, Terms_Conditions__c FROM Project__c WHERE Id = :testProject.Id LIMIT 1];
        System.assertNotEquals(null, testProject.Terms_Conditions__c, 'Public URL should be generated and stored in Terms_Conditions__c field');
    }
    
    @isTest
    static void testGeneratePublicLinkAnnexure() {
        List<ContentVersion> cvList = new List<ContentVersion>();
        
        Property__c testProperty = new Property__c();
        testProperty.Name = '1234';
        insert testProperty;
        
        ContentVersion testContentVersion = new ContentVersion();
        testContentVersion.Title = 'Test Document';
        testContentVersion.Document_Type__c = 'Annexures';
        testContentVersion.SObjectType__c = 'Property__c';
        testContentVersion.PathOnClient = 'Test Path';
        testContentVersion.VersionData = Blob.valueof('Testdata');
        testContentVersion.FirstPublishLocationId = testProperty.Id;
        insert testContentVersion;
        cvList.add(testContentVersion);
        
        testProperty.Annexures__c = null;
        
        Test.startTest();
        GeneratePublicURL.generatePublicLink(testContentVersion.ContentDocumentId);
        Test.stopTest();
        
        testProperty = [Select Id, Annexures__c From Property__c Where Id = : testProperty.Id LIMIT 1];
        System.assertNotEquals(null, testProperty.Annexures__c, 'Public URL should be generated and stored in Annexures__c field');

    }
    
    
}