dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
            <value>
                <fullName>Interest Waiver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/classes/GenerateInterestWvaveierLetter.cls
public class GenerateInterestWvaveierLetter{
     
     @InvocableMethod(label='Generate Interest Waiver Letter')
     public static List<String> execute(List<Requests> Requests){
     
        ContentVersion conVer;
        list<ContentDocumentLink> contentDocList = new list<ContentDocumentLink>();
        list<ContentVersion> ContentVersionList =new  list<ContentVersion>();
        String contentId='';
        list<Id> ContentDocId = new list<Id>();
        list<ContentDocumentLink> conDocList = new list<ContentDocumentLink>();
                   
        Payment_Milestones__c pm = [select id, name from Payment_Milestones__c where id=: Requests[0].paymentMilestoneId];
            
            PageReference ref =  page.InterestWaiverDoc;
            ref.getParameters().put('id',Requests[0].paymentMilestoneId);
            Blob body; 
            if(Test.isRunningTest()){
                body = Blob.valueOf('Interest Wavier Letter');
            }
            else{
                body = ref.getContent();
            }
            
                conVer =new ContentVersion(); 
                conVer.ContentLocation = 'S'; 
                conVer.PathOnClient = 'Interest Waiver' + '.pdf'; 
                conVer.Title = 'Interest Waiver'+' - '+pm.Name +'.pdf';
                conVer.VersionData = body;
                conVer.SObjectType__c = 'Payment_Milestones__c ';
                conVer.Document_Type__c = 'Interest Waiver';
                //conVer.ContentDocumentId=ContentDocId[0];
               // system.debug('test'+conVer);
                insert conVer;
                system.debug('test'+conVer);
                contentId = conVer.ContentDocumentId;
                
                // First get the Content Document Id from ContentVersion Object
        Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
        
        ContentDocumentLink conDocLink = New ContentDocumentLink();
        conDocLink.LinkedEntityId = Requests[0].paymentMilestoneId; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
        conDocLink.ContentDocumentId = conDoc;  //ContentDocumentId Id from ContentVersion
        conDocLink.shareType = 'V';
        
        insert conDocLink;
                  
            
            /*else
            {
                conVer = new ContentVersion();
                conVer.ContentLocation = 'S'; 
                conVer.PathOnClient = 'Interest Waiver' + '.pdf'; 
                conVer.Title = 'Interest Waiver' +' - '+ pm.Name +'.pdf';
                conVer.VersionData = body;
                conVer.SObjectType__c = 'Payment_Milestones__c ';
                conVer.Document_Type__c = 'Interest Waiver';
                conVer.isMajorVersion=false;
                Insert conVer;
                list<ContentVersion> conVerList= [SELECT ContentDocumentId,CreatedDate FROM ContentVersion WHERE Id =:conVer.Id ];
                If(conVerList.size()>0)
                {
                    for(ContentVersion con :conVerList)
                    {
                        ContentDocumentLink conDocLink = New ContentDocumentLink();
                        conDocLink.LinkedEntityId = Requests[0].paymentMilestoneId; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
                        conDocLink.ContentDocumentId = con.ContentDocumentId;  //ContentDocumentId Id from ContentVersion
                        conDocLink.shareType = 'V';
                        conDocList.add(conDocLink);
                    }
                }    
                insert conDocList;
                //contentId = conVerList[0].ContentDocumentId;
            }*/
            return new List<String>{contentId};
        
    }
             
     
      public class Requests {
      
        @InvocableVariable(label='Payment Milestone Id' required=true)
        public String paymentMilestoneId;
      }
     
    

}