dynamix/force-app/main/default/objects/Account/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>+1</fullName>
            </value>
            <value>
                <fullName>+7</fullName>
            </value>
            <value>
                <fullName>+20</fullName>
            </value>
            <value>
                <fullName>+27</fullName>
            </value>
            <value>
                <fullName>+30</fullName>
            </value>
            <value>
                <fullName>+31</fullName>
            </value>
            <value>
                <fullName>+32</fullName>
            </value>
            <value>
                <fullName>+33</fullName>
            </value>
            <value>
                <fullName>+34</fullName>
            </value>
            <value>
                <fullName>+36</fullName>
            </value>
            <value>
                <fullName>+39</fullName>
            </value>
            <value>
                <fullName>+40</fullName>
            </value>
            <value>
                <fullName>+41</fullName>
            </value>
            <value>
                <fullName>+43</fullName>
            </value>
            <value>
                <fullName>+44</fullName>
            </value>
            <value>
                <fullName>+45</fullName>
            </value>
            <value>
                <fullName>+46</fullName>
            </value>
            <value>
                <fullName>+47</fullName>
            </value>
            <value>
                <fullName>+48</fullName>
            </value>
            <value>
                <fullName>+49</fullName>
            </value>
            <value>
                <fullName>+51</fullName>
            </value>
            <value>
                <fullName>+52</fullName>
            </value>
            <value>
                <fullName>+53</fullName>
            </value>
            <value>
                <fullName>+54</fullName>
            </value>
            <value>
                <fullName>+55</fullName>
            </value>
            <value>
                <fullName>+56</fullName>
            </value>
            <value>
                <fullName>+57</fullName>
            </value>
            <value>
                <fullName>+58</fullName>
            </value>
            <value>
                <fullName>+60</fullName>
            </value>
            <value>
                <fullName>+61</fullName>
            </value>
            <value>
                <fullName>+91</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Account/fields/PAN_No__c.field-meta.xml
<CustomField>
    <fullName>PAN_No__c</fullName>
    <label>PAN No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Account/fields/Upload_PAN_Card__c.field-meta.xml
<CustomField>
    <fullName>Upload_PAN_Card__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Upload PAN Card</label>
    <type>Checkbox</type>
</CustomField>

dynamix/force-app/main/default/objects/Campaign/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Housing.com</fullName>
            </value>
            <value>
                <fullName>99 Acres</fullName>
            </value>
            <value>
                <fullName>Magic Bricks</fullName>
            </value>
            <value>
                <fullName>Common Floor</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Native</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Taboola</fullName>
            </value>
            <value>
                <fullName>Magicbrics</fullName>
            </value>
            <value>
                <fullName>99Acre</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Site Branding</fullName>
            </value>
            <value>
                <fullName>Inserts</fullName>
            </value>
            <value>
                <fullName>Bus Shelter</fullName>
            </value>
            <value>
                <fullName>IVR Call</fullName>
            </value>
            <value>
                <fullName>Exhibition/Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EN-{000000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Campaign.Source__c</field>
            <operation>equals</operation>
            <valueField>$Source.Enquiry_Source__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Enquiry Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>+1</fullName>
            </value>
            <value>
                <fullName>+7</fullName>
            </value>
            <value>
                <fullName>+20</fullName>
            </value>
            <value>
                <fullName>+27</fullName>
            </value>
            <value>
                <fullName>+30</fullName>
            </value>
            <value>
                <fullName>+31</fullName>
            </value>
            <value>
                <fullName>+32</fullName>
            </value>
            <value>
                <fullName>+33</fullName>
            </value>
            <value>
                <fullName>+34</fullName>
            </value>
            <value>
                <fullName>+35</fullName>
            </value>
            <value>
                <fullName>+36</fullName>
            </value>
            <value>
                <fullName>+39</fullName>
            </value>
            <value>
                <fullName>+40</fullName>
            </value>
            <value>
                <fullName>+41</fullName>
            </value>
            <value>
                <fullName>+43</fullName>
            </value>
            <value>
                <fullName>+44</fullName>
            </value>
            <value>
                <fullName>+45</fullName>
            </value>
            <value>
                <fullName>+46</fullName>
            </value>
            <value>
                <fullName>+47</fullName>
            </value>
            <value>
                <fullName>+48</fullName>
            </value>
            <value>
                <fullName>+49</fullName>
            </value>
            <value>
                <fullName>+51</fullName>
            </value>
            <value>
                <fullName>+52</fullName>
            </value>
            <value>
                <fullName>+53</fullName>
            </value>
            <value>
                <fullName>+54</fullName>
            </value>
            <value>
                <fullName>+55</fullName>
            </value>
            <value>
                <fullName>+56</fullName>
            </value>
            <value>
                <fullName>+57</fullName>
            </value>
            <value>
                <fullName>+58</fullName>
            </value>
            <value>
                <fullName>+60</fullName>
            </value>
            <value>
                <fullName>+91</fullName>
                <default>true</default>
                <label>+91</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Enquiry_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Source__c</fullName>
    <label>Enquiry Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Housing.com</fullName>
            </value>
            <value>
                <fullName>99 Acres</fullName>
            </value>
            <value>
                <fullName>Magic Bricks</fullName>
            </value>
            <value>
                <fullName>Common Floor</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Native</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>VDNB</fullName>
            </value>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Exhibition</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Rechurned Lead</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Magicbricks</fullName>
            </value>
            <value>
                <fullName>IVR Call</fullName>
            </value>
            <value>
                <fullName>Pre Sales</fullName>
            </value>
            <value>
                <fullName>Emailer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <label>Project Email</label>
    <type>Email</type>
</CustomField>

dynamix/force-app/main/default/classes/PicklistControllerTest.cls
@isTest
private class PicklistControllerTest {
    
    @isTest
    static void testGetValues() {
        List<String> result = picklistController.getValues('Option1;Option2;Option3');
        System.assertEquals(4, result.size()); // Including '--None--'
        System.assertEquals('--None--', result[0]);
        System.assertEquals('Option1', result[1]);
        System.assertEquals('Option2', result[2]);
        System.assertEquals('Option3', result[3]);
    }
    
    @isTest
    static void testRecordValues() {
        List<Enquiry__c> enquiryList = new List<Enquiry__c>();
        Profile pId = [select Id,Name From Profile Where Name = 'System Administrator' Limit 1];
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        User testUserRcd1 = new User();
        testUserRcd1.FirstName = 'Mayur1';
        testUserRcd1.LastName = 'Patel123';
        testUserRcd1.Email = 'mayur.patel@manras.com';
        testUserRcd1.Alias = 'MPatel';
        testUserRcd1.Username = uniqueUserName;
        testUserRcd1.ProfileId = pId.Id;
        testUserRcd1.EmailEncodingKey = 'UTF-8';
        testUserRcd1.Country = 'India';
        testUserRcd1.IsActive=true;
        testUserRcd1.LanguageLocaleKey='en_US';
        testUserRcd1.LocaleSidKey='en_US';
        testUserRcd1.TimeZoneSidKey='America/Los_Angeles';
        insert testUserRcd1;
        
        System.runAs(testUserRcd1){
            
            Id PersonRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
            
            Account accountObject = new Account();
            accountObject.FirstName = 'test';
            accountObject.LastName = 'Account';
            accountObject.BillingCountry = 'India';
            accountObject.Phone = '455546565';
            accountObject.RecordTypeId = PersonRecId;
            accountObject.PersonEmail = 'dynamix.project@gmail.com';
            accountObject.Aadhar_No__pc = '458785698547';
            accountObject.PAN_No__c = 'ABCTY1234D';
            accountObject.Aadhar_Uploaded__pc = true;
            accountObject.PAN_Card_Uploaded__pc = true;
            accountObject.Upload_PAN_Card__c=true;
            accountObject.PersonMobilePhone='12345678'; 
            try{
                insert accountObject;
            }
            catch(Exception e){
                System.debug('Exception:'+e);
            }            
            
            Project__c projectObject = new Project__c();
            projectObject.Name = 'Test Project';
            projectObject.Project_Email__c= 'mayur.patel@manras.com';
            insert projectObject;
            
            Campaign testCampRcd=new Campaign();
            testCampRcd.Name='test Campaign';
            testCampRcd.Project__c=projectObject.Id;
            testCampRcd.Source__c='Google';
            testCampRcd.StartDate=System.today();
            testCampRcd.EndDate=System.today()+15;
            testCampRcd.ActualCost=2500000;
            insert testCampRcd;
            
            Enquiry__c testEnqRcd=new Enquiry__c();
            testEnqRcd.Project__c=projectObject.Id;
            testEnqRcd.Contact_Person__c=accountObject.Id;
            testEnqRcd.Enquiry_Source__c='Google';
            testEnqRcd.Campaign__c=testCampRcd.Id;
            testEnqRcd.Country_Code__c='+91';
            testEnqRcd.Budget__c = 'None';
            testEnqRcd.Primary_Mobile_Number_Text__c='1234567890';
            testEnqRcd.OwnerId=testUserRcd1.Id;
            enquiryList.add(testEnqRcd);
            insert enquiryList;
            
            
            List<String> result = picklistController.getValues(testEnqRcd.Id);
           /* System.assertEquals(4, result.size());  
            System.assertEquals('None', result[0]);
            System.assertEquals('75 Lac	', result[1]);
            System.assertEquals('1.25 Cr', result[2]);
            System.assertEquals('₹1,000	', result[3]);*/
        }
    }
}