dynamix/force-app/main/default/objects/Account/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>+1</fullName>
            </value>
            <value>
                <fullName>+7</fullName>
            </value>
            <value>
                <fullName>+20</fullName>
            </value>
            <value>
                <fullName>+27</fullName>
            </value>
            <value>
                <fullName>+30</fullName>
            </value>
            <value>
                <fullName>+31</fullName>
            </value>
            <value>
                <fullName>+32</fullName>
            </value>
            <value>
                <fullName>+33</fullName>
            </value>
            <value>
                <fullName>+34</fullName>
            </value>
            <value>
                <fullName>+36</fullName>
            </value>
            <value>
                <fullName>+39</fullName>
            </value>
            <value>
                <fullName>+40</fullName>
            </value>
            <value>
                <fullName>+41</fullName>
            </value>
            <value>
                <fullName>+43</fullName>
            </value>
            <value>
                <fullName>+44</fullName>
            </value>
            <value>
                <fullName>+45</fullName>
            </value>
            <value>
                <fullName>+46</fullName>
            </value>
            <value>
                <fullName>+47</fullName>
            </value>
            <value>
                <fullName>+48</fullName>
            </value>
            <value>
                <fullName>+49</fullName>
            </value>
            <value>
                <fullName>+51</fullName>
            </value>
            <value>
                <fullName>+52</fullName>
            </value>
            <value>
                <fullName>+53</fullName>
            </value>
            <value>
                <fullName>+54</fullName>
            </value>
            <value>
                <fullName>+55</fullName>
            </value>
            <value>
                <fullName>+56</fullName>
            </value>
            <value>
                <fullName>+57</fullName>
            </value>
            <value>
                <fullName>+58</fullName>
            </value>
            <value>
                <fullName>+60</fullName>
            </value>
            <value>
                <fullName>+61</fullName>
            </value>
            <value>
                <fullName>+91</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EN-{000000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>Jodi</fullName>
            </value>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>1.5 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>2.5 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK (G)</fullName>
            </value>
            <value>
                <fullName>1 BHK Jodi</fullName>
            </value>
            <value>
                <fullName>2 BHK Jodi</fullName>
            </value>
            <value>
                <fullName>3 BHK Jodi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Enquiry Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>+1</fullName>
            </value>
            <value>
                <fullName>+7</fullName>
            </value>
            <value>
                <fullName>+20</fullName>
            </value>
            <value>
                <fullName>+27</fullName>
            </value>
            <value>
                <fullName>+30</fullName>
            </value>
            <value>
                <fullName>+31</fullName>
            </value>
            <value>
                <fullName>+32</fullName>
            </value>
            <value>
                <fullName>+33</fullName>
            </value>
            <value>
                <fullName>+34</fullName>
            </value>
            <value>
                <fullName>+35</fullName>
            </value>
            <value>
                <fullName>+36</fullName>
            </value>
            <value>
                <fullName>+39</fullName>
            </value>
            <value>
                <fullName>+40</fullName>
            </value>
            <value>
                <fullName>+41</fullName>
            </value>
            <value>
                <fullName>+43</fullName>
            </value>
            <value>
                <fullName>+44</fullName>
            </value>
            <value>
                <fullName>+45</fullName>
            </value>
            <value>
                <fullName>+46</fullName>
            </value>
            <value>
                <fullName>+47</fullName>
            </value>
            <value>
                <fullName>+48</fullName>
            </value>
            <value>
                <fullName>+49</fullName>
            </value>
            <value>
                <fullName>+51</fullName>
            </value>
            <value>
                <fullName>+52</fullName>
            </value>
            <value>
                <fullName>+53</fullName>
            </value>
            <value>
                <fullName>+54</fullName>
            </value>
            <value>
                <fullName>+55</fullName>
            </value>
            <value>
                <fullName>+56</fullName>
            </value>
            <value>
                <fullName>+57</fullName>
            </value>
            <value>
                <fullName>+58</fullName>
            </value>
            <value>
                <fullName>+60</fullName>
            </value>
            <value>
                <fullName>+91</fullName>
                <default>true</default>
                <label>+91</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Enquiry_Source__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Source__c</fullName>
    <label>Enquiry Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Housing.com</fullName>
            </value>
            <value>
                <fullName>99 Acres</fullName>
            </value>
            <value>
                <fullName>Magic Bricks</fullName>
            </value>
            <value>
                <fullName>Common Floor</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Native</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>VDNB</fullName>
            </value>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>Search</fullName>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Exhibition</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Rechurned Lead</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Magicbricks</fullName>
            </value>
            <value>
                <fullName>IVR Call</fullName>
            </value>
            <value>
                <fullName>Pre Sales</fullName>
            </value>
            <value>
                <fullName>Emailer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Site_Visit_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Scheduled_Date__c</fullName>
    <label>Site Visit Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Enquiry</fullName>
                <default>true</default>
                <label>New Enquiry</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Site Visit Scheduled</fullName>
            </value>
            <value>
                <fullName>Site Visit Done</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Budgets__c.field-meta.xml
<CustomField>
    <fullName>Budgets__c</fullName>
    <label>Budgets</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Budget</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/OTP_Disable_Till__c.field-meta.xml
<CustomField>
    <fullName>OTP_Disable_Till__c</fullName>
    <label>OTP Disable Till</label>
    <type>DateTime</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Project_Carpet_Area__c</fullName>
    <label>Project Carpet Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Carpet_Area</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <label>Project Email</label>
    <type>Email</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Head__c.field-meta.xml
<CustomField>
    <fullName>Project_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Header__c.field-meta.xml
<CustomField>
    <fullName>Project_Header__c</fullName>
    <label>Project Header</label>
    <type>Url</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Site_Head__c.field-meta.xml
<CustomField>
    <fullName>Site_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/globalValueSets/Budget.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Under 75 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 0.7 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.7  - 0.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.8  - 0.9 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.9  - 1 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 - 1.1 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 - 1.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.2 - 1.3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.3 - 1.4 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.4 - 1.6 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.6 - 1.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.8 - 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2 - 2.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.2 - 2.4 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.4 - 2.6 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.6 - 2.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.8 - 3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3 Cr &amp; Above</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2 – 2.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.2 – 2.5 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.5 – 2.75 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.75 – 3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3 – 3.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3.2 – 3.5 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3.5 – 3.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>4 Cr and Above</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 1.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.8 – 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 – 1.2 Cr</fullName>
    </customValue>
    <masterLabel>Budget</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/globalValueSets/Carpet_Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>475 - 1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>600 - 2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>900 - 3 BHk</fullName>
    </customValue>
    <customValue>
        <fullName>375 - 400 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>400 – 450 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>450 – 500 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>500 – 550 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>550 – 600 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>600 – 650 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>650 – 700 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>700 – 800 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>700 – 750 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>750 sq.ft. and Above</fullName>
    </customValue>
    <customValue>
        <fullName>750 – 800 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>750 – 850 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>800 – 900 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>850 -- 900 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>900 – 1000 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1000 – 1100 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1100 – 1200 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1200 sq.ft. &amp; Above</fullName>
    </customValue>
    <customValue>
        <fullName>1200 – 1300 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1300 sq.ft and above</fullName>
    </customValue>
    <masterLabel>Carpet Area</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/globalValueSets/Configuration.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Studio</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK (G)</fullName>
    </customValue>
    <customValue>
        <fullName>1 BHK Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK Jodi</fullName>
    </customValue>
    <masterLabel>Configuration</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/classes/EnquiryService_Test.cls
@isTest
global class EnquiryService_Test {
    
    @isTest  
    static void EnquiryServiceTestMethod1()
    { 
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        User userObject = new User();
        userObject.CompanyName = 'TST Comp';
        userObject.LastName = 'last';
        userObject.Email = 'puser000@amamama.com';
        userObject.Username = 'puser000@amamama.com' + System.currentTimeMillis();
        userObject.Title = 'title';
        userObject.Alias = 'alias';
        userObject.TimeZoneSidKey = 'America/Los_Angeles';
        userObject.EmailEncodingKey = 'UTF-8';
        userObject.LanguageLocaleKey = 'en_US';
        userObject.LocaleSidKey = 'en_US';
        userObject.ProfileId = pf.Id;
        insert userObject;
        
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Channel Partner').getRecordTypeId();
        String recordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        
        Account accountObject= new Account(
            RecordTypeID=recordTypeId ,
            FirstName='Test FName',
            LastName='Test LName',
            PersonMailingStreet='test@yahoo.com',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SFO',
            PersonEmail='test@yahoo.com',
            PersonHomePhone='1234567',
            PersonMobilePhone='12345678' 
        );
        insert accountObject;
        
        list<project__c> ProjectList = new list<project__c>();
        Project__c projectObject = new Project__c();
        projectObject.Name = 'Test Project';
        projectObject.Project_Email__c= 'divum@dynamixgroup.co.in';
        projectObject.Project_Carpet_Area__c = '475 - 1 BHK';
        projectObject.Budgets__c = 'Under 75 lakhs';
        projectObject.Configuration__c ='1 BHK';
        projectObject.Project_Head__c = userObject.Id;
        projectObject.Site_Head__c = userObject.id;
        projectObject.OTP_Disable_Till__c = System.now().addDays(1);
        projectObject.Project_Header__c = 'abc.com';
        insert projectObject;
        ProjectList.add(projectObject);
        Enquiry__c enquiry = new Enquiry__c(Stage__c = 'Site Visit Scheduled',Site_Visit_Scheduled_Date__c=Date.today()+4,
                                            /* Channel_Partner__c=null,*/Contact_Person__c=accountObject.id,Project__c=projectObject.id,
                                            Enquiry_Source__c = 'Offline',Primary_Mobile_Number__c='1234125678');
        
        Map<String,String> enquiryMap1= new  Map<String,String>();
        Map<String,String> contactMap1= new  Map<String,String>();
        enquiryMap1.put('OwnerId',userObject.Id);
        enquiryMap1.put('Country_Code__c','+91');
        enquiryMap1.put('Contact_Person__c',accountObject.Id);
        //enquiryMap1.put('Channel_Partner__c',accountObject.Id);
        enquiryMap1.put('ProjectId',projectObject.Id);
        enquiryMap1.put('Site_Visit_Scheduled_Date__c','2025-05-27 10:10:10');
        enquiryMap1.put('Enquiry_Source__c','Offline');
        contactMap1.put('FirstName','fgb');
        contactMap1.put('LastName','dfgs');
        contactMap1.put('Country_Code__c','+91');
        contactMap1.put('PersonMobilePhone','1234125678');
        contactMap1.put('Email__c','testmanras122@gmail.com');
        
        
        
        EnquiryRequest enq = new EnquiryRequest();
        enq.contactMap = contactMap1;
        enq.enquiryMap = enquiryMap1;
        String myJSON = JSON.serialize(enq);    
        RestRequest req = new RestRequest(); 
        req.requestUri = 'https://java-enterprise-1915-dev-ed.lightning.force.com/services/apexrest/enquiry/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(myJSON);
        RestContext.request = req; 
        
        Test.startTest();
        EnquiryResponse enqWrp= EnquiryService.doPost();
        Test.stopTest();
    }
    @isTest 
    static void EnquiryServiceTestMethod2()
    {
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        User userObject = new User();
        userObject.CompanyName = 'TST Comp';
        userObject.LastName = 'last';
        userObject.Email = 'puser000@amamama.com';
        userObject.Username = 'puser000@amamama.com' + System.currentTimeMillis();
        userObject.Title = 'title';
        userObject.Alias = 'alias';
        userObject.TimeZoneSidKey = 'America/Los_Angeles';
        userObject.EmailEncodingKey = 'UTF-8';
        userObject.LanguageLocaleKey = 'en_US';
        userObject.LocaleSidKey = 'en_US';
        userObject.ProfileId = pf.Id;
        insert userObject;
        
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Channel Partner').getRecordTypeId();
        String recordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        
        Account accountObject= new Account(
            RecordTypeID=recordTypeId ,
            FirstName='Test FName',
            LastName='Test LName',
            PersonMailingStreet='test@yahoo.com',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SFO',
            PersonEmail='test@yahoo.com',
            PersonHomePhone='1234567',
            PersonMobilePhone='1234125678' 
        );
        
        insert accountObject;
         list<project__c> ProjectList = new list<project__c>();
        Project__c projectObject = new Project__c();
        projectObject.Name = 'Test Project';
        projectObject.Project_Email__c= 'divum@dynamixgroup.co.in';
        projectObject.Project_Carpet_Area__c = '475 - 1 BHK';
        projectObject.Budgets__c = 'Under 75 lakhs';
        projectObject.Configuration__c ='1 BHK';
        projectObject.Project_Head__c = userObject.Id;
        projectObject.Site_Head__c = userObject.id;
        projectObject.OTP_Disable_Till__c = System.now().addDays(1);
        projectObject.Project_Header__c = 'abc.com';
        insert projectObject;
        ProjectList.add(projectObject);
        Map<String,String> enquiryMap1= new  Map<String,String>();
        Map<String,String> contactMap1= new  Map<String,String>();
       enquiryMap1.put('OwnerId',userObject.Id);
        enquiryMap1.put('Country_Code__c','+91');
        enquiryMap1.put('Contact_Person__c',accountObject.Id);
        //enquiryMap1.put('Channel_Partner__c',accountObject.Id);
        enquiryMap1.put('Project__c',projectObject.Id);
        enquiryMap1.put('Enquiry_Source__c','Offline');
        contactMap1.put('FirstName','fgb');
        contactMap1.put('LastName','dfgs');
        contactMap1.put('Country_Code__c','+91');
        contactMap1.put('PersonMobilePhone','1234125678');
        contactMap1.put('Email__c','testmanras122@gmail.com');
        
        EnquiryRequest enq = new EnquiryRequest();
        enq.contactMap = contactMap1;
        enq.enquiryMap = enquiryMap1;
        String myJSON = JSON.serialize(enq);    
        RestRequest req = new RestRequest(); 
        req.requestUri = 'https://java-enterprise-1915-dev-ed.lightning.force.com/services/apexrest/enquiry/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(myJSON);
        RestContext.request = req; 
        
        Test.startTest();
        EnquiryResponse enqWrp= EnquiryService.doPost();
        Test.stopTest();
    }
    
    @isTest  
    static void EnquiryServiceTestMethod3()
    { 
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        User userObject = new User();
        userObject.CompanyName = 'TST Comp';
        userObject.LastName = 'last';
        userObject.Email = 'puser000@amamama.com';
        userObject.Username = 'puser000@amamama.com' + System.currentTimeMillis();
        userObject.Title = 'title';
        userObject.Alias = 'alias';
        userObject.TimeZoneSidKey = 'America/Los_Angeles';
        userObject.EmailEncodingKey = 'UTF-8';
        userObject.LanguageLocaleKey = 'en_US';
        userObject.LocaleSidKey = 'en_US';
        userObject.ProfileId = pf.Id;
        insert userObject;
        
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Channel Partner').getRecordTypeId();
        String recordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        
        Account accountObject= new Account(
            RecordTypeID=recordTypeId ,
            FirstName='Test FName',
            LastName='Test LName',
            PersonMailingStreet='test@yahoo.com',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SFO',
            PersonEmail='test@yahoo.com',
            PersonHomePhone='1234567',
            PersonMobilePhone='12345678' 
        );
        insert accountObject;
        
        list<project__c> ProjectList = new list<project__c>();
        Project__c projectObject = new Project__c();
        projectObject.Name = 'Test Project';
        projectObject.Project_Email__c= 'divum@dynamixgroup.co.in';
        projectObject.Project_Carpet_Area__c = '475 - 1 BHK';
        projectObject.Budgets__c = 'Under 75 lakhs';
        projectObject.Configuration__c ='1 BHK';
        projectObject.Project_Head__c = userObject.Id;
        projectObject.Site_Head__c = userObject.id;
        projectObject.OTP_Disable_Till__c = System.now().addDays(1);
        projectObject.Project_Header__c = 'abc.com';
        insert projectObject;
        ProjectList.add(projectObject);        
        Enquiry__c enquiry = new Enquiry__c(Stage__c = 'Site Visit Scheduled',Site_Visit_Scheduled_Date__c=Date.today()+4,
                                            /* Channel_Partner__c=null,*/Contact_Person__c=accountObject.id,Project__c=projectObject.id,
                                            Enquiry_Source__c = 'Offline',Primary_Mobile_Number__c='12345678');
        insert enquiry;
        
        Map<String,String> enquiryMap1= new  Map<String,String>();
        Map<String,String> contactMap1= new  Map<String,String>();
        enquiryMap1.put('OwnerId',userObject.Id);
        enquiryMap1.put('Budget__c','15 Lakhs to 20 Lakhs');
        enquiryMap1.put('Project_Integration_Id__c','1');
        enquiryMap1.put('Contact_Person__c',accountObject.Id);
        //  enquiryMap1.put('Channel_Partner__c',accountObject.Id);
        //  enquiryMap1.put('Project__c',projectObject.Id);
        enquiryMap1.put('Enquiry_Source_1__c',null);
        contactMap1.put('FirstName','fgb');
        contactMap1.put('LastName','dfgs');
        contactMap1.put('PersonMobilePhone','12345678');
        contactMap1.put('PersonEmail','testmanras122@gmail.com');
        
        EnquiryRequest enq = new EnquiryRequest();
        enq.contactMap = contactMap1;
        enq.enquiryMap = enquiryMap1;
        String myJSON = JSON.serialize(enq);    
        RestRequest req = new RestRequest(); 
        req.requestUri = 'https://java-enterprise-1915-dev-ed.lightning.force.com/services/apexrest/enquiry/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(myJSON);
        RestContext.request = req; 
        
        Test.startTest();
        EnquiryResponse enqWrp= EnquiryService.doPost();
        Test.stopTest();
    }
     @isTest  
    static void EnquiryServiceTestMethod4()
    { 
        Profile pf= [Select Id from profile where Name='System Administrator']; 
        User userObject = new User();
        userObject.CompanyName = 'TST Comp';
        userObject.LastName = 'last';
        userObject.Email = 'puser000@amamama.com';
        userObject.Username = 'puser000@amamama.com' + System.currentTimeMillis();
        userObject.Title = 'title';
        userObject.Alias = 'alias';
        userObject.TimeZoneSidKey = 'America/Los_Angeles';
        userObject.EmailEncodingKey = 'UTF-8';
        userObject.LanguageLocaleKey = 'en_US';
        userObject.LocaleSidKey = 'en_US';
        userObject.ProfileId = pf.Id;
        insert userObject;
        
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Channel Partner').getRecordTypeId();
        String recordTypeId  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        
        Account accountObject= new Account(
            RecordTypeID=recordTypeId ,
            FirstName='Test FName',
            LastName='Test LName',
            PersonMailingStreet='test@yahoo.com',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SFO',
            PersonEmail='test@yahoo.com',
            PersonHomePhone='1234567',
            PersonMobilePhone='1234125678' 
        );
        insert accountObject;
        
        list<project__c> ProjectList = new list<project__c>();
        Project__c projectObject = new Project__c();
        projectObject.Name = 'Test Project';
        projectObject.Project_Email__c= 'divum@dynamixgroup.co.in';
        projectObject.Project_Carpet_Area__c = '475 - 1 BHK';
        projectObject.Budgets__c = 'Under 75 lakhs';
        projectObject.Configuration__c ='1 BHK';
        projectObject.Project_Head__c = userObject.Id;
        projectObject.Site_Head__c = userObject.id;
        projectObject.OTP_Disable_Till__c = System.now().addDays(1);
        projectObject.Project_Header__c = 'abc.com';
        insert projectObject;
        ProjectList.add(projectObject);        
        Enquiry__c enquiry = new Enquiry__c(Stage__c = 'Site Visit Scheduled',Site_Visit_Scheduled_Date__c=Date.today()+4,
                                            /* Channel_Partner__c=null,*/Contact_Person__c=accountObject.id,Project__c=projectObject.id,
                                            Enquiry_Source__c = 'Offline',Primary_Mobile_Number__c='1234125678');
        insert enquiry;
        Task task = New Task();
        task.Date_and_Time_of_Site_Visit__c = system.now().addDays(2);
        task.Subject = 'Site Visit Scheduled';
        task.whatId = enquiry.id;
        task.ActivityDate =system.today();
        task.Status ='Scheduled';
        insert task;
        
        Map<String,String> enquiryMap1= new  Map<String,String>();
        Map<String,String> contactMap1= new  Map<String,String>();
       enquiryMap1.put('OwnerId',userObject.Id);
        enquiryMap1.put('Country_Code__c','+91');
        enquiryMap1.put('Contact_Person__c',accountObject.Id);
        enquiryMap1.put('Site_Visit_Scheduled_Date__c','2025-05-27 10:10:10');
        enquiryMap1.put('ProjectId',projectObject.Id);
        enquiryMap1.put('Enquiry_Source__c','Offline');
        contactMap1.put('FirstName','fgb');
        contactMap1.put('LastName','dfgs');
        contactMap1.put('Country_Code__c','+91');
        contactMap1.put('PersonMobilePhone','1234125678');
        contactMap1.put('Email__c','testmanras122@gmail.com');
        
        EnquiryRequest enq = new EnquiryRequest();
        enq.contactMap = contactMap1;
        enq.enquiryMap = enquiryMap1;
        String myJSON = JSON.serialize(enq);    
        RestRequest req = new RestRequest(); 
        req.requestUri = 'https://java-enterprise-1915-dev-ed.lightning.force.com/services/apexrest/enquiry/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(myJSON);
        RestContext.request = req; 
        
        Test.startTest();
        EnquiryResponse enqWrp= EnquiryService.doPost();
        Test.stopTest();
    }
}