dynamix/force-app/main/default/objects/Account/fields/NRI__c.field-meta.xml
<CustomField>
    <fullName>NRI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NRI</label>
    <type>Checkbox</type>
</CustomField>

dynamix/force-app/main/default/objects/Account/fields/PAN_No__c.field-meta.xml
<CustomField>
    <fullName>PAN_No__c</fullName>
    <label>PAN No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Account/fields/Upload_PAN_Card__c.field-meta.xml
<CustomField>
    <fullName>Upload_PAN_Card__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Upload PAN Card</label>
    <type>Checkbox</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <summarizedField>Price_Details__c.Discount__c</summarizedField>
    <summaryForeignKey>Price_Details__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <formula>Project_Name__r.Project_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Email</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Suggested_Property__c.field-meta.xml
<CustomField>
    <fullName>Related_Suggested_Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Suggested Property</label>
    <referenceTo>Suggested_Property__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/SDR_Agent__c.field-meta.xml
<CustomField>
    <fullName>SDR_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SDR Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project_Name__c</field>
            <operation>equals</operation>
            <valueField>SDR_Agent__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SDR_Agent__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Co_Applicant__c/Co_Applicant__c.object-meta.xml
<CustomObject>
    <label>Co-Applicant</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Applicant</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Co_Applicant__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Co-Applicant</relationshipLabel>
    <relationshipName>Co_Applicant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/NRI__c.field-meta.xml
<CustomField>
    <fullName>NRI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NRI</label>
    <type>Checkbox</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Project_Carpet_Area__c</fullName>
    <label>Desired Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Carpet_Area</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan__c/Pricing_Plan__c.object-meta.xml
<CustomObject>
    <label>Pricing Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Pricing_Plan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Pricing Plans</relationshipLabel>
    <relationshipName>Pricing_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Budgets__c.field-meta.xml
<CustomField>
    <fullName>Budgets__c</fullName>
    <label>Budgets</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Budget</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Project_Carpet_Area__c</fullName>
    <label>Project Carpet Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Carpet_Area</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <label>Project Email</label>
    <type>Email</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Property_Price_Slab__c.field-meta.xml
<CustomField>
    <fullName>Property_Price_Slab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Price Slab</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please add price slab as per project selected</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Pricing_Plan__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pricing_Plan__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit No.</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/SDR_Agent__c/SDR_Agent__c.object-meta.xml
<CustomObject>
    <label>SDR Agent</label>
    <nameField>
        <label>SDR Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SDR Agents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/SDR_Agent__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>SDR Agents</relationshipLabel>
    <relationshipName>SDR_Agents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/Suggested_Property__c.object-meta.xml
<CustomObject>
    <label>Suggested Property</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Suggestion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suggested Property</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Suggested Property</relationshipLabel>
    <relationshipName>Suggested_Property</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Suggested Property</relationshipLabel>
    <relationshipName>Suggested_Property</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/globalValueSets/Budget.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Under 75 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 0.7 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.7  - 0.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.8  - 0.9 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.9  - 1 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 - 1.1 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 - 1.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.2 - 1.3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.3 - 1.4 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.4 - 1.6 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.6 - 1.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.8 - 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2 - 2.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.2 - 2.4 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.4 - 2.6 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.6 - 2.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.8 - 3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3 Cr &amp; Above</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2 – 2.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.2 – 2.5 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.5 – 2.75 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.75 – 3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3 – 3.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3.2 – 3.5 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3.5 – 3.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>4 Cr and Above</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 1.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.8 – 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 – 1.2 Cr</fullName>
    </customValue>
    <masterLabel>Budget</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/globalValueSets/Carpet_Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>475 - 1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>600 - 2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>900 - 3 BHk</fullName>
    </customValue>
    <customValue>
        <fullName>375 - 400 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>400 – 450 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>450 – 500 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>500 – 550 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>550 – 600 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>600 – 650 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>650 – 700 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>700 – 800 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>700 – 750 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>750 sq.ft. and Above</fullName>
    </customValue>
    <customValue>
        <fullName>750 – 800 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>750 – 850 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>800 – 900 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>850 -- 900 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>900 – 1000 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1000 – 1100 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1100 – 1200 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1200 sq.ft. &amp; Above</fullName>
    </customValue>
    <customValue>
        <fullName>1200 – 1300 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1300 sq.ft and above</fullName>
    </customValue>
    <masterLabel>Carpet Area</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/globalValueSets/Configuration.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Studio</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK (G)</fullName>
    </customValue>
    <customValue>
        <fullName>1 BHK Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK Jodi</fullName>
    </customValue>
    <masterLabel>Configuration</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/classes/SDRAgentNullTriggerHandlerTest.cls
@isTest
public class SDRAgentNullTriggerHandlerTest {
    @isTest
    static void testMethod1(){
        
         Id PersonRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
            Account accountObject = new Account();
            accountObject.FirstName = 'test';
            accountObject.LastName = 'Account';
            accountObject.BillingCountry = 'India';
            accountObject.Phone = '4555465655';
            accountObject.RecordTypeId = PersonRecId;
            accountObject.PersonEmail = 'dynamix.project@gmail.com';
            accountObject.Aadhar_No__pc = '458785698547';
            accountObject.PAN_No__c = 'ABCTY1234D';
            accountObject.Aadhar_Uploaded__pc = true;
            accountObject.PAN_Card_Uploaded__pc = true;
            accountObject.Upload_PAN_Card__c=true;
            accountObject.PersonMobilePhone = '4568214569';
            accountObject.PAN_No__pc = 'ABCTY1234D';
            accountObject.PersonMailingCity = 'Zirakpur';
            accountObject.PersonMailingState = 'Punjab';
            accountObject.PersonMailingCountry = 'India';
            accountObject.PersonMailingStreet = 'Test Street';
            accountObject.PersonMailingPostalCode = '140603';
            accountObject.NRI__c = True;
            insert accountObject;
            
            Account accountObject1 = new Account();
            accountObject1.FirstName = 'test';
            accountObject1.LastName = 'Account1';
            accountObject1.BillingCountry = 'India';
            accountObject1.Phone = '4555467855';
            accountObject1.RecordTypeId = PersonRecId;
            accountObject1.PersonEmail = 'dynamix1.project@gmail.com';
            accountObject1.Aadhar_No__pc = '458875698547';
            accountObject1.PAN_No__c = 'ABCTY1254D';
            accountObject1.Aadhar_Uploaded__pc = true;
            accountObject1.PAN_Card_Uploaded__pc = true;
            accountObject1.Upload_PAN_Card__c=true;
            accountObject1.PersonMobilePhone = '4218214569';
            accountObject1.PAN_No__pc = 'ABCTY1254D';
            accountObject1.PersonMailingCity = 'Zirakpur';
            accountObject1.PersonMailingState = 'Punjab';
            accountObject1.PersonMailingCountry = 'India';
            accountObject1.PersonMailingStreet = 'Test Street';
            accountObject1.PersonMailingPostalCode = '140603';
            accountObject1.NRI__c = True;
            insert accountObject1;
            
           
            
            Project__c projectObject = new Project__c();
            projectObject.Name = 'Test Project';
            projectObject.Project_Email__c= 'nishi@manras.com';
            projectObject.Project_Carpet_Area__c = '475 - 1 BHK';
            projectObject.Budgets__c = 'Under 75 lakhs';
            projectObject.Configuration__c ='1 BHK';
            insert projectObject;
            
            Opportunity oppoObject = new Opportunity();
            oppoObject.AccountId = accountObject.Id;
            oppoObject.Name = 'test Opportunity';
            oppoObject.StageName = 'Site Visit';
            oppoObject.CloseDate = System.Today()+3;
            oppoObject.Project__c = projectObject.Id;
            insert oppoObject;
            
            Pricing_Plan__c pricingPlanObject = new Pricing_Plan__c();
            pricingPlanObject.Name = 'Pricing Plan Test';
            pricingPlanObject.Project__c = projectObject.Id;
            insert pricingPlanObject;
            
            Property__c propertyObject = new Property__c();
            propertyObject.Name = 'test property';
            propertyObject.Project__c = projectObject.Id;
            propertyObject.Property_Price_Slab__c = pricingPlanObject.Id;
            propertyObject.Floor__c= '5';
            insert propertyObject;
            
            Suggested_Property__c suggestedProperty = new Suggested_Property__c();
            suggestedProperty.Opportunity__c = oppoObject.Id;
            suggestedProperty.Unit__c = propertyObject.Id;
            suggestedProperty.Discount__c = 10;
            insert suggestedProperty;
            
            SDR_Agent__c SDRAgent = new SDR_Agent__c();
            SDRAgent.Account_Name__c = accountObject.ID;
            SDRAgent.Project__c = projectObject.ID;
            insert SDRAgent;
        
            Booking__c booking = new Booking__c();
            booking.Primary_Applicant__c = accountObject.Id;
            booking.Related_Opportunity__c = oppoObject.Id;
            booking.Related_Suggested_Property__c = suggestedProperty.Id;
            booking.Project_Name__c = projectObject.Id;
            booking.Primary_Secondary_info_Updated__c = false;
            booking.Shared_SDR_Letter__c = false;
            booking.Date_of_First_Disbursement__c = Date.today();
            booking.Amount_of_First_Disbursement__c = 43;
            booking.Cancellation_Approval_Status__c = 'Approved';
            booking.Booking_Cancellation__c = false;
            booking.Welcome_Email_Checker__c = false;
            booking.Cancellation_Checkbox__c = false;
            booking.Cancellation_Requested_Status__c = 'Cancellation Confirmed';
            booking.Cancellation_Approval_Status__c = 'Submitted';
            booking.Source_of_Finance__c = 'Self Funded';
        	booking.Indemnity_Form__c = False;	
            
            insert booking;
            
            Co_Applicant__c COAPP = new Co_Applicant__c();
            COAPP.Account__c = accountObject1.Id;
            COAPP.Booking__c = booking.ID;
            COAPP.Role__c = 'Co-Applicant';
            insert COAPP;
        
        	
        	Test.startTest();
            booking.Welcome_Email_Checker__c = True;
            booking.SDR_Agent__c = SDRAgent.ID;
            booking.Stamp_Duty_Status__c = 'Customer';
            update booking;
        	Test.stopTest();
    }
    
    @isTest
    static void testMethod2(){
        Id PersonRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account accountObject = new Account();
            accountObject.FirstName = 'test';
            accountObject.LastName = 'Account';
            accountObject.BillingCountry = 'India';
            accountObject.Phone = '4555465655';
            accountObject.RecordTypeId = PersonRecId;
            accountObject.PersonEmail = 'dynamix.project@gmail.com';
            accountObject.Aadhar_No__pc = '458785698547';
            accountObject.PAN_No__c = 'ABCTY1234D';
            accountObject.Aadhar_Uploaded__pc = true;
            accountObject.PAN_Card_Uploaded__pc = true;
            accountObject.Upload_PAN_Card__c=true;
            accountObject.PersonMobilePhone = '4568214569';
            accountObject.PAN_No__pc = 'ABCTY1234D';
            accountObject.PersonMailingCity = 'Zirakpur';
            accountObject.PersonMailingState = 'Punjab';
            accountObject.PersonMailingCountry = 'India';
            accountObject.PersonMailingStreet = 'Test Street';
            accountObject.PersonMailingPostalCode = '140603';
            accountObject.NRI__c = True;
            insert accountObject;
           
            Project__c projectObject = new Project__c();
            projectObject.Name = 'Test Project';
            projectObject.Project_Email__c= 'nishi@manras.com';
            projectObject.Project_Carpet_Area__c = '475 - 1 BHK';
            projectObject.Budgets__c = 'Under 75 lakhs';
            projectObject.Configuration__c ='1 BHK';
            insert projectObject;
            
            Opportunity oppoObject = new Opportunity();
            oppoObject.AccountId = accountObject.Id;
            oppoObject.Name = 'test Opportunity';
            oppoObject.StageName = 'Site Visit';
            oppoObject.CloseDate = System.Today()+3;
            oppoObject.Project__c = projectObject.Id;
            insert oppoObject;
            
            Pricing_Plan__c pricingPlanObject = new Pricing_Plan__c();
            pricingPlanObject.Name = 'Pricing Plan Test';
            pricingPlanObject.Project__c = projectObject.Id;
            insert pricingPlanObject;
            
            Property__c propertyObject = new Property__c();
            propertyObject.Name = 'test property';
            propertyObject.Project__c = projectObject.Id;
            propertyObject.Property_Price_Slab__c = pricingPlanObject.Id;
            propertyObject.Floor__c= '5';
            insert propertyObject;
            
            Suggested_Property__c suggestedProperty = new Suggested_Property__c();
            suggestedProperty.Opportunity__c = oppoObject.Id;
            suggestedProperty.Unit__c = propertyObject.Id;
            suggestedProperty.Discount__c = 10;
            insert suggestedProperty;
            
            SDR_Agent__c SDRAgent = new SDR_Agent__c();
            SDRAgent.Account_Name__c = accountObject.ID;
            SDRAgent.Project__c = projectObject.ID;
            insert SDRAgent;
        
            Booking__c booking = new Booking__c();
            booking.Primary_Applicant__c = accountObject.Id;
            booking.Related_Opportunity__c = oppoObject.Id;
            booking.Related_Suggested_Property__c = suggestedProperty.Id;
            booking.Project_Name__c = projectObject.Id;
            booking.Primary_Secondary_info_Updated__c = false;
            booking.Shared_SDR_Letter__c = false;
            booking.Date_of_First_Disbursement__c = Date.today();
            booking.Amount_of_First_Disbursement__c = 43;
            booking.Cancellation_Approval_Status__c = 'Approved';
            booking.Booking_Cancellation__c = false;
            booking.Welcome_Email_Checker__c = false;
            booking.Cancellation_Checkbox__c = false;
            booking.Cancellation_Requested_Status__c = 'Cancellation Confirmed';
            booking.Cancellation_Approval_Status__c = 'Submitted';
            booking.Source_of_Finance__c = 'Self Funded';
            insert booking; 

			Test.startTest();        
            booking.Welcome_Email_Checker__c = True;
            booking.SDR_Agent__c = SDRAgent.ID;
            booking.Stamp_Duty_Status__c = 'Customer';
            update booking;
        
        	Test.stopTest();
    }
    @isTest
    static void testMethod3(){
        Id PersonRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account accountObject = new Account();
            accountObject.FirstName = 'test';
            accountObject.LastName = 'Account';
            accountObject.BillingCountry = 'India';
            accountObject.Phone = '4555465655';
            accountObject.RecordTypeId = PersonRecId;
            accountObject.PersonEmail = 'dynamix.project@gmail.com';
            accountObject.Aadhar_No__pc = '458785698547';
            accountObject.PAN_No__c = 'ABCTY1234D';
            accountObject.Aadhar_Uploaded__pc = true;
            accountObject.PAN_Card_Uploaded__pc = true;
            accountObject.Upload_PAN_Card__c=true;
            accountObject.PersonMobilePhone = '4568214569';
            accountObject.PAN_No__pc = 'ABCTY1234D';
            accountObject.PersonMailingCity = 'Zirakpur';
            accountObject.PersonMailingState = 'Punjab';
            accountObject.PersonMailingCountry = 'India';
            accountObject.PersonMailingStreet = 'Test Street';
            accountObject.PersonMailingPostalCode = '140603';
            accountObject.NRI__c = False;
            insert accountObject;

            Project__c projectObject = new Project__c();
            projectObject.Name = 'Test Project';
            projectObject.Project_Email__c= 'nishi@manras.com';
            projectObject.Project_Carpet_Area__c = '475 - 1 BHK';
            projectObject.Budgets__c = 'Under 75 lakhs';
            projectObject.Configuration__c ='1 BHK';
            insert projectObject;
            
            Opportunity oppoObject = new Opportunity();
            oppoObject.AccountId = accountObject.Id;
            oppoObject.Name = 'test Opportunity';
            oppoObject.StageName = 'Site Visit';
            oppoObject.CloseDate = System.Today()+3;
            oppoObject.Project__c = projectObject.Id;
            insert oppoObject;
            
            Pricing_Plan__c pricingPlanObject = new Pricing_Plan__c();
            pricingPlanObject.Name = 'Pricing Plan Test';
            pricingPlanObject.Project__c = projectObject.Id;
            insert pricingPlanObject;
            
            Property__c propertyObject = new Property__c();
            propertyObject.Name = 'test property';
            propertyObject.Project__c = projectObject.Id;
            propertyObject.Property_Price_Slab__c = pricingPlanObject.Id;
            propertyObject.Floor__c= '5';
            insert propertyObject;
            
            Suggested_Property__c suggestedProperty = new Suggested_Property__c();
            suggestedProperty.Opportunity__c = oppoObject.Id;
            suggestedProperty.Unit__c = propertyObject.Id;
            suggestedProperty.Discount__c = 10;
            insert suggestedProperty;
            
            SDR_Agent__c SDRAgent = new SDR_Agent__c();
            SDRAgent.Account_Name__c = accountObject.ID;
            SDRAgent.Project__c = projectObject.ID;
            insert SDRAgent;
        
            Booking__c booking = new Booking__c();
            booking.Primary_Applicant__c = accountObject.Id;
            booking.Related_Opportunity__c = oppoObject.Id;
            booking.Related_Suggested_Property__c = suggestedProperty.Id;
            booking.Project_Name__c = projectObject.Id;
            booking.Primary_Secondary_info_Updated__c = false;
            booking.Shared_SDR_Letter__c = false;
            booking.Date_of_First_Disbursement__c = Date.today();
            booking.Amount_of_First_Disbursement__c = 43;
            booking.Cancellation_Approval_Status__c = 'Approved';
            booking.Booking_Cancellation__c = false;
            booking.Welcome_Email_Checker__c = false;
            booking.Cancellation_Checkbox__c = false;
            booking.Cancellation_Requested_Status__c = 'Cancellation Confirmed';
            booking.Cancellation_Approval_Status__c = 'Submitted';
            booking.Source_of_Finance__c = 'Self Funded';
            insert booking;
        
        	Test.startTest();
            booking.Welcome_Email_Checker__c = True;
            booking.SDR_Agent__c = SDRAgent.ID;
            booking.Stamp_Duty_Status__c = 'Customer';
            update booking;
        	Test.stopTest();
    }
}