dynamix/force-app/main/default/objects/Account/fields/PAN_No__c.field-meta.xml
<CustomField>
    <fullName>PAN_No__c</fullName>
    <label>PAN No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/cancellation_fees__c.field-meta.xml
<CustomField>
    <fullName>cancellation_fees__c</fullName>
    <label>Cancellation Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Index_II_Document__c.field-meta.xml
<CustomField>
    <fullName>Index_II_Document__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Index II Document</label>
    <type>Checkbox</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Sent to Agent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking1</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Possession/Handover</fullName>
            </value>
            <value>
                <fullName>Snag/Desnag by Client</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancellation Initiated</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Pending</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Ready</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled -- Refund Done</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Handover</fullName>
                <isActive>false</isActive>
                <label>Handover</label>
            </value>
            <value>
                <fullName>In Process</fullName>
                <isActive>false</isActive>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Possession Letter</fullName>
                <isActive>false</isActive>
                <label>Possession Letter</label>
            </value>
            <value>
                <fullName>Registered</fullName>
                <isActive>false</isActive>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Sanction</fullName>
                <isActive>false</isActive>
                <label>Sanction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Co_Applicant__c/Co_Applicant__c.object-meta.xml
<CustomObject>
    <label>Co-Applicant</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Applicant</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Co_Applicant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Co-Applicant</relationshipLabel>
    <relationshipName>Co_Applicant</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Co_Applicant__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Co-Applicant</relationshipLabel>
    <relationshipName>Co_Applicant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Project_Carpet_Area__c</fullName>
    <label>Desired Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Carpet_Area</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Walk_in_Source__c.field-meta.xml
<CustomField>
    <fullName>Walk_in_Source__c</fullName>
    <label>Walk-in Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Presales</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Referred by Existing Customer</fullName>
            </value>
            <value>
                <fullName>Referred by Others</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Online Ads</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>Newspaper Ad</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>IVR Call</fullName>
            </value>
            <value>
                <fullName>Property Portal</fullName>
            </value>
            <value>
                <fullName>Email/SMS/WhatsApp</fullName>
            </value>
            <value>
                <fullName>Exhibition</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Rechurned Lead</fullName>
            </value>
            <value>
                <fullName>Magicbricks</fullName>
            </value>
            <value>
                <fullName>99 Acres</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Passing By</fullName>
                <isActive>false</isActive>
                <label>Passing By</label>
            </value>
            <value>
                <fullName>Referral</fullName>
                <isActive>false</isActive>
                <label>Referral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Budgets__c.field-meta.xml
<CustomField>
    <fullName>Budgets__c</fullName>
    <label>Budgets</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Budget</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Post_Sales_Head__c.field-meta.xml
<CustomField>
    <fullName>Post_Sales_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Post Sales Head</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Post Sales</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Project_Carpet_Area__c</fullName>
    <label>Project Carpet Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Carpet_Area</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/globalValueSets/Budget.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Under 75 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 0.7 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.7  - 0.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.8  - 0.9 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.9  - 1 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 - 1.1 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 - 1.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.2 - 1.3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.3 - 1.4 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.4 - 1.6 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.6 - 1.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.8 - 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2 - 2.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.2 - 2.4 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.4 - 2.6 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.6 - 2.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.8 - 3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3 Cr &amp; Above</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2 – 2.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.2 – 2.5 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.5 – 2.75 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.75 – 3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3 – 3.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3.2 – 3.5 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3.5 – 3.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>4 Cr and Above</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 1.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.8 – 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 – 1.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>above 3.5 crs</fullName>
    </customValue>
    <masterLabel>Budget</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/globalValueSets/Carpet_Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>475 - 1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>600 - 2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>900 - 3 BHk</fullName>
    </customValue>
    <customValue>
        <fullName>375 - 400 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>400 – 450 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>450 – 500 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>500 – 550 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>550 – 600 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>600 – 650 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>650 – 700 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>700 – 800 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>700 – 750 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>750 sq.ft. and Above</fullName>
    </customValue>
    <customValue>
        <fullName>750 – 800 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>750 – 850 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>800 – 900 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>850 -- 900 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>900 – 1000 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1000 – 1100 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1100 – 1200 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1200 sq.ft. &amp; Above</fullName>
    </customValue>
    <customValue>
        <fullName>1200 – 1300 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1300 sq.ft and above</fullName>
    </customValue>
    <masterLabel>Carpet Area</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/globalValueSets/Configuration.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Studio</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK (G)</fullName>
    </customValue>
    <customValue>
        <fullName>1 BHK Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK Jodi</fullName>
    </customValue>
    <masterLabel>Configuration</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/classes/bookingTrigger_Test.cls
@isTest
public class bookingTrigger_Test {
    @isTest 
    public static void bookingTriggerMethod()
    {
        String developerNameValue = 'Booking_Form_Link_Email_SM'; 
        EmailTemplate emailTemplate = [SELECT Developername , Name FROM EmailTemplate WHERE DeveloperName =:developerNameValue LIMIT 1] ;
        
        Profile p1=[SELECT Id From Profile WHERE Name='Post Sales'];
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User u2 =new User( Alias = uniqueName.substring(18, 23),
                          Email = uniqueName + '@test' + orgId + '.org',
                          EmailEncodingKey = 'UTF-8',
                          LastName = 'Testing',
                          Username = uniqueName + '@test' + orgId + '.org',
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', // changed for to avoid: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, Locale: bad value for restricted picklist field: America/Los_Angeles
                          
                          ProfileId=p1.Id,
                          TimeZoneSidKey    = 'America/Los_Angeles');
        insert u2;  
        
        Id PersonRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account accountObject = new Account();
        accountObject.FirstName = 'test';
        accountObject.LastName = 'Account';
        accountObject.BillingCountry = 'India';
        accountObject.Phone = '455546565';
        accountObject.RecordTypeId = PersonRecId;
        accountObject.PersonEmail = 'dynamix.project@gmail.com';
        accountObject.Aadhar_No__pc = '458785698547';
        accountObject.PAN_No__c = 'ABCTY1234D';
        accountObject.PAN_No__pc = 'ABCTY1234D';
        accountObject.Aadhar_Uploaded__pc = true;
        accountObject.PAN_Card_Uploaded__pc = true;
        accountObject.PersonMobilePhone ='8989898989';
        insert accountObject;
        
        Project__c projObj = new Project__c();
        projObj.Name = 'test project';
        projObj.Last_Invoice_Number__c = 1;
        projobj.Post_Sales_Head__c = u2.Id;
        projobj.Budgets__c = 'above 3.5 crs';
        projobj.Configuration__c = '1 BHK';
        projobj.Project_Carpet_Area__c = '475 - 1 BHK;900 - 3 BHk';
        insert projObj;
        
        Test.startTest();
        Opportunity oppoObject = new Opportunity();
        oppoObject.AccountId = accountObject.Id;
        oppoObject.Name = 'test Opportunity';
        oppoObject.StageName = 'Site Visit';
        oppoObject.CloseDate = System.Today()+3;
        oppoObject.Walk_in_Source__c = 'Channel Partner';
        oppoObject.Project__c = projObj.Id;
        oppoObject.OwnerId = u2.Id;
        insert oppoObject;
        
        Booking__c bookingObject = new Booking__c();
        bookingObject.Stage__c = 'Draft';
        bookingObject.cancellation_fees__c=10000;
        bookingObject.Registration_Status__c = 'Not Started';
        bookingObject.Index_II_Document__c = true;
        bookingObject.Sales_Manager__c = oppoObject.OwnerId;
        bookingObject.Related_Opportunity__c = oppoObject.id;
        insert bookingObject;
        
        Booking__c bookingObj = new Booking__c();
        bookingObj.Stage__c = 'Registration';
        bookingObj.cancellation_fees__c=10000;
        bookingObj.Index_II_Document__c = true;
        bookingObj.Registration_Status__c = 'Not Started';
      //  bookingObject.Sales_Manager__c = oppoObject.OwnerId;
        bookingObj.Sales_Manager__c = oppoObject.OwnerId;
        bookingObj.Related_Opportunity__c = oppoObject.id;
        
        insert bookingObj;
        
        Booking__c Book = [Select Id,Stage__c From Booking__c Where Id=:bookingObject.Id];
        Book.Stage__c = 'Registration';
        Book.Registration_Status__c = 'Completed';
        bookingObject.Sales_Manager__c = oppoObject.OwnerId;
        Update Book;
        EmailTemplate insertedTemplate = [SELECT Id, Name FROM EmailTemplate WHERE Id = :emailTemplate.Id];
        Test.stopTest();
        
    }
    @isTest 
    public static void bookingTriggerMethod1()
    {
        String developerNameValue = 'Booking_Form_Link_Email_SM'; 
        EmailTemplate emailTemplate = [SELECT Developername , Name FROM EmailTemplate WHERE DeveloperName =:developerNameValue LIMIT 1] ;
        
        Profile p1=[SELECT Id From Profile WHERE Name='Post Sales'];
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User u2 =new User( Alias = uniqueName.substring(18, 23),
                          Email = uniqueName + '@test' + orgId + '.org',
                          EmailEncodingKey = 'UTF-8',
                          LastName = 'Testing',
                          Username = uniqueName + '@test' + orgId + '.org',
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', // changed for to avoid: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, Locale: bad value for restricted picklist field: America/Los_Angeles
                          
                          ProfileId=p1.Id,
                          TimeZoneSidKey    = 'America/Los_Angeles');
        insert u2;  
        
        Project__c projObj = new Project__c();
        projObj.Name = 'test project';
        projObj.Last_Invoice_Number__c = 1;
        projobj.Post_Sales_Head__c = u2.Id;
        projobj.Budgets__c = 'above 3.5 crs';
        projobj.Configuration__c = '1 BHK';
        projobj.Project_Carpet_Area__c = '475 - 1 BHK;900 - 3 BHk';
        insert projObj;
        
        Test.startTest();
        
        Id PersonRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account accountObject = new Account();
        accountObject.FirstName = 'test';
        accountObject.LastName = 'Account';
        accountObject.BillingCountry = 'India';
        accountObject.Phone = '455546565';
        accountObject.RecordTypeId = PersonRecId;
        accountObject.PersonEmail = 'dynamix.project@gmail.com';
        accountObject.Aadhar_No__pc = '458785698547';
        accountObject.PAN_No__c = 'ABCTY1234D';
        accountObject.PAN_No__pc = 'ABCTY1234D';
        accountObject.Aadhar_Uploaded__pc = true;
        accountObject.PAN_Card_Uploaded__pc = true;
        accountObject.PersonMobilePhone ='8989898989';
        insert accountObject;
        
        Account accountObject1 = new Account();
        accountObject1.FirstName = 'test';
        accountObject1.LastName = 'Account';
        accountObject1.BillingCountry = 'India';
        accountObject1.Phone = '455546565';
        accountObject1.RecordTypeId = PersonRecId;
        accountObject1.PersonEmail = 'dynamix.project@gmail.com';
        accountObject1.Aadhar_No__pc = '458785698549';
        accountObject.PAN_No__c = 'ABCTY1234D';
        accountObject1.PAN_No__pc = 'ABCTY1234C';
        accountObject1.Aadhar_Uploaded__pc = true;
        accountObject1.PAN_Card_Uploaded__pc = true;
        accountObject1.PersonMobilePhone ='7789898989';
        insert accountObject1;
        
        Opportunity oppoObject = new Opportunity();
        oppoObject.AccountId = accountObject.Id;
        oppoObject.Name = 'test Opportunity';
        oppoObject.StageName = 'Site Visit';
        oppoObject.CloseDate = System.Today()+3;
        oppoObject.Walk_in_Source__c = 'Channel Partner';
        oppoObject.Project__c = projObj.Id;
        oppoObject.OwnerId = u2.Id;
        insert oppoObject;
        
        Booking__c bookingObject = new Booking__c();
        bookingObject.Stage__c = 'Registration';
        bookingObject.cancellation_fees__c=10000;
        bookingObject.Registration_Status__c = 'Not Started';
        bookingObject.Index_II_Document__c = true;
        bookingObject.Primary_Applicant__c = accountObject.id;
        bookingObject.Sales_Manager__c = oppoObject.OwnerId;
        bookingObject.Related_Opportunity__c = oppoObject.Id;
        insert bookingObject;
        
        Co_Applicant__c ca = new Co_Applicant__c();
        ca.Account__c = accountObject1.id;
        ca.Role__c = 'Co-Applicant';
        ca.Booking__c = bookingObject.id;
        //insert ca;
        
        bookingObject.Stage__c = 'Booked';
        bookingObject.Primary_Applicant__c = accountObject.id;
        update bookingObject;        
        Test.stopTest();
        
    }
    
    
}