dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Name_Formulla__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name_Formulla__c</fullName>
    <formula>IF( Primary_Applicant__r.FirstName &lt;&gt; null &amp;&amp;  Primary_Applicant__r.FirstName &lt;&gt; &apos;&apos;,  Primary_Applicant__r.FirstName+&apos; &apos;+ Primary_Applicant__r.LastName, Primary_Applicant__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Applicant Name Formulla</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <formula>Project_Name__r.Project_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Email</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name_Formulla__c.field-meta.xml
<CustomField>
    <fullName>Project_Name_Formulla__c</fullName>
    <formula>Project_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name Formulla</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Record_Link__c.field-meta.xml
<CustomField>
    <fullName>Record_Link__c</fullName>
    <formula>$Label.Booking_Form_Link+&quot;?Id=&quot;+Id+&quot;&amp;submitted=customer&quot;</formula>
    <label>Record Link</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Suggested_Property__c.field-meta.xml
<CustomField>
    <fullName>Related_Suggested_Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Suggested Property</label>
    <referenceTo>Suggested_Property__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <formula>Related_Suggested_Property__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Number</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Builder_Organisation__c/Builder_Organisation__c.object-meta.xml
<CustomObject>
    <label>Builder Organisation</label>
    <nameField>
        <label>Builder Organisation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builder Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
            <value>
                <fullName>Annexures</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Builder_Organization__c.field-meta.xml
<CustomField>
    <fullName>Builder_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Builder Organization</label>
    <referenceTo>Builder_Organisation__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <label>Project Email</label>
    <type>Email</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit No.</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/Suggested_Property__c.object-meta.xml
<CustomObject>
    <label>Suggested Property</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Suggestion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suggested Property</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <formula>Unit__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Suggested Property</relationshipLabel>
    <relationshipName>Suggested_Property</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/classes/SendBookingEmail.cls
public class SendBookingEmail {
    @future(Callout=true)
    public static void SendEmail(string bookingId, string ContentDocumentId) {
        
        String AttachmentName;
        Blob Data;
        String filetype;
        String AttcacmentNameAnnexure;
        Blob DataAnnexure;
        String fileTypeAnnexure;
        /*PageReference ref = Page.BookingForm;
        ref.getParameters().put('id', bookingId);*/
        
        Booking__c bookingRcd = [select Id, Name,Primary_Applicant__c,Related_Opportunity__c,Unit_Number__c,Project_Name_Formulla__c,
                                 Related_Opportunity__r.Owner.Name,Related_Opportunity__r.Owner.Email,Related_Opportunity__r.Owner.Id,Project_Name__c,Project_Name__r.Builder_Organization__r.Name,Primary_Applicant__r.PersonMobilePhone,Primary_Applicant__r.PersonEmail,
                                 Primary_Applicant_Name_Formulla__c,Related_Suggested_Property__r.Unit__c,Record_Link__c,Project_Name__r.Project_Email__c,Project_Name__r.Name,Primary_Applicant__r.PersonContactId FROM Booking__c WHERE Id=: bookingId];
        System.debug('bookingRcd:'+bookingRcd);
        
        /*Blob body; 
        
        if(Test.isRunningTest()){
            body = Blob.valueOf('Booking Form'); 
        }
        else{
            body = ref.getContent();
        }
            
                
        ContentVersion conVe = new ContentVersion();
        conVe.ContentLocation = 'S'; 
        conVe.PathOnClient =  'BookingForm.pdf';
        conVe.Title =  'BookingForm.pdf';
        conVe.VersionData = body;
        conVe.SObjectType__c = 'Booking__c';
        conVe.Document_Type__c = 'Booking Form';
        insert conVe; 
    
        Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVe.Id].ContentDocumentId;
        System.debug('conDoc----------->'+conDoc);
        
        ContentDocumentLink conDocLink = New ContentDocumentLink();
        conDocLink.LinkedEntityId = bookingId; 
        conDocLink.ContentDocumentId = conDoc;  
        conDocLink.shareType = 'V';
        insert conDocLink;*/
        
        //for send Email to Customer
        List<String> toMailList = New List<String>();
        if(bookingRcd.Primary_Applicant__c!=null){
            Account customerRecord=[Select Id,Name,PersonEmail From Account Where Id=:bookingRcd.Primary_Applicant__c];
            System.debug('customerRecord:'+customerRecord);
            EmailTemplate emailTemplate = [select Id,Name, Subject, HtmlValue, Body,DeveloperName from EmailTemplate where DeveloperName = 'generatr_Booking_form_mail' LIMIT 1];
            System.debug('emailTemplate:'+emailTemplate);

            String projectLink='';
            String projectName='';
            if(bookingRcd.Project_Name__c!=null){
                projectLink = URL.getOrgDomainUrl().toExternalForm() + '/' + bookingRcd.Project_Name__c;
                projectName = '<a href="'+projectLink+'">'+bookingRcd.Project_Name_Formulla__c+'</a>';
            }
            String bookLink='';
            String bookName='';
            if(bookingRcd.Name!=null){
                bookLink = URL.getOrgDomainUrl().toExternalForm() + '/' + bookingRcd.Id;
                bookName = '<a href="'+bookLink+'">'+bookingRcd.Name+'</a>';
            }
            
            String htmlBody = emailTemplate.HtmlValue;
            htmlBody = htmlBody.replace('{!Name}',bookName);
            if(customerRecord.Name != null){
                htmlBody = htmlBody.replace('{!SM}', customerRecord.Name);
            }
            if(bookingRcd.Project_Name__r.Builder_Organization__r.Name != null){
                htmlBody = htmlBody.replace('{!builderOrgName}', bookingRcd.Project_Name__r.Builder_Organization__r.Name);
            }
            if(bookingRcd.Related_Opportunity__r.Owner.Email != null){
                htmlBody = htmlBody.replace('{!OEmail}', bookingRcd.Related_Opportunity__r.Owner.Email);
            }
            if(bookingRcd.Related_Opportunity__r.Owner.Name != null){
                htmlBody = htmlBody.replace('{!OName}', bookingRcd.Related_Opportunity__r.Owner.Name);
            }
            if(bookingRcd.Project_Name_Formulla__c != null){
                htmlBody = htmlBody.replace('{!Project}', projectName);
            }
            if(bookingRcd.Unit_Number__c != null){
                htmlBody = htmlBody.replace('{!Unit}', bookingRcd.Unit_Number__c);
            }
            
            String plainBody = emailTemplate.Body;
            
            plainBody = plainBody.replace('{!Name}',bookName); 
            if(customerRecord.Name != null){
                plainBody = plainBody.replace('{!SM}', customerRecord.Name);
            }
            if(bookingRcd.Project_Name__r.Builder_Organization__r.Name != null){
                plainBody = plainBody.replace('{!builderOrgName}', bookingRcd.Project_Name__r.Builder_Organization__r.Name);
            }
            if(bookingRcd.Related_Opportunity__r.Owner.Name != null){
                plainBody = plainBody.replace('{!OName}', bookingRcd.Related_Opportunity__r.Owner.Name);
            }
            if(bookingRcd.Related_Opportunity__r.Owner.Email != null){
                plainBody = plainBody.replace('{!OEmail}', bookingRcd.Related_Opportunity__r.Owner.Email);
            }
            if(bookingRcd.Project_Name_Formulla__c != null){
                plainBody = plainBody.replace('{!Project}', projectName);
            }
            if(bookingRcd.Unit_Number__c != null){
                plainBody = plainBody.replace('{!Unit}', bookingRcd.Unit_Number__c);
            }
            
            List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();
            
            Contentversion conVer = [select id,ContentDocumentId,Title,VersionData,FileType from Contentversion where 
                                     ContentDocumentId = :ContentDocumentId];
            
            Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
            String Title = bookingRcd.Name+'/'+conVer.Title+'.'+ conVer.FileType;
            efa.setFileName(Title);
            efa.setBody(conVer.VersionData);
            attachments.add(efa);
            
            //for send Email to Customer
        // Terms and Conditions Attchment
        List<id> ContentDocumentidsTC = new List<id>();

         for(contentDocumentLink CDLink : [SELECT LinkedEntityid, ContentDocumentid FROM contentDocumentLink WHERE LinkedEntityid=:bookingRcd.Project_Name__c ])
        {
            ContentDocumentidsTC.add(CDLink.ContentDocumentid);  
        }
        if (ContentDocumentidsTC != null && !ContentDocumentidsTC.isEmpty()) {
    	List<ContentVersion> cvList = [SELECT title, PathOnClient, FileType, versiondata, Document_Type__c,SObjectType__c
                                   FROM contentversion 
                                   WHERE ContentDocumentId IN :ContentDocumentidsTC order by CreatedDate desc limit 1];
            if (cvList != null && !cvList.isEmpty()){
                for (ContentVersion cv1 : cvList){
                    if(cv1.Document_Type__c=='Terms & Conditions' && cv1.SObjectType__c=='Project__c'){
                	Data = cv1.VersionData;
             		AttachmentName = cv1.Title;
                    filetype = cv1.FileType;
            }
            Messaging.EmailFileAttachment efa1 = new Messaging.EmailFileAttachment();
            efa1.setFileName(AttachmentName+'.'+filetype);
            efa1.setBody(Data);
            attachments.add(efa1);
                }
            }
            
            
        } else {
            System.debug('List has no rows');
        }
        
        //Annexures Attchment
        //
        List<id> ContentDocumentidsAnnexure = new List<id>();
        for(contentDocumentLink CDLink : [SELECT LinkedEntityid, ContentDocumentid FROM contentDocumentLink WHERE LinkedEntityid=:bookingRcd.Related_Suggested_Property__r.Unit__c])
        {
            ContentDocumentidsAnnexure.add(CDLink.ContentDocumentid);  
        }
        
        if (ContentDocumentidsAnnexure != null && !ContentDocumentidsAnnexure.isEmpty()){
            List<ContentVersion> cvList2 = [SELECT title, PathOnClient, FileType, versiondata, Document_Type__c,SObjectType__c
                                   FROM contentversion 
                                   WHERE ContentDocumentId IN :ContentDocumentidsAnnexure order by CreatedDate desc limit 1];
            if (cvList2 != null && !cvList2.isEmpty()){
                for (ContentVersion cv2 : cvList2){
                    if(cv2.Document_Type__c=='Annexures' && cv2.SObjectType__c=='Property__c'){
                	DataAnnexure = cv2.VersionData;
             		AttcacmentNameAnnexure = cv2.Title;
                    fileTypeAnnexure = cv2.FileType;
            }
            Messaging.EmailFileAttachment efa2 = new Messaging.EmailFileAttachment();
            efa2.setFileName(AttcacmentNameAnnexure+'.'+fileTypeAnnexure);
            efa2.setBody(DataAnnexure);
            attachments.add(efa2);
            }
        }
        
        }
            
            
            OrgWideEmailAddress orgEmail;
            List<OrgWideEmailAddress> orgEmailList = [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress WHERE Address = :bookingRcd.Project_Name__r.Project_Email__c];
            if (!orgEmailList.isEmpty()) {
                orgEmail = orgEmailList[0];
            } else {
            }

            //OrgWideEmailAddress orgEmail = [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress WHERE Address = :bookingRcd.Project_Name__r.Project_Email__c];
            System.debug('orgEmail---->'+orgEmail);
            
            
            String Subject = emailTemplate.Subject;
            system.debug('subject ---'+emailTemplate.Subject);
            Subject = Subject.replace('{!Project}', bookingRcd.Project_Name__r.Name);
            Subject = Subject.replace('{!Unit}', bookingRcd.Unit_Number__c);
            
            List<Id> idList = new List<Id>();
                idList.add(conVer.Id);
            
            List<Messaging.SingleEmailMessage> emailMsgList = New List<Messaging.SingleEmailMessage>();

            if(bookingRcd.Primary_Applicant__r.PersonEmail != '' &&  bookingRcd.Primary_Applicant__r.PersonEmail != null)
            {   toMailList.add(bookingRcd.Primary_Applicant__r.PersonEmail );
                //Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(String.Valueof(emailTemplate.Id), bookingRcd.Primary_Applicant__r.PersonContactId, bookingRcd.id);
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setHtmlBody(htmlBody);
                email.setPlainTextBody(plainBody);
                //email.setTargetObjectId(bookingRcd.Primary_Applicant__c);
                email.setToAddresses(toMailList);
                //email.setOrgWideEmailAddressId(orgEmail.Id);
                if (orgEmail != null) {
                    email.setOrgWideEmailAddressId(orgEmail.Id);
                } else {
                    System.debug('orgEmail.Id------>'+email);
                }
                email.setFileAttachments(attachments);
                email.setSubject(Subject);
                emailMsgList.add(email);
            }
            if (emailMsgList.size() > 0) 
            {
                Messaging.SendEmailResult[] results = Messaging.sendEmail(emailMsgList);
                if(results[0].success)
                {
                    System.debug('The email was sent successfully.');
                }
                else {
                    System.debug('The email failed to send: ' +  results[0].errors[0].message);
                } 
            }
            
            /*if(emailTemplate!=null && customerRecord.PersonEmail!=null){                
                List<String> emailList=new List<String>();           
                emailList.add(customerRecord.PersonEmail);            
                SendEmailandBellNotificationUtility.SendEmail(emailTemplate.Id,htmlBody,plainBody,emailList,null);           
            }*/
        }   
    }
}