dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Name_Formulla__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name_Formulla__c</fullName>
    <formula>IF( Primary_Applicant__r.FirstName &lt;&gt; null &amp;&amp;  Primary_Applicant__r.FirstName &lt;&gt; &apos;&apos;,  Primary_Applicant__r.FirstName+&apos; &apos;+ Primary_Applicant__r.LastName, Primary_Applicant__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Applicant Name Formulla</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name_Formulla__c.field-meta.xml
<CustomField>
    <fullName>Project_Name_Formulla__c</fullName>
    <formula>Project_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name Formulla</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Phone__c.field-meta.xml
<CustomField>
    <fullName>Project_Phone__c</fullName>
    <formula>Project_Name__r.Project_Phone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Phone</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Record_Link__c.field-meta.xml
<CustomField>
    <fullName>Record_Link__c</fullName>
    <formula>$Label.Booking_Form_Link+&quot;?Id=&quot;+Id+&quot;&amp;submitted=customer&quot;</formula>
    <label>Record Link</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Suggested_Property__c.field-meta.xml
<CustomField>
    <fullName>Related_Suggested_Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Suggested Property</label>
    <referenceTo>Suggested_Property__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <formula>Related_Suggested_Property__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Number</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/communicat_o__Registered_Template__mdt/communicat_o__Registered_Template__mdt.object-meta.xml
<CustomObject>
    <label>Registered Template</label>
    <pluralLabel>Registered Templates</pluralLabel>
</CustomObject>

dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
            <value>
                <fullName>Annexures</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Phone__c.field-meta.xml
<CustomField>
    <fullName>Project_Phone__c</fullName>
    <label>Project Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Site_Head__c.field-meta.xml
<CustomField>
    <fullName>Site_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit No.</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/Suggested_Property__c.object-meta.xml
<CustomObject>
    <label>Suggested Property</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Suggestion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suggested Property</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <formula>Unit__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Site_Head__c.field-meta.xml
<CustomField>
    <fullName>Site_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Suggested_Property</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Suggested Property</relationshipLabel>
    <relationshipName>Suggested_Property</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/classes/SendBookingFormToCustomer.cls
public class SendBookingFormToCustomer {
    @InvocableMethod(label='Send BookingForm To Customer')
    public static void execute(List<Request> Requests){
        String AttachmentName;
        Blob Data;
        String filetype;
        String AttcacmentNameAnnexure;
        Blob DataAnnexure;
        String fileTypeAnnexure;
        //for send Booking Form Link Email to SM
        Booking__c bookingRcd = [select Id, Name,Related_Suggested_Property__r.Unit__c,Primary_Applicant__c,Project_Phone__c,Related_Opportunity__c,Unit_Number__c,Project_Name_Formulla__c,Related_Opportunity__r.Owner.Name,Related_Opportunity__r.Owner.Id,Project_Name__c,Primary_Applicant__r.PersonMobilePhone,Primary_Applicant_Name_Formulla__c,Record_Link__c FROM Booking__c WHERE Id=: Requests[0].bookingRecodId];
        System.debug('bookingRcd:'+bookingRcd);
        // Get the Id for our custom notification type
        CustomNotificationType notificationType = [SELECT Id, DeveloperName FROM CustomNotificationType WHERE DeveloperName='Booking_Form_Notification']; 
        
        if(bookingRcd.Project_Name__c!=null){
            Project__c projectRecod=[Select Id,Name,Site_Head__c,Site_Head__r.Id From Project__c Where Id=:bookingRcd.Project_Name__c];
            //For Send Bell Notification to Site Head
            if(notificationType!=null && projectRecod.Site_Head__r.Id!=null){
                String notificationTitle1='Booking Form Mail Sent';
                String notificationBody1='Booking Form has been sent to Customer for Booking: '+ bookingRcd.Name;
                String targetId1=bookingRcd.Id;
                Set <String> recipientIds1= new Set <String> ();
                if(projectRecod.Site_Head__r.Id!=null){
                    recipientIds1.add(projectRecod.Site_Head__r.Id);
                }
                SendEmailandBellNotificationUtility.SendBellNotification(notificationType.Id, notificationTitle1, notificationBody1, targetId1, recipientIds1);
            }            
        }
        //For Send Bell Notification to SM (Opportunity Owner)
        if(notificationType!=null && bookingRcd.Related_Opportunity__r.Owner.Id!=null){
            String notificationTitle='The Application Form Generated';
            // String notificationBody='Booking Form has been sent to Customer for Booking: '+ bookingRcd.Name;
            
            String notificationBody='Dear '+ bookingRcd.Related_Opportunity__r.Owner.Name+',\n'+ 
                'The Application Form for '+bookingRcd.Unit_Number__c+' in '+bookingRcd.Project_Name_Formulla__c+' has been generated to share with customer.\n'+
                'Kindly fill the necessary details and share the same with the customer at the earliest.';
            
            String targetId=bookingRcd.Id;
            Set <String> recipientIds= new Set <String> ();
            if(bookingRcd.Related_Opportunity__r.Owner.Id!=null){
                recipientIds.add(bookingRcd.Related_Opportunity__r.Owner.Id);
            }
            SendEmailandBellNotificationUtility.SendBellNotification(notificationType.Id, notificationTitle, notificationBody, targetId, recipientIds);
        }
        
        //for send Email to Customer
        // Terms and Conditions Attchment
        List<id> ContentDocumentidsTC = new List<id>();

         for(contentDocumentLink CDLink : [SELECT LinkedEntityid, ContentDocumentid FROM contentDocumentLink WHERE LinkedEntityid=:bookingRcd.Project_Name__c ])
        {
            ContentDocumentidsTC.add(CDLink.ContentDocumentid);  
        }
        if (ContentDocumentidsTC != null && !ContentDocumentidsTC.isEmpty()) {
            List<ContentVersion> cvList = [SELECT title, PathOnClient, FileType, versiondata, Document_Type__c,SObjectType__c
                                           FROM contentversion 
                                           WHERE ContentDocumentId IN :ContentDocumentidsTC 
                                           AND Document_Type__c ='Terms & Conditions' AND
                                           SObjectType__c ='Project__c'
                                           order by CreatedDate desc limit 1];
            if (cvList != null && !cvList.isEmpty()){
                for (ContentVersion cv : cvList){
                    Data = cv.VersionData;
                    AttachmentName = cv.Title;
                    filetype = cv.FileType;
                    
                }
            }
            
            
        } else {
            System.debug('List has no rows');
        }
        
        //Annexures Attchment
        //
        List<id> ContentDocumentidsAnnexure = new List<id>();
        for(contentDocumentLink CDLink : [SELECT LinkedEntityid, ContentDocumentid FROM contentDocumentLink WHERE LinkedEntityid=:bookingRcd.Related_Suggested_Property__r.Unit__c])
        {
            ContentDocumentidsAnnexure.add(CDLink.ContentDocumentid);  
        }
        
        if (ContentDocumentidsAnnexure != null && !ContentDocumentidsAnnexure.isEmpty()){
            List<ContentVersion> cvList1 = [SELECT title, PathOnClient, FileType, versiondata, Document_Type__c,SObjectType__c
                                            FROM contentversion 
                                            WHERE ContentDocumentId IN :ContentDocumentidsAnnexure 
                                            AND Document_Type__c= 'Annexures'
                                            AND SObjectType__c= 'Property__c'
                                            order by CreatedDate desc limit 1];
            if (cvList1 != null && !cvList1.isEmpty()){
                for (ContentVersion cv1 : cvList1){
                    DataAnnexure = cv1.VersionData;
                    AttcacmentNameAnnexure = cv1.Title;
                    fileTypeAnnexure = cv1.FileType;
                }
            }
            
        }
        //ContentVersion cv = [SELECT title,PathOnClient, FileType,
                                                //versiondata 
                                          //FROM contentversion 
                                          //WHERE ContentDocumentId IN :ContentDocumentids  
                                           //];
        
        
        if(bookingRcd.Primary_Applicant__c!=null){
            Account customerRecord=[Select Id,Name,PersonEmail From Account Where Id=:bookingRcd.Primary_Applicant__c];
            System.debug('customerRecord:'+customerRecord);
            EmailTemplate emailTemplate = [select Id,Name, Subject, HtmlValue, Body,DeveloperName from EmailTemplate where DeveloperName = 'Booking_Form_Link_Email' LIMIT 1];
            System.debug('emailTemplate:'+emailTemplate);
            
            String bookingFormLink = Label.Booking_Form_Link;
            bookingFormLink+='?Id='+bookingRcd.Id+'&submitted=customer';
            String Link = '<a href="'+bookingFormLink+'">'+bookingFormLink+'</a>';
            System.debug('Link:'+Link);
            
            
            String projectLink='';
            String projectName='';
            if(bookingRcd.Project_Name__c!=null){
                projectLink = URL.getOrgDomainUrl().toExternalForm() + '/' + bookingRcd.Project_Name__c;
                projectName = '<a href="'+projectLink+'">'+bookingRcd.Project_Name_Formulla__c+'</a>';
            }
            String bookLink='';
            String bookName='';
            if(bookingRcd.Name!=null){
                bookLink = URL.getOrgDomainUrl().toExternalForm() + '/' + bookingRcd.Id;
                bookName = '<a href="'+bookLink+'">'+bookingRcd.Name+'</a>';
            }
            
            String htmlBody = emailTemplate.HtmlValue;
            htmlBody = htmlBody.replace('{!Name}',bookName);
            if(customerRecord.Name != null){
                htmlBody = htmlBody.replace('{!SM}', customerRecord.Name);
            }
            if(Link != null){
                htmlBody = htmlBody.replace('{!Link}', Link);
            }
            if(bookingRcd.Project_Name_Formulla__c != null){
                htmlBody = htmlBody.replace('{!Project}', projectName);
            }
            if(bookingRcd.Unit_Number__c != null){
                htmlBody = htmlBody.replace('{!Unit}', bookingRcd.Unit_Number__c);
            }

            String plainBody = emailTemplate.Body;
            
            plainBody = plainBody.replace('{!Name}',bookName); 
            if(customerRecord.Name != null){
                plainBody = plainBody.replace('{!SM}', customerRecord.Name);
            }
            if(Link != null){
                plainBody = plainBody.replace('{!Link}', Link);
            }
            if(bookingRcd.Project_Name_Formulla__c != null){
                plainBody = plainBody.replace('{!Project}', projectName);
            }
            if(bookingRcd.Unit_Number__c != null){
                plainBody = plainBody.replace('{!Unit}', bookingRcd.Unit_Number__c);
            }
            if(emailTemplate!=null && customerRecord.PersonEmail!=null){                
                List<String> emailList=new List<String>();           
                emailList.add(customerRecord.PersonEmail);            
                SendEmailandBellNotificationUtility.SendEmail4(emailTemplate.Id,htmlBody,plainBody,emailList,null,true,bookingRcd.Id,Data,AttachmentName,null,filetype,fileTypeAnnexure,AttcacmentNameAnnexure,DataAnnexure);           
            }
        }
        
        //For Send WhatsApp Message
        communicat_o__Registered_Template__mdt regWhatEmailTemp=[Select Id,QualifiedApiName,label From communicat_o__Registered_Template__mdt Where label=:'WhatsApp Booking Form Link Sent' Limit 1];
        System.debug('regWhatEmailTemp:'+regWhatEmailTemp);
        if(regWhatEmailTemp!=null){
            String recipientAddress=bookingRcd.Primary_Applicant__r.PersonMobilePhone;
            String recipientId=bookingRcd.Primary_Applicant__c;
            String emailTemplateId=String.valueOf(regWhatEmailTemp.Id).substring(0, 15);
            String relatedToId=bookingRcd.Id;
            System.debug('emailTemplateId:'+emailTemplateId);
            if(recipientAddress!=null && recipientId!=null && emailTemplateId!=null){
                SendWhatsAppMessageUtility.SendMessage(recipientAddress, recipientId, emailTemplateId,relatedToId);
            }
        }
        //for Send SMS
        EmailTemplate smsEmailTemp=[Select Id,Name,HtmlValue From EmailTemplate Where Name='SMS Booking Form Link Sent' Limit 1];
        if(smsEmailTemp!=null && bookingRcd.Primary_Applicant__r.PersonMobilePhone!=null){
            String templateBody=smsEmailTemp.HtmlValue;
            String mobileNumber=bookingRcd.Primary_Applicant__r.PersonMobilePhone;
            templateBody = templateBody.replace('{{{Booking__c.Primary_Applicant_Name_Formulla__c}}}',bookingRcd.Primary_Applicant_Name_Formulla__c);
            templateBody = templateBody.replace('{{{Booking__c.Name}}}',bookingRcd.Name);
            templateBody = templateBody.replace('{{{Booking__c.Record_Link__c}}}',' ');
            templateBody=templateBody.stripHtmlTags();
            System.debug('templateBody:'+templateBody);
            if(!test.isRunningTest())
            {
                SendSMSUtility.sendSMS(templateBody,mobileNumber,'DYNAMX');
            }
          
        }
    }
    public class Request {
        @InvocableVariable(label='Booking Record Id' required=true)
        public Id bookingRecodId;
    }
}