dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking1</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Co_Applicant__c/Co_Applicant__c.object-meta.xml
<CustomObject>
    <label>Co-Applicant</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Applicant</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Co_Applicant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Co-Applicant</relationshipLabel>
    <relationshipName>Co_Applicant</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Co_Applicant__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Co-Applicant</relationshipLabel>
    <relationshipName>Co_Applicant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/Data_Sync__c.object-meta.xml
<CustomObject>
    <label>Data_Sync</label>
    <nameField>
        <displayFormat>DS-{0000000}</displayFormat>
        <label>Data_Sync Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data_Syncs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/classes/CallOutCustomerCreationTest.cls
@isTest
public class CallOutCustomerCreationTest {
    @isTest
    static void testCalledFromTransactionFlow() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Sales Manager'];
        User testUser = new User(
            Alias = 'testUser',
            Email = 'testuser1@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Test',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'America/Los_Angeles',
            ProfileId = p.Id,
            UserName = 'Chandlal0099@gmail.com'
        );
        insert testUser;
        
        Account accountObject = new Account();
        accountObject.Name = 'test Account';
        accountObject.BillingCountry = 'India';
        accountObject.Phone = '455546565';
        insert accountObject;
        
        Project__c projectObject = new Project__c();
        projectObject.Name = 'Test Project';
        insert projectObject;
        
        Opportunity oppoObject = new Opportunity();
        oppoObject.AccountId = accountObject.Id;
        oppoObject.Project__c = projectObject.Id;
        oppoObject.Name = 'test Opportunity';
        oppoObject.StageName = 'Site Visit';
        oppoObject.Sales_Manager__c = testUser.Id;
        oppoObject.CloseDate = System.Today()+3;
        insert oppoObject;
        
        Booking__c testBook = new Booking__c();
        testBook.Project_Name__c = projectObject.Id;
        testBook.Related_Opportunity__c = oppoObject.Id;
        insert testBook;

        Co_Applicant__c testCoApplicant = new Co_Applicant__c();
        testCoApplicant.Role__c = 'Primary';
        testCoApplicant.Account__c = accountObject.Id;
        testCoApplicant.Booking__c = testBook.Id;
        insert testCoApplicant;

        callOutCustomerCreation.request testRequest = new callOutCustomerCreation.request();
        testRequest.bookingIds = new List<String>{ testBook.Id };

        Test.startTest();
        callOutCustomerCreation.calledFromTransactionFLow(new List<callOutCustomerCreation.request>{ testRequest });
        Test.stopTest();

        List<Data_Sync__c> dataSyncRecords = [SELECT Id, Status__c FROM Data_Sync__c WHERE RecordId__c = :testCoApplicant.Id];
        //System.assertEquals(1, dataSyncRecords.size());
        //System.assertEquals('In Progress', dataSyncRecords[0].Status__c);
    }

    @isTest
    static void testGenerateSapCodeForCoApplicant() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Sales Manager'];
        User testUser = new User(
            Alias = 'testUser',
            Email = 'testuser1@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Test',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'America/Los_Angeles',
            ProfileId = p.Id,
            UserName = 'Chandlal0099@gmail.com'
        );
        insert testUser;
        
        Account accountObject = new Account();
        accountObject.RecordTypeId = [select Id from recordtype where developerName = 'PersonAccount' ].Id;
        accountObject.LastName = 'Account';
        accountObject.BillingCountry = 'India';
        accountObject.Phone = '455546565';
        accountObject.FirstName = 'Test';
        accountObject.PersonBirthdate = system.today() - 30;
        accountObject.PersonMobilePhone = '9856984569';
        insert accountObject;
        
        Account accountObject1 = new Account();
        accountObject1.RecordTypeId = [select Id from recordtype where developerName = 'PersonAccount' ].Id;
        accountObject1.FirstName = 'Test';
        accountObject1.LastName = 'test Account';
        accountObject1.BillingCountry = 'India';
        accountObject1.Phone = '455546565';
        accountObject1.PersonBirthdate = system.today() - 30;
        accountObject1.PersonMobilePhone = '9856984573';
        insert accountObject1;
        
        Project__c projectObject = new Project__c();
        projectObject.Name = 'Test Project';
        insert projectObject;
        
        Opportunity oppoObject = new Opportunity();
        oppoObject.AccountId = accountObject.Id;
        oppoObject.Project__c = projectObject.Id;
        oppoObject.Name = 'test Opportunity';
        oppoObject.StageName = 'Site Visit';
        oppoObject.Sales_Manager__c = testUser.Id;
        oppoObject.CloseDate = System.Today()+3;
        insert oppoObject;
        
        Booking__c testBook = new Booking__c();
        testBook.Project_Name__c = projectObject.Id;
        testBook.Related_Opportunity__c = oppoObject.Id;
        insert testBook;

        Co_Applicant__c testCoApplicant = new Co_Applicant__c();
        testCoApplicant.Role__c = 'Primary';
        testCoApplicant.Account__c = accountObject.Id;
        testCoApplicant.Booking__c = testBook.Id;
        insert testCoApplicant;
        
        Co_Applicant__c testCoApplicant1 = new Co_Applicant__c();
        testCoApplicant1.Role__c = 'Co-Applicant';
        testCoApplicant1.Account__c = accountObject1.Id;
        testCoApplicant1.Booking__c = testBook.Id;
        insert testCoApplicant1;

        Test.startTest();
        callOutCustomerCreation.generateSapCodeForCoApplicant(testBook.Id);
        Test.stopTest();
    }

    @isTest
    static void testGetSapCodes() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Test.startTest();
        callOutCustomerCreation.getSapCodes('{"sample": "json"}', new Set<String>{'coAppId'});
        Test.stopTest();

        List<Data_Sync__c> dataSyncRecords = [SELECT Id, Status__c FROM Data_Sync__c WHERE RecordId__c = 'coAppId'];
    }
}