dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <formula>Project_Name__r.Project_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Email</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Builder_Organisation__c/Builder_Organisation__c.object-meta.xml
<CustomObject>
    <label>Builder Organisation</label>
    <nameField>
        <label>Builder Organisation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Builder Organisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Builder_Organisation__c/fields/Builder_Organisation_Initials__c.field-meta.xml
<CustomField>
    <fullName>Builder_Organisation_Initials__c</fullName>
    <label>Builder Organisation Initials</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/KYC_Completed__c.field-meta.xml
<CustomField>
    <fullName>KYC_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>KYC Completed</label>
    <type>Checkbox</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Project_Carpet_Area__c</fullName>
    <label>Desired Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Carpet_Area</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Walk_in_Source__c.field-meta.xml
<CustomField>
    <fullName>Walk_in_Source__c</fullName>
    <label>Walk-in Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Presales</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Referred by Existing Customer</fullName>
            </value>
            <value>
                <fullName>Referred by Others</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Online Ads</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>Newspaper Ad</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>IVR Call</fullName>
            </value>
            <value>
                <fullName>Property Portal</fullName>
            </value>
            <value>
                <fullName>Email/SMS/WhatsApp</fullName>
            </value>
            <value>
                <fullName>Exhibition</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Rechurned Lead</fullName>
            </value>
            <value>
                <fullName>Magicbricks</fullName>
            </value>
            <value>
                <fullName>99 Acres</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Passing By</fullName>
                <isActive>false</isActive>
                <label>Passing By</label>
            </value>
            <value>
                <fullName>Referral</fullName>
                <isActive>false</isActive>
                <label>Referral</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <formula>Project_Progress__r.Invoice_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <formula>Booking__r.Project_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Email</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Project_Progress__c.field-meta.xml
<CustomField>
    <fullName>Project_Progress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Progress</label>
    <referenceTo>Project_Progress__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Budgets__c.field-meta.xml
<CustomField>
    <fullName>Budgets__c</fullName>
    <label>Budgets</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Budget</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Builder_Organization__c.field-meta.xml
<CustomField>
    <fullName>Builder_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Builder Organization</label>
    <referenceTo>Builder_Organisation__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/OTP_Disable_Till__c.field-meta.xml
<CustomField>
    <fullName>OTP_Disable_Till__c</fullName>
    <label>OTP Disable Till</label>
    <type>DateTime</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Project_Carpet_Area__c</fullName>
    <label>Project Carpet Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Carpet_Area</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <label>Project Email</label>
    <type>Email</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Header__c.field-meta.xml
<CustomField>
    <fullName>Project_Header__c</fullName>
    <label>Project Header</label>
    <type>Url</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Initials__c.field-meta.xml
<CustomField>
    <fullName>Project_Initials__c</fullName>
    <label>Project Initials</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Project_Progress__c/Project_Progress__c.object-meta.xml
<CustomObject>
    <label>Project Progress</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Progress__c/fields/Architect_Certification_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Architect_Certification_Received_Date__c</fullName>
    <label>Architect Certification Received Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Project_Progress__c/fields/Progress_Status__c.field-meta.xml
<CustomField>
    <fullName>Progress_Status__c</fullName>
    <label>Progress Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Partially Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project_Progress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Progress</relationshipLabel>
    <relationshipName>Project_Progress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Project_Progress__c/fields/Stage_Type__c.field-meta.xml
<CustomField>
    <fullName>Stage_Type__c</fullName>
    <label>Stage Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plinth</fullName>
            </value>
            <value>
                <fullName>RCC (Slab)</fullName>
            </value>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>Doors</fullName>
            </value>
            <value>
                <fullName>Windows</fullName>
            </value>
            <value>
                <fullName>Sliding</fullName>
            </value>
            <value>
                <fullName>OC</fullName>
            </value>
            <value>
                <fullName>Basement</fullName>
            </value>
            <value>
                <fullName>Podium</fullName>
            </value>
            <value>
                <fullName>habitable floor</fullName>
            </value>
            <value>
                <fullName>Terrace</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Walls</fullName>
            </value>
            <value>
                <fullName>Plaster</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Elevation</fullName>
            </value>
            <value>
                <fullName>Sanitary fittings</fullName>
            </value>
            <value>
                <fullName>Lifts</fullName>
            </value>
            <value>
                <fullName>Lobby</fullName>
            </value>
            <value>
                <fullName>Staircase</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Water pump</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Fit-outs</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Possession</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/globalValueSets/Budget.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Under 75 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 0.7 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.7  - 0.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.8  - 0.9 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>0.9  - 1 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 - 1.1 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 - 1.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.2 - 1.3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.3 - 1.4 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.4 - 1.6 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.6 - 1.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.8 - 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2 - 2.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.2 - 2.4 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.4 - 2.6 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.6 - 2.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.8 - 3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3 Cr &amp; Above</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2 – 2.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.2 – 2.5 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.5 – 2.75 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>2.75 – 3 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3 – 3.2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3.2 – 3.5 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>3.5 – 3.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>4 Cr and Above</fullName>
    </customValue>
    <customValue>
        <fullName>Less than 1.8 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1.8 – 2 Cr</fullName>
    </customValue>
    <customValue>
        <fullName>1 – 1.2 Cr</fullName>
    </customValue>
    <masterLabel>Budget</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/globalValueSets/Carpet_Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>475 - 1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>600 - 2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>900 - 3 BHk</fullName>
    </customValue>
    <customValue>
        <fullName>375 - 400 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>400 – 450 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>450 – 500 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>500 – 550 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>550 – 600 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>600 – 650 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>650 – 700 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>700 – 800 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>700 – 750 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>750 sq.ft. and Above</fullName>
    </customValue>
    <customValue>
        <fullName>750 – 800 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>750 – 850 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>800 – 900 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>850 -- 900 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>900 – 1000 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1000 – 1100 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1100 – 1200 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1200 sq.ft. &amp; Above</fullName>
    </customValue>
    <customValue>
        <fullName>1200 – 1300 sq.ft.</fullName>
    </customValue>
    <customValue>
        <fullName>1300 sq.ft and above</fullName>
    </customValue>
    <masterLabel>Carpet Area</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/globalValueSets/Configuration.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Studio</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK (G)</fullName>
    </customValue>
    <customValue>
        <fullName>1 BHK Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK Jodi</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK Jodi</fullName>
    </customValue>
    <masterLabel>Configuration</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/classes/ProjectProgressHandler_Test.cls
@isTest
public class ProjectProgressHandler_Test {
    @isTest public static void projectProgressTestMethod()
    {   
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        Profile pId = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator' LIMIT 1];        
        User testUserRcd1 = new User();
        testUserRcd1.FirstName = 'Mayur1';
        testUserRcd1.LastName = 'Patel123';
        testUserRcd1.Email = 'mayur.patel@manras.com';
        testUserRcd1.Alias = 'MPatel';
        testUserRcd1.Username = uniqueUserName;
        testUserRcd1.ProfileId = pId.Id;
        testUserRcd1.EmailEncodingKey = 'UTF-8';
        testUserRcd1.Country = 'India';
        testUserRcd1.LanguageLocaleKey='en_US';
        testUserRcd1.LocaleSidKey='en_US';
        testUserRcd1.TimeZoneSidKey='America/Los_Angeles';
        insert testUserRcd1;
        
        Account accountObject = new Account();
        accountObject.Name = 'test Account';
        accountObject.BillingCountry = 'India';
        accountObject.Phone = '455546565';
        insert accountObject;
        
        Builder_Organisation__c bo = new Builder_Organisation__c();
        bo.Builder_Organisation_Initials__c = 'c';
        insert bo;
        
        Project__c projObj = new Project__c();
        projObj.Name = 'test project';
        projObj.Builder_Organization__c = bo.id;
        projObj.Project_Initials__c = 'c';
        projObj.Project_Email__c= 'harshita.sharma@manras.com';
        projObj.Project_Carpet_Area__c = '475 - 1 BHK';
        projObj.Budgets__c = 'Under 75 lakhs';
        projObj.Configuration__c ='1 BHK';
        projObj.OTP_Disable_Till__c = System.now().addDays(1);
        projObj.Project_Header__c = 'abc.com';
        insert projObj;
        
        Opportunity oppoObject = new Opportunity();
        oppoObject.AccountId = accountObject.Id;
        oppoObject.Name = 'test Opportunity';
        oppoObject.StageName = 'Site Visit';
        oppoObject.CloseDate = System.Today()+3;
        oppoObject.KYC_Completed__c = true;
        oppoObject.Project__c = projObj.Id;
        oppoObject.Walk_in_Source__c ='Presales' ;
        insert oppoObject;
        
        List<Project_Progress__c> progressList = new List<Project_Progress__c>(); 
        Project_Progress__c projectProgressObject = new Project_Progress__c();
        projectProgressObject.Name = 'test6543';
        projectProgressObject.Project__c = projObj.Id;
        projectProgressObject.Stage_Type__c = 'Sliding';
        projectProgressObject.Progress_Status__c = 'Completed';
        projectProgressObject.Invoice_Date__c = Date.today();
        projectProgressObject.Architect_Certification_Received_Date__c = Date.today();
        projectProgressObject.Architecture_Certificate__c = true;
        insert projectProgressObject;
        progressList.add(projectProgressObject);
        
        
        
        Booking__c bookingObject = new Booking__c();
        bookingObject.Stage__c= 'Draft';
        bookingObject.Project_Name__c = projObj.id;
        bookingObject.Primary_Applicant__c = accountObject.Id;
        bookingObject.Sales_Manager__c = testUserRcd1.id;
        bookingObject.Related_Opportunity__c = oppoObject.id;
        insert bookingObject;
        
        Co_Applicant__c COP = New Co_Applicant__c();
        COP.Booking__c = bookingObject.Id;
        COP.Account__c = accountObject.Id;
        COP.Role__c = 'Primary';
        Insert COP;
        
        
        Price_Details__c priceDetailObject = new Price_Details__c();
        priceDetailObject.Name = 'Price Test1';
        priceDetailObject.Charge_Group__c= 'Agreement';
        priceDetailObject.GST_Type__c = 'Standard';
        priceDetailObject.Booking__c = bookingObject.Id;
        priceDetailObject.Amount__c = 64000;
        insert priceDetailObject;
        
        Price_Details__c priceDetailObject1 = new Price_Details__c();
        priceDetailObject1.Name = 'Price Test';
        priceDetailObject1.Charge_Group__c= 'Agreement';
        priceDetailObject1.GST_Type__c = 'Standard' ;
        priceDetailObject1.Booking__c = bookingObject.Id;
        priceDetailObject1.Amount__c = 60000;
        insert priceDetailObject1;
        
        Payment_Milestones__c paymentObject = new Payment_Milestones__c();
        paymentObject.Name = 'Test Milestone';
        paymentObject.Project_Progress__c = projectProgressObject.Id;
        paymentObject.Booking__c = bookingObject.Id ;
        paymentObject.Milestone_age__c = 10;
        paymentObject.Sequence_No__c= 2;
        insert paymentObject;
        
        Test.startTest();
        ProjectProgressHandler.projectMethod(progressList);
        Test.stopTest();
    }
}