dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <formula>Project_Name__r.Project_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Email</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Phone__c.field-meta.xml
<CustomField>
    <fullName>Project_Phone__c</fullName>
    <formula>Project_Name__r.Project_Phone__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Phone</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/EOI_CA__c.field-meta.xml
<CustomField>
    <fullName>EOI_CA__c</fullName>
    <label>EOI/CA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/EOI_CA_Number__c.field-meta.xml
<CustomField>
    <fullName>EOI_CA_Number__c</fullName>
    <label>EOI/CA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lost to Competitor</fullName>
            </value>
            <value>
                <fullName>No Budget / Lost Funding</fullName>
            </value>
            <value>
                <fullName>No Decision / Non-Responsive</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Auto cancelled due to business reason</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Reason_for_lost__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_lost__c</fullName>
    <label>Reason for lost</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Budget Mismatch</fullName>
            </value>
            <value>
                <fullName>Possession Timeline Mismatch</fullName>
            </value>
            <value>
                <fullName>Wrong Locality</fullName>
            </value>
            <value>
                <fullName>Configuration Mismatch</fullName>
            </value>
            <value>
                <fullName>Not liked the project</fullName>
            </value>
            <value>
                <fullName>Finds other project better</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Configuration</fullName>
            </value>
            <value>
                <fullName>Developer Issue</fullName>
            </value>
            <value>
                <fullName>Apartment Size</fullName>
            </value>
            <value>
                <fullName>Interested in Resale / Renting property</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>Interested In Another Project</fullName>
            </value>
            <value>
                <fullName>Possession Timeline</fullName>
            </value>
            <value>
                <fullName>Amenities</fullName>
            </value>
            <value>
                <fullName>Home Loan Issue</fullName>
            </value>
            <value>
                <fullName>Low Budget</fullName>
            </value>
            <value>
                <fullName>Own contribution Issue</fullName>
            </value>
            <value>
                <fullName>Not interested in Property</fullName>
            </value>
            <value>
                <fullName>Will Purchase Later</fullName>
            </value>
            <value>
                <fullName>Plan Dropped / Postponed</fullName>
            </value>
            <value>
                <fullName>Booked elsewhere</fullName>
            </value>
            <value>
                <fullName>Future Prospect</fullName>
            </value>
            <value>
                <fullName>Not Contactable / Not Answering</fullName>
            </value>
            <value>
                <fullName>Not Interested after multiple follow-ups</fullName>
            </value>
            <value>
                <fullName>Vastu Issue</fullName>
            </value>
            <value>
                <fullName>Finance Issue</fullName>
            </value>
            <value>
                <fullName>Auto cancelled due to business reason</fullName>
            </value>
            <value>
                <fullName>Corona Job Loss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Launch_CA_Period_s_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Launch_CA_Period_s_End_Date__c</fullName>
    <label>Launch CA Period&apos;s End Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Launch_EOI_Period_s_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Launch_EOI_Period_s_End_Date__c</fullName>
    <label>Launch EOI Period&apos;s End Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <label>Project Email</label>
    <type>Email</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Phone__c.field-meta.xml
<CustomField>
    <fullName>Project_Phone__c</fullName>
    <label>Project Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/classes/BatchforEOIWithoutBooking.cls
public class BatchforEOIWithoutBooking implements Database.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([SELECT Id, Name, StageName, Loss_Reason__c,Project__r.Project_Email__c,EOI_CA__c,
                                         Reason_for_lost__c, AccountId, Account.FirstName, Account.LastName,Account.PersonEmail, 
                                         Project__c,Project__r.Project_Phone__c,Project__r.Name,EOI_CA_Number__c  
                                         FROM Opportunity 
                                         WHERE ((Project__r.Launch_EOI_Period_s_End_Date__c  =: System.today()
                                                 AND EOI_CA__c ='EOI')
                                                Or(Project__r.Launch_CA_Period_s_End_Date__c =: System.today()
                                                   AND EOI_CA__c ='CA') )AND EOI_CA__c != null AND EOI_CA__c != ''
                                         AND StageName != 'Closed Lost'
                                         AND StageName != 'Closed Won']);
    }
    
    public void execute(Database.BatchableContext bc, List<Opportunity> opportunityList){
        Set<Id> opportunityIdSet = New Set<Id>();
        Set<Id> propertyIdSet = New Set<Id>();
        Map<Id,Booking__c> mapOfBooking = New Map<Id,Booking__c>();
        Map<String,Id> OrgWideaddressMap = new Map<String,Id>();
        List<Opportunity> updateOpportunityList = New List<Opportunity>();
        List<Property__c> updatePropertyList = New List<Property__c>();
        List<EmailMessage> insertEmailMessageList = New List<EmailMessage>();
        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();     
        
        String Name = '';
        EmailTemplate emailTemplate = [SELECT Id,Name, Subject, HtmlValue, Body,DeveloperName FROM EmailTemplate WHERE DeveloperName = : 'ForEOIWithoutBooking' LIMIT 1];
        
        for(Opportunity thisOpportunity : opportunityList){
            opportunityIdSet.add(thisOpportunity.id);
        }
        List<OrgWideEmailAddress> ListOWA = [Select Id, Address From OrgWideEmailAddress];
        for(OrgWideEmailAddress OWA:ListOWA){
            OrgWideaddressMap.put(OWA.Address,OWA.Id);
        }
        if(!opportunityIdSet.isEmpty())
        {
            List<Booking__c> bookingList = [SELECT Id, Name, Related_Opportunity__c 
                                            FROM Booking__c 
                                            WHERE Related_Opportunity__c IN: opportunityIdSet];
            if(!bookingList.isEmpty())
            {
                for(Booking__c thisBooking : bookingList)
                {
                    mapOfBooking.put(thisBooking.Related_Opportunity__c,thisBooking);
                    
                }
            }
            for(Opportunity thisOpportunity : opportunityList)
            {
                if(thisOpportunity.Account.FirstName != '' && thisOpportunity.Account.FirstName != null
                   && thisOpportunity.Account.LastName != '' && thisOpportunity.Account.LastName != null)
                {
                    Name = thisOpportunity.Account.FirstName + ' ' +thisOpportunity.Account.LastName;
                }
                else
                {
                    Name = thisOpportunity.Account.LastName; 
                }
                if(!mapOfBooking.containsKey(thisOpportunity.id))
                {
                    if(thisOpportunity.Account.PersonEmail != null && thisOpportunity.Account.PersonEmail != '')
                    {
                        String htmlbody = emailTemplate.HtmlValue;
                        String plainbody = emailTemplate.Body;
                        String subject = emailTemplate.Subject;
                        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                        htmlbody = htmlbody.replace('{customerName}',Name);
                        plainbody = plainbody.replace('{customerName}',Name);
                         subject = subject.replace('{EOI/CA}',thisOpportunity.EOI_CA__c);
                        subject = subject.replace('{EOI/CA}',thisOpportunity.EOI_CA__c);
                          htmlbody = htmlbody.replace('{EOI_CA_Number}',thisOpportunity.EOI_CA_Number__c);
                        plainbody = plainbody.replace('{EOI_CA_Number}',thisOpportunity.EOI_CA_Number__c);
                        htmlbody = htmlbody.replace('{projectNumber}',thisOpportunity.Project__r.Project_Phone__c);
                        plainbody = plainbody.replace('{projectNumber}',thisOpportunity.Project__r.Project_Phone__c);
                        htmlbody = htmlbody.replace('{projectName}',thisOpportunity.Project__r.Name);
                        plainbody = plainbody.replace('{projectName}',thisOpportunity.Project__r.Name);
                        subject = subject.replace('{projectName}',thisOpportunity.Project__r.Name);
                        mail.setToAddresses(new List<string>{thisOpportunity.Account.PersonEmail});
                        mail.setPlainTextBody(plainbody);
                        mail.setHtmlBody(htmlbody);
                        mail.setSubject(subject);
                        mail.setOrgWideEmailAddressId(OrgWideaddressMap.get(thisOpportunity.Project__r.Project_Email__c));
                        mail.setSaveAsActivity(false);
                        emailMessages.add(mail);
                        EmailMessage objEmailMessage = new EmailMessage();
                        objEmailMessage.status = '3'; // email was sent
                        objEmailMessage.RelatedToId = thisOpportunity.id;
                        objEmailMessage.fromName = 'Dynamix'; // from name
                        objEmailMessage.Subject = 'Email sent to customer '+ thisOpportunity.EOI_CA__c +' without Booking';
                        objEmailMessage.HtmlBody = htmlbody;
                        objEmailMessage.ToAddress = thisOpportunity.Account.PersonEmail;
                        insertEmailMessageList.add(objEmailMessage);
                        
                    }
                }
            }
            if(!insertEmailMessageList.isEmpty())
            {
                insert insertEmailMessageList;   
            }
            
           
            if(!emailMessages.isempty())
            {
                try{
                    List<Messaging.SendEmailResult> sendResults = Messaging.sendEmail(emailMessages);
                }
                Catch(Exception Ex)
                {
                    system.debug('Error '+Ex.getMessage()); 
                }
            }
            
        }
    }
    
    public void finish(Database.BatchableContext bc){
        
    }
}