dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Account/fields/Rera_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Rera_Expiry_Date__c</fullName>
    <label>Rera Expiry Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Account/recordTypes/Channel_Partner.recordType-meta.xml
<RecordType>
    <fullName>Channel_Partner</fullName>
    <active>true</active>
    <label>Channel Partner</label>
</RecordType>

dynamix/force-app/main/default/objects/Data_Sync__c/Data_Sync__c.object-meta.xml
<CustomObject>
    <label>Data_Sync</label>
    <nameField>
        <displayFormat>DS-{0000000}</displayFormat>
        <label>Data_Sync Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data_Syncs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>TextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/classes/calloutBrokerMaster_Test.cls
@isTest
private class calloutBrokerMaster_Test {
    @isTest static void getChannelPartner_Test(){
        RecordType channelPartnerRecordType = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'Channel_Partner' LIMIT 1];

        Account testAccount = new Account();
        testAccount.Name = 'Channel Partner Account';
        testAccount.RecordTypeId = channelPartnerRecordType.Id;
        testAccount.Rera_Expiry_Date__c = system.today()+30;
        //testAccount.Project__c = testProject.Id;
        insert testAccount;
        
        Data_Sync__c ds = new Data_Sync__c();
        ds.RecordId__c = testAccount.Id;
        ds.Status__c = 'Pending';
        ds.Event_Type__c = 'Channel Partner';
        insert ds;
        
        List<calloutBrokerMaster.request> reqList = new List<calloutBrokerMaster.request>();
        calloutBrokerMaster.request req = new calloutBrokerMaster.request();
        req.accountId = testAccount.Id;
        req.deletionFlag = '';
        reqList.add(req);
        
        Test.startTest();
       	Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        calloutBrokerMaster.getChannelPartner(reqList);
        Test.stopTest();
    }
}