dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Magicbricks</fullName>
                <default>true</default>
                <label>Magicbricks</label>
            </value>
            <value>
                <fullName>Commonfloor</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Sms</fullName>
            </value>
            <value>
                <fullName>Builder Website</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Pre Sale</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Paytm</fullName>
            </value>
            <value>
                <fullName>Big Bazaar Activity</fullName>
            </value>
            <value>
                <fullName>Focused Leads</fullName>
            </value>
            <value>
                <fullName>Homeloans Calling</fullName>
            </value>
            <value>
                <fullName>Re-churn Existing fresh Leads</fullName>
            </value>
            <value>
                <fullName>Nobroker</fullName>
            </value>
            <value>
                <fullName>Career Socially</fullName>
            </value>
            <value>
                <fullName>Paper Inserts</fullName>
            </value>
            <value>
                <fullName>Cab</fullName>
            </value>
            <value>
                <fullName>Paytunes</fullName>
            </value>
            <value>
                <fullName>Toll Free</fullName>
            </value>
            <value>
                <fullName>Ldspl mumbai</fullName>
            </value>
            <value>
                <fullName>lvr</fullName>
            </value>
            <value>
                <fullName>Test source</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Exhibition</fullName>
            </value>
            <value>
                <fullName>Project Site Hoarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/classes/OpportuntiyService_Test.cls
@isTest
public class OpportuntiyService_Test {

    @isTest static void oppServiceTest(){
        
        String JSONStr =  '{"accountMap":{"FirstName": "Rahul","LastName": "Kumar","PersonMobilePhone" : "5588446624","PersonEmail" : "rahul@gmail.com"},"opportunityMap":{"Name":"test","StageName":"Closed Won","CloseDate":"2021-06-30"}}';
	
        
        Test.startTest();
        Restrequest req  = New Restrequest();
         req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = blob.valueOf(JSONStr);
        req.requestURI = '/services/apexrest/opportunity/*';
         RestContext.request = req;
        
         Restresponse res = New Restresponse();
         RestContext.response = res;
        OpportuntiyService.doPost();
        Test.stopTest();
        
        
    }
    
    @isTest static void oppServiceTest1(){
        
        String JSONStr =  '{"accountMap":{"FirstName": "Sahil","LastName": "Kumar","PersonMobilePhone" : "5588446624","PersonEmail" : "sahil@gmail.com"},"opportunityMap":{"Name":"test1","StageName":"Closed Won","CloseDate":"10/07/2021","Source__c":"Channel Partner"}}';
	
        
        Test.startTest();
        Restrequest req  = New Restrequest();
         req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = blob.valueOf(JSONStr);
        req.requestURI = '/services/apexrest/opportunity/*';
         RestContext.request = req;
        
         Restresponse res = New Restresponse();
         RestContext.response = res;
        OpportuntiyService.doPost();
        Test.stopTest();
        
        
    }
    
      @isTest static void oppServiceTest2(){
          
          
        
        String JSONStr =  '{"accountMap":{"FirstName": "Sahil123","LastName": "Kumar456","PersonMobilePhone" : "5587846624","PersonEmail" : "testkumar145@gmail.com"},"opportunityMap":{"Name":"test2","StageName":"Closed Won","CloseDate":"12/05/2021","Source__c":"Channel Partner","Project__c":"a0L0w000001QlFlEAK","OwnerId":"0050w000002cFNcAAM"}}';
	
        
        Test.startTest();
        Restrequest req  = New Restrequest();
         req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = blob.valueOf(JSONStr);
        req.requestURI = '/services/apexrest/opportunity/*';
         RestContext.request = req;
        
         Restresponse res = New Restresponse();
         RestContext.response = res;
        OpportuntiyService.doPost();
        Test.stopTest();
        
        
    }
    
     @isTest static void oppServiceTest3(){
        
        String JSONStr =  '{"accountMap":{"FirstName": "Rohit123","LastName": "Kumar456","PersonMobilePhone" : "5747846624","PersonEmail" : "rohitkumar145@gmail.com"},"opportunityMap":{"Name":"test2","StageName":"Closed Won","CloseDate":"10/05/2021","Source__c":"Person Account","Project__c":"a0L0w000001QlFlEAK","OwnerId":"0050w000002cFNcAAM"}}';
	
        
        Test.startTest();
        Restrequest req  = New Restrequest();
         req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = blob.valueOf(JSONStr);
        req.requestURI = '/services/apexrest/opportunity/*';
         RestContext.request = req;
        
         Restresponse res = New Restresponse();
         RestContext.response = res;
        OpportuntiyService.doPost();
        Test.stopTest();
        
        
    }
    
      @isTest static void oppServiceTest4(){
        
        String JSONStr =  '{"accountMap":{"FirstName": "Sohit123","LastName": "Kumar456","PersonMobilePhone" : "5747844584","PersonEmail" : "sohitkumar145@gmail.com"},"opportunityMap":{"Name":"test5","StageName":"Closed Won","CloseDate":"11/07/2021","Source__c":"Person Account","OwnerId":"0050w000002cFNcAAM"}}';
	
        
        Test.startTest();
        Restrequest req  = New Restrequest();
         req.httpMethod = 'POST';
        RestContext.request = req;
        req.requestBody = blob.valueOf(JSONStr);
        req.requestURI = '/services/apexrest/opportunity/*';
         RestContext.request = req;
        
         Restresponse res = New Restresponse();
         RestContext.response = res;
        OpportuntiyService.doPost();
        Test.stopTest();
        
        
    }
   
   
   
   
    
   }