dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Flat_Type__c.field-meta.xml
<CustomField>
    <fullName>Flat_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COVERED STACK</fullName>
            </value>
            <value>
                <fullName>STACK</fullName>
            </value>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK G</fullName>
            </value>
            <value>
                <fullName>2.5 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
            <value>
                <fullName>PENTHOUSES</fullName>
            </value>
            <value>
                <fullName>ROW HOUSES</fullName>
            </value>
            <value>
                <fullName>VILLAS</fullName>
            </value>
            <value>
                <fullName>BUNGALOW</fullName>
            </value>
            <value>
                <fullName>SHOP WITH TERRACE</fullName>
            </value>
            <value>
                <fullName>SHOP WITHOUT TERRACE</fullName>
            </value>
            <value>
                <fullName>OFFICE WITH TERRACE</fullName>
            </value>
            <value>
                <fullName>OFFICE WITHOUT TERRACE</fullName>
            </value>
            <value>
                <fullName>REFUGEE</fullName>
            </value>
            <value>
                <fullName>STUDIO</fullName>
            </value>
            <value>
                <fullName>CAR PARKING</fullName>
            </value>
            <value>
                <fullName>BIKE PARKING</fullName>
            </value>
            <value>
                <fullName>BASEMENT PARKING</fullName>
                <isActive>false</isActive>
                <label>BASEMENT PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE OPEN PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE OPEN PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE PODIUM PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE PODIUM PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE STILT PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE STILT PARKING</label>
            </value>
            <value>
                <fullName>OPEN PARKING</fullName>
                <isActive>false</isActive>
                <label>OPEN PARKING</label>
            </value>
            <value>
                <fullName>PODIUM PARKING</fullName>
                <isActive>false</isActive>
                <label>PODIUM PARKING</label>
            </value>
            <value>
                <fullName>STILT PARKING</fullName>
                <isActive>false</isActive>
                <label>STILT PARKING</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Parking_Type__c.field-meta.xml
<CustomField>
    <fullName>Parking_Type__c</fullName>
    <label>Parking Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Puzzle Tandem</fullName>
            </value>
            <value>
                <fullName>Puzzle</fullName>
            </value>
            <value>
                <fullName>Surface</fullName>
            </value>
            <value>
                <fullName>Stack</fullName>
            </value>
            <value>
                <fullName>2 Wheeler as per Old DCPR</fullName>
            </value>
            <value>
                <fullName>2 Wheeler as per New DCPR</fullName>
            </value>
            <value>
                <fullName>2-Wheeler Parking</fullName>
            </value>
            <value>
                <fullName>Dependant</fullName>
            </value>
            <value>
                <fullName>Independent</fullName>
            </value>
            <value>
                <fullName>Basement Parking</fullName>
            </value>
            <value>
                <fullName>Stilt Parking</fullName>
            </value>
            <value>
                <fullName>Podium Parking</fullName>
            </value>
            <value>
                <fullName>Open Parking</fullName>
            </value>
            <value>
                <fullName>Double Podium Parking</fullName>
            </value>
            <value>
                <fullName>Double Stilt Parking</fullName>
            </value>
            <value>
                <fullName>Double Open Parking</fullName>
            </value>
            <value>
                <fullName>CAR PARK TYPE</fullName>
                <isActive>false</isActive>
                <label>CAR PARK TYPE</label>
            </value>
            <value>
                <fullName>Stack (Pit)</fullName>
                <isActive>false</isActive>
                <label>Stack (Pit)</label>
            </value>
            <value>
                <fullName>UNIT TYPE</fullName>
                <isActive>false</isActive>
                <label>UNIT TYPE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Property_Status__c.field-meta.xml
<CustomField>
    <fullName>Property_Status__c</fullName>
    <label>Property Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pre - Allotted</fullName>
            </value>
            <value>
                <fullName>Allotted</fullName>
            </value>
            <value>
                <fullName>Allotted In Progress</fullName>
            </value>
            <value>
                <fullName>Confirmed Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please add tower as per project selected</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Tower__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit No.</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Property_Add_On__c/Property_Add_On__c.object-meta.xml
<CustomObject>
    <label>Property Add On Charges</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties Add On</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property_Add_On__c/fields/Project_Add_On__c.field-meta.xml
<CustomField>
    <fullName>Project_Add_On__c</fullName>
    <label>Project Add On</label>
    <referenceTo>Project_Add_On_Charges__c</referenceTo>
    <relationshipName>Properties_Add_On</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Property_Add_On__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipName>Properties_Add_On</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/Suggested_Property__c.object-meta.xml
<CustomObject>
    <label>Suggested Property</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Suggestion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suggested Property</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Suggested Property</relationshipLabel>
    <relationshipName>Suggested_Property</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Suggested Property</relationshipLabel>
    <relationshipName>Suggested_Property</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/classes/BikeParkingGraphicalViewControllerTest.cls
@isTest
public class BikeParkingGraphicalViewControllerTest { 
    
    @isTest
    static void testCreateSuggestedProperty() {
        Account testAcc = new Account();
        testAcc.Name = 'Test Name';
        insert testAcc;
        
        Project__c project = new Project__c(Name='Test Project');
        insert project;
        Tower__c towerObject = new Tower__c();
        towerObject.Name = 'test tower';
        towerObject.Project__c = project.Id;
        insert towerObject;
        
        Property__c testProperty = new Property__c(Name = 'Test Property', Flat_Type__c = 'BIKE PARKING',Parking_Type__c = 'Puzzle Tandem' ,Project__c = project.id,Tower__c= towerObject.Id);
        insert testProperty;
        Opportunity testOpportunity = new Opportunity(Name = 'Test Opportunity',
                                                      AccountId = testAcc.id,
                                                      CloseDate = System.Today(),
                                                      StageName = 'Closed Won',
                                                      Project__c = project.Id);
        insert testOpportunity;
        
        Test.startTest();
        BikeParkingGraphicalViewController.createSuggestedProperty(testProperty.Id, testOpportunity.Id);
        BikeParkingGraphicalViewController.getInventory(project.Id);
        Test.stopTest();
        
    }
    
    
      @isTest
    static void testCreateSuggestedProperty323() {
        Account testAcc = new Account();
        testAcc.Name = 'Test Name';
        insert testAcc;  
        
        Project__c project = new Project__c(Name='Test Project');
        insert project;
        
         Tower__c towerObject = new Tower__c();
        towerObject.Name = 'test tower';
        towerObject.Project__c = project.Id;
        insert towerObject;
        
        Property__c testProperty = new Property__c(Name = 'Test Property', Flat_Type__c = 'BIKE PARKING',Parking_Type__c = 'Puzzle Tandem' ,Project__c = project.id,Tower__c= towerObject.Id);
        insert testProperty;
        Opportunity testOpportunity = new Opportunity(Name = 'Test Opportunity',
                                                      AccountId = testAcc.id,
                                                      CloseDate = System.Today(),
                                                      StageName = 'Closed Won',
                                                      Project__c = project.Id);
        insert testOpportunity;
        
        Test.startTest();
        BikeParkingGraphicalViewController.createSuggestedProperty(testProperty.Id, testOpportunity.Id);
        BikeParkingGraphicalViewController.getBookingInventory(project.Id);
        Test.stopTest();
        
    }
    
    
       @isTest
    static void testCreateSuggestedProperty3235() {
        Account testAcc = new Account();
        testAcc.Name = 'Test Name';
        insert testAcc;
        
        Project__c project = new Project__c(Name='Test Project');
        insert project;
        Tower__c towerObject = new Tower__c();
        towerObject.Name = 'test tower';
        towerObject.Project__c = project.Id;
        insert towerObject;
                
        Property__c testProperty = new Property__c(Name = 'Test Property',  Flat_Type__c = 'BIKE PARKING',Parking_Type__c = 'Puzzle Tandem' ,Project__c = project.id,Tower__c= towerObject.Id);
        insert testProperty;
        
        Opportunity testOpportunity = new Opportunity(Name = 'Test Opportunity',
                                                      AccountId = testAcc.id,
                                                      CloseDate = System.Today(),
                                                      StageName = 'Closed Won',
                                                      Project__c = project.Id);
        insert testOpportunity;
        
        Test.startTest();
        BikeParkingGraphicalViewController.createSuggestedProperty(testProperty.Id, testOpportunity.Id);
        BikeParkingGraphicalViewController.getProperties(project.Id);
        Test.stopTest();
        
    }
    

    
     @isTest
    static void testCreateSuggestedProperty3() {
        Account testAcc = new Account();
        testAcc.Name = 'Test Name';
        insert testAcc;
        
        Project__c project = new Project__c(Name='Test Project');
        insert project;
        
          
        
        Property__c testProperty = new Property__c(Name = 'Test Property', Flat_Type__c = 'BIKE PARKING',
                                                   Property_Status__c ='Available', Project__c = project.id);
        insert testProperty;
        
        Property_Add_On__c propertyAddOn = new Property_Add_On__c();
           
        /*propertyAddOn.Property__c = testProperty.Id;
        propertyAddOn.Is_Included__c = true;
        propertyAddOn.Project_Add_On__c = ;
            insert propertyAddOn;*/
        
        Opportunity testOpportunity = new Opportunity(Name = 'Test Opportunity',
                                                      AccountId = testAcc.id,
                                                      CloseDate = System.Today(),
                                                      StageName = 'Closed Won',
                                                      Project__c = project.Id);
        insert testOpportunity;
        
        Test.startTest();
        BikeParkingGraphicalViewController.createSuggestedProperty(testProperty.Id, testOpportunity.Id);
        BikeParkingGraphicalViewController.getBookingInventory(project.Id);
        Test.stopTest();
        
    }
    
    
    @isTest
    static void testGetSuggProp() {
        Project__c project = new Project__c(Name='Test Project');
        insert project;
        
        Account testAcc = new Account();
        testAcc.Name = 'Test Name';
        insert testAcc;
        
        Opportunity testOpportunity = new Opportunity(Name = 'Test Opportunity',
                                                      AccountId = testAcc.id,
                                                      CloseDate = System.Today(),
                                                      StageName = 'Closed Won',
                                                      Project__c = project.Id);
        insert testOpportunity;
        
        Property__c testProperty1 = new Property__c(Name = 'Test Property 1', Project__c = project.Id, Flat_Type__c = 'BIKE PARKING');
        insert testProperty1;
        
        Suggested_Property__c testSuggestedProperty = new Suggested_Property__c(Opportunity__c = testOpportunity.Id,Unit__c = testProperty1.Id);
        insert testSuggestedProperty;
        
        Test.startTest();
        BikeParkingGraphicalViewController.getSuggProp(testOpportunity.Id);
        BikeParkingGraphicalViewController.changeStatus(testProperty1.Id);  
        Test.stopTest();
    }
}