dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/EOI_CA__c.field-meta.xml
<CustomField>
    <fullName>EOI_CA__c</fullName>
    <label>EOI/CA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/CA_Terms_Conditions__c.field-meta.xml
<CustomField>
    <fullName>CA_Terms_Conditions__c</fullName>
    <label>CA Terms &amp; Conditions</label>
    <type>Url</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/EOI_Terms_Conditions__c.field-meta.xml
<CustomField>
    <fullName>EOI_Terms_Conditions__c</fullName>
    <label>EOI Terms &amp; Conditions</label>
    <type>Url</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Footer__c.field-meta.xml
<CustomField>
    <fullName>Project_Footer__c</fullName>
    <label>Project Footer</label>
    <type>Url</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Header__c.field-meta.xml
<CustomField>
    <fullName>Project_Header__c</fullName>
    <label>Project Header</label>
    <type>Url</type>
</CustomField>

dynamix/force-app/main/default/classes/TestEOICAFormDocController.cls
@isTest
private class TestEOICAFormDocController {
    static testMethod void testEOICAFormDocController() {
     
        Account testAccount = new Account(
            FirstName = 'John',
            LastName = 'Doe',
            PersonEmail = 'johndoe112@gmail.com',
            PersonMobilePhone = '1234567890',
            PersonMailingStreet = '123 Test Lane',
            PersonMailingCity = 'Testville',
            PersonMailingState = 'Test State',
            PersonMailingPostalCode = '12345',
            PersonMailingCountry = 'Testland'
        );
        insert testAccount;
        
        Project__c testProject = new Project__c(
            Name = 'Test Project',
            Project_Header__c = 'Header Info',
            Project_Footer__c = 'Footer Info',
            EOI_Terms_Conditions__c = 'EOI Terms',
            CA_Terms_Conditions__c = 'CA Terms'
            
        );
        insert testProject;

		
        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = testAccount.Id,
            Project__c= testProject.id,
            EOI_CA__c = 'EOI',
            closeDate = System.Today()+7,
            StageName = 'In Progress'
        );
        insert testOpportunity; 
 

        PageReference pageRef = Page.EOI_CA_Document; 
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', testOpportunity.Id);
        
        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(testOpportunity);
        EOICAFormDocController controller = new EOICAFormDocController(sc);

       /* System.assertEquals(false, controller.ShowHeader, 'Header should initially be false');
        System.assertEquals(false, controller.showFooter, 'Footer should initially be false');*/
        
        controller.ShowHeader = true;
        controller.showFooter = true;

       /* System.assertEquals(true, controller.ShowHeader, 'Header should now be true');
        System.assertEquals(true, controller.showFooter, 'Footer should now be true');
        System.assertEquals('Header Info', controller.ProjectHeader, 'Incorrect project header');
        System.assertEquals('Footer Info', controller.ProjectFooter, 'Incorrect project footer');
        System.assertEquals('EOI Terms', controller.termsAndCondition, 'Terms should match EOI Terms');*/
                           
    }
}