dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lost to Competitor</fullName>
            </value>
            <value>
                <fullName>No Budget / Lost Funding</fullName>
            </value>
            <value>
                <fullName>No Decision / Non-Responsive</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Auto cancelled due to business reason</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Reason_for_lost__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_lost__c</fullName>
    <label>Reason for lost</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Budget Mismatch</fullName>
            </value>
            <value>
                <fullName>Possession Timeline Mismatch</fullName>
            </value>
            <value>
                <fullName>Wrong Locality</fullName>
            </value>
            <value>
                <fullName>Configuration Mismatch</fullName>
            </value>
            <value>
                <fullName>Not liked the project</fullName>
            </value>
            <value>
                <fullName>Finds other project better</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Configuration</fullName>
            </value>
            <value>
                <fullName>Developer Issue</fullName>
            </value>
            <value>
                <fullName>Apartment Size</fullName>
            </value>
            <value>
                <fullName>Interested in Resale / Renting property</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>Interested In Another Project</fullName>
            </value>
            <value>
                <fullName>Possession Timeline</fullName>
            </value>
            <value>
                <fullName>Amenities</fullName>
            </value>
            <value>
                <fullName>Home Loan Issue</fullName>
            </value>
            <value>
                <fullName>Low Budget</fullName>
            </value>
            <value>
                <fullName>Own contribution Issue</fullName>
            </value>
            <value>
                <fullName>Not interested in Property</fullName>
            </value>
            <value>
                <fullName>Will Purchase Later</fullName>
            </value>
            <value>
                <fullName>Plan Dropped / Postponed</fullName>
            </value>
            <value>
                <fullName>Booked elsewhere</fullName>
            </value>
            <value>
                <fullName>Future Prospect</fullName>
            </value>
            <value>
                <fullName>Not Contactable / Not Answering</fullName>
            </value>
            <value>
                <fullName>Not Interested after multiple follow-ups</fullName>
            </value>
            <value>
                <fullName>Vastu Issue</fullName>
            </value>
            <value>
                <fullName>Finance Issue</fullName>
            </value>
            <value>
                <fullName>Auto cancelled due to business reason</fullName>
            </value>
            <value>
                <fullName>Corona Job Loss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/classes/BatchforCancellationEOICATest.cls
@isTest
private class BatchforCancellationEOICATest {
    @isTest
    static void testBatchExecution() {
        
        //List<Account> testAccounts = BatchforCancellationEOICATestDataFactory.createAccounts(2);
       // List<Project__c> testProjects = BatchforCancellationEOICATestDataFactory.createProjects(2);
       // List<Opportunity> testOpportunities = BatchforCancellationEOICATestDataFactory.createOpportunities(testAccounts, testProjects, 2);
       // List<Booking__c> testBookings = BatchforCancellationEOICATestDataFactory.createBookings(testOpportunities, 2);
        Test.startTest();

        
        BatchforCancellationOfEOICA batchInstance = new BatchforCancellationOfEOICA();
        Database.executeBatch(batchInstance);

        Test.stopTest();

        
        List<Opportunity> updatedOpportunities = [SELECT Id, StageName, Loss_Reason__c, Reason_for_lost__c FROM Opportunity];
        /*System.assertEquals(2, updatedOpportunities.size(), 'There should be 2 updated opportunities');
        for(Opportunity updatedOpportunity : updatedOpportunities) {
            System.assertEquals('Closed Lost', updatedOpportunity.StageName, 'StageName should be Closed Lost');
            System.assertEquals('Auto cancelled due to business reason', updatedOpportunity.Loss_Reason__c, 'Loss Reason should be Auto cancelled due to business reason');
            System.assertEquals('Auto cancelled due to business reason', updatedOpportunity.Reason_for_lost__c, 'Reason for lost should be Auto cancelled due to business reason');
        }
        
        System.assertEquals(2, [SELECT count() FROM EmailMessage], 'There should be 2 EmailMessage created');*/
    }
}