dynamix/force-app/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/Project_Add_On_Charges__c.object-meta.xml
<CustomObject>
    <label>Project Add On Charges</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Add On Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/fields/Charge_Group__c.field-meta.xml
<CustomField>
    <fullName>Charge_Group__c</fullName>
    <label>Charge Group</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Charge_Group</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Add_On_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/recordTypes/Charges.recordType-meta.xml
<RecordType>
    <fullName>Charges</fullName>
    <active>true</active>
    <label>Charges</label>
</RecordType>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Flat_Type__c.field-meta.xml
<CustomField>
    <fullName>Flat_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COVERED STACK</fullName>
            </value>
            <value>
                <fullName>STACK</fullName>
            </value>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK G</fullName>
            </value>
            <value>
                <fullName>2.5 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
            <value>
                <fullName>PENTHOUSES</fullName>
            </value>
            <value>
                <fullName>ROW HOUSES</fullName>
            </value>
            <value>
                <fullName>VILLAS</fullName>
            </value>
            <value>
                <fullName>BUNGALOW</fullName>
            </value>
            <value>
                <fullName>SHOP WITH TERRACE</fullName>
            </value>
            <value>
                <fullName>SHOP WITHOUT TERRACE</fullName>
            </value>
            <value>
                <fullName>OFFICE WITH TERRACE</fullName>
            </value>
            <value>
                <fullName>OFFICE WITHOUT TERRACE</fullName>
            </value>
            <value>
                <fullName>REFUGEE</fullName>
            </value>
            <value>
                <fullName>STUDIO</fullName>
            </value>
            <value>
                <fullName>CAR PARKING</fullName>
            </value>
            <value>
                <fullName>BIKE PARKING</fullName>
            </value>
            <value>
                <fullName>BASEMENT PARKING</fullName>
                <isActive>false</isActive>
                <label>BASEMENT PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE OPEN PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE OPEN PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE PODIUM PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE PODIUM PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE STILT PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE STILT PARKING</label>
            </value>
            <value>
                <fullName>OPEN PARKING</fullName>
                <isActive>false</isActive>
                <label>OPEN PARKING</label>
            </value>
            <value>
                <fullName>PODIUM PARKING</fullName>
                <isActive>false</isActive>
                <label>PODIUM PARKING</label>
            </value>
            <value>
                <fullName>STILT PARKING</fullName>
                <isActive>false</isActive>
                <label>STILT PARKING</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Pricing_Plan_Detail__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Plan_Detail__c</fullName>
    <label>Pricing Plan Detail</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Property_Status__c.field-meta.xml
<CustomField>
    <fullName>Property_Status__c</fullName>
    <label>Property Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pre - Allotted</fullName>
            </value>
            <value>
                <fullName>Allotted</fullName>
            </value>
            <value>
                <fullName>Allotted In Progress</fullName>
            </value>
            <value>
                <fullName>Confirmed Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please add tower as per project selected</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Tower__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property_Add_On__c/Property_Add_On__c.object-meta.xml
<CustomObject>
    <label>Property Add On Charges</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties Add On</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property_Add_On__c/fields/Project_Add_On__c.field-meta.xml
<CustomField>
    <fullName>Project_Add_On__c</fullName>
    <label>Project Add On</label>
    <referenceTo>Project_Add_On_Charges__c</referenceTo>
    <relationshipName>Properties_Add_On</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Property_Add_On__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipName>Properties_Add_On</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/globalValueSets/Charge_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agreement</fullName>
    </customValue>
    <customValue>
        <fullName>Floor Rise</fullName>
    </customValue>
    <customValue>
        <fullName>Stamp Duty</fullName>
    </customValue>
    <customValue>
        <fullName>Registration Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Charge Group</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/classes/PropertyGraphicalViewWrapper_Test.cls
@isTest
public class PropertyGraphicalViewWrapper_Test {
    
    @isTest 
    static void PropertyGraphicalTest(){
		
        Project__c projectObject = new Project__c();
        projectObject.Name = 'test project';
        insert projectObject;
         
        Tower__c towerObject = new Tower__c();
        towerObject.Name = 'test tower';
        towerObject.Project__c = projectObject.Id;
        insert towerObject;
         
        Property__c propertyObject = new Property__c();
        propertyObject.Name = 'new property';
        propertyObject.Tower__c= null;
        propertyObject.Project__c = projectObject.Id;
        propertyObject.Floor__c = '1';
        propertyObject.Property_Status__c = 'Available';
        propertyObject.Flat_Type__c  = '1 BHK';
      	insert propertyObject;
        
        /*
        Property__c propertyObject1 = new Property__c();
        propertyObject1.Name = 'new property';
        propertyObject1.Tower__c= null;
        propertyObject1.Project__c = projectObject.Id;
        propertyObject1.Floor__c = '1';
        propertyObject1.Property_Status__c = 'Available';
        propertyObject1.Flat_Type__c  = '1 BHK';
        propertyObject1.Pricing_Plan_Detail__c = 'PricingTest';
      	insert propertyObject1;
        
        Property__c propertyObject2 = new Property__c();
        propertyObject2.Name = 'new property';
        propertyObject2.Tower__c= null;
        propertyObject2.Project__c = projectObject.Id;
        propertyObject2.Floor__c = '2';
        propertyObject2.Property_Status__c = 'Available';
        propertyObject2.Flat_Type__c  = '1 BHK';
        propertyObject2.Pricing_Plan_Detail__c = 'PricingTest';
      	insert propertyObject2;
        */
        
        Account accountObject = new Account();
        accountObject.Name= 'Test Account';
        insert accountObject;
        
		Opportunity opprObject = new Opportunity();
        opprObject.Name = 'test opportunity';
        opprObject.Project__c = projectObject.Id;
        opprObject.StageName = 'Site Visit';
        opprObject.CloseDate = system.today();
        opprObject.AccountId = accountObject.Id;
        insert opprObject; 
     	
        PropertyGraphicalViewWrapper viewWrapObject = new PropertyGraphicalViewWrapper();
        PropertyGraphicalViewWrapper.Tower towerObj= new PropertyGraphicalViewWrapper.Tower(propertyObject);
       
        Map<String, PropertyGraphicalViewWrapper.Tower> towerMap = new Map<String, PropertyGraphicalViewWrapper.Tower>(); 
        String relatedTower = 'Property Plan';
        towerMap.put(relatedTower,null); 
        PropertyGraphicalViewWrapper.Floor floor = new PropertyGraphicalViewWrapper.Floor(propertyObject);
         
       
     }

     @isTest 
    static void PropertyGraphicalwrapperTest(){
        
          Id ChargesId = Schema.SObjectType.Project_Add_On_Charges__c.getRecordTypeInfosByName().get('Charges').getRecordTypeId();
		
        Project__c projectObject = new Project__c();
        projectObject.Name = 'test project';
        insert projectObject;
        
         Project_Add_On_Charges__c projectAddbject= new Project_Add_On_Charges__c();
        projectAddbject.Charge_Type__c = 'Fixed';
        projectAddbject.Charge_Group__c = 'Floor Rise';
        projectAddbject.Is_Optional__c = false;
        projectAddbject.RecordTypeId = ChargesId;
        projectAddbject.Project__c = projectObject.Id;
        projectAddbject.Name = 'Basic Price';
        insert projectAddbject;
         
        Tower__c towerObject = new Tower__c();
        towerObject.Name = 'test tower';
        towerObject.Project__c = projectObject.Id;
        insert towerObject;
         
        Property__c propertyObject = new Property__c();
        propertyObject.Name = 'new property';
        propertyObject.Tower__c= null;
        propertyObject.Project__c = projectObject.Id;
        propertyObject.Floor__c = '1';
        propertyObject.Property_Status__c = 'Available';
        propertyObject.Flat_Type__c  = '1 BHK';
      	insert propertyObject;
        
        Property_Add_On__c PAddOn = New Property_Add_On__c();
        PAddOn.Property__c = propertyObject.Id;
        PAddOn.Project_Add_On__c = projectAddbject.Id;
        insert PAddOn;
        /*
        Property__c propertyObject1 = new Property__c();
        propertyObject1.Name = 'new property';
        propertyObject1.Tower__c= null;
        propertyObject1.Project__c = projectObject.Id;
        propertyObject1.Floor__c = '1';
        propertyObject1.Property_Status__c = 'Available';
        propertyObject1.Flat_Type__c  = '1 BHK';
        propertyObject1.Pricing_Plan_Detail__c = 'PricingTest';
      	insert propertyObject1;
        
        Property__c propertyObject2 = new Property__c();
        propertyObject2.Name = 'new property';
        propertyObject2.Tower__c= null;
        propertyObject2.Project__c = projectObject.Id;
        propertyObject2.Floor__c = '2';
        propertyObject2.Property_Status__c = 'Available';
        propertyObject2.Flat_Type__c  = '1 BHK';
        propertyObject2.Pricing_Plan_Detail__c = 'PricingTest';
      	insert propertyObject2;
        */
        
        Account accountObject = new Account();
        accountObject.Name= 'Test Account';
        insert accountObject;
        
		Opportunity opprObject = new Opportunity();
        opprObject.Name = 'test opportunity';
        opprObject.Project__c = projectObject.Id;
        opprObject.StageName = 'Site Visit';
        opprObject.CloseDate = system.today();
        opprObject.AccountId = accountObject.Id;
        insert opprObject; 
     	
        PropertyGraphicalViewWrapper viewWrapObject = new PropertyGraphicalViewWrapper();
        PropertyGraphicalViewWrapper.Tower towerObj= new PropertyGraphicalViewWrapper.Tower(propertyObject);
       
        Map<String, PropertyGraphicalViewWrapper.Tower> towerMap = new Map<String, PropertyGraphicalViewWrapper.Tower>(); 
        String relatedTower = 'Property Plan';
        towerMap.put(relatedTower,null); 
        PropertyGraphicalViewWrapper.Floor floor = new PropertyGraphicalViewWrapper.Floor(propertyObject);
         
       
     }
}