dynamix/force-app/main/default/objects/Data_Sync__c/Data_Sync__c.object-meta.xml
<CustomObject>
    <label>Data_Sync</label>
    <nameField>
        <displayFormat>DS-{0000000}</displayFormat>
        <label>Data_Sync Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data_Syncs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>TextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response_Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Other_Charges__mdt/Pricing_Other_Charges__mdt.object-meta.xml
<CustomObject>
    <label>Pricing Other Charges</label>
    <pluralLabel>Pricing Other Charges</pluralLabel>
</CustomObject>

dynamix/force-app/main/default/objects/Pricing_Other_Charges__mdt/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <label>Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan__c/Pricing_Plan__c.object-meta.xml
<CustomObject>
    <label>Pricing Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Pricing_Plan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Pricing Plans</relationshipLabel>
    <relationshipName>Pricing_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan__c/fields/Valid_from__c.field-meta.xml
<CustomField>
    <fullName>Valid_from__c</fullName>
    <label>Valid from</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan__c/fields/Valid_to__c.field-meta.xml
<CustomField>
    <fullName>Valid_to__c</fullName>
    <label>Valid to</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/Pricing_Plan_Components__c.object-meta.xml
<CustomObject>
    <label>Pricing Plan Component</label>
    <nameField>
        <label>Pricing Plan Components Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Plan Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZPR0</fullName>
                <label>Flat material</label>
            </value>
            <value>
                <fullName>ZCPR</fullName>
                <label>Car Parking</label>
            </value>
            <value>
                <fullName>ZLC0</fullName>
                <label>Legal Charges</label>
            </value>
            <value>
                <fullName>ZWEC</fullName>
                <label>Utility conn. Charge</label>
            </value>
            <value>
                <fullName>ZSF0</fullName>
                <label>Society Formation</label>
            </value>
            <value>
                <fullName>ZSAM</fullName>
                <label>Share Appl Money</label>
            </value>
            <value>
                <fullName>ZSD1</fullName>
                <label>Security Deposit</label>
            </value>
            <value>
                <fullName>ZREG</fullName>
                <label>Registration Charge</label>
            </value>
            <value>
                <fullName>ZSDT</fullName>
                <label>Stamp Duty</label>
            </value>
            <value>
                <fullName>ZCPA</fullName>
                <label>Additional Car Parking</label>
            </value>
            <value>
                <fullName>ZCLS</fullName>
                <label>Large Car Parkspace</label>
            </value>
            <value>
                <fullName>ZCSS</fullName>
                <label>Small Car Parkspace</label>
            </value>
            <value>
                <fullName>ZCP1</fullName>
                <label>Car Parking 1</label>
            </value>
            <value>
                <fullName>ZCP2</fullName>
                <label>Car Parking 2</label>
            </value>
            <value>
                <fullName>Base</fullName>
                <isActive>false</isActive>
                <label>Base</label>
            </value>
            <value>
                <fullName>Feature</fullName>
                <isActive>false</isActive>
                <label>Feature</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Price_Lumpsum__c.field-meta.xml
<CustomField>
    <fullName>Price_Lumpsum__c</fullName>
    <label>Price (Lumpsum)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Pricing_Plan__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Plan__c</fullName>
    <label>Pricing Plan</label>
    <referenceTo>Pricing_Plan__c</referenceTo>
    <relationshipLabel>Pricing Plan Components</relationshipLabel>
    <relationshipName>Pricing_Plan_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Project_SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_SAP_Code__c</fullName>
    <label>Project SAP Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>Residential</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Commercial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Property_Price_Slab__c.field-meta.xml
<CustomField>
    <fullName>Property_Price_Slab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Price Slab</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please add price slab as per project selected</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Pricing_Plan__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pricing_Plan__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please add tower as per project selected</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Tower__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Tower__c/fields/Tower_SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>Tower_SAP_Code__c</fullName>
    <label>Tower SAP Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/classes/calloutPricingMaster.cls
/*
 * Author : Nachiketa Khera
 * Created Date : 11th December 2023
 * Description : Pricing Master Api for SAP integration.
 * Last Modified Date : 4th January 2024
*/
public with sharing class calloutPricingMaster {
    @InvocableMethod
    public static void getPricingPlanComponent(List<request> reqList){
        System.debug('reqList'+reqList);
        if(reqList != null){
            for(request req :reqList){
                exposePricingPlanToSAP(req.prPlanComponentIds);
            }
            // exposePricingPlanToSAP(reqList[0].prPlanComponentIds);
        }
    }
    @future(Callout=true)
    public static void exposePricingPlanToSAP(String prPlanComponentIds){
        System.debug('Inside class'+prPlanComponentIds);
        try{
            system.debug('prPlanComponentIds---> '+prPlanComponentIds);
            Set<String> pricingPlanIds = new Set<String>();
            Set<String> pricingComponentIds = new Set<String>();
            Set<Id> projectId = new Set<Id>();
            Map<Id,Pricing_Plan_Components__c> prPlanComponentMap = new Map<Id,Pricing_Plan_Components__c>();
            Map<Id,List<Property__c>> propertyMap = new Map<Id,List<Property__c>>();
            Map<Id,List<Tower__c>> towerMap = new Map<Id,List<Tower__c>>();
            Set<String> prPlanCompProcessed = new Set<String>();
            for (Data_Sync__c dataSync:[Select Id,Event_Type__c,RecordId__c, Status__c from Data_Sync__c where Status__c ='Pending' and RecordId__c =:prPlanComponentIds]){
                pricingComponentIds.add(dataSync.RecordId__c);
            }
            if(pricingComponentIds != null){
                for(Pricing_Plan_Components__c prPlanComp:[
                    Select Id,Component_Type__c,Pricing_Plan__c,Price_Lumpsum__c,Pricing_Plan__r.Project__r.Project_SAP_Code__c,
                    Pricing_Plan__r.Project__r.Project_Type__c,Pricing_Plan__r.Valid_from__c,Pricing_Plan__r.Valid_to__c,
                    Pricing_Plan__r.Project__c
                    from Pricing_Plan_Components__c where Id =: pricingComponentIds
                ]){
                    if(prPlanComp != null){
                        prPlanComponentMap.put(prPlanComp.Id,prPlanComp);
                        pricingPlanIds.add(prPlanComp.Pricing_Plan__c);
                        projectId.add(prPlanComp.Pricing_Plan__r.Project__c);
                    }
                }
            }
            if(!pricingPlanIds.isEmpty()){
                for(Property__c prop:[Select Id,Name,Tower__c,Tower__r.Tower_SAP_Code__c,Property_Price_Slab__c,SAP_Code__c from Property__c where Property_Price_Slab__c IN:pricingPlanIds AND SAP_Code__c != null]){
                    if(prop != null){
                        if(!propertyMap.containsKey(prop.Property_Price_Slab__c)){
                            propertyMap.put(prop.Property_Price_Slab__c,new List<Property__c>{prop});
                        }
                        else{
                            propertyMap.get(prop.Property_Price_Slab__c).add(prop);
                        }
                    }
                }
            }
            if(!projectId.isEmpty()){
                for(Project__c proj:[Select Id,Name,(Select Id,Project__c,Tower_SAP_Code__c from Towers__r where Tower_SAP_Code__c!=null) from Project__c where Id IN:projectId]){
                    if(proj != null){
                        if(!towerMap.containsKey(proj.Id)){
                            List<Tower__c> towerToAddInMap = new List<Tower__c>();
                            towerToAddInMap.addAll(proj.Towers__r);
                            towerMap.put(proj.Id,towerToAddInMap);
                        }
                        else{
                            towerMap.get(proj.Id).addAll(proj.Towers__r);
                        }
                    }
                }
            }
            List<Pricing_Other_Charges__mdt> materialMetadata = [Select Id,Label,Material__c from Pricing_Other_Charges__mdt];
            Map<String,String> materialMap = new Map<String,String>();
            if(!materialMetadata.isEmpty()){
                for(Pricing_Other_Charges__mdt materialCode:materialMetadata){
                    materialMap.put(materialCode.Label,materialCode.Material__c);
                }
            }
            List<JSONGenerator> jsonGeneratorList = new List<JSONGenerator>();
            if(!prPlanComponentMap.isEmpty()){
                for(String prPlanCompId:prPlanComponentMap.keySet()){
                    prPlanCompProcessed.add(prPlanCompId);
                    JSONGenerator jsonGenerator1 = JSON.createGenerator(true);
                    Pricing_Plan_Components__c prPlanComp = prPlanComponentMap.get(prPlanCompId);
                    if(prPlanComp.Component_Type__c == 'ZPR0' || prPlanComp.Component_Type__c == 'ZREG' || prPlanComp.Component_Type__c == 'ZSDT' || prPlanComp.Component_Type__c == 'ZCPR' || prPlanComp.Component_Type__c == 'ZDIS'){
                        if(propertyMap.containsKey(prPlanComp.Pricing_Plan__c)){
                            jsonGenerator1.writeStartObject();
                            jsonGenerator1.writeFieldName('ZSD_SFDC_PRICE_MASTER');
                            jsonGenerator1.writeStartObject();
                            jsonGenerator1.writeFieldName('PRICING_DATA');
                            jsonGenerator1.writeStartObject();
                            jsonGenerator1.writeFieldName('item');
                            jsonGenerator1.writeStartArray();
                            
                            for(Property__c prop:propertyMap.get(prPlanComp.Pricing_Plan__c)){
                                jsonGenerator1.writeStartObject();
                                jsonGenerator1.writeStringField('KSCHL',prPlanComp.Component_Type__c!=null?string.valueOF(prPlanComp.Component_Type__c):'');
                                jsonGenerator1.writeStringField('VKORG',prPlanComp.Pricing_Plan__r.Project__r.Project_SAP_Code__c!=null?string.valueOF(prPlanComp.Pricing_Plan__r.Project__r.Project_SAP_Code__c):'');
                                jsonGenerator1.writeStringField('VTWEG',prPlanComp.Pricing_Plan__r.Project__r.Project_Type__c!=null?string.valueOF(prPlanComp.Pricing_Plan__r.Project__r.Project_Type__c):'');
                                jsonGenerator1.writeStringField('WERKS',prop.Tower__r.Tower_SAP_Code__c!=null?prop.Tower__r.Tower_SAP_Code__c:'');
                                jsonGenerator1.writeStringField('MATNR',prop.SAP_Code__c!=null?prop.SAP_Code__c:'');
                                jsonGenerator1.writeStringField('KBETR',prPlanComp.Price_Lumpsum__c!=null?string.valueOF(prPlanComp.Price_Lumpsum__c):'');
                                if(prPlanComp.Pricing_Plan__r.Valid_from__c!=null){
                                    Date validDate = prPlanComp.Pricing_Plan__r.Valid_from__c;
                                    String formattedDay = (validDate.day() < 10) ? '0' + String.valueOf(validDate.day()) : String.valueOf(validDate.day());
                                    String formattedMonth = (validDate.month() < 10) ? '0' + String.valueOf(validDate.month()) : String.valueOf(validDate.month());
                                    String validFromDate = formattedDay + '.' + formattedMonth + '.' + validDate.year();
                                    jsonGenerator1.writeStringField('KDATU',validFromDate!=null?String.valueOf(validFromDate):'');
                                }
                                else{
                                    jsonGenerator1.writeStringField('KDATU','');
                                }
                                if(prPlanComp.Pricing_Plan__r.Valid_to__c!=null){
                                    Date validDate = prPlanComp.Pricing_Plan__r.Valid_to__c;
                                    String formattedDay = (validDate.day() < 10) ? '0' + String.valueOf(validDate.day()) : String.valueOf(validDate.day());
                                    String formattedMonth = (validDate.month() < 10) ? '0' + String.valueOf(validDate.month()) : String.valueOf(validDate.month());
                                    String validToDate = formattedDay + '.' + formattedMonth + '.' + validDate.year();
                                    jsonGenerator1.writeStringField('DATBI',validToDate!=null?String.valueOf(validToDate):'');
                                }
                                else{
                                    jsonGenerator1.writeStringField('DATBI','');
                                }
                                jsonGenerator1.writeStringField('SFDC_ID',prPlanComp.Id!=null?prPlanComp.Id:'');
                                jsonGenerator1.writeEndObject();
                            }
                            
                            jsonGenerator1.writeEndArray();
                            jsonGenerator1.writeEndObject();
                            jsonGenerator1.writeEndObject();
                            jsonGenerator1.writeEndObject();
                            jsonGeneratorList.add(jsonGenerator1);
                        }
                    }
                    else{
                        if(towerMap.containsKey(prPlanComp.Pricing_Plan__r.Project__c)){
                            jsonGenerator1.writeStartObject();
                            jsonGenerator1.writeFieldName('ZSD_SFDC_PRICE_MASTER');
                            jsonGenerator1.writeStartObject();
                            jsonGenerator1.writeFieldName('PRICING_DATA');
                            jsonGenerator1.writeStartObject();
                            jsonGenerator1.writeFieldName('item');
                            jsonGenerator1.writeStartArray();
                            
                            for(Tower__c towr:towerMap.get(prPlanComp.Pricing_Plan__r.Project__c)){
                                jsonGenerator1.writeStartObject();
                                jsonGenerator1.writeStringField('KSCHL',prPlanComp.Component_Type__c!=null?string.valueOF(prPlanComp.Component_Type__c):'');
                                jsonGenerator1.writeStringField('VKORG',prPlanComp.Pricing_Plan__r.Project__r.Project_SAP_Code__c!=null?string.valueOF(prPlanComp.Pricing_Plan__r.Project__r.Project_SAP_Code__c):'');
                                jsonGenerator1.writeStringField('VTWEG',prPlanComp.Pricing_Plan__r.Project__r.Project_Type__c!=null?string.valueOF(prPlanComp.Pricing_Plan__r.Project__r.Project_Type__c):'');
                                jsonGenerator1.writeStringField('WERKS',towr.Tower_SAP_Code__c!=null?towr.Tower_SAP_Code__c:'');
                                jsonGenerator1.writeStringField('MATNR',materialMap.get(prPlanComp.Component_Type__c)!=null?materialMap.get(prPlanComp.Component_Type__c):'');
                                jsonGenerator1.writeStringField('KBETR',prPlanComp.Price_Lumpsum__c!=null?string.valueOF(prPlanComp.Price_Lumpsum__c):'');
                                if(prPlanComp.Pricing_Plan__r.Valid_from__c!=null){
                                    Date validDate = prPlanComp.Pricing_Plan__r.Valid_from__c;
                                    String formattedDay = (validDate.day() < 10) ? '0' + String.valueOf(validDate.day()) : String.valueOf(validDate.day());
                                    String formattedMonth = (validDate.month() < 10) ? '0' + String.valueOf(validDate.month()) : String.valueOf(validDate.month());
                                    String validFromDate = formattedDay + '.' + formattedMonth + '.' + validDate.year();
                                    jsonGenerator1.writeStringField('KDATU',validFromDate!=null?String.valueOf(validFromDate):'');
                                }
                                else{
                                    jsonGenerator1.writeStringField('KDATU','');
                                }
                                if(prPlanComp.Pricing_Plan__r.Valid_to__c!=null){
                                    Date validDate = prPlanComp.Pricing_Plan__r.Valid_to__c;
                                    String formattedDay = (validDate.day() < 10) ? '0' + String.valueOf(validDate.day()) : String.valueOf(validDate.day());
                                    String formattedMonth = (validDate.month() < 10) ? '0' + String.valueOf(validDate.month()) : String.valueOf(validDate.month());
                                    String validToDate = formattedDay + '.' + formattedMonth + '.' + validDate.year();
                                    jsonGenerator1.writeStringField('DATBI',validToDate!=null?String.valueOf(validToDate):'');
                                }
                                else{
                                    jsonGenerator1.writeStringField('DATBI','');
                                }
                                jsonGenerator1.writeStringField('SFDC_ID',prPlanComp.Id!=null?prPlanComp.Id:'');
                                jsonGenerator1.writeEndObject();
                            }
                            
                            jsonGenerator1.writeEndArray();
                            jsonGenerator1.writeEndObject();
                            jsonGenerator1.writeEndObject();
                            jsonGenerator1.writeEndObject();
                            jsonGeneratorList.add(jsonGenerator1);
                        }                        
                    }
                }
            }
            if(jsonGeneratorList.size()>0){
                String jsonString = '';
                for (JSONGenerator generator : jsonGeneratorList) {
                    jsonString += generator.getAsString();
                }
                system.debug('jsonString--> '+jsonString);
                getSapCodes(jsonString,prPlanCompProcessed);
            } 
        }catch (Exception e) {
            System.debug('Exception: ' + e.getMessage());
        }
    }
    
    public static String getSapCodes( String jsonString,Set<String>prPlanCompProcessed){
        HttpRequest request = new HttpRequest();
        HttpResponse response = new HttpResponse();
        Http http = new Http();
        request.setEndpoint('callout:SAP_PriceMaster');
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Authorization', 'Basic UzAwMjQzMDI0NDA6Umlja3lAOTk2OQ==');
        request.setBody(jsonString);
        request.setTimeout(120000);
        List<Pricing_Plan_Components__c> prPlanCompToUpdate = new List<Pricing_Plan_Components__c>();
        Set<String>propertyIds=new Set<String>();
        try {
            response = http.send(request);
            ResponseAPIClass.getResponse(response);
           List<Data_Sync__c> DSToUpdate = new List<Data_Sync__c>(); 
           Map<String,String> coAppIdNew=new Map<String,String>();
            if (response.getStatusCode() == 200 ||response.getStatusCode() == 201) {
                String responseBody = response.getBody();
                Map<String, Object> jsonResponse = (Map<String, Object>) JSON.deserializeUntyped(responseBody);
               
                if(prPlanCompProcessed.size()>0){
                    for(Data_Sync__c DS:[select id,Status__c,RecordId__c from Data_Sync__c where RecordId__c IN :prPlanCompProcessed AND Status__c = 'Pending']){
                        Data_Sync__c dataSync=new Data_Sync__c();
                        dataSync.Status__c='Success';
                        dataSync.Response_Body__c = response.getBody();
                        dataSync.Request_Body__c = jsonString;
                        dataSync.Id=DS.id;
                        DSToUpdate.add(dataSync);
                    }
                    System.debug('HTTP Request sent Successfully: ' + response.getStatusCode());
                    System.debug('Response body: ' + response.getBody());
                }
                
            } else {
               if(prPlanCompProcessed.size()>0){
                    for(Data_Sync__c DS:[select id,Status__c,RecordId__c from Data_Sync__c  where RecordId__c IN :prPlanCompProcessed AND Status__c = 'Pending']){
                        Data_Sync__c dataSync=new Data_Sync__c();
                        dataSync.Status__c='Error';
                        dataSync.Response_Body__c=response.getBody();
                        dataSync.Request_Body__c=jsonString;
                        dataSync.Id=DS.id;
                        DSToUpdate.add(dataSync);
                    }
                }
                System.debug('HTTP Request failed with status code: ' + response.getStatusCode());
                System.debug('Response body: ' + response.getBody());
            }
            
            
            if(DSToUpdate.size()>0){
                update DSToUpdate;
            }
        } catch (Exception e) {
            System.debug('Exception: ' + e.getMessage());
        }
        return null;
    }
    public class request{
        @InvocableVariable (required=true)
        public string prPlanComponentIds;
    }
}