dynamix/force-app/main/default/objects/Interest_Charged__c/Interest_Charged__c.object-meta.xml
<CustomObject>
    <label>Interest Charged</label>
    <nameField>
        <displayFormat>Int-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Charged</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Interest_Charged__c/fields/Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount__c</fullName>
    <label>Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Interest_Charged__c/fields/Interest_Amount_GST__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount_GST__c</fullName>
    <label>Interest Amount GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Interest_Charged__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <referenceTo>Payment_Milestones__c</referenceTo>
    <relationshipLabel>Interest Charged</relationshipLabel>
    <relationshipName>Interest_Charged</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount__c</fullName>
    <label>Interest Amount</label>
    <summarizedField>Interest_Charged__c.Interest_Amount__c</summarizedField>
    <summaryForeignKey>Interest_Charged__c.Milestone__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Interest_Amount_GST__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount_GST__c</fullName>
    <label>Interest Amount GST</label>
    <summarizedField>Interest_Charged__c.Interest_Amount_GST__c</summarizedField>
    <summaryForeignKey>Interest_Charged__c.Milestone__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Interest_on_GST__c.field-meta.xml
<CustomField>
    <fullName>Interest_on_GST__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest on GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Interest_on_milestone_amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_on_milestone_amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest on Milestone Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/classes/InterestChargedTriggerHandler.cls
public class InterestChargedTriggerHandler {
    public static void InterestOnPaymentMilestone(List<Interest_Charged__c> intChargeList , Map<Id,Interest_Charged__c> oldMap){
        
        set<Id> MilestoneIdSet = new set<Id>();
        Map<Id,Interest_Charged__c> MapMilestoneToInterestCharged = new Map<Id,Interest_Charged__c>();
        for(Interest_Charged__c objIntCharged : intChargeList){
            if(oldMap.get(objIntCharged.Id).Interest_Amount_GST__c == null && objIntCharged.Interest_Amount_GST__c != null &&
              oldMap.get(objIntCharged.Id).Interest_Amount__c == null && objIntCharged.Interest_Amount__c != null){
              MilestoneIdSet.add(objIntCharged.Milestone__c);
              MapMilestoneToInterestCharged.put(objIntCharged.Milestone__c,objIntCharged);  
            }
        }
        List<Payment_Milestones__c> ListToUpdate = new List<Payment_Milestones__c>();
        List<Payment_Milestones__c> pmList = [Select Id,Name,Interest_on_milestone_amount__c,Interest_on_GST__c from Payment_Milestones__c where id in: MilestoneIdSet];
        for(Payment_Milestones__c pm : pmList){
            pm.Interest_on_GST__c = pm.Interest_on_GST__c + MapMilestoneToInterestCharged.get(pm.Id).Interest_Amount_GST__c;
            pm.Interest_on_milestone_amount__c = pm.Interest_on_milestone_amount__c + MapMilestoneToInterestCharged.get(pm.Id).Interest_Amount__c;
            ListToUpdate.add(pm);
        }
        if(!ListToUpdate.isEmpty()){
          update ListToUpdate;
        }
    }
}