dynamix/force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EN-{000000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <formula>Project__r.Name</formula>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/GPS_location__c.field-meta.xml
<CustomField>
    <fullName>GPS_location__c</fullName>
    <label>GPS location</label>
    <type>Url</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/fields/Show_flat_walkthrough_video__c.field-meta.xml
<CustomField>
    <fullName>Show_flat_walkthrough_video__c</fullName>
    <label>Show flat walkthrough video</label>
    <type>Url</type>
</CustomField>

dynamix/force-app/main/default/classes/SendBrochureThroughSMS.cls
public class SendBrochureThroughSMS {
    @InvocableMethod(callout=true label='Send Brochure Throw Whatapp And SMS')
    
    public static void SendBrochureThroughSMSMethod(List<requestWrapper> requestWrapperList) {
        //Send SMS
        EmailTemplate smsEmailTemp = [select Id,Name, Subject, HtmlValue, Body,DeveloperName from EmailTemplate where Name = 'SMS Brochure sent' LIMIT 1];
        system.debug('smsEmailTemp----'+smsEmailTemp);
        if(smsEmailTemp!=null && requestWrapperList[0].primaryMobileNumber != null){
            String templateBody=smsEmailTemp.HtmlValue;
            templateBody=templateBody.stripHtmlTags();
            String mobileNumber=requestWrapperList[0].primaryMobileNumber;
            system.debug('requestWrapperList[0].projectName'+ requestWrapperList[0].projectName);
            templateBody = templateBody.replace('{{{Project__c.GPS_location__c}}}',requestWrapperList[0].Location);
            templateBody = templateBody.replace('{{{Project__c.Brochure__c}}}', requestWrapperList[0].brochure);
            templateBody = templateBody.replace('{{{Enquiry__c.ProjectName__c}}}', requestWrapperList[0].projectName);
            templateBody = templateBody.replace('{{{Project__c.Project_Area__c}}}', requestWrapperList[0].projectArea);
            templateBody = templateBody.replace('{{{contactNumber}}}', requestWrapperList[0].projectPhone);
            templateBody = templateBody.replace('{{{Project__c.Show_flat_walkthrough_video__c}}}',+requestWrapperList[0].flatVideo );
            system.debug('templateBody----'+templateBody);
            if(!Test.isRunningTest())
            {
                SendSMSUtility.sendSMS(templateBody,mobileNumber,'DYNAMX');
            }
            
        }
    }
    public class requestWrapper{
        @InvocableVariable
        public String projectName;
        
        @InvocableVariable
        public String projectArea;
        
        @InvocableVariable
        public String flatVideo;
        
        @InvocableVariable
        public String primaryMobileNumber;
        
        @InvocableVariable
        public String Location;
        
        @InvocableVariable
        public String brochure;
        
        @InvocableVariable
        public String enquiryId;
        
        @InvocableVariable
        public String personAccountId;
        
        @InvocableVariable
        public String projectPhone;
    }  
}