dynamix/force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EN-{000000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Call_Status__c.field-meta.xml
<CustomField>
    <fullName>Call_Status__c</fullName>
    <label>Call Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Connected</fullName>
            </value>
            <value>
                <fullName>Not-Connected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Enquiry</fullName>
                <default>true</default>
                <label>New Enquiry</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Site Visit Scheduled</fullName>
            </value>
            <value>
                <fullName>Site Visit Done</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/classes/EnquiryStateChangeHandler.cls
public class EnquiryStateChangeHandler {
    Public Static Boolean PreventRecursiononEnquiryStage = False;
    public static void main(List<Task> taskList, Map<id,Task> oldMap){
        
        set<id> taskId = new set<id>();
        List<Enquiry__c> updateEnquiryList = new List<Enquiry__c>();
        
        for(Task taskRecord: taskList){
            String objectName = taskRecord.WhatId.getSObjectType().getDescribe().getName();
            if(objectName == 'Enquiry__c' && taskRecord.Call_Status__c != oldMap.get(taskRecord.id).Call_Status__c && (taskRecord.Call_Status__c == 'Connected' || taskRecord.Call_Status__c == 'Not Connected')){
                taskId.add(taskRecord.WhatId);
            }
        }
        if(!taskId.isEmpty()){
            List<Enquiry__c> enquiryList = [SELECT id,name,Stage__c 
                                            FROM Enquiry__c 
                                            WHERE id IN : taskId 
                                            AND Stage__c = 'New Enquiry'];
            if(!enquiryList.isEmpty()){
                for(Enquiry__c enquiryRecord : enquiryList){
                    {
                        enquiryRecord.Stage__c = 'Contacted';
                        updateEnquiryList.add(enquiryRecord);
                    }
                }
                if(!updateEnquiryList.isEmpty()){
                    update updateEnquiryList;
                }
            }
        }
    }
}