dynamix/force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Plan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payment Plan</relationshipLabel>
    <relationshipName>Payment_Plan</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Plan_Milestones__c/Payment_Plan_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Plan Milestones</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plan Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Plan_Milestones__c/fields/Days_after_Booking__c.field-meta.xml
<CustomField>
    <fullName>Days_after_Booking__c</fullName>
    <label>Days after Booking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Plan_Milestones__c/fields/Milestone_Activation__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Activation__c</fullName>
    <label>Milestone Activation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booking Date</fullName>
            </value>
            <value>
                <fullName>Project Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Plan_Milestones__c/fields/Milestone_age__c.field-meta.xml
<CustomField>
    <fullName>Milestone_age__c</fullName>
    <label>Milestone %age</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Plan_Milestones__c/fields/Project_Progress__c.field-meta.xml
<CustomField>
    <fullName>Project_Progress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Progress</label>
    <referenceTo>Project_Progress__c</referenceTo>
    <relationshipLabel>Payment Plan Milestones</relationshipLabel>
    <relationshipName>Payment_Plan_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Plan_Milestones__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <label>Sequence No</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Progress__c/Project_Progress__c.object-meta.xml
<CustomObject>
    <label>Project Progress</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Progress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Progress</relationshipLabel>
    <relationshipName>Project_Progress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Project_Progress__c/fields/Stage_Type__c.field-meta.xml
<CustomField>
    <fullName>Stage_Type__c</fullName>
    <label>Stage Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plinth</fullName>
            </value>
            <value>
                <fullName>RCC (Slab)</fullName>
            </value>
            <value>
                <fullName>Flooring</fullName>
            </value>
            <value>
                <fullName>Doors</fullName>
            </value>
            <value>
                <fullName>Windows</fullName>
            </value>
            <value>
                <fullName>Sliding</fullName>
            </value>
            <value>
                <fullName>OC</fullName>
            </value>
            <value>
                <fullName>Basement</fullName>
            </value>
            <value>
                <fullName>Podium</fullName>
            </value>
            <value>
                <fullName>habitable floor</fullName>
            </value>
            <value>
                <fullName>Terrace</fullName>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Walls</fullName>
            </value>
            <value>
                <fullName>Plaster</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Elevation</fullName>
            </value>
            <value>
                <fullName>Sanitary fittings</fullName>
            </value>
            <value>
                <fullName>Lifts</fullName>
            </value>
            <value>
                <fullName>Lobby</fullName>
            </value>
            <value>
                <fullName>Staircase</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Water pump</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
            <value>
                <fullName>Fit-outs</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Possession</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/classes/CustomPaymentPlan_Test.cls
@isTest
public class CustomPaymentPlan_Test {
	 @isTest
     public static void CustomPaymentPlanMethod()
     {	
         Project__c projectObject = new Project__c();
         projectObject.Name = 'test';
         insert projectObject;
         
         Payment_Plan__c payment = new Payment_Plan__c();
         payment.Name = 'TEST';
         payment.Project__c = projectObject.Id;
         insert payment;
         
         Project_Progress__c projectProgress = new Project_Progress__c();
         projectProgress.Name = 'testProject';
         projectProgress.Project__c = projectObject.Id;
         projectProgress.Stage_Type__c = 'Plinth';
         insert projectProgress;
         
         Test.startTest();
         
         Payment_Plan_Milestones__c paymentObject  = new Payment_Plan_Milestones__c();
         paymentObject.Days_after_Booking__c =   20;
         paymentObject.Milestone_age__c = 20; 
         paymentObject.Milestone_Activation__c= 'Booking Date';
         paymentObject.Name  = 'Test';
         paymentObject.Payment_Plan__c= payment.Id;
         paymentObject.Project_Progress__c= projectProgress.Id;
         paymentObject.Sequence_No__c = 30;
         insert paymentObject;
        
         Payment_Plan_Milestones__c paymentObject1  = new Payment_Plan_Milestones__c();
         paymentObject1.Days_after_Booking__c =   20;
         paymentObject1.Milestone_age__c = 20; 
         paymentObject1.Milestone_Activation__c= 'Booking Date';
         paymentObject1.Name  = 'Test';
         paymentObject1.Payment_Plan__c= payment.Id;
         paymentObject1.Project_Progress__c= projectProgress.Id;
         paymentObject1.Sequence_No__c = 30;
         insert paymentObject1;
         try{
            CustomPaymentPlan.Requests request = new CustomPaymentPlan.Requests();
            request.planId = payment.Id;
        
            String playmentPlanDetail = CustomPaymentPlan.getPaymentPlanMilestones(new List<CustomPaymentPlan.Requests>{request})[0];
         }catch(Exception e){}
         Test.stopTest();
     }
}