dynamix/force-app/main/default/objects/Booking_Line_Items__c/Booking_Line_Items__c.object-meta.xml
<CustomObject>
    <label>Booking Line Items</label>
    <nameField>
        <label>Booking Line Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booking Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking_Line_Items__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Booking Line Items</relationshipLabel>
    <relationshipName>Booking_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Deck_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>Deck_Carpet_Area__c</fullName>
    <label>Deck Carpet Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Flat_Type__c.field-meta.xml
<CustomField>
    <fullName>Flat_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COVERED STACK</fullName>
            </value>
            <value>
                <fullName>STACK</fullName>
            </value>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK G</fullName>
            </value>
            <value>
                <fullName>2.5 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
            <value>
                <fullName>PENTHOUSES</fullName>
            </value>
            <value>
                <fullName>ROW HOUSES</fullName>
            </value>
            <value>
                <fullName>VILLAS</fullName>
            </value>
            <value>
                <fullName>BUNGALOW</fullName>
            </value>
            <value>
                <fullName>SHOP WITH TERRACE</fullName>
            </value>
            <value>
                <fullName>SHOP WITHOUT TERRACE</fullName>
            </value>
            <value>
                <fullName>OFFICE WITH TERRACE</fullName>
            </value>
            <value>
                <fullName>OFFICE WITHOUT TERRACE</fullName>
            </value>
            <value>
                <fullName>REFUGEE</fullName>
            </value>
            <value>
                <fullName>STUDIO</fullName>
            </value>
            <value>
                <fullName>CAR PARKING</fullName>
            </value>
            <value>
                <fullName>BIKE PARKING</fullName>
            </value>
            <value>
                <fullName>BASEMENT PARKING</fullName>
                <isActive>false</isActive>
                <label>BASEMENT PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE OPEN PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE OPEN PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE PODIUM PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE PODIUM PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE STILT PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE STILT PARKING</label>
            </value>
            <value>
                <fullName>OPEN PARKING</fullName>
                <isActive>false</isActive>
                <label>OPEN PARKING</label>
            </value>
            <value>
                <fullName>PODIUM PARKING</fullName>
                <isActive>false</isActive>
                <label>PODIUM PARKING</label>
            </value>
            <value>
                <fullName>STILT PARKING</fullName>
                <isActive>false</isActive>
                <label>STILT PARKING</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Property_Status__c.field-meta.xml
<CustomField>
    <fullName>Property_Status__c</fullName>
    <label>Property Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pre - Allotted</fullName>
            </value>
            <value>
                <fullName>Allotted</fullName>
            </value>
            <value>
                <fullName>Allotted In Progress</fullName>
            </value>
            <value>
                <fullName>Confirmed Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/RERA_Carpet_Area__c.field-meta.xml
<CustomField>
    <fullName>RERA_Carpet_Area__c</fullName>
    <label>RERA Carpet Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Total_Area__c.field-meta.xml
<CustomField>
    <fullName>Total_Area__c</fullName>
    <formula>Approved_Area__c +  Deck_Approved_Area__c + Utility_Area__c +Enclosed_balcony__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approved Total Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please add tower as per project selected</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Tower__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property_Add_On__c/Property_Add_On__c.object-meta.xml
<CustomObject>
    <label>Property Add On Charges</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties Add On</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property_Add_On__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipName>Properties_Add_On</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/Suggested_Property__c.object-meta.xml
<CustomObject>
    <label>Suggested Property</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Suggestion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suggested Property</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Short Listed</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Send for Cost-Sheet Approval</fullName>
            </value>
            <value>
                <fullName>Custom Payment Plan Approved</fullName>
            </value>
            <value>
                <fullName>Custom Payment Plan Reject</fullName>
            </value>
            <value>
                <fullName>Send for Cost-Sheet Discount Approval</fullName>
            </value>
            <value>
                <fullName>Discount Approved</fullName>
            </value>
            <value>
                <fullName>Discount Reject</fullName>
            </value>
            <value>
                <fullName>Send for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Confirmed Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/classes/PropertyGraphicalViewWrapper.cls
public with sharing class PropertyGraphicalViewWrapper {
    
    @AuraEnabled
    public List<Tower> towers;

    public class Tower{

        @AuraEnabled
        public String name;

        @AuraEnabled
        public List<Floor> floors;

        public Tower(Property__c prop){

            this.name = prop.Tower__r.Name;
            this.floors = new List<Floor>();
            this.floors.add(new Floor(prop));
        }
    }

    public class Floor{

        @AuraEnabled
        public String name;

        @AuraEnabled
        public List<Property> properties;

        public Floor(Property__c prop){
            this.name = prop.Floor__c;
            this.properties = new List<Property>();
            this.properties.add(new Property(prop));
        }
    }

    public class Property{
        
        @AuraEnabled
        public String id;

        @AuraEnabled
        public String name;

        @AuraEnabled
        public String floor;

        @AuraEnabled
        public String status;

        @AuraEnabled
        public String unitType;

        @AuraEnabled
        public String propertyType;

        @AuraEnabled
        public String tower;

        @AuraEnabled
        public Decimal totalArea;

        @AuraEnabled
        public String preferredLocation;

        @AuraEnabled
        public Decimal basicPrice;

        @AuraEnabled
        public Decimal floorRise;

        @AuraEnabled
        public Decimal pLC;

        @AuraEnabled
        public String bookedBy;

        @AuraEnabled
        public String salesManager;

        @AuraEnabled
        public Date bookingDate;

        @AuraEnabled
        public Id bookingId;

        @AuraEnabled
        public Decimal RERACarpetArea;

        @AuraEnabled
        public Decimal DeckCarpetArea;

        @AuraEnabled
        public Decimal UtilityArea;

        public Property(Property__c prop){
            this.id = prop.Id;
            this.name = prop.Name;
            this.status = prop.Property_Status__c;
            this.unitType = prop.Flat_Type__c;
            this.tower = prop.Tower__r.Name;
            this.floor = prop.Floor__c;
            this.totalArea = prop.Total_Area__c;
            this.RERACarpetArea = prop.RERA_Carpet_Area__c;
            this.DeckCarpetArea = prop.Deck_Carpet_Area__c;
            this.UtilityArea = prop.Utility_Area__c;
            this.preferredLocation = '';
            
            if(prop.Properties_Add_On__r.size() > 0){
                List<String> plcs = new List<String>();
                for(Property_Add_On__c propAddOn: prop.Properties_Add_On__r){
                    plcs.add(propAddOn.Project_Add_On__r.Name);
                }

                this.preferredLocation = String.join(plcs, ', ');
            }
            else{
                this.preferredLocation = 'Not Available';
            }

            this.pLC = 0;
            this.floorRise = 0;
            this.basicPrice = 0;

            if(prop.Pricing_Plan_Detail__c != null){
                PropertyPriceJSON propertyPrice = (PropertyPriceJSON)JSON.deserialize(prop.Pricing_Plan_Detail__c, PropertyPriceJSON.class);

                for(PropertyPriceJSON.PriceComponent component: propertyPrice.components){

                    Decimal price = component.priceLumpSum == null? component.pricePerSQFT*this.totalArea:component.priceLumpSum;
                    if(component.name == 'Basic Price'){
                        this.basicPrice = price;
                    }
                    else if(component.name == 'Floor Rise'){
                        if(prop.Floor__c != null)
                        {
                            this.floorRise = price*Decimal.valueOf(prop.Floor__c);
                        }
                    }
                    else if(component.type == 'Preferred Location' && this.preferredLocation.contains(component.name)){
                        this.pLC += price;
                    }
                }
            }

            if(prop.Suggested_Property__r.size() > 0){
                for(Suggested_Property__c suggestedProp: prop.Suggested_Property__r){
                    if(suggestedProp.Status__c == prop.Property_Status__c && prop.Property_Status__c == 'In Progress'){
                        this.bookedBy = suggestedProp.Opportunity__r.Account.FirstName + ' ' + suggestedProp.Opportunity__r.Account.LastName;
                        this.salesManager = suggestedProp.Opportunity__r.Owner.Name;
                        this.bookingDate = suggestedProp.Status_Change_Date__c;
                    }
                }
            }

            if(prop.Booking_Line_Items__r.size() > 0){
                for(Booking_Line_Items__c booking: prop.Booking_Line_Items__r){
                    this.bookedBy = booking.Booking__r.Primary_Applicant__r.FirstName + ' ' + booking.Booking__r.Primary_Applicant__r.LastName;
                    this.salesManager = booking.Booking__r.Sales_Manager__r.Name;
                    this.bookingDate = booking.Booking__r.Booking_Date__c;
                    this.bookingId = booking.Booking__c;
                }
            }
        }
    }
}