dynamix/force-app/main/default/objects/EOI_CA_Payment__c/EOI_CA_Payment__c.object-meta.xml
<CustomObject>
    <label>EOI/CA Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>EOI/CA Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EOI/CA Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/EOI_CA_Payment__c/fields/EOI_CA_Payment__c.field-meta.xml
<CustomField>
    <fullName>EOI_CA_Payment__c</fullName>
    <formula>Text(Opportunity__r.EOI_CA__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EOI/CA Payment</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/EOI_CA_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Bounced</fullName>
                <isActive>false</isActive>
                <label>Bounced</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Cleared</fullName>
                <isActive>false</isActive>
                <label>Cleared</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
            <value>
                <fullName>Wrong Entry</fullName>
                <isActive>false</isActive>
                <label>Wrong Entry</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/EOI_CA_Payment__c/fields/Reason_for_reject__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_reject__c</fullName>
    <inlineHelpText>Please add a reason for payment is rejection.</inlineHelpText>
    <label>Reason for reject</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insufficient Funds</fullName>
            </value>
            <value>
                <fullName>POD</fullName>
            </value>
            <value>
                <fullName>Signature Mismatch</fullName>
            </value>
            <value>
                <fullName>Amount Mismatch</fullName>
            </value>
            <value>
                <fullName>Overwriting</fullName>
            </value>
            <value>
                <fullName>Payment stop by client</fullName>
            </value>
            <value>
                <fullName>Details Mismatch</fullName>
            </value>
            <value>
                <fullName>INSUFFICIENT FUND</fullName>
            </value>
            <value>
                <fullName>Amount in word and figure mismatch</fullName>
            </value>
            <value>
                <fullName>Stop Payment done by Allottee</fullName>
            </value>
            <value>
                <fullName>Contact Drawer</fullName>
            </value>
            <value>
                <fullName>Receipt entry not reflected in Bank Statement</fullName>
            </value>
            <value>
                <fullName>Double entry done by CRM Team</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/EOI_CA_Payment__c/fields/SAP_Approved_Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>SAP_Approved_Rejected_Date__c</fullName>
    <label>SAP Approved/Rejected Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/EOI_CA_Payment__c/fields/Sap_code__c.field-meta.xml
<CustomField>
    <fullName>Sap_code__c</fullName>
    <label>Sap code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>Pay-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment__c/fields/EOI_CA_Payment__c.field-meta.xml
<CustomField>
    <fullName>EOI_CA_Payment__c</fullName>
    <label>EOI/CA Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Bounced</fullName>
                <isActive>false</isActive>
                <label>Bounced</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Cleared</fullName>
                <isActive>false</isActive>
                <label>Cleared</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
            <value>
                <fullName>Wrong Entry</fullName>
                <isActive>false</isActive>
                <label>Wrong Entry</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Reason_for_reject__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_reject__c</fullName>
    <inlineHelpText>Please add a reason for payment is rejection.</inlineHelpText>
    <label>Reason for reject</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Insufficient Funds</fullName>
            </value>
            <value>
                <fullName>POD</fullName>
            </value>
            <value>
                <fullName>Signature Mismatch</fullName>
            </value>
            <value>
                <fullName>Amount Mismatch</fullName>
            </value>
            <value>
                <fullName>Overwriting</fullName>
            </value>
            <value>
                <fullName>Payment stop by client</fullName>
            </value>
            <value>
                <fullName>Details Mismatch</fullName>
            </value>
            <value>
                <fullName>INSUFFICIENT FUND</fullName>
            </value>
            <value>
                <fullName>Amount in word and figure mismatch</fullName>
            </value>
            <value>
                <fullName>Stop Payment done by Allottee</fullName>
            </value>
            <value>
                <fullName>Contact Drawer</fullName>
            </value>
            <value>
                <fullName>Receipt entry not reflected in Bank Statement.</fullName>
            </value>
            <value>
                <fullName>Double entry done by CRM Team.</fullName>
            </value>
            <value>
                <fullName>Unit Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/SAP_Approved_Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>SAP_Approved_Rejected_Date__c</fullName>
    <label>SAP Approved/Rejected Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Sap_code__c.field-meta.xml
<CustomField>
    <fullName>Sap_code__c</fullName>
    <label>Sap code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/classes/ReceiptConfirmation.cls
@RestResource(urlMapping='/receiptconfirmation/*')
global class ReceiptConfirmation {
    @HttpGet
    global static Void getdemandRecord() {
        RestResponse res = RestContext.response;
		try {
            List<SObject> paymentToUpdate=new List<SObject>();
            Map<String, Object> demandObject = (Map<String, Object>)JSON.deserializeUntyped(RestContext.request.requestBody.toString());
            Map<String, Object> innerBody = (Map<String, Object>)demandObject.get('ZFI012_SFDC_REC_POS_OUTBOUND');
            Map<String, Object> internalMap = (Map<String, Object>)innerBody.get('RECPOS_DATA');
            List<Object> itemList = (List<Object>)internalMap.get('item');
            System.debug('ppp'+itemList);
            if(itemList.size()>0){
                for (Object obj:itemList){
                    Map<String, Object> item = (Map<String, Object>)obj;
    				Id SF_Id = SFValidId.repairCasing(String.valueOf(item.get('ZSFDC_ID')));
                    String Status = String.valueOf(item.get('ZPAYMENT_STATUS'));
                    String Description = String.valueOf(item.get('ZPAYMENT_DES'));
                    String PaymentSapCode = String.valueOf(item.get('ZRECEIPT_DOC'));
                    
                    Schema.SObjectType objectType = SF_Id.getSObjectType();
                    String objectName = objectType.getDescribe().getName();
                    if(objectName=='Payment__c'){
                        if(Status=='Accept'){
                            Payment__c pp=new Payment__c();
                            pp.id=SF_Id;
                            pp.Payment_Status__c='Approved';
                            pp.Sap_code__c=PaymentSapCode;
                            pp.SAP_Approved_Rejected_Date__c = system.today();
                            paymentToUpdate.add(pp);
                            
                        }
                        if(Status=='Reject'){
                            Payment__c pp=new Payment__c();
                            pp.id=SF_Id;
                            pp.Payment_Status__c='Rejected';
                            pp.Reason_for_reject__c=Description;
                            pp.Sap_code__c=PaymentSapCode;
                            pp.SAP_Approved_Rejected_Date__c = system.today();
                            paymentToUpdate.add(pp);
                            
                        }
                    }
                    else if(objectName=='EOI_CA_Payment__c'){
                        if(Status=='Accept'){
                            EOI_CA_Payment__c pp=new EOI_CA_Payment__c();
                            pp.id=SF_Id;
                            pp.Payment_Status__c='Approved';
                            pp.Sap_code__c=PaymentSapCode;
                            pp.SAP_Approved_Rejected_Date__c = system.today();
                            paymentToUpdate.add(pp);
                            
                        }
                        if(Status=='Reject'){
                            EOI_CA_Payment__c pp=new EOI_CA_Payment__c();
                            pp.id=SF_Id;
                            pp.Payment_Status__c='Rejected';
                            pp.Reason_for_reject__c=Description;
                            pp.Sap_code__c=PaymentSapCode;
                            pp.SAP_Approved_Rejected_Date__c = system.today();
                            paymentToUpdate.add(pp);
                            
                        }
                    }
                }
            }
            List<JSONGenerator> jsonGeneratorList = new List<JSONGenerator>();
            if(paymentToUpdate.size()>0){
                JSONGenerator jsonGenerator1 = JSON.createGenerator(true);
            jsonGenerator1.writeStartObject();
            jsonGenerator1.writeFieldName('RESPONSE');
            
            jsonGenerator1.writeStartObject(); //RECPOS_DATA
            
            jsonGenerator1.writeFieldName('item');
                jsonGenerator1.writeStartArray();
                Database.SaveResult[] updateResults = Database.update(paymentToUpdate, false); 
                for (Database.SaveResult result : updateResults) {
                    if (result.isSuccess()) {
                        jsonGenerator1.writeStartObject();
                        jsonGenerator1.writeStringField('SFDC_ID',String.valueOf(result.getId()).toUpperCase());
                        jsonGenerator1.writeStringField('STATUS','Success'); jsonGenerator1.writeStringField('MESSAGE','Received'); 
                        jsonGenerator1.writeEndObject();
                        System.debug('Success'+result.getId());
                    }
                }
                jsonGenerator1.writeEndArray();
            
            jsonGenerator1.writeEndObject();
            jsonGenerator1.writeEndObject();
            jsonGeneratorList.add(jsonGenerator1);
            }
            String jsonString = '';
             if(jsonGeneratorList.size()>0){
                
                for (JSONGenerator generator : jsonGeneratorList) {
                    jsonString += generator.getAsString();
                }
                system.debug('jsonString--> '+jsonString);
               // getSapCodes(jsonString,TransProcessed);
            }
           
            
           res.statusCode = 201;
           String  jsonResponse = jsonString; //MESSAGE
           res.responseBody = blob.valueOf(jsonResponse);
        }
        catch (Exception e){
           System.debug('---Request----'+e);
           res.statusCode = 400;
           String  jsonResponse = '{"response": {"SFDC_ID": '+''+'\", "STATUS": "' + 'Error' + '"," MESSAGE":"'+'Error occured while updating a payment :'+e+'}}';
           res.responseBody = blob.valueOf(jsonResponse);
           return;
        }
       
}
 public class CustomException extends Exception {}
}