dynamix/force-app/main/default/objects/Pricing_Plan__c/Pricing_Plan__c.object-meta.xml
<CustomObject>
    <label>Pricing Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Pricing_Plan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Pricing Plans</relationshipLabel>
    <relationshipName>Pricing_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan__c/fields/Valid_from__c.field-meta.xml
<CustomField>
    <fullName>Valid_from__c</fullName>
    <label>Valid from</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan__c/fields/Valid_to__c.field-meta.xml
<CustomField>
    <fullName>Valid_to__c</fullName>
    <label>Valid to</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/Pricing_Plan_Components__c.object-meta.xml
<CustomObject>
    <label>Pricing Plan Component</label>
    <nameField>
        <label>Pricing Plan Components Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Plan Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZPR0</fullName>
                <label>Flat material</label>
            </value>
            <value>
                <fullName>ZCPR</fullName>
                <label>Car Parking</label>
            </value>
            <value>
                <fullName>ZLC0</fullName>
                <label>Legal Charges</label>
            </value>
            <value>
                <fullName>ZWEC</fullName>
                <label>Utility conn. Charge</label>
            </value>
            <value>
                <fullName>ZSF0</fullName>
                <label>Society Formation</label>
            </value>
            <value>
                <fullName>ZSAM</fullName>
                <label>Share Appl Money</label>
            </value>
            <value>
                <fullName>ZSD1</fullName>
                <label>Security Deposit</label>
            </value>
            <value>
                <fullName>ZREG</fullName>
                <label>Registration Charge</label>
            </value>
            <value>
                <fullName>ZSDT</fullName>
                <label>Stamp Duty</label>
            </value>
            <value>
                <fullName>ZCPA</fullName>
                <label>Additional Car Parking</label>
            </value>
            <value>
                <fullName>ZCLS</fullName>
                <label>Large Car Parkspace</label>
            </value>
            <value>
                <fullName>ZCSS</fullName>
                <label>Small Car Parkspace</label>
            </value>
            <value>
                <fullName>ZCP1</fullName>
                <label>Car Parking 1</label>
            </value>
            <value>
                <fullName>ZCP2</fullName>
                <label>Car Parking 2</label>
            </value>
            <value>
                <fullName>Base</fullName>
                <isActive>false</isActive>
                <label>Base</label>
            </value>
            <value>
                <fullName>Feature</fullName>
                <isActive>false</isActive>
                <label>Feature</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/GST_Treatment__c.field-meta.xml
<CustomField>
    <fullName>GST_Treatment__c</fullName>
    <label>GST Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>0%</fullName>
            </value>
            <value>
                <fullName>1%</fullName>
            </value>
            <value>
                <fullName>3%</fullName>
            </value>
            <value>
                <fullName>5%</fullName>
            </value>
            <value>
                <fullName>12%</fullName>
            </value>
            <value>
                <fullName>18%</fullName>
            </value>
            <value>
                <fullName>28%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Price_Lumpsum__c.field-meta.xml
<CustomField>
    <fullName>Price_Lumpsum__c</fullName>
    <label>Price (Lumpsum)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Price_per_SQFT__c.field-meta.xml
<CustomField>
    <fullName>Price_per_SQFT__c</fullName>
    <label>Price (per SQFT.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Pricing_Plan__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Plan__c</fullName>
    <label>Pricing Plan</label>
    <referenceTo>Pricing_Plan__c</referenceTo>
    <relationshipLabel>Pricing Plan Components</relationshipLabel>
    <relationshipName>Pricing_Plan_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Project_Add_On_Charges__c.field-meta.xml
<CustomField>
    <fullName>Project_Add_On_Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Add On Charges</label>
    <referenceTo>Project_Add_On_Charges__c</referenceTo>
    <relationshipLabel>Pricing Plan Components</relationshipLabel>
    <relationshipName>Pricing_Plan_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/Project_Add_On_Charges__c.object-meta.xml
<CustomObject>
    <label>Project Add On Charges</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Add On Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/fields/Allotted_Units__c.field-meta.xml
<CustomField>
    <fullName>Allotted_Units__c</fullName>
    <label>Allotted Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Add_On_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/recordTypes/Charges.recordType-meta.xml
<RecordType>
    <fullName>Charges</fullName>
    <active>true</active>
    <label>Charges</label>
</RecordType>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Property_Price_Slab__c.field-meta.xml
<CustomField>
    <fullName>Property_Price_Slab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Price Slab</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please add price slab as per project selected</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Pricing_Plan__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pricing_Plan__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/classes/pricingPlanClass_Test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-31-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   12-31-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@isTest
public class pricingPlanClass_Test {
	@isTest public static void pricingPlanClassTestMethod()
    {	
        List<Pricing_Plan_Components__c> planObjectList = new List<Pricing_Plan_Components__c>();
        Project__c projObj = new Project__c();
        projObj.Name = 'test project';
        insert projObj;
        
        Pricing_Plan__c pricingObject = new Pricing_Plan__c();
        pricingObject.Name= 'Pricing Object';
        pricingObject.Project__c = projObj.Id;
        pricingObject.Valid_from__c = system.today();
        pricingObject.Valid_to__c = system.today() + 30;
        insert pricingObject;
        
        Property__c prop1 = new Property__c(Name='Testing property1',Floor__c='1',Property_Price_Slab__c=pricingObject.id,Project__c=projObj.id);
        insert prop1;
        
        Pricing_Plan_Components__c planObject = new Pricing_Plan_Components__c();
        planObject.Name = 'test123';
       // planObject.Price_Lumpsum__c = 400;
        planObject.Pricing_Plan__c = pricingObject.Id;
        planObject.GST_Treatment__c='5%';
        planObject.Price_per_SQFT__c =20 ;
        planObjectList.add(planObject);
        insert planObjectList;
        
        List<Project_Add_On_Charges__c> addOnList = new List<Project_Add_On_Charges__c>();
        Project_Add_On_Charges__c projAddOnObject = new Project_Add_On_Charges__c();
        projAddOnObject.Name = 'Test Charges';
        projAddOnObject.Project__c = projObj.Id;
        projAddOnObject.Allotted_Units__c = 20;
        insert projAddOnObject;
        addOnList.add(projAddOnObject);
        
        List<Pricing_Plan_Components__c> pricingPlanCmpList = [select Id,Name,Pricing_Plan__r.Project__c,Pricing_Plan__c from Pricing_Plan_Components__c where Pricing_Plan__c =: pricingObject.Id limit 1];
        system.debug('pricingPlanCmpList=='+pricingPlanCmpList);
        
        Project_Add_On_Charges__c projAddOnObject1 = new Project_Add_On_Charges__c();
        projAddOnObject1.Name = 'Test Add On Charges';
        projAddOnObject1.Project__c = pricingPlanCmpList[0].Pricing_Plan__r.Project__c;
        projAddOnObject1.Allotted_Units__c = 20;
        insert projAddOnObject1;
        addOnList.add(projAddOnObject1);
        
        Test.startTest();
        pricingPlanClass.createRecords(planObjectList, pricingObject.Name,pricingObject.Valid_from__c,pricingObject.Valid_to__c, projObj.Id, pricingObject.Id);
        pricingPlanClass.getPricingList(projObj.Id);
        Test.stopTest();
    }
    @isTest public static void pricingPlanClassTestMethodA()
    {	
        List<Pricing_Plan_Components__c> planObjectList = new List<Pricing_Plan_Components__c>();
        Project__c projObj = new Project__c();
        projObj.Name = 'test project';
        insert projObj;
        
        Pricing_Plan__c pricingObject = new Pricing_Plan__c();
        pricingObject.Name= 'Pricing Object';
        pricingObject.Project__c = projObj.Id;
        pricingObject.Valid_from__c = system.today();
        pricingObject.Valid_to__c = system.today() + 30;
        insert pricingObject;
        
        Property__c prop1 = new Property__c(Name='Testing property1',Floor__c='1',Property_Price_Slab__c=pricingObject.id,Project__c=projObj.id);
        insert prop1;
        
        Pricing_Plan_Components__c planObject = new Pricing_Plan_Components__c();
        planObject.Name = 'test123';
        planObject.Price_Lumpsum__c = 400;
        planObject.Pricing_Plan__c = pricingObject.Id;
        planObject.GST_Treatment__c='5%';
        //planObject.Price_per_SQFT__c =20 ;
        planObjectList.add(planObject);
        insert planObjectList;
        
        Project_Add_On_Charges__c projAddOnObject = new Project_Add_On_Charges__c();
        projAddOnObject.Name = 'Test Charges';
        projAddOnObject.Project__c = projObj.Id;
        projAddOnObject.Allotted_Units__c = 20;
        insert projAddOnObject;
        
        Test.startTest();
        pricingPlanClass.createRecords(planObjectList, pricingObject.Name,pricingObject.Valid_from__c,pricingObject.Valid_to__c, projObj.Id, pricingObject.Id);
        pricingPlanClass.getPricingList(projObj.Id);
        Test.stopTest();
    }
    
    @isTest public static void pricingPlanClassTestMethodC()
    {	
        List<Pricing_Plan_Components__c> planObjectList = new List<Pricing_Plan_Components__c>();
        Project__c projObj = new Project__c();
        projObj.Name = 'test project';
        insert projObj;
        
        Pricing_Plan__c pricingObject = new Pricing_Plan__c();
        pricingObject.Name= 'Pricing Object';
        pricingObject.Project__c = projObj.Id;
        pricingObject.Valid_from__c = system.today();
        pricingObject.Valid_to__c = system.today() + 30;
        insert pricingObject;
        
        Property__c prop1 = new Property__c(Name='Testing property1',Floor__c='1',Property_Price_Slab__c=pricingObject.id,Project__c=projObj.id);
        insert prop1;
        
        Pricing_Plan_Components__c planObject = new Pricing_Plan_Components__c();
        planObject.Name = 'test123';
       // planObject.Price_Lumpsum__c = 400;
        planObject.Pricing_Plan__c = pricingObject.Id;
        planObject.GST_Treatment__c='5%';
        planObject.Price_per_SQFT__c =20 ;
        planObjectList.add(planObject);
        insert planObjectList;
        
        Map<String,Pricing_Plan_Components__c> pricingPlanMap = new Map<String,Pricing_Plan_Components__c>();
        pricingPlanMap.put(planObject.Name,planObject);
        
        List<Project_Add_On_Charges__c> addOnList = new List<Project_Add_On_Charges__c>();
        Project_Add_On_Charges__c projAddOnObject = new Project_Add_On_Charges__c();
        projAddOnObject.Name = 'Test Charges';
        projAddOnObject.Project__c = projObj.Id;
        projAddOnObject.Allotted_Units__c = 20;
        insert projAddOnObject;
        addOnList.add(projAddOnObject);
        
        List<Pricing_Plan_Components__c> pricingPlanCmpList = [select Id,Name,Pricing_Plan__r.Project__c,Pricing_Plan__c from Pricing_Plan_Components__c where Pricing_Plan__c =: pricingObject.Id limit 1];
        system.debug('pricingPlanCmpList=='+pricingPlanCmpList);
        
        Project_Add_On_Charges__c projAddOnObject1 = new Project_Add_On_Charges__c();
        projAddOnObject1.Name = 'Test Add On Charges';
        projAddOnObject1.Project__c = pricingPlanCmpList[0].Pricing_Plan__r.Project__c;
        projAddOnObject1.Allotted_Units__c = 20;
        insert projAddOnObject1;
        addOnList.add(projAddOnObject1);
        
        Test.startTest();
        system.debug('planObjectList==='+planObjectList);
        system.debug('pricingObject.Name==='+pricingObject.Name);
        system.debug('pricingObject.Id==='+pricingObject.Id);
        pricingPlanClass.createRecords(planObjectList,planObject.Name,pricingObject.Valid_from__c,pricingObject.Valid_to__c,pricingObject.Id, pricingObject.Id);
        pricingPlanClass.getPricingList(pricingObject.Id);
        Test.stopTest();
    }
    
    @isTest public static void pricingPlanClassTestMethod1()
    {	
        List<Pricing_Plan_Components__c> planObjectList = new List<Pricing_Plan_Components__c>();
        Project__c projObj = new Project__c();
        projObj.Name = 'test project';
        insert projObj;
        
        Pricing_Plan__c pricingObject = new Pricing_Plan__c();
        pricingObject.Name= 'Pricing Object';
        pricingObject.Project__c = projObj.Id;
        pricingObject.Valid_from__c = system.today();
        pricingObject.Valid_to__c = system.today() + 30;
        insert pricingObject;
        
        Property__c prop1 = new Property__c(Name='Testing property1',Floor__c='1',Property_Price_Slab__c=pricingObject.id,Project__c=projObj.id);
        insert prop1;
        
        Pricing_Plan_Components__c planObject = new Pricing_Plan_Components__c();
        planObject.Name = 'test123';
        //planObject.Price_per_SQFT__c = 400;
        planObject.Pricing_Plan__c = pricingObject.Id;
        planObject.GST_Treatment__c='5%';
        //planObject.Component_Type__c = 'Feature';
        planObjectList.add(planObject);
        insert planObjectList;
        
        Project_Add_On_Charges__c projAddOnObject = new Project_Add_On_Charges__c();
        projAddOnObject.Name = 'Test Charges';
        projAddOnObject.Project__c = projObj.Id;
        projAddOnObject.Allotted_Units__c = 20;
        insert projAddOnObject;
        
        Test.startTest();
        pricingPlanClass.createRecords(planObjectList,planObject.Name,pricingObject.Valid_from__c,pricingObject.Valid_to__c,projObj.Id, null);
        pricingPlanClass.getPricingList(pricingObject.Id);
        Test.stopTest();
    }
     @isTest public static void pricingPlanClassTestMethod2()
    {	
        List<Pricing_Plan_Components__c> planObjectList = new List<Pricing_Plan_Components__c>();
        Project__c projObj = new Project__c();
        projObj.Name = 'test project';
        insert projObj;
        
        Pricing_Plan__c pricingObject = new Pricing_Plan__c();
        pricingObject.Name= 'Pricing Object';
        pricingObject.Project__c = projObj.Id;
        pricingObject.Valid_from__c = system.today();
        pricingObject.Valid_to__c = system.today() + 30;
        insert pricingObject;
        
        Pricing_Plan__c pricingObject1 = new Pricing_Plan__c();
        pricingObject1.Name= 'Pricing Object';
        pricingObject1.Project__c = projObj.Id;
        insert pricingObject1;
        
        Property__c prop1 = new Property__c(Name='Testing property1',Floor__c='1',Property_Price_Slab__c=pricingObject.id,Project__c=projObj.id);
        insert prop1;
        
        Pricing_Plan_Components__c planObject = new Pricing_Plan_Components__c();
        planObject.Name = 'test123';
        planObject.Price_per_SQFT__c = 400;
        planObject.Pricing_Plan__c = pricingObject1.Id;
        planObject.GST_Treatment__c='5%';
        planObject.Component_Type__c = '';
        planObjectList.add(planObject);
        insert planObjectList;
        
        Project_Add_On_Charges__c projAddOnObject = new Project_Add_On_Charges__c();
        projAddOnObject.Name = 'Test Charges';
        projAddOnObject.Project__c = projObj.Id;
        projAddOnObject.Allotted_Units__c = 20;
        insert projAddOnObject;
        
        Test.startTest();
        pricingPlanClass.createRecords(planObjectList, pricingObject.Name,pricingObject.Valid_from__c,pricingObject.Valid_to__c, projObj.Id, pricingObject.Id);
        //pricingPlanClass.pricingPlanWrapper pwrap = pricingPlanClass.getPricingList(projObj.Id);
        pricingPlanClass.getPricingList(projObj.Id);
        Test.stopTest();
    }
}