dynamix/force-app/main/default/objects/Pricing_Plan__c/Pricing_Plan__c.object-meta.xml
<CustomObject>
    <label>Pricing Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/Pricing_Plan_Components__c.object-meta.xml
<CustomObject>
    <label>Pricing Plan Component</label>
    <nameField>
        <label>Pricing Plan Components Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Plan Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Price_Lumpsum__c.field-meta.xml
<CustomField>
    <fullName>Price_Lumpsum__c</fullName>
    <label>Price (Lumpsum)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Pricing_Plan__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Plan__c</fullName>
    <label>Pricing Plan</label>
    <referenceTo>Pricing_Plan__c</referenceTo>
    <relationshipLabel>Pricing Plan Components</relationshipLabel>
    <relationshipName>Pricing_Plan_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Project_Add_On_Charges__c.field-meta.xml
<CustomField>
    <fullName>Project_Add_On_Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Add On Charges</label>
    <referenceTo>Project_Add_On_Charges__c</referenceTo>
    <relationshipLabel>Pricing Plan Components</relationshipLabel>
    <relationshipName>Pricing_Plan_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/Project_Add_On_Charges__c.object-meta.xml
<CustomObject>
    <label>Project Add On Charges</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Add On Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/recordTypes/Charges.recordType-meta.xml
<RecordType>
    <fullName>Charges</fullName>
    <active>true</active>
    <label>Charges</label>
</RecordType>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Pricing_Plan_Detail__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Plan_Detail__c</fullName>
    <label>Pricing Plan Detail</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Property_Price_Slab__c.field-meta.xml
<CustomField>
    <fullName>Property_Price_Slab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Price Slab</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please add price slab as per project selected</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Pricing_Plan__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pricing_Plan__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property_Add_On__c/Property_Add_On__c.object-meta.xml
<CustomObject>
    <label>Property Add On Charges</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties Add On</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property_Add_On__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipName>Properties_Add_On</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/classes/GetBasePrice.cls
public class GetBasePrice {
    
     @InvocableMethod(label='Get Charges By Type')
    public static List<Decimal> execute( List<Requests> requestLst){
         	List<Property_Add_On__c> propertyAddOnList = new List<Property_Add_On__c>();
         	PropertyPriceJSON propertyPrice = new PropertyPriceJSON();
          	List<Decimal> basePriceList = new List<Decimal>();
        	Pricing_Plan_Components__c PricingPlanList = new Pricing_Plan_Components__c();
        
         	Property__c property = [SELECT id,Pricing_Plan_Detail__c,Property_Price_Slab__c FROM Property__c WHERE Id =: requestLst[0].propertyId];
            if(property <> null)
            {
              PricingPlanList = [select id,Price_Lumpsum__c from Pricing_Plan_Components__c where (Pricing_Plan__c =: property.Property_Price_Slab__c AND (Name =: 'Basic Price' OR Project_Add_On_Charges__r.name = 'Basic Price'))];  
            }
            basePriceList.add(PricingPlanList.Price_Lumpsum__c);
            return basePriceList;
    }
    
    public class Requests {
        @InvocableVariable(label='Property Id' required=true)
        public String propertyId;

    }

}