dynamix/force-app/main/default/objects/Pricing_Plan__c/Pricing_Plan__c.object-meta.xml
<CustomObject>
    <label>Pricing Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Pricing_Plan__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Pricing Plans</relationshipLabel>
    <relationshipName>Pricing_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/Pricing_Plan_Components__c.object-meta.xml
<CustomObject>
    <label>Pricing Plan Component</label>
    <nameField>
        <label>Pricing Plan Components Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Plan Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/GST_Treatment__c.field-meta.xml
<CustomField>
    <fullName>GST_Treatment__c</fullName>
    <label>GST Treatment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>0%</fullName>
            </value>
            <value>
                <fullName>1%</fullName>
            </value>
            <value>
                <fullName>3%</fullName>
            </value>
            <value>
                <fullName>5%</fullName>
            </value>
            <value>
                <fullName>12%</fullName>
            </value>
            <value>
                <fullName>18%</fullName>
            </value>
            <value>
                <fullName>28%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Price_Lumpsum__c.field-meta.xml
<CustomField>
    <fullName>Price_Lumpsum__c</fullName>
    <label>Price (Lumpsum)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Price_per_SQFT__c.field-meta.xml
<CustomField>
    <fullName>Price_per_SQFT__c</fullName>
    <label>Price (per SQFT.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Pricing_Plan__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Plan__c</fullName>
    <label>Pricing Plan</label>
    <referenceTo>Pricing_Plan__c</referenceTo>
    <relationshipLabel>Pricing Plan Components</relationshipLabel>
    <relationshipName>Pricing_Plan_Components</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Pricing_Plan_Components__c/fields/Project_Add_On_Charges__c.field-meta.xml
<CustomField>
    <fullName>Project_Add_On_Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Add On Charges</label>
    <referenceTo>Project_Add_On_Charges__c</referenceTo>
    <relationshipLabel>Pricing Plan Components</relationshipLabel>
    <relationshipName>Pricing_Plan_Components</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/Project_Add_On_Charges__c.object-meta.xml
<CustomObject>
    <label>Project Add On Charges</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Add On Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Variable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Add_On_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Pricing_Plan_Detail__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Plan_Detail__c</fullName>
    <label>Pricing Plan Detail</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Property_Price_Slab__c.field-meta.xml
<CustomField>
    <fullName>Property_Price_Slab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Price Slab</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please add price slab as per project selected</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Pricing_Plan__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pricing_Plan__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/classes/PricingPlanToJSON.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-31-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   12-31-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public class PricingPlanToJSON {

    public static void toJSON(List<Property__c> properties){

        Set<Id> planIds = new set<Id>();
        Map<id,List<Property__c>> propertPlanMap = new Map<id,List<Property__c>>();
       
        for(Property__c p : properties){  
            planIds.add(p.Property_Price_Slab__c); 
            
            if(propertPlanMap.containsKey(p.Property_Price_Slab__c)){   
                
                List<Property__c> propertyList = propertPlanMap.get(p.Property_Price_Slab__c);
                propertyList.add(p);
                propertPlanMap.put(p.Property_Price_Slab__c,propertyList);
            }
            else{
                List<Property__c> propertyList = new List<Property__c>();
                propertyList.add(p);
                propertPlanMap.put(p.Property_Price_Slab__c,propertyList);
            }
        }
     
        List<Pricing_Plan__c> pricingPlans = [SELECT Id, Name, Project__c, 
                                                (SELECT Id, Name, GST_Treatment__c, Project_Add_On_Charges__r.recordType.Name,
                                                    Price_Lumpsum__c,Price_per_SQFT__c,Pricing_Plan__c 
                                                    FROM Pricing_Plan_Components__r 
                                                    WHERE Project_Add_On_Charges__r.Charge_Type__c = 'Fixed') 
                                             FROM Pricing_Plan__c WHERE Id IN: planIds];
        
        for(Pricing_Plan__c plan : pricingPlans){

            PropertyPriceJSON priceJSON = new PropertyPriceJSON();
            priceJSON.components = new List<PropertyPriceJSON.PriceComponent>();

            for(Pricing_Plan_Components__c planComponent: plan.Pricing_Plan_Components__r){

                PropertyPriceJSON.PriceComponent priceComponent = new PropertyPriceJSON.PriceComponent();
                priceComponent.name = planComponent.Name;
                priceComponent.type = planComponent.Project_Add_On_Charges__r.recordType.name;
                priceComponent.gst = planComponent.GST_Treatment__c;
                priceComponent.priceLumpSum = planComponent.Price_Lumpsum__c;
                priceComponent.pricePerSQFT = planComponent.Price_per_SQFT__c;

                priceJSON.components.add(priceComponent);
            }
            
            List<Property__c> proList = propertPlanMap.get(plan.id);
            for(Property__c prop : proList){
                prop.Pricing_Plan_Detail__c = JSON.serialize(priceJSON);
            }
        }
    }
    
    public static void updateJSON(List<Pricing_Plan_Components__c> planComponents){
           
        Set<Id> planIds = new Set<Id>();
        Map<id,List<Property__c>> propertPlanMap = new Map<id,List<Property__c>>();
        List<Property__c> propertiesToUpdate = new List<Property__c>();
        
        for(Pricing_Plan_Components__c planComponent : planComponents){
            planIds.add(planComponent.Pricing_Plan__c);
        }

        for(Property__c property: [SELECT Id, Property_Price_Slab__c FROM Property__c WHERE Property_Price_Slab__c IN: planIds]){

            if(propertPlanMap.containsKey(property.Property_Price_Slab__c)){

                List<Property__c> propertyList = propertPlanMap.get(property.Property_Price_Slab__c);
                propertyList.add(property);
                propertPlanMap.put(property.Property_Price_Slab__c,propertyList);
            }
            else{   
                List<Property__c> propertyList = new List<Property__c>();
                propertyList.add(property);
                propertPlanMap.put(property.Property_Price_Slab__c,propertyList);
            }
        }

        List<Pricing_Plan__c> pricingPlans = [SELECT Id, Name, Project__c, 
                                                (SELECT Id, Name, GST_Treatment__c, Project_Add_On_Charges__r.recordType.Name,
                                                    Price_Lumpsum__c,Price_per_SQFT__c,Pricing_Plan__c 
                                                    FROM Pricing_Plan_Components__r 
                                                    WHERE Project_Add_On_Charges__r.Charge_Type__c = 'Fixed') 
                                             FROM Pricing_Plan__c WHERE Id IN: planIds];

        for(Pricing_Plan__c plan : pricingPlans){

            PropertyPriceJSON priceJSON = new PropertyPriceJSON();
            priceJSON.components = new List<PropertyPriceJSON.PriceComponent>();

            for(Pricing_Plan_Components__c planComponent: plan.Pricing_Plan_Components__r){

                PropertyPriceJSON.PriceComponent priceComponent = new PropertyPriceJSON.PriceComponent();
                priceComponent.name = planComponent.Name;
                priceComponent.type = planComponent.Project_Add_On_Charges__r.recordType.name;
                priceComponent.gst = planComponent.GST_Treatment__c;
                priceComponent.priceLumpSum = planComponent.Price_Lumpsum__c;
                priceComponent.pricePerSQFT = planComponent.Price_per_SQFT__c;

                priceJSON.components.add(priceComponent);
            }
            System.debug(plan.id);
            System.debug(propertPlanMap);
            
            if(propertPlanMap.containsKey(plan.id)){
                List<Property__c> proList = propertPlanMap.get(plan.id);
                
                for(Property__c prop: proList){
                    prop.Pricing_Plan_Detail__c = JSON.serialize(priceJSON);
                    propertiesToUpdate.add(prop);
                }
            }
        }
     
        if(!propertiesToUpdate.isEmpty()){
            update propertiesToUpdate;
        }
    }
}