dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Disable_All_Reminders__c.field-meta.xml
<CustomField>
    <fullName>Disable_All_Reminders__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable All Reminders</label>
    <type>Checkbox</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <formula>Project_Name__r.Project_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Email</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Suggested_Property__c.field-meta.xml
<CustomField>
    <fullName>Related_Suggested_Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Suggested Property</label>
    <referenceTo>Suggested_Property__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <formula>Related_Suggested_Property__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Number</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/BookingId__c.field-meta.xml
<CustomField>
    <fullName>BookingId__c</fullName>
    <description>BookingId For Backend.</description>
    <label>BookingId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>Pay-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>NEFT/ RTGS/ IMPS</fullName>
            </value>
            <value>
                <fullName>Credit/Debit Cards</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>SAP Credit Note</fullName>
            </value>
            <value>
                <fullName>Bank Disbursement</fullName>
                <isActive>false</isActive>
                <label>Bank Disbursement</label>
            </value>
            <value>
                <fullName>Debit Note</fullName>
                <isActive>false</isActive>
                <label>Debit Note</label>
            </value>
            <value>
                <fullName>Electronic NEFT/ RTGS</fullName>
                <isActive>false</isActive>
                <label>Electronic NEFT/ RTGS</label>
            </value>
            <value>
                <fullName>IMPS</fullName>
                <isActive>false</isActive>
                <label>IMPS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant__c</fullName>
    <formula>IF( Booking__r.Primary_Applicant__r.FirstName &lt;&gt; null &amp;&amp; Booking__r.Primary_Applicant__r.FirstName &lt;&gt; &apos;&apos;,Booking__r.Primary_Applicant__r.FirstName+&apos; &apos;+Booking__r.Primary_Applicant__r.LastName , Booking__r.Primary_Applicant__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Applicant</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Receipt_No__c.field-meta.xml
<CustomField>
    <fullName>Receipt_No__c</fullName>
    <description>RA0000001</description>
    <label>Receipt No:</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <formula>Booking__r.Related_Suggested_Property__r.Unit__r.Name</formula>
    <label>Unit Number</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <label>Project Email</label>
    <type>Email</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit No.</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/Suggested_Property__c.object-meta.xml
<CustomObject>
    <label>Suggested Property</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Suggestion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suggested Property</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <formula>Unit__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Suggested Property</relationshipLabel>
    <relationshipName>Suggested_Property</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/classes/GeneratePaymentReceiptForWaiveOff.cls
public class GeneratePaymentReceiptForWaiveOff {
    @future(callout=true)
    public static void GeneratePaymentReceipt(string bookingld,string paymentId){
        system.debug('Line number  ---------' + paymentId);
        system.debug('Line number  ---------' + bookingld);
        PageReference ref = Page.Payment_Receipt;
        ref.getParameters().put('id', paymentId);
        
        Payment__c paymentRec = [Select Id,Receipt_No__c,Payment_Type__c,Project_Name__c, Booking__c from Payment__c where Id =:paymentId];
        system.debug('paymentRec----->' +paymentRec);
        
        Blob body; 
        
        if(Test.isRunningTest()){
            body = Blob.valueOf('Payment Receipt');
        }
        else{
            body = ref.getContent();
        }
        
        ContentVersion conVer = new ContentVersion();
        conVer.ContentLocation = 'S'; 
        conVer.PathOnClient =  paymentRec.Receipt_No__c+'.pdf';
        conVer.Title =  paymentRec.Receipt_No__c+'.pdf';
        conVer.VersionData = body;
        conVer.SObjectType__c = 'Booking__c';
        conVer.BookingId__c = paymentRec.Booking__c;
        conVer.Document_Type__c = 'Payment Receipt';
        insert conVer; 
        System.debug('conVer--------->'+conVer);
        
        /* ContentVersion conVer2 = new ContentVersion();
conVer2.ContentLocation = 'S'; 
conVer2.PathOnClient =  paymentRec.Receipt_No__c+'.pdf';
conVer2.Title =  paymentRec.Receipt_No__c+'.pdf';
conVer2.VersionData = body;
conVer2.SObjectType__c = 'Payment__c';
conVer2.BookingId__c = paymentRec.Id;
//conVer2.Document_Type__c = 'Payment Receipt';
insert conVer2; 
System.debug('conVer--------->'+conVer2);*/
        
        Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
        System.debug('conDoc----------->'+conDoc);
        
        ContentDocumentLink conDocLink = New ContentDocumentLink();
        conDocLink.LinkedEntityId = bookingld; 
        conDocLink.ContentDocumentId = conDoc;  
        conDocLink.shareType = 'V';
        insert conDocLink;
        
        ContentDocumentLink conDocLink1 = New ContentDocumentLink();
        conDocLink1.LinkedEntityId = paymentId; 
        conDocLink1.ContentDocumentId = conDoc; 
        conDocLink1.shareType = 'V';
        insert conDocLink1;
        Boolean checkEmailSending = Boolean.valueOf(System.Label.Credit_Note_Receipt_Email);
        Boolean checkCondition = Boolean.valueOf(System.Label.Payment_Receipt_Send_to_Cusomer);
        if(paymentRec.Payment_Type__c=='SAP Credit Note' && checkEmailSending){
            SendEmail(conDocLink1,bookingld,paymentId);
        }
        else if(paymentRec.Payment_Type__c!='SAP Credit Note' && checkCondition){
            SendEmail(conDocLink1,bookingld,paymentId);
        }
    }
    public static void SendEmail(ContentDocumentLink conDocLink1, Id bkid, id payId){
        List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();
        List<String> toMailList = New List<String>();
        Booking__c booking = [select id, Disable_All_Reminders__c,Related_Opportunity__c, Project_Name__c,Related_Suggested_Property__c,
                              Project_Name__r.Name,Unit_Number__c,Project_Name__r.Project_Email__c, Primary_Applicant__r.PersonEmail,
                              Primary_Applicant__r.PersonContactId
                              from Booking__c where id=: bkid];
        System.debug('booking----->'+booking);
        
        Suggested_Property__c suggestedProperty = [Select Id, Unit__c,Unit__r.Name from Suggested_Property__c where Id =:booking.Related_Suggested_Property__c ];
        
        List<Contentversion> conlist = [select id,ContentDocumentId,Title,VersionData from Contentversion where ContentDocumentId = :conDocLink1.ContentDocumentId];
        System.debug('conlist---------->'+conlist);
        
        for (Contentversion cov : conlist) {
            Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
            String Title = booking.Project_Name__r.Name+ '/'+ booking.Unit_Number__c+'/'+cov.Title;
            System.debug('Title----------->'+Title);
            
            efa.setFileName(Title);
            efa.setBody(cov.VersionData);
            attachments.add(efa);
            System.debug('efa:--------' +efa);
        }
        system.debug('attachments'+attachments);  
        
        EmailTemplate emailTemplate = [SELECT Id, Subject, Description, HtmlValue, DeveloperName, Body FROM EmailTemplate WHERE Name = 'Generate Payment Notification'];	//Receipt'];
        System.debug('emailTemplate---------->'+emailTemplate);
        OrgWideEmailAddress orgEmail = [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress WHERE Address =: booking.Project_Name__r.Project_Email__c];
        System.debug('orgEmail--------->'+orgEmail);
        String bookingFormLink = Label.Booking_Form_Link;
        bookingFormLink += '?Id=' + booking.Id;
        
        String Subject = emailTemplate.Subject;
        if (booking != null && booking.Project_Name__c != null && booking.Project_Name__r.Name != null) {
            Subject = Subject.replace('Booking__c.Project_Name__r.Name', booking.Project_Name__r.Name);
        }
        if(suggestedProperty != null && suggestedProperty.Unit__c != null && suggestedProperty.Unit__r.Name != null){
            Subject = Subject.replace('suggestedProperty.Unit__r.Name', suggestedProperty.Unit__r.Name);
        }
        if(booking != null && booking.Unit_Number__c != null){
            Subject = Subject.replace('Booking__c.Unit_Number__c', booking.Unit_Number__c);
        }
        
        Subject = Subject.replace('{!bookingFormLink}', bookingFormLink);      
        
        List<Messaging.SingleEmailMessage> emailMsgList = New List<Messaging.SingleEmailMessage>();
        Boolean checkCondition = Boolean.valueOf(System.Label.Payment_Receipt_Send_to_Cusomer);
        if(checkCondition){
            if(booking.Primary_Applicant__r.PersonEmail != '' &&  booking.Primary_Applicant__r.PersonEmail != null)
            {
                List<Id> idList = new List<Id>();
                for (Contentversion con : conlist) {
                    idList.add(con.Id);
                }
                toMailList.add(booking.Primary_Applicant__r.PersonEmail);
                Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(String.Valueof(emailTemplate.Id), null, booking.id);
                // email.setTargetObjectId(booking.Primary_Applicant__r.PersonContactId);
                email.setOrgWideEmailAddressId(orgEmail.Id);
                email.setToAddresses(toMailList);
                email.setEntityAttachments(new List<Id>(idList));
                email.setSubject(Subject);
                emailMsgList.add(email);
            }
            if (emailMsgList.size() > 0) 
            {
                Messaging.SendEmailResult[] results = Messaging.sendEmail(emailMsgList);
                if(results[0].success)
                {
                    System.debug('The email was sent successfully.');
                }
                else {
                    System.debug('The email failed to send: ' +  results[0].errors[0].message);
                } 
            }
        }
    }
}