dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Suggested_Property__c.field-meta.xml
<CustomField>
    <fullName>Related_Suggested_Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Suggested Property</label>
    <referenceTo>Suggested_Property__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Activation_Date__c</fullName>
    <label>Milestone Activation Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_age__c.field-meta.xml
<CustomField>
    <fullName>Milestone_age__c</fullName>
    <label>Milestone %</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Amount1__c</fullName>
    <label>Milestone Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Project_Progress__c.field-meta.xml
<CustomField>
    <fullName>Project_Progress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Progress</label>
    <referenceTo>Project_Progress__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <label>Sequence No</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Project_Progress__c/Project_Progress__c.object-meta.xml
<CustomObject>
    <label>Project Progress</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/classes/UpdateBookingPaymentMilestones.cls
public with sharing class UpdateBookingPaymentMilestones{
    
    @InvocableMethod(label='Update Booking Payment Milestones')
    public static void execute( List<Requests> requestLst){
        
        system.debug('===> requestLst ' + requestLst);
        String bookingId= requestLst[0].bookingId;
        String paymentMilestoneId = requestLst[0].JsonMilestone;
        Decimal newAgreementValue = requestLst[0].newAgreementValue;
        
        List<String> paymentMilestoneIdforDelete = new List<String>();
        String[] VarIds;
        if(requestLst[0].DeleteIdsOfPM != null)
        {
            // paymentMilestoneIdforDelete =+ requestLst[0].DeleteIdsOfPM;
            VarIds = requestLst[0].DeleteIdsOfPM;
        }
        system.debug('paymentMilestoneIdforDelete ==> ' + paymentMilestoneIdforDelete );
        system.debug('VarIds ==> ' + VarIds );
        Booking__c bk = [select Related_Suggested_Property__c from Booking__c where id =: bookingId];
        
        List<Payment_Milestones__c> UpdatePaymentMilestoneList = [select id,Name,Project_Progress__c,Milestone_age__c,Milestone_Activation_Date__c from Payment_Milestones__c where Booking__c = : bookingId];
        system.debug('===> UpdatePaymentMilestoneList ' + UpdatePaymentMilestoneList);
        system.debug('===> paymentMilestoneId ' + paymentMilestoneId);
        
        List<Payment_Milestones__c> paymentMilestones = (List<Payment_Milestones__c>)JSON.deserialize(requestLst[0].JsonMilestone, List<Payment_Milestones__c>.class);
        
        for(Payment_Milestones__c ppm : paymentMilestones){
            if(ppm.Name != 'Possession/Handover(Other) Charge'){
                ppm.Milestone_age__c = (ppm.Milestone_Amount1__c/newAgreementValue)*100;
            }
            if(ppm.id == null)
            {
                ppm.Booking__c = bookingId;
            }
            ppm.Name = ppm.Name;
            ppm.Sequence_No__c = ppm.Sequence_No__c;
            
            
        }
        
        if(paymentMilestones.size() > 0)
        {
            upsert paymentMilestones;
        }
        //system.debug('===> updatePaymentMilestoneLst' + updatePaymentMilestoneLst);
        
        // For Payment Milestones Delete
        List<Payment_Milestones__c> DeletePaymentMilestoneLst = new List<Payment_Milestones__c>();
        DeletePaymentMilestoneLst = [select id from Payment_Milestones__c where Id IN : VarIds];
        system.debug('==> var id ' + DeletePaymentMilestoneLst);
        if(DeletePaymentMilestoneLst.size() > 0)
        {
            delete DeletePaymentMilestoneLst;
        }
        
        
        
    }
    public class Requests {
        
        @InvocableVariable(label='Booking Id' required=true)
        public String bookingId;
        
        @InvocableVariable(label='JsonString' required=true)
        public String JsonMilestone;
        
        @InvocableVariable(label='DeleteIdsOfPM' required=true)
        public String[] DeleteIdsOfPM;
        
        @InvocableVariable(label='New Agreement Value' required=true)
        public Decimal newAgreementValue;
        
    }
}