dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Sap_Code__c.field-meta.xml
<CustomField>
    <fullName>Sap_Code__c</fullName>
    <label>Sap Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Total_TDS_Pending__c.field-meta.xml
<CustomField>
    <fullName>Total_TDS_Pending__c</fullName>
    <label>Total TDS Pending</label>
    <summarizedField>Payment_Milestones__c.TDS_Pending__c</summarizedField>
    <summaryForeignKey>Payment_Milestones__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Total_TDS_Received__c.field-meta.xml
<CustomField>
    <fullName>Total_TDS_Received__c</fullName>
    <label>Total TDS Received</label>
    <summarizedField>Payment_Milestones__c.TDS_Received__c</summarizedField>
    <summaryForeignKey>Payment_Milestones__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Total_TDS_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_TDS_Value__c</fullName>
    <label>Total TDS Value</label>
    <summarizedField>Payment_Milestones__c.TDS_Value__c</summarizedField>
    <summaryForeignKey>Payment_Milestones__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Transferred_To_Booking__c.field-meta.xml
<CustomField>
    <fullName>Transferred_To_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transferred To Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/Data_Sync__c.object-meta.xml
<CustomObject>
    <label>Data_Sync</label>
    <nameField>
        <displayFormat>DS-{0000000}</displayFormat>
        <label>Data_Sync Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data_Syncs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>TextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response_Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Sync_Direction__c.field-meta.xml
<CustomField>
    <fullName>Sync_Direction__c</fullName>
    <label>Sync Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SFDC to SAP</fullName>
            </value>
            <value>
                <fullName>SAP to SFDC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>Pay-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Cheque_Transaction_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Transaction_Number__c</fullName>
    <label>Cheque/ Transaction/ Challan Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Paid_By__c.field-meta.xml
<CustomField>
    <fullName>Paid_By__c</fullName>
    <label>Paid By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Loan Disbursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment_Category__c.field-meta.xml
<CustomField>
    <fullName>Payment_Category__c</fullName>
    <label>Payment Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unit Cost</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>GST</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Refundable Interior Deposit</fullName>
            </value>
            <value>
                <fullName>Temporary Electricity Charges</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Security Deposits</fullName>
            </value>
            <value>
                <fullName>Possession/Handover(Other) Charge</fullName>
            </value>
            <value>
                <fullName>Possession/Handover(Other) Charge GST</fullName>
            </value>
            <value>
                <fullName>Security and Share Money</fullName>
            </value>
            <value>
                <fullName>Security and Share Money GST</fullName>
            </value>
            <value>
                <fullName>Transfer Charge</fullName>
            </value>
            <value>
                <fullName>Brokerage Charges</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>GST Avanya Tower A</fullName>
            </value>
            <value>
                <fullName>OCR</fullName>
                <isActive>false</isActive>
                <label>OCR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Bounced</fullName>
                <isActive>false</isActive>
                <label>Bounced</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Cleared</fullName>
                <isActive>false</isActive>
                <label>Cleared</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
            <value>
                <fullName>Wrong Entry</fullName>
                <isActive>false</isActive>
                <label>Wrong Entry</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>NEFT/ RTGS/ IMPS</fullName>
            </value>
            <value>
                <fullName>Credit/Debit Cards</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>SAP Credit Note</fullName>
            </value>
            <value>
                <fullName>Bank Disbursement</fullName>
                <isActive>false</isActive>
                <label>Bank Disbursement</label>
            </value>
            <value>
                <fullName>Debit Note</fullName>
                <isActive>false</isActive>
                <label>Debit Note</label>
            </value>
            <value>
                <fullName>Electronic NEFT/ RTGS</fullName>
                <isActive>false</isActive>
                <label>Electronic NEFT/ RTGS</label>
            </value>
            <value>
                <fullName>IMPS</fullName>
                <isActive>false</isActive>
                <label>IMPS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Receipt_No__c.field-meta.xml
<CustomField>
    <fullName>Receipt_No__c</fullName>
    <description>RA0000001</description>
    <label>Receipt No:</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/SAP_Approved_Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>SAP_Approved_Rejected_Date__c</fullName>
    <label>SAP Approved/Rejected Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Sap_code__c.field-meta.xml
<CustomField>
    <fullName>Sap_code__c</fullName>
    <label>Sap code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/classes/TDSPaymentRestAPI.cls
/*
 * Author : Nachiketa Khera
 * Created Date : 22th January 2024
 * Description : Rest API to capture TDS data from SAP and Create a Payment record with category TDS
 * Last Modified Date : 31th January 2024
*/
@RestResource(urlMapping='/tdsPayment/*')
global class TDSPaymentRestAPI {
    @HttpGet
    global static void getTdsRecord() {
        RestResponse res = RestContext.response;
		try {
            List<Payment__c> paymentToInsert = new List<Payment__c>();
            Map<String, Object> tdsPayment = (Map<String, Object>)JSON.deserializeUntyped(RestContext.request.requestBody.toString());
            Map<String, Object> innerBody = (Map<String, Object>)tdsPayment.get('ZFI016_SFDC_TDS_OUTBOUND');
            Map<String, Object> internalMap = (Map<String, Object>)innerBody.get('TDS_DATA');
            List<Object> itemList = (List<Object>)internalMap.get('item');
            System.debug('ppp'+itemList);
            Map<String,String> CodesOfBooking = new Map<String,String>();
            List<JSONGenerator> jsonGeneratorList = new List<JSONGenerator>();
         	List<JSONGenerator> jsonGeneratorList2 = new List<JSONGenerator>();
            if(itemList.size()>0){
                for (Object obj:itemList){
                    Map<String, Object> item = (Map<String, Object>)obj;
                    String bookingCode = String.valueOf(item.get('BOOKING_ID'));
                    String customerCode = String.valueOf(item.get('CUSTOMER_ID'));
                    String paymentCategory = String.valueOf(item.get('CATEGORY'));
                    String paymentAmount = String.valueOf(item.get('AMOUNT'));
                    String tdsDate = String.valueOf(item.get('DATE'));
                    String challanNo = String.valueOf(item.get('CHALLAN_NO'));
                    
                    List<Booking__c> bookList = [Select Id,Sap_Code__c from Booking__c where Sap_Code__c =: bookingCode limit 1];
                    if(bookList.size()>0){
                        Payment__c tdsPay = new Payment__c();
                        tdsPay.Booking__c = bookList[0].Id;
                        tdsPay.Payment_Category__c = 'TDS';
                        tdsPay.Amount__c = Decimal.valueOf(paymentAmount);
                        system.debug('tdsDate-- '+tdsDate);
                        Date paymentDate = Date.valueOf(dateFormat(tdsDate));
                        system.debug('paymentDate-- '+paymentDate);
                        tdsPay.Payment_Date__c = paymentDate;
                        tdsPay.Cheque_Transaction_Number__c = challanNo;
                        tdsPay.Paid_By__c = 'Self';
                        tdsPay.Payment_Status__c = 'Approved';
                        tdsPay.Status__c = 'Approved';
                        tdsPay.Payment_Type__c = 'NEFT/ RTGS/ IMPS';
                        tdsPay.SAP_Approved_Rejected_Date__c = paymentDate;
                        if(test.isRunningTest()){
                            tdsPay.Receipt_No__c = '12345';
                        }
                        paymentToInsert.add(tdsPay);
                    }
                    else{
                        system.debug('In else');
                        CodesOfBooking.put(bookingCode,tdsDate);
                    }
                }
            }
            
            if(paymentToInsert.size()>0){
                JSONGenerator jsonGenerator1 = JSON.createGenerator(true);
                jsonGenerator1.writeStartObject();
                jsonGenerator1.writeFieldName('RESPONSE');
                jsonGenerator1.writeStartObject();
                jsonGenerator1.writeFieldName('item');
                jsonGenerator1.writeStartArray();
                Database.SaveResult[] insertResults = Database.insert(paymentToInsert, false); 
                for (Database.SaveResult result : insertResults) {
                    if(result.isSuccess()){
                        Payment__c insertedPayment = [Select Id,Amount__c,Booking__c,Booking__r.Total_TDS_Value__c,Booking__r.Total_TDS_Received__c,
                                                      Booking__r.Total_TDS_Pending__c,Booking__r.Sap_Code__c,Payment_Date__c from Payment__c where Id=:result.getId()];
                        jsonGenerator1.writeStartObject();
                        jsonGenerator1.writeStringField('BOOKING_ID',insertedPayment.Booking__r.Sap_Code__c!=null?insertedPayment.Booking__r.Sap_Code__c:'');
                        jsonGenerator1.writeStringField('STATUS','SUCCESS');
                        jsonGenerator1.writeStringField('TDS_AMOUNT',insertedPayment != null && insertedPayment.Amount__c != null?string.valueOf(insertedPayment.Amount__c):'');
                        
                        Date payDate = insertedPayment.Payment_Date__c;
                        String formattedDay = (payDate.day() < 10) ? '0' + String.valueOf(payDate.day()) : String.valueOf(payDate.day());
                        String formattedMonth = (payDate.month() < 10) ? '0' + String.valueOf(payDate.month()) : String.valueOf(payDate.month());
                        String paymentDate = formattedDay + '.' + formattedMonth + '.' + payDate.year();
                        
                        jsonGenerator1.writeStringField('TDS_DATE',paymentDate != null?string.valueOf(paymentDate):'');
                        jsonGenerator1.writeStringField('TOTAL_TDS',insertedPayment.Booking__r.Total_TDS_Value__c != null?string.valueOf(insertedPayment.Booking__r.Total_TDS_Value__c):'');
                        jsonGenerator1.writeStringField('TOTAL_TDS_REC',insertedPayment.Booking__r.Total_TDS_Received__c != null?string.valueOf(insertedPayment.Booking__r.Total_TDS_Received__c):'');
                        jsonGenerator1.writeStringField('TOTAL_TDS_BAL',insertedPayment.Booking__r.Total_TDS_Pending__c != null?string.valueOf(insertedPayment.Booking__r.Total_TDS_Pending__c):'');
                        jsonGenerator1.writeStringField('MESSAGE','TDS Created Successfully');
                        jsonGenerator1.writeEndObject();
                        System.debug('Success>> '+result.getId());
                    }
                    else{
                        for(Database.Error err : result.getErrors()) {
                            jsonGenerator1.writeStartObject();
                            jsonGenerator1.writeStringField('BOOKING_ID','');
                            jsonGenerator1.writeStringField('STATUS','ERROR');
                            jsonGenerator1.writeStringField('TDS_AMOUNT','0.00');
                            jsonGenerator1.writeStringField('TDS_DATE','');
                            jsonGenerator1.writeStringField('TOTAL_TDS','0.00');
                            jsonGenerator1.writeStringField('TOTAL_TDS_REC','0.00');
                            jsonGenerator1.writeStringField('TOTAL_TDS_BAL','0.00');
                            jsonGenerator1.writeStringField('MESSAGE',err.getMessage());
                            jsonGenerator1.writeEndObject();
                        }
                    }
                }
                jsonGenerator1.writeEndArray();
                jsonGenerator1.writeEndObject();
                jsonGenerator1.writeEndObject();
                jsonGeneratorList.add(jsonGenerator1);
            }
            if(paymentToInsert.size()==0 || !CodesOfBooking.isEmpty()){
                system.debug('inside error');
                system.debug('bookingCodes--> '+CodesOfBooking);
                //res.statusCode = 400;
                JSONGenerator jsonGenerator1 = JSON.createGenerator(true);
                jsonGenerator1.writeStartObject();
                jsonGenerator1.writeFieldName('RESPONSE');
                jsonGenerator1.writeStartObject();
                jsonGenerator1.writeFieldName('item');
                jsonGenerator1.writeStartArray();
                for(String codes:CodesOfBooking.keySet()){
                    jsonGenerator1.writeStartObject();
                    jsonGenerator1.writeStringField('BOOKING_ID',string.valueOf(codes));
                    jsonGenerator1.writeStringField('STATUS','ERROR');
                    jsonGenerator1.writeStringField('TDS_AMOUNT','0.00');
                    jsonGenerator1.writeStringField('TDS_DATE',string.valueOf(CodesOfBooking.get(codes)));
                    jsonGenerator1.writeStringField('TOTAL_TDS','0.00');
                    jsonGenerator1.writeStringField('TOTAL_TDS_REC','0.00');
                    jsonGenerator1.writeStringField('TOTAL_TDS_BAL','0.00');
                    jsonGenerator1.writeStringField('MESSAGE','This Booking Code '+codes+' does not exist');
                    jsonGenerator1.writeEndObject();
                }
                jsonGenerator1.writeEndArray();
                jsonGenerator1.writeEndObject();
                jsonGenerator1.writeEndObject();
                jsonGeneratorList.add(jsonGenerator1);
            }
            String jsonString = '';
            if(jsonGeneratorList.size()>0){
                for (JSONGenerator generator : jsonGeneratorList) {
                    jsonString += generator.getAsString();
                }
                system.debug('jsonString--> '+jsonString);
            }
            res.statusCode = 201;
            String  jsonResponse = jsonString;
            res.responseBody = blob.valueOf(jsonResponse);
            Data_Sync__c ds = new Data_Sync__c();
            ds.Event_Type__c = 'TDS Payment';
            ds.Request_Body__c = RestContext.request.requestBody.toString();
            ds.Response_Body__c = jsonString;
            ds.Sync_Direction__c = 'SAP to SFDC';
            ds.Status__c = 'Success';
            insert ds;
        }
        catch (Exception e){
            System.debug('---Request----'+String.valueOf(e.getLineNumber()));
            res.statusCode = 400;
            String  jsonResponse = '{"response": {"STATUS": "' + 'Error' + '"," MESSAGE":"'+'Error occured while creating tds payment :'+e+'}}';
            res.responseBody = blob.valueOf(jsonResponse);
            Data_Sync__c ds = new Data_Sync__c();
            ds.Event_Type__c = 'TDS Payment';
            ds.Request_Body__c = RestContext.request.requestBody.toString();
            ds.Response_Body__c = jsonResponse;
            ds.Sync_Direction__c = 'SAP to SFDC';
            ds.Status__c = 'Error';
            insert ds;
            
            return;
        }
    }
    public static string dateFormat(string str){
        System.debug('Inside1---'+str);
        String dateFull  = String.valueOf(str);
        System.debug('Inside1str---'+str);
        String[] tdsDate = dateFull.split('\\.');
        System.debug('Inside1-demandDate--'+tdsDate);
        String dd = tdsDate[0]; 
        String mm = tdsDate[1];
        String yyyy = tdsDate[2];
        string tdscreateDate = yyyy+'-'+mm+'-'+dd;
        System.debug('---tdscreateDate------'+tdscreateDate);
        return tdscreateDate;
    }
}