dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Amount__c</fullName>
    <formula>Agreement_Value__c -  Total_Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/communicat_o__Registered_Template__mdt/communicat_o__Registered_Template__mdt.object-meta.xml
<CustomObject>
    <label>Registered Template</label>
    <pluralLabel>Registered Templates</pluralLabel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/First_Payment_Email_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Email_Reminder_Date__c</fullName>
    <formula>Due_Date__c+ 7</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Payment Email Reminder Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/forth_Payment_Email_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>forth_Payment_Email_Reminder_Date__c</fullName>
    <formula>Due_Date__c  +28</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>forth Payment Email Reminder Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Status__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Status__c</fullName>
    <label>Milestone Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Amount__c</fullName>
    <formula>Milestone_Amount1__c - Payment_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_GST__c.field-meta.xml
<CustomField>
    <fullName>Remaining_GST__c</fullName>
    <formula>GST_Amount1__c - GST_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Second_Payment_Email_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>Second_Payment_Email_Reminder_Date__c</fullName>
    <formula>Due_Date__c+ 14</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Second Payment Email Reminder Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Third_Payment_Email_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>Third_Payment_Email_Reminder_Date__c</fullName>
    <formula>Due_Date__c  + 21</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Third Payment Email Reminder Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/classes/secondWhatsappReminderBatch.cls
public class secondWhatsappReminderBatch implements Database.Batchable<sObject>,Database.AllowsCallouts,DataBase.Stateful {
    
    public secondWhatsappReminderBatch(){}
    communicat_o__Registered_Template__mdt regWhatEmailTemp;
    public Database.QueryLocator start(Database.BatchableContext BC){
        Date todayDate=Date.today();
        System.debug('todayDate:'+todayDate);
        //For Send WhatsApp Message
        regWhatEmailTemp=[Select Id,QualifiedApiName,label From communicat_o__Registered_Template__mdt Where label=:'WhatsApp 2nd Payment Reminder' Limit 1];
        System.debug('regWhatEmailTemp:'+regWhatEmailTemp);
        return Database.getQueryLocator([SELECT Id,Name,booking__c,Milestone_Status__c,First_Payment_Email_Reminder_Date__c,forth_Payment_Email_Reminder_Date__c,Third_Payment_Email_Reminder_Date__c,Second_Payment_Email_Reminder_Date__c,Due_Date__c,Remaining_GST__c,Remaining_Amount__c  FROM Payment_Milestones__c where ((First_Payment_Email_Reminder_Date__c=:todayDate OR Third_Payment_Email_Reminder_Date__c=:todayDate OR forth_Payment_Email_Reminder_Date__c=:todayDate OR Second_Payment_Email_Reminder_Date__c=:todayDate) AND Remaining_Amount__c > 0 and Milestone_Status__c ='Active')]);
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope)
    {
        Date todayDate1=Date.today();
        list<Payment_Milestones__c >pmList =  scope;
        system.debug('2nd WP Reminder execute '+scope);
        map<id,id>  mapFirst = new  map<id,id>(); 
        map<id,Payment_Milestones__c> mapSecond = new  map<id,Payment_Milestones__c>(); 
        map<id,id>  mapthird = new  map<id,id>(); 
        map<id,id>  mapforth = new  map<id,id>(); 
        for(Payment_Milestones__c p:pmList ) {
            if(p.Second_Payment_Email_Reminder_Date__c==todayDate1)
            {
                mapSecond.put(p.booking__c,p);
            }
        }
        if(!mapSecond.isEmpty()) 
        {
            // SendSMSForReminder.sendWhatsappRem(mapSecond,Label.Whatsapp_Second_Reminder);
            Set<ID> bookingIds=mapSecond.keyset();
            //for Send WhatsApp SMS
            if(bookingIds.size()>0 && regWhatEmailTemp!=null ){
                for(Id bookingRcdId : bookingIds){
                    Booking__c bookingRcd = [select Id, Name,Primary_Applicant__c,Primary_Applicant__r.PersonMobilePhone FROM Booking__c WHERE Id=: bookingRcdId];
                    System.debug('bookingRcd:'+bookingRcd);
                    if(bookingRcd.Primary_Applicant__r.PersonMobilePhone!=null){
                        String recipientAddress=bookingRcd.Primary_Applicant__r.PersonMobilePhone;
                        String recipientId=bookingRcd.Primary_Applicant__c;
                        String emailTemplateId=String.valueOf(regWhatEmailTemp.Id).substring(0, 15);
                        String relatedToId=bookingRcd.Id;
                        System.debug('emailTemplateId:'+emailTemplateId);
                        if(recipientAddress!=null && recipientId!=null && emailTemplateId!=null){
                            SendPaymentReminderMessage.SendWhatsAppMessage(recipientAddress, recipientId, emailTemplateId,relatedToId);
                        }
                    }
                }
            }
        }
    }  
    public void finish(Database.BatchableContext BC){
        
        ThirdWhatsappReminderBatch bcn = new ThirdWhatsappReminderBatch() ;
        ID batchprocessid = Database.executeBatch(bcn,100);
        
    }
    
}