dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Property_Name__c</fullName>
    <formula>Related_Suggested_Property__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Name</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower Name</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/classes/GeneratEscalationForm.cls
public class GeneratEscalationForm {
    
    @InvocableMethod(label='Generat Escalation Form')
    public static List<String> execute( List<Requests> requestLst){

        Booking__c booking = [SELECT Id,Tower_Name__r.Name,Property_Name__c,Tower_Name__r.Building_Type__c, Name from Booking__c WHERE Id =: requestLst[0].bookingId];
        PageReference ref = Page.Escalation_Form;
        ref.getParameters().put('id', requestLst[0].bookingId);
        
        Blob body; 
        if(Test.isRunningTest()){
            body = Blob.valueOf('Escalation Form');
        }
        else{
            body = ref.getContent();
        }

        ContentVersion conVer = new ContentVersion();
        conVer.ContentLocation = 'S'; // to use S specify this document is in Salesforce, to use E for external files
        conVer.PathOnClient = 'Escalation Form'+ '-' + booking.Property_Name__c +'.pdf'; 
        conVer.Title = 'Escalation Form'+ '-' +booking.Property_Name__c +'.pdf';
        conVer.VersionData = body;
        conVer.SObjectType__c = 'Booking__c';
        conVer.Document_Type__c = 'Escalation';
        insert conVer;    
       
        
        Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
        
        ContentDocumentLink conDocLink = New ContentDocumentLink();
        conDocLink.LinkedEntityId = requestLst[0].bookingId; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
        conDocLink.ContentDocumentId = conDoc;  //ContentDocumentId Id from ContentVersion
        conDocLink.shareType = 'V';
        
        insert conDocLink;

       
        return new List<String>{conDoc};
    }

    public class Requests {
       

        @InvocableVariable(label='Booking Id' required=true)
        public String bookingId;
    }
}