dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/ROC_Uploaded_Date__c.field-meta.xml
<CustomField>
    <fullName>ROC_Uploaded_Date__c</fullName>
    <label>ROC Uploaded Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/BookingId__c.field-meta.xml
<CustomField>
    <fullName>BookingId__c</fullName>
    <description>BookingId For Backend.</description>
    <label>BookingId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
            <value>
                <fullName>Bank Approved ROC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/classes/BatchBankApprovedROCNotUplaodedClass.cls
global class BatchBankApprovedROCNotUplaodedClass implements DataBase.Batchable<Sobject>{
    global Database.QueryLocator start(DataBase.BatchableContext bc){
        
        Date pastThreeDays = System.Today().addDays(-3);
        Date pastSixDays = System.Today().addDays(-6);
        List<Booking__c> b = [Select Id,Name,OwnerId,Owner.Name,CreatedById,ROC_Uploaded_Date__c From Booking__c Where ROC_Uploaded_Date__c =: pastThreeDays OR ROC_Uploaded_Date__c =: pastSixDays];
        System.debug('booookings'+b);

        return Database.getQueryLocator('Select Id,Name,OwnerId,Owner.Name,CreatedById,ROC_Uploaded_Date__c From Booking__c Where ROC_Uploaded_Date__c =: pastThreeDays OR ROC_Uploaded_Date__c =: pastSixDays');
    }
    global void execute(Database.BatchableContext bc,List<Booking__c> BookingList){
        System.debug('booookings');
        EmailTemplate emailTemplate1 = [Select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where DeveloperName = 'Bank_Approved_ROC_Not_Uploded_After_3_days' limit 1];
        EmailTemplate emailTemplate2 = [Select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where DeveloperName = 'Bank_Approved_ROC_Not_Uploded_Even_After_6_Days' limit 1];
        UserRole CRMHeadRoleObj = [select id,Name,DeveloperName from UserRole where DeveloperName =: 'CRM_Head'];
        String CRMHeadUserName = Label.CRM_Head_User;
        User CRMHeadRoleObjUser = [Select Id,Name,Email From User Where UserName =: CRMHeadUserName AND UserRoleId =: CRMHeadRoleObj.Id AND isActive =: true Limit 1];
        System.debug('CRMHeadRoleObjUser'+CRMHeadRoleObjUser);

        Set<Id> setOfBookinIds = new Set<Id>();
        for(Booking__c bookObj : BookingList){
            setOfBookinIds.add(bookObj.Id);
        }
        System.debug('setOfBookinIds'+setOfBookinIds);
        List<ContentVersion> listOfContentVersions = new List<ContentVersion>([Select Id,SObjectType__c,Document_Type__c,BookingId__c From ContentVersion where Document_Type__c =: 'Bank Approved ROC' AND BookingId__c In : setOfBookinIds]);
        Map<Id,ContentVersion> mapBookingIdToContenVersion = new Map<Id,ContentVersion>();
        
        for(ContentVersion con : listOfContentVersions){
            mapBookingIdToContenVersion.put(con.BookingId__c,con);
        }
        System.debug('mapBookingIdToContenVersion'+mapBookingIdToContenVersion);
        Map<Id,User> mapIdToUser = new Map<Id,User>([Select Id,Email,Name From User Where isActive =: true]);   
        OrgWideEmailAddress orgEmail = [select id, Address, DisplayName from OrgWideEmailAddress where DisplayName = 'Divum' Limit 1];
        List<Messaging.SingleEmailMessage> emailMsgList = New List<Messaging.SingleEmailMessage>();
        
        System.debug('Before Loop');
        for(Booking__c bookObj : BookingList){
            String recordLink=URL.getOrgDomainUrl().toExternalForm() + '/' + bookObj.Id;
            System.debug('bookObj'+bookObj);

            if(bookObj.ROC_Uploaded_Date__c.addDays(3) == Date.today()){
                System.debug('bookObj.ROC_Uploaded_Date__c.addDays(3)'+bookObj.ROC_Uploaded_Date__c.addDays(3));
                List<String> addresses1 = new List<String>();
                if(mapIdToUser.size() > 0 && mapIdToUser.containsKey(bookObj.OwnerId)){
                    addresses1.add(mapIdToUser.get(bookObj.OwnerId).Email); 
                }
                if(!mapBookingIdToContenVersion.containsKey(bookObj.Id)){   
                    System.debug('In mapBookingIdToContenVersion');
                    String htmlBody1 = emailTemplate1.HtmlValue;
                    htmlBody1 = htmlBody1.replace('{!bookingName}', '<a href="'+recordLink+'">' + bookObj.Name +'</a>');
                    htmlBody1 = htmlBody1.replace('{!rmName}', mapIdToUser.get(bookObj.OwnerId).Name);
                    String plainBody1 = emailTemplate1.Body;
                    plainBody1 = plainBody1.replace('{!bookingName}', '<a href="'+recordLink+'">' + bookObj.Name +'</a>'); 
                    plainBody1 = plainBody1.replace('{!rmName}', mapIdToUser.get(bookObj.OwnerId).Name);

                    SendEmailandBellNotificationUtility.SendEmail2(emailTemplate1.Id,htmlBody1,plainBody1,addresses1,null,true,bookObj.Id,null,null,null);
                }
            }
            if(bookObj.ROC_Uploaded_Date__c.addDays(6) == Date.today()){
                List<String> addresses2 = new List<String>();
                addresses2.add(CRMHeadRoleObjUser.Email);     
                if(!mapBookingIdToContenVersion.containsKey(bookObj.Id)){
                    String htmlBody1 = emailTemplate2.HtmlValue;
                    htmlBody1 = htmlBody1.replace('{!bookingName}', '<a href="'+recordLink+'">' + bookObj.Name +'</a>');
                    htmlBody1 = htmlBody1.replace('{!rmName}', mapIdToUser.get(bookObj.OwnerId).Name);
                    htmlBody1 = htmlBody1.replace('{!crmHeadName}', CRMHeadRoleObjUser.Name);
                    String plainBody1 = emailTemplate2.Body;
                    plainBody1 = plainBody1.replace('{!bookingName}', '<a href="'+recordLink+'">' + bookObj.Name +'</a>'); 
                    plainBody1 = plainBody1.replace('{!rmName}', mapIdToUser.get(bookObj.OwnerId).Name);

                    plainBody1 = plainBody1.replace('{!crmHeadName}', CRMHeadRoleObjUser.Name);
                    SendEmailandBellNotificationUtility.SendEmail2(emailTemplate2.Id,htmlBody1,plainBody1,addresses2,null,true,bookObj.Id,null,null,null);
                }
            }
        }
    }
    global void finish(Database.BatchableContext bc){
        
    }
}