dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <summarizedField>Price_Details__c.Discount__c</summarizedField>
    <summaryForeignKey>Price_Details__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <summarizedField>Price_Details__c.GST_Calculated__c</summarizedField>
    <summaryFilterItems>
        <field>Price_Details__c.Charge_Group__c</field>
        <operation>contains</operation>
        <value>Agreement</value>
    </summaryFilterItems>
    <summaryForeignKey>Price_Details__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Price_Details__c/Price_Details__c.object-meta.xml
<CustomObject>
    <label>Price Details</label>
    <nameField>
        <label>Price Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Price_Details__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Price Details</relationshipLabel>
    <relationshipName>Price_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Price_Details__c/fields/Charge_Group__c.field-meta.xml
<CustomField>
    <fullName>Charge_Group__c</fullName>
    <label>Charge Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Price_Details__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

dynamix/force-app/main/default/objects/Price_Details__c/fields/GST_Calculated__c.field-meta.xml
<CustomField>
    <fullName>GST_Calculated__c</fullName>
    <formula>Amount_after_discount__c *GST__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Price_Details__c/fields/Total_Amount_incl_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_incl_Tax__c</fullName>
    <formula>Amount__c  +  GST_Calculated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount (incl Tax)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/classes/ManageDiscontForPriceDetails.cls
public class ManageDiscontForPriceDetails {
    
    @InvocableMethod(label='Get Price Detail for Discount')
    public static List<String> execute(List<Requests> requestLst){
        
        List<Price_Details__c> priceDetailLst = [SELECT Id, Name, Amount__c, GST_Calculated__c, Discount__c, 
                                                    Total_Amount_incl_Tax__c, Charge_Group__c,GST__c
                                                    
                                                    FROM Price_Details__c 
                                                    WHERE Booking__c =: requestLst[0].bookingId 
                                                        AND Charge_Group__c LIKE '%Agreement%' 
                                                        ORDER BY Name];
        
        String JsonPmString = JSON.serialize(priceDetailLst);
        
        return new List<String>{JSON.serialize(priceDetailLst)};
    }

    public class Requests {
        @InvocableVariable(label='Booking Id' required=true)
        public String bookingId;
    }
}