dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <label>Agreement Value</label>
    <summarizedField>Price_Details__c.Amount_after_discount__c</summarizedField>
    <summaryFilterItems>
        <field>Price_Details__c.Charge_Group__c</field>
        <operation>contains</operation>
        <value>Agreement</value>
    </summaryFilterItems>
    <summaryForeignKey>Price_Details__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Campaign/fields/Number_of_Bookings__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Bookings__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Bookings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Campaign/fields/Sum_of_Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Sum_of_Agreement_Value__c</fullName>
    <label>Sum of  Agreement Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EN-{000000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Enquiry__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Campaign.Source__c</field>
            <operation>equals</operation>
            <valueField>$Source.Enquiry_Source__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Linked_Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Linked_Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Linked Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/classes/BookingNumberOnCampaign.cls
public class BookingNumberOnCampaign {
    public static void getBookingsOnCampaign(List<Booking__c> bookList){
        Set<Id> oppId = new Set<Id>();
        Set<Id> enqId = new Set<Id>();
        Set<Id> campId = new Set<Id>();
        Map<Id,decimal> agreementValueCountMap = New Map<Id,decimal>();
        Map<Id,decimal> agreementValueCountFinalMap = New Map<Id,decimal>();
        for(Booking__c book:bookList){
            if(book.Related_Opportunity__c != null){
                oppId.add(book.Related_Opportunity__c);
                agreementValueCountMap.put(book.Related_Opportunity__c,book.Agreement_Value__c);
            }
        }
        if(oppId != null){
            for(Opportunity opp:[Select Id,Linked_Enquiry__c from Opportunity where Id=:oppId]){
                if(opp.Linked_Enquiry__c != null){
                    enqId.add(opp.Linked_Enquiry__c);
                    if(agreementValueCountMap.containsKey(opp.Linked_Enquiry__c))
                    {
                        agreementValueCountFinalMap.put(opp.Linked_Enquiry__c,agreementValueCountMap.get(opp.Linked_Enquiry__c));
                    }
                }
            }
        }
        if(enqId != null){
            for(Enquiry__c enq:[Select Id,Campaign__c from Enquiry__c where Id=:enqId]){
                if(enq.Campaign__c != null){
                    campId.add(enq.Campaign__c);
                    if(agreementValueCountFinalMap.containsKey(enq.id))
                    {
                        agreementValueCountFinalMap.put(enq.Campaign__c,agreementValueCountFinalMap.get(enq.id));
                    }
                }
            }
        }
        //Decimal count = 0;
        if(campId != null){
            List<Campaign> campUpdateList = new List<Campaign>();
            for(Campaign camp:[Select Id,Number_of_Bookings__c from Campaign where Id=:campId]){
                if(agreementValueCountFinalMap.containsKey(camp.id))
                {
                    if(camp.Sum_of_Agreement_Value__c != null)
                    {
                       camp.Sum_of_Agreement_Value__c += integer.valueof(agreementValueCountFinalMap.get(camp.id)); 
                    }
                    else
                    {
                         camp.Sum_of_Agreement_Value__c = integer.valueof(agreementValueCountFinalMap.get(camp.id));
                    }
                }
                camp.Number_of_Bookings__c += 1;
                campUpdateList.add(camp);
            }
            update campUpdateList;
        }        
    }
    public static void getBookingsOnCampaignDelete(List<Booking__c> bookList){
        Set<Id> oppId = new Set<Id>();
        Set<Id> enqId = new Set<Id>();
        Set<Id> campId = new Set<Id>();
        Map<Id,decimal> agreementValueCountMap = New Map<Id,decimal>();
        Map<Id,decimal> agreementValueCountFinalMap = New Map<Id,decimal>();

        for(Booking__c book:bookList){
            if(book.Related_Opportunity__c != null){
                oppId.add(book.Related_Opportunity__c);
                agreementValueCountMap.put(book.Related_Opportunity__c,book.Agreement_Value__c);

            }
        }
        if(oppId != null){
            for(Opportunity opp:[Select Id,Linked_Enquiry__c from Opportunity where Id=:oppId]){
                if(opp.Linked_Enquiry__c != null){
                    enqId.add(opp.Linked_Enquiry__c);
                    if(agreementValueCountMap.containsKey(opp.Linked_Enquiry__c))
                    {
                        agreementValueCountFinalMap.put(opp.Linked_Enquiry__c,agreementValueCountMap.get(opp.Linked_Enquiry__c));
                    }
                }
            }
        }
        if(enqId != null){
            for(Enquiry__c enq:[Select Id,Campaign__c from Enquiry__c where Id=:enqId]){
                if(enq.Campaign__c != null){
                    campId.add(enq.Campaign__c);
                    if(agreementValueCountFinalMap.containsKey(enq.id))
                    {
                        agreementValueCountFinalMap.put(enq.Campaign__c,agreementValueCountFinalMap.get(enq.id));
                    }
                }
            }
        }
        //Decimal count = 0;
        if(campId != null){
            List<Campaign> campUpdateList = new List<Campaign>();
            for(Campaign camp:[Select Id,Number_of_Bookings__c from Campaign where Id=:campId]){
                camp.Number_of_Bookings__c -= 1;
                campUpdateList.add(camp);
                if(agreementValueCountFinalMap.containsKey(camp.id))
                {
                    if(camp.Sum_of_Agreement_Value__c != null)
                    {
                       camp.Sum_of_Agreement_Value__c -= integer.valueof(agreementValueCountFinalMap.get(camp.id)); 
                    }
                   
                }
            }
            update campUpdateList;
        }        
    }
}