dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Hidden_Interest_Wave_Off_Amount__c.field-meta.xml
<CustomField>
    <fullName>Hidden_Interest_Wave_Off_Amount__c</fullName>
    <label>Interest Wave Off Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Interest_Wafe_Off_Approved__c.field-meta.xml
<CustomField>
    <fullName>Interest_Wafe_Off_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Interest Wafe Off Approved</label>
    <type>Checkbox</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Suggested_Property__c.field-meta.xml
<CustomField>
    <fullName>Related_Suggested_Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Suggested Property</label>
    <referenceTo>Suggested_Property__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Amount__c</fullName>
    <formula>Agreement_Value__c -  Total_Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Total_interest_amount__c.field-meta.xml
<CustomField>
    <fullName>Total_interest_amount__c</fullName>
    <inlineHelpText>Interest Amount without GST</inlineHelpText>
    <label>Total Interest amount</label>
    <summarizedField>Payment_Milestones__c.Interest_Amount__c</summarizedField>
    <summaryForeignKey>Payment_Milestones__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/GST_Amount1__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount1__c</fullName>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount__c</fullName>
    <label>Interest Amount</label>
    <summarizedField>Interest_Charged__c.Interest_Amount__c</summarizedField>
    <summaryForeignKey>Interest_Charged__c.Milestone__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Interest_Wave_Off_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Wave_Off_Amount__c</fullName>
    <label>Interest Wave Off Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Amount1__c</fullName>
    <label>Milestone Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Status__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Status__c</fullName>
    <label>Milestone Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Amount__c</fullName>
    <formula>Milestone_Amount1__c - Payment_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_GST__c.field-meta.xml
<CustomField>
    <fullName>Remaining_GST__c</fullName>
    <formula>GST_Amount1__c - GST_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <label>Sequence No</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Total_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount__c</fullName>
    <formula>Interest_Amount__c - Interest_Wave_Off_Amount__c-Interest_Payment_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/classes/UpdatePaymentMilestonesForWaveOff.cls
public with sharing class UpdatePaymentMilestonesForWaveOff{
    
    @InvocableMethod(label='Update Booking Payment Milestones For Wave Off')
    public static void execute( List<Requests> requestLst){
        
        system.debug('===> requestLst ' + requestLst);
        String bookingId= requestLst[0].bookingId;
       // String paymentMilestoneId = requestLst[0].JsonMilestone;
         system.debug('===> bookingId' + bookingId);
        
       
        
        Booking__c bk = [select Related_Suggested_Property__c,Hidden_Interest_Wave_Off_Amount__c,Interest_Wafe_Off_Approved__c from Booking__c where id =: bookingId];
        Decimal InterestWaveOffAmount = bk.Hidden_Interest_Wave_Off_Amount__c;
        system.debug('===> InterestWaveOffAmount ' + InterestWaveOffAmount);
        

       List<Payment_Milestones__c> paymentMileStoneList = [SELECT Id,Interest_Amount__c,Total_Interest_Amount__c,Interest_Wave_Off_Amount__c,Milestone_Amount1__c,GST_Amount1__c,Remaining_Amount__c, Remaining_GST__c 
                                                            FROM Payment_Milestones__c 
                                                            WHERE Booking__c = : bookingId And Total_Interest_Amount__c > 0 ORDER BY Milestone_Status__c Asc,Sequence_No__c asc];
        system.debug('======> paymentMileStoneList ' + paymentMileStoneList );
       for(Payment_Milestones__c pm : paymentMileStoneList)
       {
               system.debug('======> pm.Interest_Wave_Off_Amount__c' + pm.Interest_Wave_Off_Amount__c);
                system.debug('======> pm.pm.Interest_Amount__c' + pm.Interest_Amount__c);
                system.debug('======> InterestWaveOffAmount' + InterestWaveOffAmount);
              if(pm.Interest_Wave_Off_Amount__c == null)
              {
                  pm.Interest_Wave_Off_Amount__c = 0;
              }
              if(pm.Total_Interest_Amount__c>= InterestWaveOffAmount){
                   pm.Interest_Wave_Off_Amount__c = pm.Interest_Wave_Off_Amount__c + InterestWaveOffAmount;
                   break;
              }
              else{
                   pm.Interest_Wave_Off_Amount__c = pm.Interest_Wave_Off_Amount__c + pm.Total_Interest_Amount__c;
                   InterestWaveOffAmount = InterestWaveOffAmount - pm.Total_Interest_Amount__c;
                   
              }
       }
       
       update paymentMileStoneList;
       
       // update Interest Wafe Off Approved Field
       bk.Interest_Wafe_Off_Approved__c = false;
       update bk;
        
    }
    public class Requests {
        
       @InvocableVariable(label='Booking Id' required=true)
        public String bookingId;
        
      /* @InvocableVariable(label='JsonString' required=true)
        public String JsonMilestone;
        
       @InvocableVariable(label='Input Interest Value' required=true)
        public Decimal inputedInterestValue;*/

    }
}