dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Cancellation_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Approval_Status__c</fullName>
    <label>Cancellation Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/No_of_Car_Parking__c.field-meta.xml
<CustomField>
    <fullName>No_of_Car_Parking__c</fullName>
    <label>No of Car Parking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Suggested_Property__c.field-meta.xml
<CustomField>
    <fullName>Related_Suggested_Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Suggested Property</label>
    <referenceTo>Suggested_Property__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/Project_Add_On_Charges__c.object-meta.xml
<CustomObject>
    <label>Project Add On Charges</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Add On Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_Add_On_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Project_Add_On_Charges__c/recordTypes/Parking.recordType-meta.xml
<RecordType>
    <fullName>Parking</fullName>
    <active>true</active>
    <label>Parking</label>
</RecordType>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Flat_Type__c.field-meta.xml
<CustomField>
    <fullName>Flat_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COVERED STACK</fullName>
            </value>
            <value>
                <fullName>STACK</fullName>
            </value>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK G</fullName>
            </value>
            <value>
                <fullName>2.5 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
            <value>
                <fullName>PENTHOUSES</fullName>
            </value>
            <value>
                <fullName>ROW HOUSES</fullName>
            </value>
            <value>
                <fullName>VILLAS</fullName>
            </value>
            <value>
                <fullName>BUNGALOW</fullName>
            </value>
            <value>
                <fullName>SHOP WITH TERRACE</fullName>
            </value>
            <value>
                <fullName>SHOP WITHOUT TERRACE</fullName>
            </value>
            <value>
                <fullName>OFFICE WITH TERRACE</fullName>
            </value>
            <value>
                <fullName>OFFICE WITHOUT TERRACE</fullName>
            </value>
            <value>
                <fullName>REFUGEE</fullName>
            </value>
            <value>
                <fullName>STUDIO</fullName>
            </value>
            <value>
                <fullName>CAR PARKING</fullName>
            </value>
            <value>
                <fullName>BIKE PARKING</fullName>
            </value>
            <value>
                <fullName>BASEMENT PARKING</fullName>
                <isActive>false</isActive>
                <label>BASEMENT PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE OPEN PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE OPEN PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE PODIUM PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE PODIUM PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE STILT PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE STILT PARKING</label>
            </value>
            <value>
                <fullName>OPEN PARKING</fullName>
                <isActive>false</isActive>
                <label>OPEN PARKING</label>
            </value>
            <value>
                <fullName>PODIUM PARKING</fullName>
                <isActive>false</isActive>
                <label>PODIUM PARKING</label>
            </value>
            <value>
                <fullName>STILT PARKING</fullName>
                <isActive>false</isActive>
                <label>STILT PARKING</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/No_of_Car_Parking__c.field-meta.xml
<CustomField>
    <fullName>No_of_Car_Parking__c</fullName>
    <label>No of Parking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Property_Status__c.field-meta.xml
<CustomField>
    <fullName>Property_Status__c</fullName>
    <label>Property Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pre - Allotted</fullName>
            </value>
            <value>
                <fullName>Allotted</fullName>
            </value>
            <value>
                <fullName>Allotted In Progress</fullName>
            </value>
            <value>
                <fullName>Confirmed Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit No.</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Property_Add_On__c/Property_Add_On__c.object-meta.xml
<CustomObject>
    <label>Property Add On Charges</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties Add On</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property_Add_On__c/fields/Car_Parking__c.field-meta.xml
<CustomField>
    <fullName>Car_Parking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car Parking</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Properties Add On (Car Parking)</relationshipLabel>
    <relationshipName>Properties_Add_On1</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property_Add_On__c/fields/Project_Add_On__c.field-meta.xml
<CustomField>
    <fullName>Project_Add_On__c</fullName>
    <label>Project Add On</label>
    <referenceTo>Project_Add_On_Charges__c</referenceTo>
    <relationshipName>Properties_Add_On</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Property_Add_On__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipName>Properties_Add_On</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/Suggested_Property__c.object-meta.xml
<CustomObject>
    <label>Suggested Property</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Suggestion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suggested Property</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <formula>Unit__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Suggested Property</relationshipLabel>
    <relationshipName>Suggested_Property</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/classes/AssignCarParkonProperty.cls
public class AssignCarParkonProperty {
    public static void carPark(List<Booking__c> bookList,Map<Id,Booking__c> oldBookMap){
        system.debug('bookList----'+bookList);
        Set<Id> bookId = new Set<Id>();
        Set<Id> carParkId = new set<Id>();
        Set<Id> preAllotCarparkId= new Set<Id>();
        Id unitId;
        Id ProjectId;
        Decimal carParkCount = 0;
        Decimal carParkToAsign = 0;
        List<Property__c> carParkToUpdate = new List<Property__c>();
        List<Property__c> PreAllotCarParkToUpdate = new List<Property__c>();
        List<Project_Add_On_Charges__c> projAddOnAdd = new List<Project_Add_On_Charges__c>();
        List<Property_Add_On__c> propAddOnAdd = new List<Property_Add_On__c>();
        Id ProjAddOnRecordTypeId = Schema.SObjectType.Project_Add_On_Charges__c.getRecordTypeInfosByName().get('Parking').getRecordTypeId();
        
        if(!bookList.isEmpty()){
            for(Booking__c book:bookList){
                if((book.Cancellation_Approval_Status__c=='Approved') && (oldBookMap.get(book.Id).Cancellation_Approval_Status__c !=book.Cancellation_Approval_Status__c)){
                    bookId.add(book.Id);
                    ProjectId = book.Project_Name__c;
                    
                }
                system.debug('bookId----'+bookId);
                if(!bookId.isEmpty()){
                    List<Property__c> carParkList = [Select Id,Name,Property_Status__c From Property__c Where Booking__c In :bookId AND Property_Status__c = 'Allotted'];
                    List<Property__c> preAllotCarPark = [Select Id,Name From Property__c Where Booking__c In :bookId AND Property_Status__c = 'Pre - Allotted'];
                    system.debug('carParkList----'+carParkList);
                    system.debug('preAllotCarPark----'+preAllotCarPark);
                    if(!carParkList.isEmpty()){
                        for(Property__c carPark:carParkList){
                            carpark.Property_Status__c = 'Available';
                            carPark.Booking__c = null;
                            carParkToUpdate.add(carPark);
                            system.debug('carParkToUpdate----'+carParkToUpdate);
                        }
                        update carParkToUpdate;
                    }
                    
                    List<Booking__c> ListBooking = [Select Id,Name,Related_Suggested_property__r.unit__c,No_of_car_Parking__c From Booking__c WHere Id In :bookId];
                    system.debug('ListBooking----'+ListBooking);    
                    if(!ListBooking.isEmpty()){
                        for(Booking__c booking:ListBooking){
                            unitId = booking.Related_Suggested_Property__r.Unit__c;
                        }
                        system.debug('unitId----'+unitId);
                        List<Property__c> unitList = [Select Id,Name,No_of_car_Parking__c From Property__c Where Id=:unitId];
                        system.debug('unitList----'+unitList);
                        if(!unitList.isEmpty()){
                            for(Property__c unit:unitList){
                                carParkCount = unit.No_of_car_Parking__c;
                            }
                            system.debug('carParkCount----'+carParkCount);
                            if(carParkCount>preAllotCarPark.size()){
                                carParkToAsign = carParkCount-preAllotCarPark.size();
                                system.debug('carParkToAsign----'+carParkToAsign);
                                List<Property__c> AvailCarParkList = [Select Id,Name,Project__c,Property_Status__c From Property__c Where Property_Status__c='Available'  AND Flat_Type__c  IN ('CAR PARKING','BIKE PARKING') LIMIT :carParkToAsign.intValue()];
                                system.debug('AvailCarParkList----'+AvailCarParkList);
                                Project_Add_On_Charges__c projAddOn = new Project_Add_On_Charges__c();
                                projAddOn.Project__c = ProjectId;
                                projAddOn.Name = 'Project AddOn';
                                projAddOn.RecordTypeId = ProjAddOnRecordTypeId;
                                insert projAddOn;
                                //List<Project_Add_On_Charges__c> projAddOnList = [Select Id,Name From Project_Add_On_Charges__c Where Id IN =projAddOn.Id];
                                if(!AvailCarParkList.isEmpty()){
                                    for(Property__c AvailCarPark:AvailCarParkList){
                                        AvailCarPark.Property_Status__c = 'Pre - Allotted';
                                        Property_Add_On__c  propAddOn = new Property_Add_On__c();
                                        propAddOn.Car_Parking__c = AvailCarPark.Id;
                                        propAddOn.Project_Add_On__c = projAddOn.Id;
                                        propAddOn.Property__c = unitId;
                                        propAddOnAdd.add(propAddOn);
                                    }
                                    //insert projAddOnAdd;
                                    insert propAddOnAdd;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}