dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Amount__c</fullName>
    <formula>Agreement_Value__c -  Total_Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/First_Payment_Email_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Email_Reminder_Date__c</fullName>
    <formula>Due_Date__c+ 7</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Payment Email Reminder Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/forth_Payment_Email_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>forth_Payment_Email_Reminder_Date__c</fullName>
    <formula>Due_Date__c  +28</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>forth Payment Email Reminder Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Status__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Status__c</fullName>
    <label>Milestone Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Amount__c</fullName>
    <formula>Milestone_Amount1__c - Payment_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_GST__c.field-meta.xml
<CustomField>
    <fullName>Remaining_GST__c</fullName>
    <formula>GST_Amount1__c - GST_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Second_Payment_Email_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>Second_Payment_Email_Reminder_Date__c</fullName>
    <formula>Due_Date__c+ 14</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Second Payment Email Reminder Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Third_Payment_Email_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>Third_Payment_Email_Reminder_Date__c</fullName>
    <formula>Due_Date__c  + 21</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Third Payment Email Reminder Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/classes/EmailReminderBatch.cls
public class EmailReminderBatch implements Database.Batchable<sObject>,Database.AllowsCallouts {
 
   public EmailReminderBatch(){
   }
   
   public Database.QueryLocator start(Database.BatchableContext BC){
      list<Payment_Milestones__c >pmList =[SELECT Id,Name,booking__c,Milestone_Status__c,First_Payment_Email_Reminder_Date__c,
                                           forth_Payment_Email_Reminder_Date__c,Third_Payment_Email_Reminder_Date__c,
                                           Second_Payment_Email_Reminder_Date__c,Due_Date__c,Remaining_GST__c,
                                           Remaining_Amount__c  FROM Payment_Milestones__c 
                                           where ((First_Payment_Email_Reminder_Date__c=:Date.today() 
                                                   OR Third_Payment_Email_Reminder_Date__c=:Date.today() 
                                                   OR forth_Payment_Email_Reminder_Date__c=:Date.today() 
                                                   OR Second_Payment_Email_Reminder_Date__c=:Date.today()) 
                                                  AND Remaining_Amount__c > 0 and Milestone_Status__c ='Active')];
      system.debug('pmList=='+pmList );
      return Database.getQueryLocator([SELECT Id,Name,booking__c,Milestone_Status__c,First_Payment_Email_Reminder_Date__c,forth_Payment_Email_Reminder_Date__c,Third_Payment_Email_Reminder_Date__c,Second_Payment_Email_Reminder_Date__c,Due_Date__c,Remaining_GST__c,Remaining_Amount__c  FROM Payment_Milestones__c where ((First_Payment_Email_Reminder_Date__c=:Date.today() OR Third_Payment_Email_Reminder_Date__c=:Date.today() OR forth_Payment_Email_Reminder_Date__c=:Date.today() OR Second_Payment_Email_Reminder_Date__c=:Date.today()) AND Remaining_Amount__c > 0 and Milestone_Status__c ='Active')]);
   }
 
   public void execute(Database.BatchableContext BC, List<sObject> scope)
   {
      system.debug('scope=='+scope); 
      list<Payment_Milestones__c >pmList =  scope;
      map<id,id>  mapFirst = new  map<id,id>(); 
      map<id,id> mapSecond = new  map<id,id>(); 
      map<id,id>  mapthird = new  map<id,id>(); 
      map<id,id>  mapforth = new  map<id,id>(); 
      for(Payment_Milestones__c p:pmList ) {
          if(p.First_Payment_Email_Reminder_Date__c==Date.today())
          {
              mapFirst.put(p.booking__c,p.id);
          }
          else if(p.Second_Payment_Email_Reminder_Date__c==Date.today())
          {
              mapSecond.put(p.booking__c,p.id);
          }
          else if(p.Third_Payment_Email_Reminder_Date__c==Date.today())
          {
              mapthird.put(p.booking__c,p.id);
              system.debug(' mapthird=='+ mapthird);
          }
          else if(p.forth_Payment_Email_Reminder_Date__c==Date.today())
          {
              mapforth.put(p.booking__c,p.id);
          }
      }
      if(!mapFirst.isEmpty()) 
      {
           system.debug('mapFirst=='+mapFirst);
           SendEmailClass.SendEmailReminder(mapFirst, Label.First_Payment_Reminder_Notification);
      }
      if(!mapSecond.isEmpty()) 
      {
           system.debug('mapSecond=='+mapSecond);
           SendEmailClass.SendEmailReminder(mapSecond,Label.Second_Payment_Reminder_Notification);
      }
      if(!mapthird.isEmpty()) 
      {
          system.debug('mapthird=='+mapthird);
          SendEmailClass.SendEmailReminder(mapthird,Label.Final_Reminder);
      }
      if(!mapforth.isEmpty()) 
      {
           system.debug('mapforth=='+mapforth);
           SendEmailClass.SendEmailReminder(mapforth,Label.Termination_Note);
      }
      
   }  
   public void finish(Database.BatchableContext BC){
       system.debug('call finish method');
     //  SMSOnEmailReminderBatch.sendSMS();
   }
 
}