dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Brokerage_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage_Percentage__c</fullName>
    <label>Brokerage Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

dynamix/force-app/main/default/classes/ChannelPartnerBrokerageHandler.cls
public class ChannelPartnerBrokerageHandler {
public static void updateBookingBrokerage(Set<Id> bookingIds) {
        if (bookingIds.isEmpty()) return;

        Map<Id, Decimal> bookingToBrokerageSum = new Map<Id, Decimal>();
        
        for (AggregateResult ar : [
            SELECT Booking__c bId, SUM(Total_Brokerage__c) totalPct
            FROM Channel_Partner_Brokrage__c
            WHERE Booking__c IN :bookingIds
            GROUP BY Booking__c
        ]) {
            bookingToBrokerageSum.put((Id)ar.get('bId'), (Decimal)ar.get('totalPct'));
        }

        // Prepare Booking updates
        List<Booking__c> updates = new List<Booking__c>();
        for (Id bId : bookingIds) {
            Decimal sumPct = bookingToBrokerageSum.containsKey(bId) ? bookingToBrokerageSum.get(bId) : 0;
            system.debug('line sumPct ==>' + sumPct);
            updates.add(new Booking__c(
                Id = bId,
                Brokerage_Percentage__c = sumPct
            ));
        }

        if (!updates.isEmpty()) {
            system.debug('updates' + updates);
            update updates;
        }
    }
}