dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Credit_Note_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_Amount__c</fullName>
    <label>Credit Note Amount</label>
    <summarizedField>Credit_Note__c.Credit_Note_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Credit_Note__c.Credit_Note_Status__c</field>
        <operation>equals</operation>
        <value>Created</value>
    </summaryFilterItems>
    <summaryForeignKey>Credit_Note__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Description(Non-Critical)</label>
    <type>Checkbox</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Sap_Code__c.field-meta.xml
<CustomField>
    <fullName>Sap_Code__c</fullName>
    <label>Sap Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Credit_Note__c/Credit_Note__c.object-meta.xml
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Credit Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Credit_Note__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Credit Notes</relationshipLabel>
    <relationshipName>Credit_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Credit_Note__c/fields/Credit_Note_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_Amount__c</fullName>
    <label>Credit Note Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Credit_Note__c/fields/Credit_Note_Date__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_Date__c</fullName>
    <label>Credit Note Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Credit_Note__c/fields/Credit_Note_Status__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_Status__c</fullName>
    <label>Credit Note Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Credit_Note__c/fields/Sap_Code__c.field-meta.xml
<CustomField>
    <fullName>Sap_Code__c</fullName>
    <label>Credit Note Invoice Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/Data_Sync__c.object-meta.xml
<CustomObject>
    <label>Data_Sync</label>
    <nameField>
        <displayFormat>DS-{0000000}</displayFormat>
        <label>Data_Sync Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data_Syncs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>TextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response_Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Data_Sync__c/fields/Sync_Direction__c.field-meta.xml
<CustomField>
    <fullName>Sync_Direction__c</fullName>
    <label>Sync Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SFDC to SAP</fullName>
            </value>
            <value>
                <fullName>SAP to SFDC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/classes/CreditNoteRestAPI.cls
/*
* Author : Nachiketa Khera
* Created Date : 15th May 2024
* Description : Rest API to capture Credit Note Payment details from SAP and store the information at Booking.
* Last Modified Date : 17th May 2024
*/
@RestResource(urlMapping='/CreditNote/*')
global class CreditNoteRestAPI {
    @HttpPost
    global static void getCreditNoteDetails(){
        RestResponse res = RestContext.response;
        try{
            List<Credit_Note__c> creditNoteToUpsert = new List<Credit_Note__c>();
            List<JSONGenerator> jsonGeneratorList = new List<JSONGenerator>();
            Set<String> CodesOfBooking = new Set<String>();
            
            Map<String, Object> creditNote = (Map<String, Object>)JSON.deserializeUntyped(RestContext.request.requestBody.toString());
            Map<String, Object> innerBody = (Map<String, Object>)creditNote.get('ZSD028_SFDC_CREDIT_NOTE');
            Map<String, Object> internalMap = (Map<String, Object>)innerBody.get('CREDIT_NOTE');
            List<Object> itemList = (List<Object>)internalMap.get('item');
            System.debug('Payload--> '+itemList);
            
            if(itemList.size()>0){
                for(Object obj:itemList){
                    Map<String, Object> item = (Map<String, Object>)obj;
                    String creditNoteSapCode = String.valueOf(item.get('VBELN'));
                    String creditNoteDate = String.valueOf(item.get('FKDAT'));
                    String customerSapCode = String.valueOf(item.get('KUNAG'));
                    String bookingSapCode = String.valueOf(item.get('AUBEL'));
                    String description = String.valueOf(item.get('AUGRU'));
                    String creditNoteAmount = String.valueOf(item.get('NETWR'));
                    String creditNoteStatus = String.valueOf(item.get('FKSTO'));
                    
                    List<Booking__c> bookList = [Select Id,Sap_Code__c from Booking__c where Sap_Code__c =: bookingSapCode limit 1];
                    if(!bookList.isEmpty()){
                        List<Credit_Note__c> creditList = [Select Id,Sap_Code__c from Credit_Note__c where Sap_Code__c=:creditNoteSapCode limit 1];
                        Credit_Note__c creditRecord = new Credit_Note__c();
                        creditRecord.Booking__c = bookList[0].Id;
                        creditRecord.Credit_Note_Date__c = Date.valueOf(dateFormat(creditNoteDate));
                        creditRecord.Credit_Note_Amount__c = Decimal.valueOf(creditNoteAmount);
                        creditRecord.Credit_Note_Status__c = creditNoteStatus;
                        creditRecord.Description__c = description;
                        
                        if(creditList.isEmpty()){
                            creditRecord.Sap_Code__c = creditNoteSapCode;
                            creditNoteToUpsert.add(creditRecord);
                        }
                        else{
                            creditRecord.Id = creditList[0].Id;
                            creditRecord.Sap_Code__c = creditList[0].Sap_Code__c;
                            creditNoteToUpsert.add(creditRecord);
                        }
                    }
                    else{
                        CodesOfBooking.add(bookingSapCode);
                        system.debug('CodesOfBooking--> '+CodesOfBooking);
                    }
                }
            }
            system.debug('creditNoteToUpsert--> '+creditNoteToUpsert);
            JSONGenerator jsonGenerator1 = JSON.createGenerator(true);
            jsonGenerator1.writeStartObject();
            jsonGenerator1.writeFieldName('RESPONSE');
            jsonGenerator1.writeStartObject();
            jsonGenerator1.writeFieldName('item');
            jsonGenerator1.writeStartArray();
            if(!creditNoteToUpsert.isEmpty()){
                Database.UpsertResult[] upsertResults = Database.upsert(creditNoteToUpsert, false);
                for (Database.UpsertResult sr : upsertResults) {
                    Set<String> bookingCodes = new Set<String>();
                    if (sr.isSuccess()) {
                        Credit_Note__c upsertedCreditNote = [Select Id,Sap_Code__c from Credit_Note__c where Id=:sr.getId()];
                        jsonGenerator1.writeStartObject();
                        jsonGenerator1.writeStringField('VBELN',upsertedCreditNote.Sap_Code__c);
                        jsonGenerator1.writeStringField('STATUS','SUCCESS');
                        if(sr.isCreated()){
                            jsonGenerator1.writeStringField('MESSAGE','Credit Note Created Successfully');
                        }
                        else{
                            jsonGenerator1.writeStringField('MESSAGE','Credit Note Updated Successfully');
                        }
                        jsonGenerator1.writeEndObject();
                    }
                    else {
                        String errorCreditNoteSAPCode='';
                        if(!sr.isCreated()){
                            Credit_Note__c errorCreditNote = [Select Id,Sap_Code__c from Credit_Note__c where Id=:sr.getId()];
                            errorCreditNoteSAPCode=errorCreditNote.Sap_Code__c;
                        }
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            jsonGenerator1.writeStartObject();
                            if(!sr.isCreated()){ 
                            	jsonGenerator1.writeStringField('VBELN',errorCreditNoteSAPCode);
                            }
                            jsonGenerator1.writeStringField('STATUS','ERROR');
                            jsonGenerator1.writeStringField('MESSAGE',err.getMessage());
                            jsonGenerator1.writeEndObject();
                        }
                    }
                }
            }
            if(!CodesOfBooking.isEmpty()){
                system.debug('inside error');
                system.debug('bookingCodes--> '+CodesOfBooking);
                for(String codes:CodesOfBooking){
                    jsonGenerator1.writeStartObject();
                    jsonGenerator1.writeStringField('AUBEL',string.valueOf(codes));
                    jsonGenerator1.writeStringField('STATUS','ERROR');
                    jsonGenerator1.writeStringField('MESSAGE','This Booking Code '+codes+' does not exist');
                    jsonGenerator1.writeEndObject();
                }
            }
            jsonGenerator1.writeEndArray();
            jsonGenerator1.writeEndObject();
            jsonGenerator1.writeEndObject();
            jsonGeneratorList.add(jsonGenerator1);
            String jsonString = '';
            if(jsonGeneratorList.size()>0){
                for (JSONGenerator generator : jsonGeneratorList) {
                    jsonString += generator.getAsString();
                }
                system.debug('jsonString--> '+jsonString);
            }
            res.statusCode = 201;
            String  jsonResponse = jsonString;
            res.responseBody = blob.valueOf(jsonResponse);
            Data_Sync__c ds = new Data_Sync__c();
            ds.Event_Type__c = 'Credit Note';
            ds.Request_Body__c = RestContext.request.requestBody.toString();
            ds.Response_Body__c = jsonString;
            ds.Sync_Direction__c = 'SAP to SFDC';
            ds.Status__c = 'Success';
            insert ds;
        }
        catch(Exception e){
            System.debug('---Request----'+ String.valueOf(e.getLineNumber()));
            res.statusCode = 400;
            String  jsonResponse = '{"RESPONSE": {"STATUS": "' + 'Error' + '","MESSAGE":"'+'Exception occured, Credit Note not created :'+e+'\"}}';
            res.responseBody = blob.valueOf(jsonResponse);
            Data_Sync__c ds = new Data_Sync__c();
            ds.Event_Type__c = 'Credit Note';
            ds.Request_Body__c = RestContext.request.requestBody.toString();
            ds.Response_Body__c = jsonResponse;
            ds.Sync_Direction__c = 'SAP to SFDC';
            ds.Status__c = 'Error';
            insert ds;
            
            return;
        }
    }
    public static string dateFormat(string str){
        System.debug('Inside1---'+str);
        String dateFull  = String.valueOf(str);
        System.debug('Inside1str---'+str);
        String[] creditNoteDate = dateFull.split('\\.');
        System.debug('Inside1-demandDate--'+creditNoteDate);
        String dd = creditNoteDate[0]; 
        String mm = creditNoteDate[1];
        String yyyy = creditNoteDate[2];
        string formattedCreditNoteDate = yyyy+'-'+mm+'-'+dd;
        System.debug('---formattedCreditNoteDate------'+formattedCreditNoteDate);
        return formattedCreditNoteDate;
    }
}