dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <label>Agreement Value</label>
    <summarizedField>Price_Details__c.Amount_after_discount__c</summarizedField>
    <summaryFilterItems>
        <field>Price_Details__c.Charge_Group__c</field>
        <operation>contains</operation>
        <value>Agreement</value>
    </summaryFilterItems>
    <summaryForeignKey>Price_Details__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Cancellation_Reasons__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reasons__c</fullName>
    <label>Cancellation Reasons</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corona Job Loss</fullName>
            </value>
            <value>
                <fullName>Covid 19</fullName>
            </value>
            <value>
                <fullName>Data Entry Error</fullName>
            </value>
            <value>
                <fullName>Financial Loss</fullName>
            </value>
            <value>
                <fullName>Flat Upgrade</fullName>
            </value>
            <value>
                <fullName>Flat Upgrade Post Regiseration</fullName>
            </value>
            <value>
                <fullName>Flat Downgrade</fullName>
            </value>
            <value>
                <fullName>Loan Eligibility Issue</fullName>
            </value>
            <value>
                <fullName>Medical Emergency</fullName>
            </value>
            <value>
                <fullName>Project Location</fullName>
            </value>
            <value>
                <fullName>Personal Issue</fullName>
            </value>
            <value>
                <fullName>Purchased Property Elsewhere</fullName>
            </value>
            <value>
                <fullName>Ready Possession</fullName>
            </value>
            <value>
                <fullName>Bank Information Misguiding</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Job Transfer</fullName>
            </value>
            <value>
                <fullName>Flat Transfer Before Login</fullName>
            </value>
            <value>
                <fullName>Sale of Flat</fullName>
            </value>
            <value>
                <fullName>Dummy Entry</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Unit Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Cancellation_Request_Confirmation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Request_Confirmation_Date__c</fullName>
    <label>Cancellation Request Confirmation Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Cancellation_Sub_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Sub_Reason__c</fullName>
    <label>Cancellation Sub Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Job Loss</fullName>
            </value>
            <value>
                <fullName>Financial Loss</fullName>
            </value>
            <value>
                <fullName>Job Transfer</fullName>
            </value>
            <value>
                <fullName>COVID-19</fullName>
            </value>
            <value>
                <fullName>COVID Job Loss</fullName>
            </value>
            <value>
                <fullName>Non Payment</fullName>
            </value>
            <value>
                <fullName>Unit Transfer</fullName>
            </value>
            <value>
                <fullName>Job Less</fullName>
                <isActive>false</isActive>
                <label>Job Less</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Forfeiture__c.field-meta.xml
<CustomField>
    <fullName>Forfeiture__c</fullName>
    <label>Forfeiture %</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Forfeiture_Amount__c.field-meta.xml
<CustomField>
    <fullName>Forfeiture_Amount__c</fullName>
    <label>Forfeiture Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Forfeiture_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Forfeiture_Criteria__c</fullName>
    <label>Forfeiture Criteria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agreement Value</fullName>
            </value>
            <value>
                <fullName>Received Value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Non_Recoverable_GST_of_Invoice_Raised__c.field-meta.xml
<CustomField>
    <fullName>Non_Recoverable_GST_of_Invoice_Raised__c</fullName>
    <label>Non Recoverable GST of Invoice Raised</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Sent to Agent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Source_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Booking__c</fullName>
    <formula>TEXT( Related_Opportunity__r.Walk_in_Source__c )</formula>
    <label>Source of Booking</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Possession/Handover</fullName>
            </value>
            <value>
                <fullName>Snag/Desnag by Client</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancellation Initiated</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Pending</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Ready</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled -- Refund Done</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Handover</fullName>
                <isActive>false</isActive>
                <label>Handover</label>
            </value>
            <value>
                <fullName>In Process</fullName>
                <isActive>false</isActive>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Possession Letter</fullName>
                <isActive>false</isActive>
                <label>Possession Letter</label>
            </value>
            <value>
                <fullName>Registered</fullName>
                <isActive>false</isActive>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Sanction</fullName>
                <isActive>false</isActive>
                <label>Sanction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/TDS_Received__c.field-meta.xml
<CustomField>
    <fullName>TDS_Received__c</fullName>
    <label>TDS Received</label>
    <summarizedField>Payment__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Payment__c.Payment_Category__c</field>
        <operation>equals</operation>
        <value>TDS</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Payment__c.Status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Total_Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Received__c</fullName>
    <inlineHelpText>All Payment Received Against Milestone</inlineHelpText>
    <label>Total Amount Received</label>
    <summarizedField>Payment__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Payment__c.Payment_Status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Payment__c.Payment_Category__c</field>
        <operation>notEqual</operation>
        <value>Interest</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Payment__c.Payment_Type__c</field>
        <operation>notEqual</operation>
        <value>Credit Note</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Payment__c.Payment_Category__c</field>
        <operation>notEqual</operation>
        <value>Stamp Duty</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Payment__c.Payment_Category__c</field>
        <operation>notEqual</operation>
        <value>Registration</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower Name</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <formula>Related_Suggested_Property__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Number</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Co_Applicant__c/Co_Applicant__c.object-meta.xml
<CustomObject>
    <label>Co-Applicant</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Applicant</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Co_Applicant__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Co-Applicant</relationshipLabel>
    <relationshipName>Co_Applicant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/classes/BookingCancellationChecklist.cls
Public class BookingCancellationChecklist {
    
    Public Booking__c bookingRecord{get;set;}
    Public String recordId{get;set;}
    Public List<Co_Applicant__c> coApplicantList {get;set;}
    Public Co_Applicant__c coAppllicantRecord {get;set;}
    
    Public BookingCancellationChecklist(ApexPages.StandardController controller){     
        recordId = ApexPages.CurrentPage().getparameters().get('id');   
       // recordId='a0CBh000000Msg5MAC';     
        bookingRecord = [select Id,Tower_Name__c,Related_Opportunity__c,Tower_Name__r.Name,Project_Name__r.Name,Primary_Applicant__c,Primary_Applicant__r.FirstName,Primary_Applicant__r.LastName,
                         Agreement_Value__c,Unit_Number__c,Stage__c,Source_of_Booking__c,Registration_Status__c,Cancellation_Request_Confirmation_Date__c,
                         Cancellation_Reasons__c,Cancellation_Sub_Reason__c,Total_Amount_Received__c,TDS_Received__c,Non_Recoverable_GST_of_Invoice_Raised__c,
                         Forfeiture__c,Forfeiture_Criteria__c,Forfeiture_Amount__c,Brokerage_Amount_Paid2__c,Brokerage_Paid__c,Interest_Accrued_on_Amount_Due__c,
                         MVAT__c,Service_Tax__c,TDS__c,Payment_Received_GST__c,Miscellaneous_Expense__c,Total_Forfeiture_Amount__c,Total_Refund_Amount__c
                         FROM Booking__c WHERE Id =: recordId];
        //get Co-Applicant
        coApplicantList=[Select Id,Name,Account__c,Role__c,Booking__c,Account__r.Name From Co_Applicant__c Where Booking__c=:recordId AND Role__c=:'Co-Applicant' ];
        if(coApplicantList.size()>0){
            coAppllicantRecord=coApplicantList[0];
        }
        
    }
}