dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking1</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Possession/Handover</fullName>
            </value>
            <value>
                <fullName>Snag/Desnag by Client</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancellation Initiated</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Pending</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Ready</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled -- Refund Done</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Handover</fullName>
                <isActive>false</isActive>
                <label>Handover</label>
            </value>
            <value>
                <fullName>In Process</fullName>
                <isActive>false</isActive>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Possession Letter</fullName>
                <isActive>false</isActive>
                <label>Possession Letter</label>
            </value>
            <value>
                <fullName>Registered</fullName>
                <isActive>false</isActive>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Sanction</fullName>
                <isActive>false</isActive>
                <label>Sanction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Task_Target__c/Task_Target__c.object-meta.xml
<CustomObject>
    <label>Task Target</label>
    <nameField>
        <displayFormat>TT-{0000}</displayFormat>
        <label>Task Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Task_Target__c/fields/No_of_Follow_Ups__c.field-meta.xml
<CustomField>
    <fullName>No_of_Follow_Ups__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of Follow Ups</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Task_Target__c/fields/No_of_Walk_ins__c.field-meta.xml
<CustomField>
    <fullName>No_of_Walk_ins__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of Walk-ins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Task_Target__c/fields/Number_of_Connected_Call__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Connected_Call__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Connected Call</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Task_Target__c/fields/Number_of_Targets_Achievement__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Targets_Achievement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Targets Achievement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Task_Target__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Task Targets</relationshipLabel>
    <relationshipName>Task_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Task_Target__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Connected Call</fullName>
            </value>
            <value>
                <fullName>Walk-In</fullName>
            </value>
            <value>
                <fullName>Unique-Revisits</fullName>
            </value>
            <value>
                <fullName>Bookings</fullName>
            </value>
            <value>
                <fullName>Unique Inbound</fullName>
            </value>
            <value>
                <fullName>Unique Outbound</fullName>
            </value>
            <value>
                <fullName>Customer Walk In(CP)</fullName>
            </value>
            <value>
                <fullName>CP Visits</fullName>
                <isActive>false</isActive>
                <label>CP Visits</label>
            </value>
            <value>
                <fullName>Event</fullName>
                <isActive>false</isActive>
                <label>Event</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Task_Target__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Enquiry_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Task_Target__c/fields/X1st_Week__c.field-meta.xml
<CustomField>
    <fullName>X1st_Week__c</fullName>
    <defaultValue>0</defaultValue>
    <label>1st Week</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Task_Target__c/fields/X2nd_Week__c.field-meta.xml
<CustomField>
    <fullName>X2nd_Week__c</fullName>
    <label>2nd Week</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Task_Target__c/fields/X3rd_Week__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Week__c</fullName>
    <label>3rd Week</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Task_Target__c/fields/X4th_Week__c.field-meta.xml
<CustomField>
    <fullName>X4th_Week__c</fullName>
    <label>4th Week</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Task_Target__c/fields/X5th_Week__c.field-meta.xml
<CustomField>
    <fullName>X5th_Week__c</fullName>
    <label>5th Week</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Task_Target__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
            <value>
                <fullName>2051</fullName>
            </value>
            <value>
                <fullName>2052</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/classes/BookingTaskTargetCount.cls
public class BookingTaskTargetCount {
    public static void bookingTaskTarget(List<Booking__c> bookingList)
    {
        Set<Id> projectIdSet = New Set<Id>();
        Set<Id> salesIdSet = New Set<Id>();
        Set<Id> projectId = New Set<Id>();
        for(Booking__c thisBooking: bookingList)
        {
            ProjectIdSet.add(thisBooking.Project_Name__c);
            if(thisBooking.Sales_Manager__c != null)
            {
                salesIdSet.add(thisBooking.Sales_Manager__c);
            }
        }
        List<Task_Target__c> taskTargetList = [SELECT Id, Name, User__c, Month__c,Type__c,
                                               Year__c, Number_of_Targets_Achievement__c,
                                               X1st_Week__c, X2nd_Week__c, X3rd_Week__c,
                                               X4th_Week__c, X5th_Week__c, Project__c,
                                               Number_of_Connected_Call__c, No_of_Walk_ins__c, No_of_Follow_Ups__c
                                               FROM Task_Target__c
                                               WHERE User__c IN :salesIdSet  AND Year__c = :String.valueof(System.today().year()) 
                                               AND Month__c =: System.now().format('MMMMM')
                                               AND Project__c IN: ProjectIdSet AND Type__c =: 'Bookings'];
        Map<String, Task_Target__c> updateTaskTarget = New Map<String, Task_Target__c>();
        
        Map<String, Task_Target__c> mapOfUserToGetTaskTargetId = New Map<String, Task_Target__c>();
        Map<String, Integer> mapUserForBooking = New Map<String, Integer>();
        for(Task_Target__c taskTarget : taskTargetList)
        {
            
            String Key = taskTarget.Month__c+'-'+taskTarget.Year__c+'-'+String.valueOf(taskTarget.Project__c)+'-'+String.valueOf(taskTarget.User__c);
            mapOfUserToGetTaskTargetId.put(Key,taskTarget);
            system.debug('Task Target---');
            System.debug('Key' + Key);
            if( taskTarget.Type__c == 'Bookings'){
                if(taskTarget.Number_of_Targets_Achievement__c == null)
                {
                    mapUserForBooking.put(Key,0);
                }
                else
                {
                    mapUserForBooking.put(Key,Integer.valueof(taskTarget.Number_of_Targets_Achievement__c));
                }
            }
        }
        for(Booking__c thisBooking: bookingList)
        {
            String Key = thisBooking.CreatedDate.format('MMMMM')+'-'+thisBooking.CreatedDate.year()+'-'+String.valueOf(thisBooking.Project_Name__c)+'-'+String.valueOf(thisBooking.Sales_Manager__c);
            
            if(mapOfUserToGetTaskTargetId.containsKey(Key))
            {
                Task_Target__c taskTarget = New Task_Target__c();
                taskTarget.id = mapOfUserToGetTaskTargetId.get(Key).id;
                mapUserForBooking.put(Key, mapUserForBooking.get(Key)+1);
                taskTarget.Number_of_Targets_Achievement__c = mapUserForBooking.get(Key);
                updateTaskTarget.put(taskTarget.id,taskTarget);
                
            }
        }
        if(!updateTaskTarget.values().IsEmpty())
        {
            update updateTaskTarget.values();
        }
    }
    public static void bookingCancellationTaskTarget(List<Booking__c> bookingList, Map<Id,Booking__c> mapOfBooking)
    {
        Set<Id> projectIdSet = New Set<Id>();
        Set<Id> salesIdSet = New Set<Id>();
        List<Booking__c> cancellationBookingList = New List<Booking__c>();
        for(Booking__c thisBooking: bookingList)
        {
            if((thisBooking.Stage__c == 'Terminated' ||  thisBooking.Stage__c =='Cancellation Initiated' ||
                thisBooking.Stage__c == 'Booking Cancelled – Refund Pending' ||  thisBooking.Stage__c =='Booking Cancelled – Refund Ready')
               && thisBooking.Stage__c != mapOfBooking.get(thisBooking.id).Stage__c )
            {
                if(thisBooking.Sales_Manager__c != null)
                {
                    salesIdSet.add(thisBooking.Sales_Manager__c);
                }
                if(thisBooking.Project_Name__c != null)
                {
                    ProjectIdSet.add(thisBooking.Project_Name__c);
                }
                
                cancellationBookingList.add(thisBooking);
                
            }
        }
        if(!cancellationBookingList.isEmpty()){
            List<Task_Target__c> taskTargetList = [SELECT Id, Name, User__c, Month__c,Type__c,
                                                   Year__c, Number_of_Targets_Achievement__c,
                                                   X1st_Week__c, X2nd_Week__c, X3rd_Week__c,
                                                   X4th_Week__c, X5th_Week__c, Project__c,
                                                   Number_of_Connected_Call__c, No_of_Walk_ins__c, No_of_Follow_Ups__c
                                                   FROM Task_Target__c
                                                   WHERE User__c IN :salesIdSet  AND Year__c = :String.valueof(System.today().year()) 
                                                   AND Month__c =: System.now().format('MMMMM')
                                                   AND Project__c IN: ProjectIdSet AND Type__c =: 'Bookings'];
            Map<String, Task_Target__c> updateTaskTarget = New Map<String, Task_Target__c>();
            
            Map<String, Task_Target__c> mapOfUserToGetTaskTargetId = New Map<String, Task_Target__c>();
            Map<String, Integer> mapUserForBooking = New Map<String, Integer>();
            for(Task_Target__c taskTarget : taskTargetList)
            {
                
                String Key = taskTarget.Month__c+'-'+taskTarget.Year__c+'-'+String.valueOf(taskTarget.Project__c)+'-'+String.valueOf(taskTarget.User__c);
                mapOfUserToGetTaskTargetId.put(Key,taskTarget);
                system.debug('Task Target---');
                System.debug('Key' + Key);
                if( taskTarget.Type__c == 'Bookings'){
                    if(taskTarget.Number_of_Targets_Achievement__c == null)
                    {
                        mapUserForBooking.put(Key,0);
                    }
                    else
                    {
                        mapUserForBooking.put(Key,Integer.valueof(taskTarget.Number_of_Targets_Achievement__c));
                    }
                }
            }
            for(Booking__c thisBooking: cancellationBookingList)
            {
                String Key = thisBooking.CreatedDate.format('MMMMM')+'-'+thisBooking.CreatedDate.year()+'-'+String.valueOf(thisBooking.Project_Name__c)+'-'+String.valueOf(thisBooking.Sales_Manager__c);
                
                if(mapOfUserToGetTaskTargetId.containsKey(Key))
                {
                    Task_Target__c taskTarget = New Task_Target__c();
                    taskTarget.id = mapOfUserToGetTaskTargetId.get(Key).id;
                    mapUserForBooking.put(Key, mapUserForBooking.get(Key)-1);
                    taskTarget.Number_of_Targets_Achievement__c = mapUserForBooking.get(Key);
                    updateTaskTarget.put(taskTarget.id,taskTarget);
                    
                }
            }
            if(!updateTaskTarget.values().IsEmpty())
            {
                update updateTaskTarget.values();
            }
        }
    }
    
}