dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_age__c.field-meta.xml
<CustomField>
    <fullName>Milestone_age__c</fullName>
    <label>Milestone %</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Amount1__c</fullName>
    <label>Milestone Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <label>Sequence No</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Price_Details__c/Price_Details__c.object-meta.xml
<CustomObject>
    <label>Price Details</label>
    <nameField>
        <label>Price Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Price_Details__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Price Details</relationshipLabel>
    <relationshipName>Price_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/classes/UpdateDiscountforPriceDetail.cls
public with sharing class UpdateDiscountforPriceDetail{
    
    @InvocableMethod(label='Update Dicount Price Detail')
    public static void execute( List<Requests> requestLst){

        Decimal newAgreementValue = requestLst[0].newAgreementValue;
        Decimal newGSTValue = requestLst[0].newGSTValue;
        String bookingId= requestLst[0].bookingId;
        String[] DeleteListofPaymentMilestone;
        
        if(requestLst[0].DeleteIdsOfPM != null)
        {
           // paymentMilestoneIdforDelete =+ requestLst[0].DeleteIdsOfPM;
            DeleteListofPaymentMilestone = requestLst[0].DeleteIdsOfPM;
        }
        
        List<Price_Details__c> priceDetails = (List<Price_Details__c>)JSON.deserialize(requestLst[0].priceDetails, List<Price_Details__c>.class);

        update priceDetails;

        List<Payment_Milestones__c> paymentMilestones = (List<Payment_Milestones__c>)JSON.deserialize(requestLst[0].paymentMilestones, List<Payment_Milestones__c>.class);

        for(Payment_Milestones__c ppm : paymentMilestones){
            
            ppm.Milestone_age__c = (ppm.Milestone_Amount1__c/newAgreementValue)*100;
            
            if(ppm.id == null)
            {
             ppm.Booking__c = bookingId;
            }
            ppm.Name = ppm.Name;
            ppm.Sequence_No__c = ppm.Sequence_No__c;
            
           
        }

        upsert paymentMilestones;
        
          // For Payment Milestones Delete
       List<Payment_Milestones__c> DeletePaymentMilestoneLst = new List<Payment_Milestones__c>();
       DeletePaymentMilestoneLst = [select id from Payment_Milestones__c where Id IN : DeleteListofPaymentMilestone];
       system.debug('==> var id ' + DeletePaymentMilestoneLst);
       if(DeletePaymentMilestoneLst.size() > 0)
       {
           delete DeletePaymentMilestoneLst;
       }
    }

    public class Requests {
        
        @InvocableVariable(label='Price Details' required=true)
        public String priceDetails;
        
        @InvocableVariable(label='Payment Milestones' required=true)
        public String paymentMilestones;

        @InvocableVariable(label='New Agreement Value' required=true)
        public Decimal newAgreementValue;
        
        @InvocableVariable(label='New GST Value' required=true)
        public Decimal newGSTValue;
        
        @InvocableVariable(label='DeleteIdsOfPM' required=true)
        public String[] DeleteIdsOfPM;
        
        @InvocableVariable(label='Booking Id' required=true)
        public String bookingId;
        
        
    }
}