dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Cheque_Bounced_Charges__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Bounced_Charges__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cheque Bounced Charges(Including GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Amount__c</fullName>
    <formula>Agreement_Value__c -  Total_Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>Pay-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment_Category__c.field-meta.xml
<CustomField>
    <fullName>Payment_Category__c</fullName>
    <label>Payment Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unit Cost</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>GST</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Refundable Interior Deposit</fullName>
            </value>
            <value>
                <fullName>Temporary Electricity Charges</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Security Deposits</fullName>
            </value>
            <value>
                <fullName>Possession/Handover(Other) Charge</fullName>
            </value>
            <value>
                <fullName>Possession/Handover(Other) Charge GST</fullName>
            </value>
            <value>
                <fullName>Security and Share Money</fullName>
            </value>
            <value>
                <fullName>Security and Share Money GST</fullName>
            </value>
            <value>
                <fullName>Transfer Charge</fullName>
            </value>
            <value>
                <fullName>Brokerage Charges</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>GST Avanya Tower A</fullName>
            </value>
            <value>
                <fullName>OCR</fullName>
                <isActive>false</isActive>
                <label>OCR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Bounced</fullName>
                <isActive>false</isActive>
                <label>Bounced</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Cleared</fullName>
                <isActive>false</isActive>
                <label>Cleared</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
            <value>
                <fullName>Wrong Entry</fullName>
                <isActive>false</isActive>
                <label>Wrong Entry</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Line__c/Payment_Line__c.object-meta.xml
<CustomObject>
    <label>Payment Line</label>
    <nameField>
        <displayFormat>PL-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Line__c/fields/Adjusted_against__c.field-meta.xml
<CustomField>
    <fullName>Adjusted_against__c</fullName>
    <label>Adjusted against</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Line__c/fields/Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Amount__c</fullName>
    <label>Credit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Line__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <referenceTo>Payment_Milestones__c</referenceTo>
    <relationshipLabel>Payment Line</relationshipLabel>
    <relationshipName>Payment_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Line__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment Line</relationshipLabel>
    <relationshipName>Payment_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Line__c/fields/Payment_Category__c.field-meta.xml
<CustomField>
    <fullName>Payment_Category__c</fullName>
    <label>Payment Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Category</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Line__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Interest_on_GST__c.field-meta.xml
<CustomField>
    <fullName>Interest_on_GST__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest on GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Interest_on_milestone_amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_on_milestone_amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest on Milestone Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Status__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Status__c</fullName>
    <label>Milestone Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Amount__c</fullName>
    <formula>Milestone_Amount1__c - Payment_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_GST1__c.field-meta.xml
<CustomField>
    <fullName>Remaining_GST1__c</fullName>
    <label>Remaining GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_GST__c.field-meta.xml
<CustomField>
    <fullName>Remaining_GST__c</fullName>
    <formula>GST_Amount1__c - GST_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_Milestone_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Milestone_Amount__c</fullName>
    <label>Remaining Milestone Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Unit_Cost__c</fullName>
    <label>Remaining Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <label>Sequence No</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <formula>Milestone_Amount1__c  -  TDS_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/globalValueSets/Payment_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unit Cost</fullName>
        <default>true</default>
        <label>Unit Cost</label>
    </customValue>
    <customValue>
        <fullName>Stamp Duty</fullName>
    </customValue>
    <customValue>
        <fullName>GST</fullName>
    </customValue>
    <customValue>
        <fullName>TDS</fullName>
    </customValue>
    <customValue>
        <fullName>Parking</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Interest</fullName>
    </customValue>
    <customValue>
        <fullName>Refundable Interior Deposit</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Electricity Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Possession/Handover(Other) Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Possession/Handover(Other) Charge GST</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Security and Share Money</fullName>
    </customValue>
    <customValue>
        <fullName>Security and Share Money GST</fullName>
    </customValue>
    <masterLabel>Payment Category</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/classes/CreatePaymentLineItemForMilestone.cls
public with sharing class CreatePaymentLineItemForMilestone {
    @InvocableMethod(label='Create Payment Line Item For Milestone')
    public static void execute( List<Request> requestLst){
        for(request req :requestLst){
            String paymentId = req.paymentId;
            String bookingId = req.bookingId;
            String category = req.category;
            set<Payment_Milestones__c> paymentMilestoneIdSet = new set<Payment_Milestones__c>();
            List<Payment_Milestones__c> ListToUpdatePM_01 = new List<Payment_Milestones__c>();
            List<Payment_Milestones__c> ListToUpdatePM_02 = new List<Payment_Milestones__c>();
            List<Payment_Milestones__c> ListToUpdatePM_03 = new List<Payment_Milestones__c>();
            List<Payment_Milestones__c> ListToUpdatePM_04 = new List<Payment_Milestones__c>();
            List<Payment_Line__c> creditPayment = new List<Payment_Line__c>();
            List<Payment_Line__c> paymentLinesToInsert = new List<Payment_Line__c>();
            Decimal Balance = 0;
            Decimal UnitCostBalance =0;
            Payment__c payment =[SELECT Id, Amount__c, Payment_Category__c, Payment_Status__c FROM Payment__c WHERE Id =: paymentId];
            List<Payment_Milestones__c> paymentMileStoneList = [SELECT Id,name, Remaining_Amount__c, Remaining_GST__c,Remaining_Milestone_Amount__c,Interest_on_milestone_amount__c
                                                                ,Remaining_GST1__c,Interest_on_GST__c,Milestone_Status__c,Unit_Cost__c,Remaining_Unit_Cost__c
                                                                FROM Payment_Milestones__c 
                                                                WHERE Booking__c =: bookingId AND Name!=:System.Label.OtherChargesMilestone ORDER BY Milestone_Status__c Asc,Sequence_No__c asc];
            for(Payment_Milestones__c objPm : paymentMileStoneList){
                if(objPm.Milestone_Status__c == 'Active'){
                    if(objPm.Remaining_Milestone_Amount__c != null && objPm.Remaining_Milestone_Amount__c > 0)
                    {
                         Balance = Balance + objPm.Remaining_Milestone_Amount__c; 
                    }
                    if(objPm.Remaining_Unit_Cost__c != null && objPm.Remaining_Unit_Cost__c > 0)
                    {
                         UnitCostBalance = UnitCostBalance + objPm.Remaining_Unit_Cost__c;
                    }
                   
                }
            }
            Booking__c objBooking = [Select Id, Name,Cheque_Bounced_Charges__c From Booking__c where Id =: bookingId];
            List<Booking__c> ListToUpdateBooking = new List<Booking__c>();
            Decimal remaining_amount;
            remaining_amount = payment.Amount__c;
            if(paymentMileStoneList!=null && paymentMileStoneList.size()>0){
                if(payment.Payment_Category__c == 'Unit Cost'){
                    for(Payment_Milestones__c objPm : paymentMileStoneList){
                        if(objPm.Milestone_Status__c == 'Active' && objPm.Remaining_Milestone_Amount__c > 0){
                            Payment_Line__c payLine = new Payment_Line__c();
                            payLine.Credit_Amount__c = payment.Amount__c;
                            payLine.Milestone__c = objPm.Id;
                            payLine.Payment__c = payment.Id;
                            payLine.Adjusted_against__c= payment.Payment_Category__c;
                            payLine.Payment_Category__c = payment.Payment_Category__c;
                            payLine.Balance__c = Balance;
                            creditPayment.add(payLine);
                            break;
                        }
                    }
                    for(Payment_Milestones__c paymentMilestone : paymentMileStoneList){
                        system.debug('payment.Payment_Category__c=='+payment.Payment_Category__c);
                        if(objBooking.Cheque_Bounced_Charges__c > 0){
                            if(objBooking.Cheque_Bounced_Charges__c >= remaining_amount){
                                Balance = Balance - remaining_amount;
                                Payment_Line__c paymentLine = new Payment_Line__c();
                                paymentLine.Amount__c = remaining_amount;
                                paymentLine.Milestone__c = paymentMilestone.Id;
                                paymentLine.Payment__c = payment.Id;
                                paymentLine.Adjusted_against__c = 'Cheque Bounce Charges';
                                paymentLine.Balance__c = Balance;
                                paymentLinesToInsert.add(paymentLine);
                                objBooking.Cheque_Bounced_Charges__c = objBooking.Cheque_Bounced_Charges__c - remaining_amount;
                                break;
                            }
                            else{
                                remaining_amount = remaining_amount - objBooking.Cheque_Bounced_Charges__c;
                                Balance = Balance - objBooking.Cheque_Bounced_Charges__c;
                                Payment_Line__c paymentLine = new Payment_Line__c();
                                paymentLine.Amount__c = objBooking.Cheque_Bounced_Charges__c;
                                paymentLine.Milestone__c = paymentMilestone.Id;
                                paymentLine.Payment__c = payment.Id;
                                paymentLine.Adjusted_against__c = 'Cheque Bounce Charges';
                                paymentLine.Balance__c = Balance;
                                paymentLinesToInsert.add(paymentLine);
                                objBooking.Cheque_Bounced_Charges__c = 0;
    
                                if(remaining_amount > 0){
                                    if( paymentMilestone.Interest_on_milestone_amount__c >= remaining_amount ){
                                        Balance = Balance - remaining_amount;
                                        Payment_Line__c paymentLine4 = new Payment_Line__c();
                                        paymentLine4.Amount__c = remaining_amount;
                                        paymentLine4.Milestone__c = paymentMilestone.Id;
                                        paymentLine4.Payment__c = payment.Id;
                                        paymentLine4.Adjusted_against__c = 'Interest on due Milestone Amount';
                                        paymentLine4.Balance__c = Balance;
                                        paymentLinesToInsert.add(paymentLine4);
                                        paymentMilestone.Interest_on_milestone_amount__c = paymentMilestone.Interest_on_milestone_amount__c - remaining_amount;
                                        ListToUpdatePM_03.add(paymentMilestone);
                                        break;
                                    }
                                    else{
                                        remaining_amount = remaining_amount - paymentMilestone.Interest_on_milestone_amount__c;
                                        Balance = Balance - paymentMilestone.Interest_on_milestone_amount__c;
                                        Payment_Line__c paymentLine4 = new Payment_Line__c();
                                        paymentLine4.Amount__c = paymentMilestone.Interest_on_milestone_amount__c;
                                        paymentLine4.Milestone__c = paymentMilestone.Id;
                                        paymentLine4.Payment__c = payment.Id;
                                        paymentLine4.Adjusted_against__c = 'Interest on due Milestone Amount';
                                        paymentLine4.Balance__c = Balance;
                                        paymentLinesToInsert.add(paymentLine4);
                                        paymentMilestone.Interest_on_milestone_amount__c = 0;
                                        ListToUpdatePM_03.add(paymentMilestone);
                                        if(remaining_amount > 0){
                                            if( paymentMilestone.Remaining_Milestone_Amount__c >= remaining_amount ){
                                                Balance = Balance - remaining_amount;
                                                Payment_Line__c paymentLine5 = new Payment_Line__c();
                                                paymentLine5.Amount__c = remaining_amount;
                                                paymentLine5.Milestone__c = paymentMilestone.Id;
                                                paymentLine5.Payment__c = payment.Id;
                                                paymentLine5.Adjusted_against__c = 'Milestone Amount';
                                                paymentLine5.Balance__c = Balance;
                                                paymentLinesToInsert.add(paymentLine5);
                                                paymentMilestone.Remaining_Milestone_Amount__c = paymentMilestone.Remaining_Milestone_Amount__c - remaining_amount;
                                                ListToUpdatePM_04.add(paymentMilestone);
                                                break;
                                            }
                                            else{
                                                remaining_amount = remaining_amount - paymentMilestone.Remaining_Milestone_Amount__c;
                                                Balance = Balance - paymentMilestone.Remaining_Milestone_Amount__c;
                                                Payment_Line__c paymentLine5 = new Payment_Line__c();
                                                paymentLine5.Amount__c = paymentMilestone.Remaining_Milestone_Amount__c;
                                                paymentLine5.Milestone__c = paymentMilestone.Id;
                                                paymentLine5.Payment__c = payment.Id;
                                                paymentLine5.Adjusted_against__c = 'Milestone Amount';
                                                paymentLine5.Balance__c = Balance;
                                                paymentLinesToInsert.add(paymentLine5);
                                                paymentMilestone.Remaining_Milestone_Amount__c = 0;
                                                ListToUpdatePM_04.add(paymentMilestone);
                                            }
                                        }else{
                                            break;
                                        }
                                    }
                                }else{
                                    break;
                                }
                            }
                        }/*else if(paymentMilestone.Interest_on_milestone_amount__c != null && paymentMilestone.Interest_on_milestone_amount__c > 0){
                            if( paymentMilestone.Interest_on_milestone_amount__c >= remaining_amount ){
                                Balance = Balance - remaining_amount;
                                Payment_Line__c paymentLine4 = new Payment_Line__c();
                                paymentLine4.Amount__c = remaining_amount;
                                paymentLine4.Milestone__c = paymentMilestone.Id;
                                paymentLine4.Payment__c = payment.Id;
                                paymentLine4.Adjusted_against__c = 'Interest on due Milestone Amount';
                                paymentLine4.Balance__c = Balance;
                                paymentLinesToInsert.add(paymentLine4);
                                paymentMilestone.Interest_on_milestone_amount__c = paymentMilestone.Interest_on_milestone_amount__c - remaining_amount;
                                ListToUpdatePM_01.add(paymentMilestone);
                                break;
                            }
                            else{
                                remaining_amount = remaining_amount - paymentMilestone.Interest_on_milestone_amount__c;
                                Balance = Balance - paymentMilestone.Interest_on_milestone_amount__c;
                                Payment_Line__c paymentLine4 = new Payment_Line__c();
                                paymentLine4.Amount__c = paymentMilestone.Interest_on_milestone_amount__c;
                                paymentLine4.Milestone__c = paymentMilestone.Id;
                                paymentLine4.Payment__c = payment.Id;
                                paymentLine4.Adjusted_against__c = 'Interest on due Milestone Amount';
                                paymentLine4.Balance__c = Balance;
                                paymentLinesToInsert.add(paymentLine4);
                                paymentMilestone.Interest_on_milestone_amount__c = 0;
                                ListToUpdatePM_01.add(paymentMilestone);
                                if(remaining_amount > 0){
                                    if( paymentMilestone.Remaining_Milestone_Amount__c >= remaining_amount ){
                                        Balance = Balance - remaining_amount;
                                        Payment_Line__c paymentLine5 = new Payment_Line__c();
                                        paymentLine5.Amount__c = remaining_amount;
                                        paymentLine5.Milestone__c = paymentMilestone.Id;
                                        paymentLine5.Payment__c = payment.Id;
                                        paymentLine5.Adjusted_against__c = 'Milestone Amount';
                                        paymentLine5.Balance__c = Balance;
                                        paymentLinesToInsert.add(paymentLine5);
                                        paymentMilestone.Remaining_Milestone_Amount__c = paymentMilestone.Remaining_Milestone_Amount__c - remaining_amount;
                                        ListToUpdatePM_02.add(paymentMilestone);
                                        break;
                                    }
                                    else{
                                        remaining_amount = remaining_amount - paymentMilestone.Remaining_Milestone_Amount__c;
                                        Balance = Balance - paymentMilestone.Remaining_Milestone_Amount__c;
                                        Payment_Line__c paymentLine5 = new Payment_Line__c();
                                        paymentLine5.Amount__c = paymentMilestone.Remaining_Milestone_Amount__c;
                                        paymentLine5.Milestone__c = paymentMilestone.Id;
                                        paymentLine5.Payment__c = payment.Id;
                                        paymentLine5.Adjusted_against__c = 'Milestone Amount';
                                        paymentLine5.Balance__c = Balance;
                                        paymentLinesToInsert.add(paymentLine5);
                                        paymentMilestone.Remaining_Milestone_Amount__c = 0;
                                        ListToUpdatePM_02.add(paymentMilestone); 
                                    }
                                }else{
                                    break;
                                }
                            }
                        }*/else if(paymentMilestone.Remaining_Unit_Cost__c != null && paymentMilestone.Remaining_Unit_Cost__c > 0){  
                            if( paymentMilestone.Remaining_Unit_Cost__c >= remaining_amount ){
                                system.debug('1--'+paymentMilestone.Unit_Cost__c);
                                system.debug('3--'+Balance);
                                Balance = Balance - remaining_amount;
                                system.debug('2--'+Balance);
                                Payment_Line__c paymentLine5 = new Payment_Line__c();
                                paymentLine5.Amount__c = remaining_amount;
                                paymentLine5.Milestone__c = paymentMilestone.Id;
                                paymentLine5.Payment__c = payment.Id;
                                paymentLine5.Adjusted_against__c = 'Milestone Amount';
                                paymentLine5.Payment_Category__c = payment.Payment_Category__c;
                                paymentLine5.Payment_Status__c = payment.Payment_Status__c;
                                paymentLine5.Balance__c = Balance;
                                paymentLinesToInsert.add(paymentLine5);
                                paymentMilestone.Remaining_Milestone_Amount__c = paymentMilestone.Remaining_Milestone_Amount__c - remaining_amount;
                                paymentMilestone.Remaining_Unit_Cost__c = paymentMilestone.Remaining_Unit_Cost__c - remaining_amount;
                                ListToUpdatePM_01.add(paymentMilestone);
                                break;
                            }
                            else{
                                remaining_amount = remaining_amount - paymentMilestone.Remaining_Unit_Cost__c;
                                Balance = Balance - paymentMilestone.Remaining_Milestone_Amount__c;
                                Payment_Line__c paymentLine5 = new Payment_Line__c();
                                paymentLine5.Amount__c = paymentMilestone.Remaining_Unit_Cost__c;
                                paymentLine5.Milestone__c = paymentMilestone.Id;
                                paymentLine5.Payment__c = payment.Id;
                                paymentLine5.Adjusted_against__c = 'Milestone Amount';
                                paymentLine5.Payment_Category__c = payment.Payment_Category__c;
                                paymentLine5.Payment_Status__c = payment.Payment_Status__c;
                                paymentLine5.Balance__c = Balance;
                                paymentLinesToInsert.add(paymentLine5);
                                system.debug('paymentLine5--'+paymentLine5);
                                paymentMilestone.Remaining_Milestone_Amount__c = paymentMilestone.Remaining_Milestone_Amount__c - paymentMilestone.Remaining_Unit_Cost__c;
                                paymentMilestone.Remaining_Unit_Cost__c = 0;
                                ListToUpdatePM_01.add(paymentMilestone);
                            }
                        } 
                    }
                }
                else{
                    /*for(Payment_Milestones__c objPm : paymentMileStoneList){
                        if(objPm.Milestone_Status__c == 'Active'){
                            Payment_Line__c payLine = new Payment_Line__c();
                            payLine.Payment_Category__c = category;
                            payLine.Credit_Amount__c = payment.Amount__c;
                            payLine.Milestone__c = objPm.Id;
                            payLine.Payment__c = payment.Id;
                            payLine.Adjusted_against__c= payment.Payment_Category__c;
                            payLine.Balance__c = Balance;
                            creditPayment.add(payLine);
                            break;
                        }
                    }*/
                }
            }
            if(!creditPayment.isEmpty()){
                insert creditPayment;
            }
            if(!paymentLinesToInsert.isEmpty()){
                system.debug('paymentLinesToInsert.>> '+paymentLinesToInsert.size());
                insert paymentLinesToInsert;
            }
            if(!ListToUpdatePM_01.isEmpty()){
                update ListToUpdatePM_01;
            }
            if(!ListToUpdatePM_02.isEmpty()){
                update ListToUpdatePM_02;
            }
            if(!ListToUpdatePM_03.isEmpty()){
                update ListToUpdatePM_03;
            }
            if(!ListToUpdatePM_04.isEmpty()){
                update ListToUpdatePM_04;
            }
            update objBooking;
        }
    }
    public class Request {
        @InvocableVariable(label='Payment Id' required=true)
        public String paymentId;
        @InvocableVariable(label='Booking Id' required=true)
        public String bookingId;
        @InvocableVariable(label='Category' required=true)
        public String category;
    }
}