dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Total_interest_amount__c.field-meta.xml
<CustomField>
    <fullName>Total_interest_amount__c</fullName>
    <inlineHelpText>Interest Amount without GST</inlineHelpText>
    <label>Total Interest amount</label>
    <summarizedField>Payment_Milestones__c.Interest_Amount__c</summarizedField>
    <summaryForeignKey>Payment_Milestones__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/GST_Amount1__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount1__c</fullName>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount__c</fullName>
    <label>Interest Amount</label>
    <summarizedField>Interest_Charged__c.Interest_Amount__c</summarizedField>
    <summaryForeignKey>Interest_Charged__c.Milestone__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Activation_Date__c</fullName>
    <label>Milestone Activation Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_age__c.field-meta.xml
<CustomField>
    <fullName>Milestone_age__c</fullName>
    <label>Milestone %</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Amount1__c</fullName>
    <label>Milestone Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Status__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Status__c</fullName>
    <label>Milestone Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Payment_Received__c.field-meta.xml
<CustomField>
    <fullName>Payment_Received__c</fullName>
    <label>Payment Received</label>
    <summarizedField>Payment_Line__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Payment_Line__c.Payment_Category__c</field>
        <operation>equals</operation>
        <value>Unit Cost, Possession/Handover(Other) Charge, Transfer Charge, Security and Share Money</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Payment_Line__c.Payment_Status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment_Line__c.Milestone__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Project_Progress__c.field-meta.xml
<CustomField>
    <fullName>Project_Progress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Progress</label>
    <referenceTo>Project_Progress__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <label>Sequence No</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Total_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount__c</fullName>
    <formula>Interest_Amount__c - Interest_Wave_Off_Amount__c-Interest_Payment_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Project_Progress__c/Project_Progress__c.object-meta.xml
<CustomObject>
    <label>Project Progress</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/classes/ManageInterestWaveOff.cls
public class ManageInterestWaveOff {
    
    @InvocableMethod(label='Get Booking Payment Plans for Interest Wave Off')
    public static List<String> execute(List<Requests> requestLst){
        Decimal newAgreementValue = 0;
        
        Decimal newGSTValue = 0;
        
        
        List<Payment_Milestones__c> paymentPlanLst = [SELECT Id, Total_Interest_Amount__c,Milestone_age__c, Milestone_Status__c,Milestone_Amount1__c,GST_Amount1__c, Name,Interest_Amount__c, Due_Date__c,Milestone_Activation_Date__c, 
                                                                Payment_Received__c, Project_Progress__c, Sequence_No__c 
                                                                FROM Payment_Milestones__c 
                                                                WHERE Booking__c =: requestLst[0].bookingId and Total_Interest_Amount__c > 0 
                                                                ORDER BY Sequence_No__c];
                                                                
        return new List<String>{JSON.serialize(paymentPlanLst)};
       
    }

    public class Requests {
        @InvocableVariable(label='Booking Id' required=true)
        public String bookingId;
       
    }
     
}