dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Name_Formulla__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name_Formulla__c</fullName>
    <formula>IF( Primary_Applicant__r.FirstName &lt;&gt; null &amp;&amp;  Primary_Applicant__r.FirstName &lt;&gt; &apos;&apos;,  Primary_Applicant__r.FirstName+&apos; &apos;+ Primary_Applicant__r.LastName, Primary_Applicant__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Applicant Name Formulla</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Possession/Handover</fullName>
            </value>
            <value>
                <fullName>Snag/Desnag by Client</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancellation Initiated</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Pending</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Ready</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled -- Refund Done</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Handover</fullName>
                <isActive>false</isActive>
                <label>Handover</label>
            </value>
            <value>
                <fullName>In Process</fullName>
                <isActive>false</isActive>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Possession Letter</fullName>
                <isActive>false</isActive>
                <label>Possession Letter</label>
            </value>
            <value>
                <fullName>Registered</fullName>
                <isActive>false</isActive>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Sanction</fullName>
                <isActive>false</isActive>
                <label>Sanction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Transferred_To_Booking__c.field-meta.xml
<CustomField>
    <fullName>Transferred_To_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transferred To Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <formula>Related_Suggested_Property__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Number</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Amount1__c</fullName>
    <label>Milestone Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Status__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Status__c</fullName>
    <label>Milestone Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Project_Progress__c.field-meta.xml
<CustomField>
    <fullName>Project_Progress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Progress</label>
    <referenceTo>Project_Progress__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Project_Progress__c/Project_Progress__c.object-meta.xml
<CustomObject>
    <label>Project Progress</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project_Progress__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commencement</fullName>
            </value>
            <value>
                <fullName>Completion</fullName>
                <default>true</default>
                <label>Completion</label>
            </value>
            <value>
                <fullName>OC</fullName>
                <isActive>false</isActive>
                <label>OC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/classes/MilestoneLWCHelper.cls
public with sharing class MilestoneLWCHelper {
    @AuraEnabled (cacheable=true)
    public static List<Payment_Milestones__c> getMilestoneList(String projectProgId){
        try {
            system.debug('projectProgId ==>> ' + projectProgId);
            List<Payment_Milestones__c> paymentMilestoneList=new List<Payment_Milestones__c>();
            paymentMilestoneList= [Select Id,Name,Milestone_Amount1__c,Milestone_Status__c,Booking__c,Booking__r.name,Booking__r.Primary_Applicant_Name_Formulla__c,
                                   Booking__r.Unit_Number__c,Project_Progress__c,Booking__r.Stage__c From Payment_Milestones__c Where Milestone_Status__c=:'Inactive' 
                                   AND Project_Progress__c!=null AND Booking__r.Stage__c!='Terminated' AND Booking__r.Stage__c!='Cancellation Initiated' 
                                   AND Booking__r.Stage__c!='Booking Cancelled – Refund Pending' AND Booking__r.Stage__c!='Booking Cancelled – Refund Ready'
                                   AND Project_Progress__c=:projectProgId];
            return paymentMilestoneList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}