dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/TDS_Received__c.field-meta.xml
<CustomField>
    <fullName>TDS_Received__c</fullName>
    <label>TDS Received</label>
    <summarizedField>Payment__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Payment__c.Payment_Category__c</field>
        <operation>equals</operation>
        <value>TDS</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Payment__c.Status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>Pay-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment_Category__c.field-meta.xml
<CustomField>
    <fullName>Payment_Category__c</fullName>
    <label>Payment Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unit Cost</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>GST</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Refundable Interior Deposit</fullName>
            </value>
            <value>
                <fullName>Temporary Electricity Charges</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Security Deposits</fullName>
            </value>
            <value>
                <fullName>Possession/Handover(Other) Charge</fullName>
            </value>
            <value>
                <fullName>Possession/Handover(Other) Charge GST</fullName>
            </value>
            <value>
                <fullName>Security and Share Money</fullName>
            </value>
            <value>
                <fullName>Security and Share Money GST</fullName>
            </value>
            <value>
                <fullName>Transfer Charge</fullName>
            </value>
            <value>
                <fullName>Brokerage Charges</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>GST Avanya Tower A</fullName>
            </value>
            <value>
                <fullName>OCR</fullName>
                <isActive>false</isActive>
                <label>OCR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Bounced</fullName>
                <isActive>false</isActive>
                <label>Bounced</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Cleared</fullName>
                <isActive>false</isActive>
                <label>Cleared</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
            <value>
                <fullName>Wrong Entry</fullName>
                <isActive>false</isActive>
                <label>Wrong Entry</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Remaining_TDS_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_TDS_Amount__c</fullName>
    <label>Remaining TDS Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Status__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Status__c</fullName>
    <label>Milestone Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <label>Sequence No</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/TDS_Due__c.field-meta.xml
<CustomField>
    <fullName>TDS_Due__c</fullName>
    <formula>TDS_Value__c  -  TDS_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TDS Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/TDS_Pending__c.field-meta.xml
<CustomField>
    <fullName>TDS_Pending__c</fullName>
    <formula>TDS_Value__c  -  TDS_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TDS Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/TDS_Received__c.field-meta.xml
<CustomField>
    <fullName>TDS_Received__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TDS Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/TDS_Value__c.field-meta.xml
<CustomField>
    <fullName>TDS_Value__c</fullName>
    <formula>IF( Calculate_TDS__c ==True, Milestone_Amount1__c  * 0.01, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TDS Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/classes/TDSScript.cls
public class TDSScript {

    Public static Void Execute(String Status){
        
        Map<Id,List<Payment__c>> PaymentMap = New  Map<Id,List<Payment__c>>();
        Decimal PaymentBalance =0;
        
        List<Payment__c> paymentList = [SELECT ID,Amount__c,Payment_Category__c,Booking__c,Remaining_TDS_Amount__c
                                        FROM Payment__c WHERE Payment_Category__c ='TDS' 
                                        AND Payment_Status__c ='Approved' AND Booking__c!= NULL  ];
        system.debug('paymentList--'+paymentList);
        
        if(!paymentList.IsEmpty()){
            for(Payment__c pc :paymentList){
                if(PaymentMap.containsKey(pc.Booking__c)){
                    PaymentMap.get(pc.Booking__c).add(pc);
                    
                }else{
                    PaymentMap.put(pc.Booking__c,New List<Payment__c>{pc});
                }       
            }
        }
        system.debug('PaymentMap....'+PaymentMap);
        List<Payment_Milestones__c> MilestoneUpdateList = new List<Payment_Milestones__c>();
        
        List<Payment_Milestones__c> MilestoneList = [SELECT Id,Booking__c ,TDS_Received__c,TDS_Pending__c,TDS_Due__c,TDS_Value__c
                                                     from Payment_Milestones__c WHERE Booking__c =:PaymentMap.Keyset() AND TDS_Pending__c >0 AND Milestone_Status__c =: Status  Order By Sequence_No__c ASC];
        system.debug('MilestoneList--'+MilestoneList);
        if(!MilestoneList.IsEmpty()){
            Map<String,Decimal> paymentKNOCKOFFMaP = NEW Map<String,Decimal>();
            Map<String,Decimal> paymentMilKNOCKOFFMaP = NEW Map<String,Decimal>();
            for(Payment_Milestones__c  miles :MilestoneList){
                system.debug('miles--'+miles);
                Decimal TDSBalance = miles.TDS_Pending__c;
                if(PaymentMap.containsKey(miles.Booking__c)){
                    system.debug('PaymentMap.get(miles.Booking__c)--'+PaymentMap.get(miles.Booking__c));
                    system.debug('TDSBalance--'+TDSBalance);
                    for(Payment__C payment :PaymentMap.get(miles.Booking__c)){  
                        system.debug('TDSBalance in p--'+TDSBalance);
                        if(!paymentKNOCKOFFMaP.containskey(payment.Id)){
                            IF(payment.Remaining_TDS_Amount__c != null){
                                paymentKNOCKOFFMaP.put(payment.Id,payment.Remaining_TDS_Amount__c);
                            }else{
                                paymentKNOCKOFFMaP.put(payment.Id,payment.Amount__C);
                            }
                        }
                        system.debug('paymentKNOCKOFFMaP.get(payment.Id)--'+paymentKNOCKOFFMaP.get(payment.Id));
                        if(TDSBalance > 0 && paymentKNOCKOFFMaP.get(payment.Id) > 0){
                            SYSTEM.DEBUG('Clled');
                            if(TDSBalance >= paymentKNOCKOFFMaP.get(payment.Id)){
                                Payment_Milestones__c paymentMilestone = New Payment_Milestones__c();
                                paymentMilestone.id= miles.Id;
                                paymentMilestone.TDS_Received__c = paymentKNOCKOFFMaP.get(payment.Id);
                                //paymentMilestone.TDS_Pending__c = TDS_Pending__c-payment.Amount__C;
                                TDSBalance = TDSBalance - paymentMilestone.TDS_Received__c;
                                paymentKNOCKOFFMaP.put(payment.Id, 0);
                                
                                system.debug('paymentMilestone.TDS_Received__c--'+paymentMilestone.TDS_Received__c);
                                if(paymentMilKNOCKOFFMaP.containskey(miles.Id)){
                                    Decimal amount = paymentMilKNOCKOFFMaP.get(miles.Id) + paymentMilestone.TDS_Received__c;
                                    paymentMilKNOCKOFFMaP.put(miles.Id,amount);
                                }else{
                                    paymentMilKNOCKOFFMaP.put(miles.Id,paymentMilestone.TDS_Received__c);
                                }
                                  
                            }else{
                                Payment_Milestones__c paymentMilestone = New Payment_Milestones__c();
                                paymentMilestone.id= miles.Id;
                                paymentMilestone.TDS_Received__c = TDSBalance;
                                
                                paymentKNOCKOFFMaP.put(payment.Id, paymentKNOCKOFFMaP.get(payment.Id) - TDSBalance);
                                system.debug('paymentMilestone.paymentMilestone.TDS_Received__c--'+paymentMilestone.TDS_Received__c);
                                if(paymentMilKNOCKOFFMaP.containskey(miles.Id)){
                                    Decimal amount = paymentMilKNOCKOFFMaP.get(miles.Id) + paymentMilestone.TDS_Received__c;
                                    paymentMilKNOCKOFFMaP.put(miles.Id,amount);
                                }else{
                                    paymentMilKNOCKOFFMaP.put(miles.Id,paymentMilestone.TDS_Received__c);
                                }
                                TDSBalance = 0;
                            }
                        }
                    }      
                    
                }
            }
            SYSTEM.DEBUG('paymentKNOCKOFFMaP---'+paymentKNOCKOFFMaP);
            for(String pymnt1 :paymentMilKNOCKOFFMaP.Keyset()){
                Payment_Milestones__c newpymntMilestone = New Payment_Milestones__c();
                newpymntMilestone.id=pymnt1;
                newpymntMilestone.TDS_Received__c = paymentMilKNOCKOFFMaP.get(pymnt1);
                MilestoneUpdateList.add(newpymntMilestone);
            }
            system.debug('MilestoneUpdateList--'+MilestoneUpdateList);
            if(!MilestoneUpdateList.IsEmpty()){
                Update  MilestoneUpdateList;
                system.debug('MilestoneUpdateList--'+MilestoneUpdateList);
            }
            List<Payment__c> pymntupdateList = New  List<Payment__c>();
            for(String pymnt :paymentKNOCKOFFMaP.Keyset()){
                Payment__c newpymnt = New Payment__c();
                newpymnt.id=pymnt;
                newpymnt.Remaining_TDS_Amount__c = paymentKNOCKOFFMaP.get(pymnt);
                pymntupdateList.Add(newpymnt);
            }
            system.debug('pymntupdateList--'+pymntupdateList);
            If(!pymntupdateList.IsEmpty()){
                Update pymntupdateList;
            }
        }   
    } 
}