dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/NOC_Uploaded_Date__c.field-meta.xml
<CustomField>
    <fullName>NOC_Uploaded_Date__c</fullName>
    <label>NOC Uploaded Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/BookingId__c.field-meta.xml
<CustomField>
    <fullName>BookingId__c</fullName>
    <description>BookingId For Backend.</description>
    <label>BookingId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
            <value>
                <fullName>Bank Approved NOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/classes/BatchToSendEmailNOCPendingClass.cls
global class BatchToSendEmailNOCPendingClass implements DataBase.Batchable<Sobject>{
    
    global Database.QueryLocator start(DataBase.BatchableContext bc){
        Date pastThreeDays = System.Today().addDays(-3);
        List<Booking__c> a = [Select Id,Name,OwnerId,NOC_Uploaded_Date__c From Booking__c Where NOC_Uploaded_Date__c =: pastThreeDays];
        System.debug('a'+a);
        return Database.getQueryLocator('Select Id,Name,OwnerId,NOC_Uploaded_Date__c From Booking__c Where NOC_Uploaded_Date__c =: pastThreeDays');
    }
    global void execute(Database.BatchableContext bc,List<Booking__c> BookingList){
        
        UserRole CRMHeadRoleObj = [select id,Name,DeveloperName from UserRole where DeveloperName =: 'CRM_Head'];
        String CRMHeadUserName = Label.CRM_Head_User;
        User CRMHeadRoleObjUser = [Select Id,Name,Email From User Where UserName =: CRMHeadUserName AND UserRoleId =: CRMHeadRoleObj.Id AND isActive =: true Limit 1];
        System.debug('CRMHeadRoleObjUser'+CRMHeadRoleObjUser);
        EmailTemplate emailTemplate = [Select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where DeveloperName =: 'NOC_Not_Uploaded_Email_Template' limit 1];
        System.debug('emailTemplate'+emailTemplate);
        Set<Id> setOfBookingOWnerIds = new Set<Id>();
        for(Booking__c bookObj : BookingList)
            setOfBookingOWnerIds.add(bookObj.OwnerId);
        System.debug('setOfBookingOWnerIds'+setOfBookingOWnerIds);
        Map<Id,User> mapIdToUser = new Map<Id,User>([Select Id,Email From User Where isActive =: true AND Id IN : setOfBookingOWnerIds]);
        System.debug('mapIdToUser'+mapIdToUser);
        List<String> addresses = new List<String>();
        addresses.add(CRMHeadRoleObjUser.Email);
        Set<Id> setOfBookingIds = new Set<Id>();
        for(Booking__c bookObj : BookingList)
            if(bookObj.Id != null)
            setOfBookingIds.add(bookObj.Id);
        System.debug('setOfBookingIds'+setOfBookingIds);
        List<ContentVersion> listOfContentVersions = new List<ContentVersion>([Select Id,SObjectType__c,Document_Type__c,BookingId__c From ContentVersion where Document_Type__c =: 'Bank Approved NOC' AND BookingId__c In : setOfBookingIds]);
        Map<Id,ContentVersion> mapBookingIdToContenVersion = new Map<Id,ContentVersion>();
        
        for(ContentVersion con : listOfContentVersions){
            mapBookingIdToContenVersion.put(con.BookingId__c,con);
        }
        System.debug('mapBookingIdToContenVersion'+mapBookingIdToContenVersion);
        for(Booking__c bookObj : BookingList){
            System.debug('bookObj'+bookObj);
            String recordLink=URL.getOrgDomainUrl().toExternalForm() + '/' + bookObj.Id;
            System.debug('bookObj.NOC_Uploaded_Date__c'+bookObj.NOC_Uploaded_Date__c);
            if((bookObj.NOC_Uploaded_Date__c).addDays(3) == Date.today()){
                System.debug('bookObj.NOC_Uploaded_Date__c'+bookObj.NOC_Uploaded_Date__c);
                addresses.add(mapIdToUser.get(bookObj.OwnerId).Email);
                if(!mapBookingIdToContenVersion.containsKey(bookObj.Id)){
                    System.debug('In mapBookingIdToContenVersion'+mapBookingIdToContenVersion);
                    String htmlBody = emailTemplate.htmlValue;
                    htmlBody = htmlBody.replace('{!bookingName}', '<a href="'+recordLink+'">' + bookObj.Name +'</a>');
                    htmlBody = htmlBody.replace('{!crmHeadName}', CRMHeadRoleObjUser.Name);
                    String plainBody = emailTemplate.Body;
                    plainBody = plainBody.replace('{!bookingName}', '<a href="'+recordLink+'">' + bookObj.Name +'</a>'); 
                    plainBody = plainBody.replace('{!crmHeadName}', CRMHeadRoleObjUser.Name);
                    String Subject = emailTemplate.Subject;
                    Subject = bookObj.Name + ' ' + Subject;
                    SendEmailandBellNotificationUtility.SendEmail2(emailTemplate.Id,htmlBody,plainBody,addresses,null,true,bookObj.Id,null,null,null);
                }
            }
        }
    } 
    global void finish(Database.BatchableContext bc){
        
    }
}