dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <summarizedField>Price_Details__c.Discount__c</summarizedField>
    <summaryForeignKey>Price_Details__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <formula>Related_Suggested_Property__r.Payment_Plan__r.Name</formula>
    <label>Payment Plan</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <formula>Project_Name__r.Project_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Email</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name_Formulla__c.field-meta.xml
<CustomField>
    <fullName>Project_Name_Formulla__c</fullName>
    <formula>Project_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name Formulla</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Suggested_Property__c.field-meta.xml
<CustomField>
    <fullName>Related_Suggested_Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Suggested Property</label>
    <referenceTo>Suggested_Property__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <formula>Related_Suggested_Property__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Number</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <label>Project Email</label>
    <type>Email</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Property__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Flat_Type__c.field-meta.xml
<CustomField>
    <fullName>Flat_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COVERED STACK</fullName>
            </value>
            <value>
                <fullName>STACK</fullName>
            </value>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK G</fullName>
            </value>
            <value>
                <fullName>2.5 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
            <value>
                <fullName>PENTHOUSES</fullName>
            </value>
            <value>
                <fullName>ROW HOUSES</fullName>
            </value>
            <value>
                <fullName>VILLAS</fullName>
            </value>
            <value>
                <fullName>BUNGALOW</fullName>
            </value>
            <value>
                <fullName>SHOP WITH TERRACE</fullName>
            </value>
            <value>
                <fullName>SHOP WITHOUT TERRACE</fullName>
            </value>
            <value>
                <fullName>OFFICE WITH TERRACE</fullName>
            </value>
            <value>
                <fullName>OFFICE WITHOUT TERRACE</fullName>
            </value>
            <value>
                <fullName>REFUGEE</fullName>
            </value>
            <value>
                <fullName>STUDIO</fullName>
            </value>
            <value>
                <fullName>CAR PARKING</fullName>
            </value>
            <value>
                <fullName>BIKE PARKING</fullName>
            </value>
            <value>
                <fullName>BASEMENT PARKING</fullName>
                <isActive>false</isActive>
                <label>BASEMENT PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE OPEN PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE OPEN PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE PODIUM PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE PODIUM PARKING</label>
            </value>
            <value>
                <fullName>DOUBLE STILT PARKING</fullName>
                <isActive>false</isActive>
                <label>DOUBLE STILT PARKING</label>
            </value>
            <value>
                <fullName>OPEN PARKING</fullName>
                <isActive>false</isActive>
                <label>OPEN PARKING</label>
            </value>
            <value>
                <fullName>PODIUM PARKING</fullName>
                <isActive>false</isActive>
                <label>PODIUM PARKING</label>
            </value>
            <value>
                <fullName>STILT PARKING</fullName>
                <isActive>false</isActive>
                <label>STILT PARKING</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Property_Price_Slab__c.field-meta.xml
<CustomField>
    <fullName>Property_Price_Slab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Price Slab</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please add price slab as per project selected</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Pricing_Plan__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Pricing_Plan__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Property_Status__c.field-meta.xml
<CustomField>
    <fullName>Property_Status__c</fullName>
    <label>Property Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Pre - Allotted</fullName>
            </value>
            <value>
                <fullName>Allotted</fullName>
            </value>
            <value>
                <fullName>Allotted In Progress</fullName>
            </value>
            <value>
                <fullName>Confirmed Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Proposed_Deck_Area_in_sq_mt__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Deck_Area_in_sq_mt__c</fullName>
    <formula>Deck_Proposed_Area__c/10.764</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proposed Deck Area (in sq. mt.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Proposed_Utility_Area_in_sq_mt__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Utility_Area_in_sq_mt__c</fullName>
    <formula>Proposed_Utility_Area__c/10.764</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proposed Utility Area (in sq. mt.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please add tower as per project selected</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Tower__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit No.</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/Suggested_Property__c.object-meta.xml
<CustomObject>
    <label>Suggested Property</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Suggestion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suggested Property</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Cost_Sheet_Provided__c.field-meta.xml
<CustomField>
    <fullName>Cost_Sheet_Provided__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cost Sheet Provided</label>
    <type>Checkbox</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Suggested Property</relationshipLabel>
    <relationshipName>Suggested_Property</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>Payment_Plan__c</referenceTo>
    <relationshipLabel>Suggested Property</relationshipLabel>
    <relationshipName>Suggested_Property</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <formula>Unit__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Name</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Suggested_Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Suggested Property</relationshipLabel>
    <relationshipName>Suggested_Property</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/classes/GenerateBookingCostSheet.cls
public with sharing class GenerateBookingCostSheet {
    public boolean data;
    @InvocableMethod(label='Generate Booking Cost Sheet')
    public static List<String> execute( List<Requests> requestLst){
        
        return new List<String> {generateCS(requestLst[0].bookingId)};
            }
    
    public static String generateCS(String bookId){
        
        ContentVersion conVer;
        list<ContentDocumentLink> contentDocList = new list<ContentDocumentLink>();
        list<ContentVersion> ContentVersionList =new  list<ContentVersion>();
        String contentId='';
        string whereCausLike;
        list<Id> ContentDocId = new list<Id>();
        List<user> collaborators = new List<user>();
        list<ContentDocumentLink> conDocList = new list<ContentDocumentLink>();
        list<ContentDocumentLink> conDocListC = new list<ContentDocumentLink>();
        
        Booking__c book = [Select Id,Name,Related_Suggested_Property__c,Project_Name__r.Project_Email__c,Primary_Applicant__r.PersonEmail,
                           Unit_Number__c,Project_Name_Formulla__c from Booking__c where Id =: bookId];
        String pId = book.Related_Suggested_Property__c;
        Suggested_Property__c sp = [SELECT Id, Name, Discount__c,Cost_Sheet_Provided__c, Opportunity__c,Unit__r.Tower__r.Name,Unit__r.Property_Status__c, Payment_Plan__c,
                                    Unit__r.Property_Price_Slab__c,Unit__r.Proposed_Deck_Area_in_sq_mt__c,Unit__r.Proposed_Utility_Area_in_sq_mt__c, Unit__r.Flat_Type__c, Unit__r.Name,Site_Head__c, Payment_Plan_Detail__c 
                                    FROM Suggested_Property__c WHERE Id =: pId];
        collaborators = [select id from user where ((id=: sp.Site_Head__c OR Profile.Name = 'System Administrator')AND (id !=: UserInfo.getUserId()) AND IsActive = true)];
        List<ContentDocumentLink> cDLLst = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId =: book.Id];
        
        PageReference ref = Page.BookingCostSheet;
        ref.getParameters().put('id',book.Id);
        
        Blob body; 
        if(Test.isRunningTest()){
            body = Blob.valueOf('Booking Cost Sheet');
        }
        else{
            body = ref.getContent();
        }
        
        String unitName;
        if(sp.Unit__r.Name.length() < 4)
        {
            unitName = 0 + sp.Unit__r.Name;
        }
        else{
            unitName = sp.Unit__r.Name;
        }
        if(sp.Unit__r.Tower__r.Name <> null && unitName <> null && sp.Name <> null)
        {
            whereCausLike = 'Cost Sheet/'+sp.Unit__r.Tower__r.Name.left(3) + '/' + unitName  +'/'+'%';  
        } 
        contentDocList =[select id,ContentDocumentId,LinkedEntityId from ContentDocumentLink where LinkedEntityId=:book.Id];
        system.debug('===> contentDocList ' + contentDocList );
        if(contentDocList.size()>0)
        {
            for(ContentDocumentLink cd :contentDocList)
            {   
                ContentDocId.add(cd.ContentDocumentId);
            }
            ContentVersionlist =[SELECT ContentDocumentId,VersionData,isMajorVersion,PathOnClient,CreatedDate FROM ContentVersion where Title Like: whereCausLike and ContentDocumentId IN :ContentDocId];
        }
        if(ContentVersionlist.size()>0)
        {
            conVer =new ContentVersion(); 
            conVer.ContentLocation = 'S'; 
            conVer.PathOnClient = 'Cost Sheet/'+sp.Unit__r.Tower__r.Name.left(3) + '/' + unitName + '/' + book.Name.right(4) + cDLLst.size() +'.pdf'; 
            conVer.Title = 'Cost Sheet/'+sp.Unit__r.Tower__r.Name.left(3) + '/' + unitName  + '/' + book.Name.right(4) + cDLLst.size() +'.pdf';
            conVer.VersionData = body;
            conVer.SObjectType__c = 'Booking__c';
            conVer.Document_Type__c = 'Cost Sheet with Additional Parking';
            conVer.ContentDocumentId=ContentVersionlist[0].ContentDocumentId;
            insert conVer;
            system.debug('test'+conVer);
            contentId = conVer.ContentDocumentId;
            try{
                ContentDistribution newDist = new ContentDistribution();
                newDist.ContentVersionId = conVer.id;
                newDist.Name = 'Cost Sheet/'+sp.Unit__r.Tower__r.Name.left(3) + '/' + unitName + '/' + book.Name.right(4) + cDLLst.size();
                newDist.PreferencesAllowViewInBrowser = true;
                newDist.RelatedRecordId = conVer.FirstPublishLocationId;
                insert newDist;
                
                List<ContentDistribution> ContentDistributionList =[SELECT id, RelatedRecordId, Name,ContentDownloadUrl, DistributionPublicUrl 
                                                                    FROM ContentDistribution
                                                                    WHERE ContentVersionId = :conVer.id];
                /*Suggested_Property__c suggestedProperty = New Suggested_Property__c();
                suggestedProperty.id = pId;
                system.debug('pId'+pId);
                suggestedProperty.Cost_Sheet_Link__c = ContentDistributionList[0].DistributionPublicUrl;
                suggestedProperty.Lock_Record__c = true;
                update suggestedProperty;*/
                Booking__c updatebook = new Booking__c();
                updatebook.Id = book.Id;
                updatebook.Updated_Cost_Sheet_Link__c = ContentDistributionList[0].DistributionPublicUrl;
                updatebook.Updated_Cost_Sheet_Generated__c = true;
                update updatebook;
                
                List<OrgWideEmailAddress> fromEmailAddress = [SELECT Id, Address FROM OrgWideEmailAddress where Address=:book.Project_Name__r.Project_Email__c limit 1];
                EmailTemplate emailTemplate = [Select Id,Name, Subject, HtmlValue, Body,DeveloperName from EmailTemplate where DeveloperName = 'Email_for_Cost_Sheet_with_Additional_Parking' LIMIT 1];
                String subject1 = emailTemplate.Subject;
                String htmlBody = emailTemplate.HtmlValue;
                String plainBody = emailTemplate.Body;
                if(book.Unit_Number__c != null){
                    htmlBody = htmlBody.replace('{FlatNumber}', book.Unit_Number__c);
                    plainBody = plainBody.replace('{FlatNumber}', book.Unit_Number__c);
                }
                if(book.Project_Name_Formulla__c != null){
                    htmlBody = htmlBody.replace('{ProjectName}', book.Project_Name_Formulla__c);
                    plainBody = plainBody.replace('{ProjectName}', book.Project_Name_Formulla__c);
                }
                if(emailTemplate!=null && book.Primary_Applicant__r.PersonEmail!=null){
                    List<String> toEmailList=new List<String>();
                    toEmailList.add(book.Primary_Applicant__r.PersonEmail);
                    String fromMail = '';
                    if(!fromEmailAddress.isEmpty()){
                        fromMail = fromEmailAddress[0].Id;
                    }
                    SendEmailandBellNotificationUtility.SendEmail2(emailTemplate.Id,subject1,htmlBody,plainBody,toEmailList,null,true,book.Id,conVer.VersionData,conVer.Title,fromMail,conVer.Id);
                }
            }
            catch(Exception ex)
            {
                System.debug('Error--- ' +ex.getMessage()+ ' LineNumber- '+ex.getlineNumber());
                
            }
            
        }
        
        else
        {
            conVer = new ContentVersion();
            conVer.ContentLocation = 'S'; 
            conVer.PathOnClient = 'Cost Sheet/'+sp.Unit__r.Tower__r.Name.left(3) + '/' + unitName + '/' + book.Name.right(4) + cDLLst.size() +'.pdf'; 
            conVer.Title = 'Cost Sheet/'+sp.Unit__r.Tower__r.Name.left(3) + '/' + unitName  + '/' + book.Name.right(4) + cDLLst.size() +'.pdf';
            conVer.VersionData = body;
            conVer.SObjectType__c = 'Booking__c';
            conVer.Document_Type__c = 'Cost Sheet with Additional Parking';
            conVer.isMajorVersion=false;
            Insert conVer;
            ContentVersion contentverlink = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :conVer.Id LIMIT 1];
            
            ContentDocumentLink conDocLink = New ContentDocumentLink();
            conDocLink.LinkedEntityId = book.Id; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
            conDocLink.ContentDocumentId = contentverlink.ContentDocumentId;  //ContentDocumentId Id from ContentVersion
            conDocLink.shareType = 'V';
            conDocList.add(conDocLink);
            
            for(user uId : collaborators)
            {
                ContentDocumentLink conDocLinkC = New ContentDocumentLink();
                conDocLinkC.LinkedEntityId = uId.id; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
                conDocLinkC.ContentDocumentId = contentverlink.ContentDocumentId;  //ContentDocumentId Id from ContentVersion
                conDocLinkC.shareType = 'C';
                conDocList.add(conDocLinkC); 
            }                             
            insert conDocList; 
            contentId = contentverlink.ContentDocumentId;
            try{
                ContentDistribution newDist = new ContentDistribution();
                newDist.ContentVersionId = conVer.id;
                newDist.Name = 'Cost Sheet/'+sp.Unit__r.Tower__r.Name.left(3) + '/' + unitName + '/' + book.Name.right(4) + cDLLst.size();
                newDist.PreferencesAllowViewInBrowser = true;
                newDist.RelatedRecordId = conVer.FirstPublishLocationId;
                insert newDist;
                
                List<ContentDistribution> ContentDistributionList =[SELECT id, RelatedRecordId, Name,ContentDownloadUrl, DistributionPublicUrl 
                                                                    FROM ContentDistribution
                                                                    WHERE ContentVersionId = :conVer.id];
                /*Suggested_Property__c suggestedProperty = New Suggested_Property__c();
                suggestedProperty.id = pId;
                system.debug('pId'+pId);
                suggestedProperty.Cost_Sheet_Link__c = ContentDistributionList[0].DistributionPublicUrl;
                suggestedProperty.Lock_Record__c = true;
                update suggestedProperty;*/
                Booking__c updatebook = new Booking__c();
                updatebook.Id = book.Id;
                updatebook.Updated_Cost_Sheet_Link__c = ContentDistributionList[0].DistributionPublicUrl;
                updatebook.Updated_Cost_Sheet_Generated__c = true;
                update updatebook;
                
                List<OrgWideEmailAddress> fromEmailAddress = [SELECT Id, Address FROM OrgWideEmailAddress where Address=:book.Project_Name__r.Project_Email__c limit 1];
                EmailTemplate emailTemplate = [Select Id,Name, Subject, HtmlValue, Body,DeveloperName from EmailTemplate where DeveloperName = 'Email_for_Cost_Sheet_with_Additional_Parking' LIMIT 1];
                String subject1 = emailTemplate.Subject;
                String htmlBody = emailTemplate.HtmlValue;
                String plainBody = emailTemplate.Body;
                if(book.Unit_Number__c != null){
                    htmlBody = htmlBody.replace('{FlatNumber}', book.Unit_Number__c);
                    plainBody = plainBody.replace('{FlatNumber}', book.Unit_Number__c);
                }
                if(book.Project_Name_Formulla__c != null){
                    htmlBody = htmlBody.replace('{ProjectName}', book.Project_Name_Formulla__c);
                    plainBody = plainBody.replace('{ProjectName}', book.Project_Name_Formulla__c);
                }
                if(emailTemplate!=null && book.Primary_Applicant__r.PersonEmail!=null){
                    List<String> toEmailList=new List<String>();
                    toEmailList.add(book.Primary_Applicant__r.PersonEmail);
                    String fromMail = '';
                    if(!fromEmailAddress.isEmpty()){
                        fromMail = fromEmailAddress[0].Id;
                    }
                    SendEmailandBellNotificationUtility.SendEmail2(emailTemplate.Id,subject1,htmlBody,plainBody,toEmailList,null,true,book.Id,conVer.VersionData,conVer.Title,fromMail,conVer.Id);
                }
            }
            catch(Exception ex)
            {
                System.debug('Error--- ' +ex.getMessage()+ ' LineNumber- '+ex.getlineNumber());
            }
        }
        
        return contentId;
    }
    
    public class Requests {
        @InvocableVariable(label='Booking Id' required=true)
        public String bookingId;
    }
}