dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Sap_Code__c.field-meta.xml
<CustomField>
    <fullName>Sap_Code__c</fullName>
    <label>Sap Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Possession/Handover</fullName>
            </value>
            <value>
                <fullName>Snag/Desnag by Client</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Cancellation Initiated</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Pending</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled – Refund Ready</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled -- Refund Done</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Handover</fullName>
                <isActive>false</isActive>
                <label>Handover</label>
            </value>
            <value>
                <fullName>In Process</fullName>
                <isActive>false</isActive>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Possession Letter</fullName>
                <isActive>false</isActive>
                <label>Possession Letter</label>
            </value>
            <value>
                <fullName>Registered</fullName>
                <isActive>false</isActive>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Sanction</fullName>
                <isActive>false</isActive>
                <label>Sanction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Co_Applicant__c/Co_Applicant__c.object-meta.xml
<CustomObject>
    <label>Co-Applicant</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Applicant</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Co_Applicant__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Co-Applicant</relationshipLabel>
    <relationshipName>Co_Applicant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Co_Applicant__c/fields/Sap_Code__c.field-meta.xml
<CustomField>
    <fullName>Sap_Code__c</fullName>
    <label>Sap Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
            <value>
                <fullName>Demand Letter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Demand__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Demand__c/fields/Demand_Date__c.field-meta.xml
<CustomField>
    <fullName>Demand_Date__c</fullName>
    <label>Demand Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Demand__c/fields/Sap_Code__c.field-meta.xml
<CustomField>
    <fullName>Sap_Code__c</fullName>
    <label>Sap Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Demand__c/fields/Sap_Demand_Status__c.field-meta.xml
<CustomField>
    <fullName>Sap_Demand_Status__c</fullName>
    <label>Sap Demand Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Demand__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Demand__c/fields/TDS_Charges_SAP__c.field-meta.xml
<CustomField>
    <fullName>TDS_Charges_SAP__c</fullName>
    <label>TDS Charges (SAP)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Demand__c/fields/Total_Amount_SAP__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_SAP__c</fullName>
    <label>Total Amount (SAP)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Invoice-{00000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Invoice__c/fields/Co_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Co_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-Applicant</label>
    <referenceTo>Co_Applicant__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Invoice__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <label>Demand</label>
    <referenceTo>Demand__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>Invoice Line Item - {00000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Invoice_Line_Item__c/fields/Sap_Code__c.field-meta.xml
<CustomField>
    <fullName>Sap_Code__c</fullName>
    <externalId>true</externalId>
    <label>Sap Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Sap_Code__c.field-meta.xml
<CustomField>
    <fullName>Sap_Code__c</fullName>
    <label>Milestone Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/classes/DemandApi.cls
@RestResource(urlMapping='/demand/*')
global class DemandApi{
    public static void createAttachmenet(String json, String demandId,string sapCode){
        
        ContentVersion cv = new ContentVersion();
        cv.Title = sapCode;
        cv.Document_Type__c ='Demand Letter';
        cv.PathOnClient = 'demandLetter.pdf'; // Replace with your file's name
        cv.SObjectType__c ='Demand__c';
        cv.VersionData = EncodingUtil.base64Decode(json);
        insert cv;
        ContentVersion contentVersion_2 = [SELECT Id, Title, ContentDocumentId 
                                           FROM ContentVersion WHERE Id =:cv.Id LIMIT 1];
        
        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = demandId;
        contentlink.contentdocumentid = contentVersion_2.contentdocumentid;
        contentlink.ShareType = 'V';
        insert contentlink;
        
    }
    @HttpGet
    global static Void getdemandRecord() {
        RestResponse res = RestContext.response;
        try {
            Map<String,ResponseWrapper> responseMap = New Map<String,ResponseWrapper>();
            Map<String,String> iLISapCodeVsInvoiceSapCodeMap = new Map<String,String>();
            Map<String, Demand__c> demandMap = new Map<String, Demand__c>();
            Map<String, Invoice__c> invoiceMap = new Map<String, Invoice__c>();
            Map<String, Object> demandObject = (Map<String, Object>)JSON.deserializeUntyped(RestContext.request.requestBody.toString());
            Map<String, Object> innerBody = (Map<String, Object>)demandObject.get('ZSD021_SFDC_DEMAND');
            Map<String, Object> demandHeader = (Map<String, Object>)innerBody.get('DEMAND_HEADER');
            Map<String, Object> demandItems = (Map<String, Object>)innerBody.get('DEMAND_ITEMS');
            List<Object> itemList = (List<Object>)demandItems.get('item');
            
            String demdId='';
            String InvoiceId;
            String Status ;
            if(!demandHeader.isEmpty()){
                String demandSapCode=String.valueOf(demandHeader.get('VBELN'));
                String demandCreatedDate=String.valueOf(demandHeader.get('FKDAT')); // milestone Activation date (billing date)
                System.debug('demandCreatedDate'+demandCreatedDate+ '--dd.mm.yyyy---'); 
               
                String bookingSapCode=String.valueOf(demandHeader.get('AUBEL')); 
                String bookingDate=String.valueOf(demandHeader.get('AUDAT')); // No use
                String SapCustomerCode=String.valueOf(demandHeader.get('KUNAG')); //0020000133
                String tower=String.valueOf(demandHeader.get('WERKS')); // No use
                String invoiceNetValue=String.valueOf(demandHeader.get('NETWR'));
                String MWSBK=String.valueOf(demandHeader.get('MWSBK')); // No Mapping
                String totalAmountIncludingGST=String.valueOf(demandHeader.get('TOTAL_AMOUNT'));
                String TDSCharges=String.valueOf(demandHeader.get('TDS'));
                String interest=String.valueOf(demandHeader.get('INTEREST'));
                Status=String.valueOf(demandHeader.get('FKSTO'));
                String emailStatus=String.valueOf(demandHeader.get('EMAIL_STATUS'));
                String base64File=String.valueOf(demandHeader.get('PDF_FILE'));
                List<Booking__c> bookingIds=[ select id, Name  from Booking__c  where Sap_Code__c=:bookingSapCode LIMIT 1];
                String bookingId='';
                if(bookingIds.size()>0){
                    bookingId=bookingIds[0].id;
                }
                else{
                    //throw new CustomException('No Booking found with the given Sap code');
                    res.statusCode = 200;
                    String  jsonResponse = '{"RESPONSE": {"SFDC_ID": \"'+''+'\", "STATUS": "' + 'Error' + '","MESSAGE":"'+'booking not exist"'+'}}'; //MESSAGE
                    res.responseBody = blob.valueOf(jsonResponse);
                    return;   
                }
                if (SapCustomerCode.length() < 10) {
                    Integer zeroesToAdd = 10 - SapCustomerCode.length();
                    
                    for (Integer i = 0; i < zeroesToAdd; i++) {
                        SapCustomerCode = '0' + SapCustomerCode;
                    }
                }
                List<Co_Applicant__c> coApp=[select id from Co_Applicant__c  where Sap_Code__c =:SapCustomerCode LIMIT 1];
                String coAppId='';
                if(coApp.size()>0){
                    coAppId=coApp[0].id;
                }
                else{
                    //throw new CustomException('co Applicant not exist ');
                    res.statusCode = 200;
                    String  jsonResponse = '{"RESPONSE": {"SFDC_ID": \"'+''+'\", "STATUS": "' + 'Error' + '","MESSAGE":"'+'co Applicant not exist"'+'}}'; //MESSAGE
                    res.responseBody = blob.valueOf(jsonResponse);
                    return;
                }
                
                SYstem.debug('demandSapCode'+demandSapCode);
                List<Demand__c> demandList=[Select id from demand__c where Sap_Code__c=:demandSapCode LIMIT 1];
                
                List<Invoice__c> invoiceList =[Select id,Demand__c from Invoice__c where Demand__r.Sap_Code__c=:demandSapCode LIMIT 1];
                Demand__c demand = new Demand__c();
                System.debug('Test+'+bookingId);
                demand.Booking__c = bookingId;
                demand.Sap_Code__c = demandSapCode;
                demand.Demand_Date__c = Date.valueOf(dateFormat(demandCreatedDate));
                demand.Total_Amount_SAP__c=Decimal.valueOf(totalAmountIncludingGST);
                demand.Stage__c = 'New';
                demand.TDS_Charges_SAP__c=Decimal.valueOf(TDSCharges);
                demand.Sap_Demand_Status__c=Status;   
                demand.Interest_SAP__c=Decimal.valueOf(interest);
                Invoice__c invoice = new Invoice__c();
                invoice.Co_Applicant__c = coAppId;
                invoice.Invoice_Date__c = Date.valueOf(dateFormat(demandCreatedDate));
                invoice.Status__c = Status;
                
                if(demandList.IsEmpty()){
                    insert demand;
                    demdId=demand.id;
                    
                    invoice.Demand__c = demand.Id;
                    insert invoice;
                    InvoiceId = invoice.id;
                    
                }else{
                    demand.id =  demandList[0].Id;
                    Update demand;
                    demdId=demand.id;
                    
                    invoice.Demand__c = demand.Id;
                    invoice.Id =invoiceList[0].Id;
                    Update invoice;
                    InvoiceId = invoice.id;
                    
                }
                
                //insert invoice line items
                List<Invoice_Line_Item__c> invoiceLineItemList = new List<Invoice_Line_Item__c>();
                Set<String> pmSapCodeList =new Set<String>();
                if(demandItems.get('item') !=null){
                    for (Object obj:itemList){
                        Map<String, Object> item = (Map<String, Object>)obj;
                        String Statusfield = String.valueOf(item.get('POSNR')); // no use
                        String MATERIAL_NO = String.valueOf(item.get('MATERIAL_NO'));
                        String particular = String.valueOf(item.get('ARKTX'));
                        String XREF1 = String.valueOf(item.get('XREF1')); // milestone code sap
                        String Amount = String.valueOf(item.get('NETWR'));
                        String CGST_AMOUNT = String.valueOf(item.get('CGST_AMOUNT'));
                        String SGST_AMOUNT = String.valueOf(item.get('SGST_AMOUNT'));
                        String IGST_AMOUNT = String.valueOf(item.get('IGST_AMOUNT'));
                        String DISCOUNT = String.valueOf(item.get('DISCOUNT'));
                        String TOTAL_AMOUNT = String.valueOf(item.get('TOTAL_AMOUNT'));
                        if(String.isNotBlank(XREF1)){
                            pmSapCodeList.add(XREF1);
                        }
                        Invoice_Line_Item__c invoiceLineItem = new Invoice_Line_Item__c();
                        invoiceLineItem.Invoice__c = invoice.Id;
                        invoiceLineItem.Particular__c = '';
                        invoiceLineItem.Amount__c =null;
                        invoiceLineItem.Sap_Code__c=demandSapCode;
                        invoiceLineItem.Particular__c=particular;
                        invoiceLineItem.Amount__c=Decimal.valueOf(Amount);
                        invoiceLineItem.GST__c=Decimal.valueOf(CGST_AMOUNT)+Decimal.valueOf(SGST_AMOUNT);
                        invoiceLineItemList.add(invoiceLineItem);
                        iLISapCodeVsInvoiceSapCodeMap.put(invoiceLineItem.Sap_Code__c, demandSapCode);
                        
                        System.debug('ssss'+iLISapCodeVsInvoiceSapCodeMap);
                        
                    }
                    List<Payment_Milestones__c> pmToUpdate=new List<Payment_Milestones__c>();
                    List<Demand__c> dmToUpdate=new List<Demand__c>();
                    system.debug('pmSapCodeList--> '+pmSapCodeList);
                    if(!pmSapCodeList.isEmpty() && pmSapCodeList!=null){
                        system.debug('pmSapCodeList.size()--> '+pmSapCodeList.size());
                        for(Payment_Milestones__c pm :[Select id,Milestone_Activation_Date__c, Booking__r.Sap_Code__c from Payment_Milestones__c where Sap_Code__c in :pmSapCodeList AND Booking__r.Sap_Code__c=:bookingSapCode]){
                            Payment_Milestones__c pp=new Payment_Milestones__c();
                            system.debug('pm.Name--'+pm.Booking__c);
                            pp.Id=pm.id;
                            
                            if(Status =='Cancelled'){
                                pp.Milestone_Status__c='Inactive';
                                pp.Milestone_Activation_Date__c = Null ;
                                pp.Due_Date__c = Null;
                            }else{
                                pp.Milestone_Status__c='Active';
                                pp.Milestone_Activation_Date__c=Date.valueOf(dateFormat(demandCreatedDate));
                            }
                            pmToUpdate.add(pp);
                            
                            Demand__c De = New Demand__c();
                            De.Id =demdId;
                            De.Payment_Milestones__c = pm.Id;
                            dmToUpdate.add(De);
                            
                        }
                    }
                    else{
                        String MilestoneName = System.Label.OtherChargesMilestone;
                        for(Payment_Milestones__c pm :[Select id,Milestone_Activation_Date__c, Booking__r.Sap_Code__c from Payment_Milestones__c where Name =:MilestoneName AND Booking__r.Sap_Code__c=:bookingSapCode]){
                            Payment_Milestones__c pp=new Payment_Milestones__c();
                            system.debug('pm.Name--'+pm.Booking__c);
                            pp.Id=pm.id;
                            
                            if(Status =='Cancelled'){
                                pp.Milestone_Status__c='Inactive';
                                pp.Milestone_Activation_Date__c = Null;
                                pp.Due_Date__c = Null;
                            }else{
                                pp.Milestone_Status__c='Active';
                                pp.Milestone_Activation_Date__c=Date.valueOf(dateFormat(demandCreatedDate));
                            }
                            pmToUpdate.add(pp);
                            
                            Demand__c De = New Demand__c();
                            De.Id =demdId;
                            De.Payment_Milestones__c = pm.Id;
                            dmToUpdate.add(De);
                            
                        }
                    }
                    if(Status!= 'Cancelled'){
                        createAttachmenet(base64File,demdId,demandSapCode);
                    }
                    
                    if(!pmToUpdate.isEmpty()){
                        update pmToUpdate;
                    }
                    
                    if(!dmToUpdate.isEmpty()){
                        update dmToUpdate;
                    }
                    
                    List<Invoice_Line_Item__c> iLIListToUpsert = new List<Invoice_Line_Item__c>();
                    
                    if(!invoiceLineItemList.isEmpty()){
                        Schema.SObjectField ILIftoken = Invoice_Line_Item__c.Sap_Code__c;
                        Database.UpsertResult[] upsertResultList = Database.upsert(
                            invoiceLineItemList,
                            ILIftoken,
                            false
                        );
                        
                        for (Integer i = 0; i < upsertResultList.size(); i++) {
                            if (!upsertResultList[i].isSuccess()) {
                                for (Database.Error err : upsertResultList[i].getErrors()) {
                                    //responseMap.get(iLISapCodeVsInvoiceSapCodeMap.get(invoiceLineItemList[i].Sap_Code__c)).message +
                                    String  jsonResponse = JSON.serialize(
                                        'Error Code: ' +
                                        err.getStatusCode() +
                                        'Error Message: ' +
                                        err.getMessage() +
                                        ' Error Field: ' +
                                        err.fields
                                    );
                                    res.statusCode = 200;
                                    res.responseBody = blob.valueOf(jsonResponse);
                                }
                                //responseMap.get(iLISapCodeVsInvoiceSapCodeMap.get(invoiceLineItemList[i].Sap_Code__c)).Status = 'Error';
                            }
                        }
                    }
                }
            }
            
            res.statusCode = 200;
            String  jsonResponse = '{"RESPONSE": {"SFDC_ID": \"'+demdId+'\", "STATUS": "' + 'Success' + '","MESSAGE":"'+'Demand Created Succesfully\"'+'}}'; //MESSAGE
            res.responseBody = blob.valueOf(jsonResponse);
        }
        catch (Exception e){
            System.debug('---Request----'+ String.valueOf(e.getLineNumber()));
            res.statusCode = 200;
            String  jsonResponse = '{"RESPONSE": {"SFDC_ID": \"'+''+'\", "STATUS": "' + 'Error' + '","MESSAGE":"'+'Exception occured, demand Not created :'+e+'\"}}';
            res.responseBody = blob.valueOf(jsonResponse);
            return;
        }
        
    }
    public static string dateFormat(string str){
        System.debug('Inside1---'+str);
        String dateFull  = String.valueOf(str);
        System.debug('Inside1str---'+str);
        String[] demandDate     = dateFull.split('\\.');
        System.debug('Inside1-demandDate--'+demandDate);
        String dd = demandDate[0]; 
        String mm = demandDate[1];
        String yyyy = demandDate[2];
        string demandcreateDate = yyyy+'-'+mm+'-'+dd;
        System.debug('---demandcreateDate------'+demandcreateDate);
        return demandcreateDate;
    }
    global class ResponseWrapper {
        public String SapCode;
        public String message;
        public String Status;
    }
    
    public class CustomException extends Exception {}
}