dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Amount__c</fullName>
    <formula>Agreement_Value__c -  Total_Amount_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>Pay-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment_Category__c.field-meta.xml
<CustomField>
    <fullName>Payment_Category__c</fullName>
    <label>Payment Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unit Cost</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>GST</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Refundable Interior Deposit</fullName>
            </value>
            <value>
                <fullName>Temporary Electricity Charges</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Security Deposits</fullName>
            </value>
            <value>
                <fullName>Possession/Handover(Other) Charge</fullName>
            </value>
            <value>
                <fullName>Possession/Handover(Other) Charge GST</fullName>
            </value>
            <value>
                <fullName>Security and Share Money</fullName>
            </value>
            <value>
                <fullName>Security and Share Money GST</fullName>
            </value>
            <value>
                <fullName>Transfer Charge</fullName>
            </value>
            <value>
                <fullName>Brokerage Charges</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>GST Avanya Tower A</fullName>
            </value>
            <value>
                <fullName>OCR</fullName>
                <isActive>false</isActive>
                <label>OCR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Bounced</fullName>
                <isActive>false</isActive>
                <label>Bounced</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Cleared</fullName>
                <isActive>false</isActive>
                <label>Cleared</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
            <value>
                <fullName>Wrong Entry</fullName>
                <isActive>false</isActive>
                <label>Wrong Entry</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Line__c/Payment_Line__c.object-meta.xml
<CustomObject>
    <label>Payment Line</label>
    <nameField>
        <displayFormat>PL-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Line__c/fields/Adjusted_against__c.field-meta.xml
<CustomField>
    <fullName>Adjusted_against__c</fullName>
    <label>Adjusted against</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Line__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <referenceTo>Payment_Milestones__c</referenceTo>
    <relationshipLabel>Payment Line</relationshipLabel>
    <relationshipName>Payment_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Line__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment Line</relationshipLabel>
    <relationshipName>Payment_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Line__c/fields/Payment_Category__c.field-meta.xml
<CustomField>
    <fullName>Payment_Category__c</fullName>
    <label>Payment Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Category</valueSetName>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Line__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <label>Milestone name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/GST_Amount1__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount1__c</fullName>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Amount1__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Amount1__c</fullName>
    <label>Milestone Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Status__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Status__c</fullName>
    <label>Milestone Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Amount__c</fullName>
    <formula>Milestone_Amount1__c - Payment_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_GST1__c.field-meta.xml
<CustomField>
    <fullName>Remaining_GST1__c</fullName>
    <label>Remaining GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_GST__c.field-meta.xml
<CustomField>
    <fullName>Remaining_GST__c</fullName>
    <formula>GST_Amount1__c - GST_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining GST</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_Milestone_Amount__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Milestone_Amount__c</fullName>
    <label>Remaining Milestone Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Remaining_Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Unit_Cost__c</fullName>
    <label>Remaining Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment_Milestones__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <label>Sequence No</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/globalValueSets/Payment_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Unit Cost</fullName>
        <default>true</default>
        <label>Unit Cost</label>
    </customValue>
    <customValue>
        <fullName>Stamp Duty</fullName>
    </customValue>
    <customValue>
        <fullName>GST</fullName>
    </customValue>
    <customValue>
        <fullName>TDS</fullName>
    </customValue>
    <customValue>
        <fullName>Parking</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Interest</fullName>
    </customValue>
    <customValue>
        <fullName>Refundable Interior Deposit</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Electricity Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Possession/Handover(Other) Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Possession/Handover(Other) Charge GST</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Security and Share Money</fullName>
    </customValue>
    <customValue>
        <fullName>Security and Share Money GST</fullName>
    </customValue>
    <masterLabel>Payment Category</masterLabel>
</GlobalValueSet>

dynamix/force-app/main/default/classes/CreatePaymentLineMilestoneTransfer.cls
public with sharing class CreatePaymentLineMilestoneTransfer {
    
    @InvocableMethod(label='Create Payment Line Item For Milestone Transfer Booking')
    public static void execute( List<Request> requestLst){
        String bookingId = requestLst[0].bookingId;
        system.debug('===> bookingId ' + bookingId);
        Boolean flag = false;
        
        List<Payment_Line__c> paymentLinesToInsert = new List<Payment_Line__c>();
        Map<Id,Payment_Milestones__c> MapToUpdateMilestone = new Map<Id,Payment_Milestones__c>();
        List<Payment_Milestones__c> ListToUpdateMilestone2 = new List<Payment_Milestones__c>();
        
        List<Payment_Milestones__c> paymentMileStoneList = [SELECT Id,Booking__c,Milestone_Amount1__c,GST_Amount1__c,Remaining_Amount__c,Remaining_Unit_Cost__c, 
                                                            Remaining_GST__c,Remaining_GST1__c,Sequence_No__c,Remaining_Milestone_Amount__c 
                                                            FROM Payment_Milestones__c 
                                                            WHERE Booking__c =: bookingId ORDER BY Milestone_Status__c Asc,Sequence_No__c asc];
        
        Map<Id,Decimal> MapOfPaymentMilestoneAndRemainingAmt = new Map<Id,Decimal>();
        Map<Id,Decimal> MapOfPaymentMilestoneAndRemainingGSTAmt = new Map<Id,Decimal>();
        if(paymentMileStoneList != null && paymentMileStoneList.size() > 0)
        {
            for(Payment_Milestones__c pm : paymentMileStoneList)
            {
                
                MapOfPaymentMilestoneAndRemainingAmt.put(pm.id,pm.Remaining_Unit_Cost__c);
                MapOfPaymentMilestoneAndRemainingGSTAmt.put(pm.id,pm.Remaining_GST__c);
            }
        }
        
        List<Payment__c> payment = [SELECT Id, Amount__c,Booking__c,Payment_Category__c,Payment_Status__c FROM Payment__c WHERE Booking__c =: bookingId ORDER BY CreatedDate];
        
        if(payment!=null && payment.size()>0){
            for(Payment__c pay : payment)
            {
                for(Payment_Milestones__c paymentMilestone : paymentMileStoneList)
                {
                    if(pay.Amount__c==0)
                    {
                        break;
                    }
                    Decimal RemainAmount = MapOfPaymentMilestoneAndRemainingAmt.get(paymentMilestone.id);
                    Decimal GSTRemainAmount = MapOfPaymentMilestoneAndRemainingGSTAmt.get(paymentMilestone.id);
                    if(pay.Payment_Category__c.containsignorecase('Unit Cost'))
                    {
                        system.debug('===> paymentMilestone.Remaining_Amount__c ' + MapOfPaymentMilestoneAndRemainingAmt.get(paymentMilestone.id));
                        system.debug('===> pay.Amount__c ' + pay.Amount__c);
                        if(RemainAmount > 0 && RemainAmount != null){
                            if(RemainAmount >= pay.Amount__c )
                            {
                                system.debug('in if');
                                Payment_Line__c paymentLine = new Payment_Line__c();
                                paymentLine.Amount__c = pay.Amount__c;
                                paymentLine.Milestone__c = paymentMilestone.Id;
                                paymentLine.Payment__c = pay.Id;
                                paymentLine.Payment_Category__c = pay.Payment_Category__c;
                                paymentLine.Payment_Status__c = pay.Payment_Status__c;
                                paymentLine.Adjusted_against__c = 'Unit Cost';
                                paymentLinesToInsert.add(paymentLine);
                                RemainAmount-=pay.Amount__c;
                                MapOfPaymentMilestoneAndRemainingAmt.put(paymentMilestone.id,RemainAmount);
                                paymentMilestone.Remaining_Milestone_Amount__c = paymentMilestone.Remaining_Milestone_Amount__c - pay.Amount__c;
                                paymentMilestone.Remaining_Unit_Cost__c = paymentMilestone.Remaining_Unit_Cost__c - pay.Amount__c;
                                MapToUpdateMilestone.put(paymentMilestone.Id,paymentMilestone);
                                break;
                            }
                            else{
                                system.debug('in else');
                                system.debug('=======> in else ' + pay.Amount__c );
                                pay.Amount__c = pay.Amount__c - RemainAmount ;
                                Payment_Line__c paymentLine = new Payment_Line__c();
                                paymentLine.Amount__c = RemainAmount ;
                                paymentLine.Milestone__c = paymentMilestone.Id;
                                paymentLine.Payment__c = pay.Id;
                                paymentLine.Payment_Category__c = pay.Payment_Category__c;
                                paymentLine.Payment_Status__c = pay.Payment_Status__c;
                                paymentLine.Adjusted_against__c = 'Unit Cost';
                                paymentLinesToInsert.add(paymentLine);
                                RemainAmount = 0;
                                MapOfPaymentMilestoneAndRemainingAmt.put(paymentMilestone.id,RemainAmount);
                                paymentMilestone.Remaining_Milestone_Amount__c = paymentMilestone.Remaining_Milestone_Amount__c - paymentMilestone.Remaining_Unit_Cost__c;
                                paymentMilestone.Remaining_Unit_Cost__c = 0;
                                MapToUpdateMilestone.put(paymentMilestone.Id,paymentMilestone);
                            }
                        }
                    }
                    else if(pay.Payment_Category__c.containsignorecase('GST'))
                    {
                        system.debug('===> paymentMilestone.Remaining_GST__c ' + MapOfPaymentMilestoneAndRemainingGSTAmt.get(paymentMilestone.id));
                        system.debug('===> pay.Amount__c ' + pay.Amount__c);
                        
                        if(GSTRemainAmount > 0 && GSTRemainAmount != null){
                            if(GSTRemainAmount >= pay.Amount__c )
                            {
                                Payment_Line__c paymentLine = new Payment_Line__c();
                                paymentLine.Amount__c = pay.Amount__c;
                                paymentLine.Milestone__c = paymentMilestone.Id;
                                paymentLine.Payment__c = pay.Id;
                                paymentLine.Payment_Category__c = pay.Payment_Category__c;
                                paymentLine.Payment_Status__c = pay.Payment_Status__c;
                                paymentLine.Adjusted_against__c = 'GST Amount';
                                paymentLinesToInsert.add(paymentLine);
                                GSTRemainAmount-=pay.Amount__c;
                                MapOfPaymentMilestoneAndRemainingGSTAmt.put(paymentMilestone.id,GSTRemainAmount);
                                paymentMilestone.Remaining_GST1__c = paymentMilestone.Remaining_GST1__c - pay.Amount__c;
                                MapToUpdateMilestone.put(paymentMilestone.Id,paymentMilestone);
                                break;
                            }
                            else{
                                pay.Amount__c = pay.Amount__c - GSTRemainAmount;
                                Payment_Line__c paymentLine = new Payment_Line__c();
                                paymentLine.Amount__c = GSTRemainAmount;
                                paymentLine.Milestone__c = paymentMilestone.Id;
                                paymentLine.Payment__c = pay.Id;
                                paymentLine.Payment_Category__c = pay.Payment_Category__c;
                                paymentLine.Payment_Status__c = pay.Payment_Status__c;
                                paymentLine.Adjusted_against__c = 'GST Amount';
                                paymentLinesToInsert.add(paymentLine); 
                                GSTRemainAmount = 0;
                                MapOfPaymentMilestoneAndRemainingGSTAmt.put(paymentMilestone.id,GSTRemainAmount);
                                paymentMilestone.Remaining_GST1__c = 0;
                                MapToUpdateMilestone.put(paymentMilestone.Id,paymentMilestone);            
                            }
                        }
                    }
                }
            }
            if(!paymentLinesToInsert.isEmpty()){
                system.debug('===> paymentLinesToInsert'  + paymentLinesToInsert);
                system.debug('===> paymentLinesToInsert size'  + paymentLinesToInsert.size());
                upsert paymentLinesToInsert; 
            }
            if(!MapToUpdateMilestone.isEmpty()){
                update MapToUpdateMilestone.values();
            }
        }
    }
    public class Request {
        @InvocableVariable(label='Booking Id' required=true)
        public String bookingId;
    }
}