dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <label>Agreement Value</label>
    <summarizedField>Price_Details__c.Amount_after_discount__c</summarizedField>
    <summaryFilterItems>
        <field>Price_Details__c.Charge_Group__c</field>
        <operation>contains</operation>
        <value>Agreement</value>
    </summaryFilterItems>
    <summaryForeignKey>Price_Details__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Booking_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Booking_Owner_Email__c</fullName>
    <formula>Owner:User.Email</formula>
    <label>Booking Owner Email</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Booking_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Booking_Owner_Name__c</fullName>
    <formula>Owner:User.FirstName + &quot; &quot; +  Owner:User.LastName</formula>
    <label>Booking Owner Name</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <label>Registration Date</label>
    <type>Date</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Suggested_Property__c.field-meta.xml
<CustomField>
    <fullName>Related_Suggested_Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Suggested Property</label>
    <referenceTo>Suggested_Property__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower Name</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <formula>Related_Suggested_Property__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Number</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Tower__c/fields/Tower_Initials__c.field-meta.xml
<CustomField>
    <fullName>Tower_Initials__c</fullName>
    <label>Tower Initials</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/classes/GeneratePossessionLetter.cls
public without sharing class GeneratePossessionLetter {
    public boolean data;
    @InvocableMethod(label='Generate Possession Letter')
    public static List<String> execute( List<Requests> requestLst){
		System.debug('----requestLst'+requestLst);
        return new List<String> {
            generateCS(requestLst[0].bookingId)
                };
    }

    public static String generateCS(String bookingId){
        
        ContentVersion conVer;
        list<ContentDocumentLink> contentDocList = new list<ContentDocumentLink>();
        list<ContentVersion> ContentVersionList =new  list<ContentVersion>();
           list<ContentVersion> ContentVersionLetterOfAmenitieslist =new  list<ContentVersion>();
        String contentId='';
        string whereCausLike;
        list<Id> ContentDocId = new list<Id>();
        List<user> collaborators = new List<user>();
        list<ContentDocumentLink> conDocList = new list<ContentDocumentLink>();
        list<ContentDocumentLink> conDocListC = new list<ContentDocumentLink>();
        Booking__c booking = [select Id,Tower_Name__c,Related_Opportunity__c,Registration_Date__c,Tower_Name__r.Name,
                           Tower_Name__r.Building_Type__c,Tower_Name__r.Tower_Initials__c,Project_Name__c,Primary_Applicant__c,
                           Primary_Applicant__r.Name,Related_Suggested_Property__c,Agreement_Value__c,Booking_Date__c,
                           Booking_Owner_Email__c,OwnerId,Booking_Owner_Name__c,Unit_Number__c,Name
                           from Booking__c where Id =: bookingId];

       
        List<ContentDocumentLink> cDLLst = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId =: bookingId];
        
        PageReference refOfPossessionLetter = Page.PossessionLetter;
        refOfPossessionLetter.getParameters().put('id',booking.id);
        PageReference refOfPendingCommonAmenities = Page.LetterPendingCommonAmenities;
        refOfPendingCommonAmenities.getParameters().put('id',booking.id);
        
        Blob body; 
        if(Test.isRunningTest()){
            body = Blob.valueOf('Possession Letter');
        }
        else{
            body = refOfPossessionLetter.getContent();
        }
        
        Blob bodyLetterPendingCommonAmenities; 
        if(Test.isRunningTest()){
            bodyLetterPendingCommonAmenities = Blob.valueOf('Letter Pending Common Amenities');
        }
        else{
            bodyLetterPendingCommonAmenities = refOfPendingCommonAmenities.getContent();
        }
        
        String unitName;
        String whereCausLikebodyLetterPendingCommonAmenities;
        if(booking.Unit_Number__c.length() < 4)
        {
             unitName = 0 + booking.Unit_Number__c;
        }
        else{
             unitName = booking.Unit_Number__c;
        }
        if(booking.Tower_Name__r.Name <> null && unitName <> null && booking.Name <> null)
        {
          whereCausLike = 'Possession Letter/'+booking.Tower_Name__r.Name.left(3) + '/' + unitName  +'/'+'%';  
          whereCausLikebodyLetterPendingCommonAmenities = 'Letter Pending Common Amenities/'+booking.Tower_Name__r.Name.left(3) + '/' + unitName  +'/'+'%'; 
        } 
        System.debug('whereCausLike'+whereCausLike); 
        contentDocList =[select id,ContentDocumentId,LinkedEntityId from ContentDocumentLink where LinkedEntityId =: bookingId];
            system.debug('===> contentDocList ' + contentDocList );
            if(contentDocList.size()>0)
            {
                for(ContentDocumentLink cd :contentDocList)
                {   
                    ContentDocId.add(cd.ContentDocumentId);
                }
                ContentVersionlist =[SELECT ContentDocumentId,VersionData,isMajorVersion,PathOnClient,CreatedDate FROM ContentVersion where Title Like: whereCausLike and ContentDocumentId IN :ContentDocId];
                ContentVersionLetterOfAmenitieslist =[SELECT ContentDocumentId,VersionData,isMajorVersion,PathOnClient,CreatedDate FROM ContentVersion where Title Like: whereCausLikebodyLetterPendingCommonAmenities and ContentDocumentId IN :ContentDocId];

            }
            if(ContentVersionlist.size()>0)
            {
                conVer =new ContentVersion(); 
                conVer.ContentLocation = 'S'; 
                conVer.PathOnClient = 'Possession Letter/'+booking.Tower_Name__r.Name.left(3) + '/' + unitName  + cDLLst.size() +'.pdf'; 
                conVer.Title = 'Possession Letter/'+booking.Tower_Name__r.Name.left(3) + '/' + unitName + cDLLst.size() +'.pdf';
                conVer.VersionData = body;
                conVer.SObjectType__c = 'Booking__c';
                conVer.Document_Type__c = 'Handover of Possession Letter';
                conVer.ContentDocumentId=ContentVersionlist[0].ContentDocumentId;
                insert conVer;
                system.debug('test'+conVer);
                contentId = conVer.ContentDocumentId;
                  
            }
            else
            {
                conVer = new ContentVersion();
                conVer.ContentLocation = 'S'; 
                conVer.PathOnClient = 'Possession Letter/'+booking.Tower_Name__r.Name.left(3) + '/' + unitName  + cDLLst.size() +'.pdf'; 
                conVer.Title = 'Possession Letter/'+booking.Tower_Name__r.Name.left(3) + '/' + unitName   + cDLLst.size() +'.pdf';
                conVer.VersionData = body;
                conVer.SObjectType__c = 'Booking__c';
                conVer.Document_Type__c = 'Handover of Possession Letter';
                conVer.isMajorVersion=false;
                Insert conVer;
                ContentVersion contentverlink = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :conVer.Id LIMIT 1];
              
                        ContentDocumentLink conDocLink = New ContentDocumentLink();
                        conDocLink.LinkedEntityId = bookingId; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
                        conDocLink.ContentDocumentId = contentverlink.ContentDocumentId;  //ContentDocumentId Id from ContentVersion
                        conDocLink.shareType = 'V';
                        conDocList.add(conDocLink);
                        
                       /* for(user uId : collaborators)
                        {
                        ContentDocumentLink conDocLinkC = New ContentDocumentLink();
                        conDocLinkC.LinkedEntityId = uId.id; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
                        conDocLinkC.ContentDocumentId = contentverlink.ContentDocumentId;  //ContentDocumentId Id from ContentVersion
                        conDocLinkC.shareType = 'C';
                        conDocList.add(conDocLinkC); 
                        } */                            
                insert conDocList; 
                contentId = contentverlink.ContentDocumentId;
            }
         if(ContentVersionLetterOfAmenitieslist.size()>0)
            {
                conVer =new ContentVersion(); 
                conVer.ContentLocation = 'S'; 
                conVer.PathOnClient = 'Letter Pending Common Amenities/'+booking.Tower_Name__r.Name.left(3) + '/' + unitName  + cDLLst.size() +'.pdf'; 
                conVer.Title = 'Letter Pending Common Amenities/'+booking.Tower_Name__r.Name.left(3) + '/' + unitName + cDLLst.size() +'.pdf';
                conVer.VersionData = bodyLetterPendingCommonAmenities;
                conVer.SObjectType__c = 'Booking__c';
                conVer.Document_Type__c = 'Letter Pending Common Amenities';
                conVer.ContentDocumentId=ContentVersionlist[0].ContentDocumentId;
                insert conVer;
                system.debug('test'+conVer);
                contentId = conVer.ContentDocumentId;
                  
            }
            else
            {
                conVer = new ContentVersion();
                conVer.ContentLocation = 'S'; 
                conVer.PathOnClient = 'Letter Pending Common Amenities/'+booking.Tower_Name__r.Name.left(3) + '/' + unitName  + cDLLst.size() +'.pdf'; 
                conVer.Title = 'Letter Pending Common Amenities/'+booking.Tower_Name__r.Name.left(3) + '/' + unitName   + cDLLst.size() +'.pdf';
                conVer.VersionData = bodyLetterPendingCommonAmenities;
                conVer.SObjectType__c = 'Booking__c';
                conVer.Document_Type__c = 'Letter Pending Common Amenities';
                conVer.isMajorVersion=false;
                Insert conVer;
                ContentVersion contentverlink = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :conVer.Id LIMIT 1];
              
                        ContentDocumentLink conDocLink = New ContentDocumentLink();
                        conDocLink.LinkedEntityId = bookingId; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
                        conDocLink.ContentDocumentId = contentverlink.ContentDocumentId;  //ContentDocumentId Id from ContentVersion
                        conDocLink.shareType = 'V';
                        conDocList.add(conDocLink);
                        
                       /* for(user uId : collaborators)
                        {
                        ContentDocumentLink conDocLinkC = New ContentDocumentLink();
                        conDocLinkC.LinkedEntityId = uId.id; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
                        conDocLinkC.ContentDocumentId = contentverlink.ContentDocumentId;  //ContentDocumentId Id from ContentVersion
                        conDocLinkC.shareType = 'C';
                        conDocList.add(conDocLinkC); 
                        } */                            
                upsert conDocList; 
                contentId = contentverlink.ContentDocumentId;
            }
            return contentId;
    }

    public class Requests {
        @InvocableVariable(label='Booking Id' required=true)
        public String bookingId;
    }
}