dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Property_Name__c</fullName>
    <formula>Related_Suggested_Property__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Name</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower Name</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Opportunity/fields/Project_No_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Project_No_of_Days__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>180 Days</fullName>
                <default>true</default>
                <label>180 Days</label>
            </value>
            <value>
                <fullName>30 Days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/classes/GenerateAFSDocuments.cls
public class GenerateAFSDocuments {
    
    @InvocableMethod(label='Generate Agreement of Sale Documents')
    public static List<String> execute(List<Request> Requests){
        ContentVersion conVer;
        String VFPageName;
        list<ContentDocumentLink> contentDocList = new list<ContentDocumentLink>();
        list<ContentVersion> ContentVersionList =new  list<ContentVersion>();
        String contentId='';
        list<Id> ContentDocId = new list<Id>();
        list<ContentDocumentLink> conDocList = new list<ContentDocumentLink>();
        booking__c bookingobj = [select id, Property_Name__c,Project_Name__r.name,Related_Opportunity__r.Project_No_of_Days__c,Tower_Name__r.Name,Tower_Name__c,Project_Name__c from Booking__c where id=: Requests[0].bookingId];
        
        if(bookingobj != null){
            
            //AFS For Parkwood 
            if(bookingobj.Project_Name__r.Name == System.Label.Parkwoods_project_name){
                
                String pageName = 'ParkwoodsBuildingD5';
                
                if(bookingobj.Related_Opportunity__r.Project_No_of_Days__c == '180 Days'){
                    
                    String vfpage = pageName+bookingobj.Related_Opportunity__r.Project_No_of_Days__c;
                    VFPageName = vfpage.deleteWhitespace();
                    System.debug('Page Name 180 Days--: '+vfpage);
                    system.debug('Remove Spaces-->'+vfpage.deleteWhitespace());
                    
                }else if(bookingobj.Related_Opportunity__r.Project_No_of_Days__c == '30 Days'){
                    
                    String vfpage = pageName+bookingobj.Related_Opportunity__r.Project_No_of_Days__c;
                    VFPageName = vfpage.deleteWhitespace();
                    
                    system.debug('Remove Spaces-->'+vfpage.deleteWhitespace());
                    System.debug('Page Name for 30 Days--: '+vfpage);
                }
                
                
            }
            // For Divum
            else if(bookingobj.Project_Name__r.Name == System.Label.Divum_Project_Name){
                
                String pageName = 'Divum';
                pageName += '180Days';
                
                VFPageName =  pageName.deleteWhitespace();               
                
                
            }
            
            // For Avanya
            /* else if(bookingobj.Project_Name__r.Name == System.Label.Avanya_Project_Name){

String pageName = 'Avanya';

if(bookingobj.Tower_Name__r.Name == 'Tower A'){

String vfpage = pageName+bookingobj.Tower_Name__r.Name;
VFPageName = vfpage.deleteWhitespace();

}
else if(bookingobj.Tower_Name__r.Name == 'Tower B'){

String vfpage = pageName+bookingobj.Tower_Name__r.Name;
VFPageName = vfpage.deleteWhitespace();

}


}*/
            
            else if(bookingobj.Project_Name__r.Name == 'Avanya Tower A' || bookingobj.Project_Name__r.Name =='Avanya Tower C'){                
                String pageName = 'AvanyaTowerA';
                VFPageName=pageName;
            }
            else if(bookingobj.Tower_Name__r.Name ==  'Avanya Tower B'){
                String pageName = 'AvanyaTowerB';    
                VFPageName=pageName;
            }                            
        }
        String url = '/apex/'+VFPageName+'?id='+Requests[0].bookingId;
        PageReference ref = new PageReference(url);
        Blob body;
        
        if(Test.isRunningTest()) { 
            body = blob.valueOf('Unit.Test');
        } else { 
            body = ref.getContent();
        }
        
        
        contentDocList =[select id,ContentDocumentId,LinkedEntityId from ContentDocumentLink where LinkedEntityId=:Requests[0].bookingId];
        
        if(contentDocList.size()>0)
        {
            for(ContentDocumentLink cd :contentDocList)
            {   
                ContentDocId.add(cd.ContentDocumentId);
            }
            ContentVersionlist =[SELECT ContentDocumentId,VersionData,isMajorVersion,PathOnClient,CreatedDate FROM ContentVersion where PathOnClient ='Agreement of Sale.pdf' and ContentDocumentId IN :ContentDocId];
        }
        
        if(ContentVersionlist.size()>0)
        {
            conVer =new ContentVersion(); 
            conVer.ContentLocation = 'S'; 
            conVer.PathOnClient = 'Agreement of Sale' + '.pdf'; 
            conVer.Title = 'Agreement of Sale'+' - '+bookingobj.Property_Name__c +'.pdf';
            conVer.VersionData = body;
            conVer.SObjectType__c = 'Booking__c';
            conVer.Document_Type__c = 'Agreement Sale';
            conVer.ContentDocumentId=ContentDocId[0];
            // system.debug('test'+conVer);
            insert conVer;
            system.debug('test'+conVer);
            contentId = conVer.ContentDocumentId;
            
        }
        else
        {
            conVer = new ContentVersion();
            conVer.ContentLocation = 'S'; 
            conVer.PathOnClient = 'Agreement of Sale' + '.pdf'; 
            conVer.Title = 'Agreement of Sale'+' - '+bookingobj.Property_Name__c +'.pdf';
            conVer.VersionData = body;
            conVer.SObjectType__c = 'Booking__c';
            conVer.Document_Type__c = 'Agreement Sale';
            conVer.isMajorVersion=false;
            Insert conVer;
            list<ContentVersion> conVerList= [SELECT ContentDocumentId,CreatedDate FROM ContentVersion WHERE Id =:conVer.Id ];
            If(conVerList.size()>0)
            {
                for(ContentVersion con :conVerList)
                {
                    ContentDocumentLink conDocLink = New ContentDocumentLink();
                    conDocLink.LinkedEntityId = Requests[0].bookingId; // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
                    conDocLink.ContentDocumentId = con.ContentDocumentId;  //ContentDocumentId Id from ContentVersion
                    conDocLink.shareType = 'V';
                    conDocList.add(conDocLink);
                }
            }    
            insert conDocList;
            contentId = conVerList[0].ContentDocumentId;
            system.debug('bookingobj.id=='+bookingobj.id);
            system.debug('System.Label.SMSaggrement=='+System.Label.SMSaggrement);
            SendSMS.sendSMSfun(bookingobj.id,System.Label.SMSaggrement);
            SendWhatsappMsg.sendwhsms(System.Label.Whatsapp_Agreement,bookingobj.Id,'');
        }
        
        return new List<String>{contentId};
            }
    
    public class Request {
        @InvocableVariable(label='Booking Id' required=true)
        public id bookingId;
    }
    
}