dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Booking_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Booking_Owner_Email__c</fullName>
    <formula>Owner:User.Email</formula>
    <label>Booking Owner Email</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Booking_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Booking_Owner_Name__c</fullName>
    <formula>Owner:User.FirstName + &quot; &quot; +  Owner:User.LastName</formula>
    <label>Booking Owner Name</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Name_Formulla__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name_Formulla__c</fullName>
    <formula>IF( Primary_Applicant__r.FirstName &lt;&gt; null &amp;&amp;  Primary_Applicant__r.FirstName &lt;&gt; &apos;&apos;,  Primary_Applicant__r.FirstName+&apos; &apos;+ Primary_Applicant__r.LastName, Primary_Applicant__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Applicant Name Formulla</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <formula>Project_Name__r.Project_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Email</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Property_Name__c</fullName>
    <formula>Related_Suggested_Property__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Property Name</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower Name</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/communicat_o__Registered_Template__mdt/communicat_o__Registered_Template__mdt.object-meta.xml
<CustomObject>
    <label>Registered Template</label>
    <pluralLabel>Registered Templates</pluralLabel>
</CustomObject>

dynamix/force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SObjectType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>PAN Card</fullName>
            </value>
            <value>
                <fullName>Approved Cost Sheet</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Other Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Agreement Sale</fullName>
            </value>
            <value>
                <fullName>Architecture Certificate</fullName>
            </value>
            <value>
                <fullName>Allotment</fullName>
            </value>
            <value>
                <fullName>Payment Receipt</fullName>
            </value>
            <value>
                <fullName>Agreement Checklist</fullName>
            </value>
            <value>
                <fullName>Name Change Note</fullName>
            </value>
            <value>
                <fullName>KIT</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Sanction Letter</fullName>
            </value>
            <value>
                <fullName>Index II Document</fullName>
            </value>
            <value>
                <fullName>Flat Cancellation</fullName>
            </value>
            <value>
                <fullName>Flat Refund</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
                <label>TDS Challan</label>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Bank NOC</fullName>
            </value>
            <value>
                <fullName>Lien Letter</fullName>
            </value>
            <value>
                <fullName>Brokerage Invoice</fullName>
            </value>
            <value>
                <fullName>CheckList – Booking Checklist</fullName>
            </value>
            <value>
                <fullName>CheckList – Cost Change Note</fullName>
            </value>
            <value>
                <fullName>Checklist – Stamp Duty Payment</fullName>
            </value>
            <value>
                <fullName>CheckList – KIT Handover</fullName>
            </value>
            <value>
                <fullName>CheckList – Excess Amount Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/ContentVersion/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Booking__c</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Project_Progress__c</fullName>
            </value>
            <value>
                <fullName>Bank_Loan_Details__c</fullName>
            </value>
            <value>
                <fullName>Builder_Organisation__c</fullName>
            </value>
            <value>
                <fullName>Payment_Milestones__c</fullName>
            </value>
            <value>
                <fullName>Broker_Payment__c</fullName>
            </value>
            <value>
                <fullName>Property__c</fullName>
            </value>
            <value>
                <fullName>Demand__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dynamix/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Project__c/fields/Project_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Email__c</fullName>
    <label>Project Email</label>
    <type>Email</type>
</CustomField>

dynamix/force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/classes/GenerateRefundletter.cls
public with sharing class GenerateRefundletter{
    
    @InvocableMethod(label='Generate Refund letter')
    public static List<String> execute(List<Request> Requests){
        ContentVersion conVer;
        ContentVersion conVerRnote;
        list<ContentDocumentLink> conDocList = new list<ContentDocumentLink>();
        
        booking__c bookingobj = [select id,Name,Project_Name__r.Project_Email__c,Tower_Name__r.Name,Primary_Applicant__c,Property_Name__c,Primary_Applicant__r.PersonMobilePhone,Primary_Applicant_Name_Formulla__c,Booking_Owner_Name__c,Booking_Owner_Email__c from Booking__c where id=: Requests[0].bookingId];
        Account acc = [select id,personcontactid from Account where id=:bookingobj.Primary_Applicant__c];
        List<contact> conList = [select id,phone,AccountID from contact where AccountID=:bookingobj.Primary_Applicant__c ];
        PageReference refRnote;
        Blob bodyRnote;
        system.debug('closedReason=='+Requests[0].closedReason);
        system.debug('PaymentType=='+Requests[0].PaymentType);
        system.debug('bookingId=='+Requests[0].bookingId);
        system.debug('paymentId=='+Requests[0].paymentId);
        
        if(Requests[0].closedReason=='Cancelled' && Requests[0].PaymentType=='Cheque')
        {
            refRnote =  page.Cancellation_Refund_Letter_Cheque;
            refRnote.getParameters().put('payid', Requests[0].paymentId);
            system.debug('acc.personcontactid=='+acc.personcontactid);
            system.debug('System.Label.Refund_Note_Cancellation=='+System.Label.Refund_Note_Cancellation);
            system.debug('Requests[0].paymentId=='+Requests[0].paymentId);
            SendEmailClass.SendEmail(acc.personcontactid ,System.Label.Refund_Note_Cancellation,Requests[0].paymentId,bookingobj.Project_Name__r.Project_Email__c);
            SendSMSclass.SendSMS(Requests[0].bookingId,Requests[0].paymentId,System.Label.SMS_Cancellation_Booking_Cheque);
            //  SendSMS.sendSMSforPayment(Requests[0].bookingId,Requests[0].paymentId,System.Label.SMS_Cancellation_Booking_Cheque); 
            SendWhatsappMsg.sendwhsmsForPayment(System.Label.Whatsapp_Cheque_Refund_Details_Cancellat,bookingobj.Id,Requests[0].paymentId);
        }
        else if(Requests[0].closedReason=='Cancelled' && Requests[0].PaymentType=='NEFT/ RTGS/ IMPS')
        {
            refRnote =  page.Cancellation_Refund_Letter_RTGS;
            // refRnote.getParameters().put('id',Requests[0].bookingId);
            refRnote.getParameters().put('payid', Requests[0].paymentId);
            system.debug('acc.personcontactid=='+acc.personcontactid);
            system.debug('System.Label.Refund_Note_Cancellation=='+System.Label.Refund_Note_Cancellation);
            system.debug('Requests[0].paymentId=='+Requests[0].paymentId);
            SendEmailClass.SendEmail(acc.personcontactid ,System.Label.Refund_Note_Cancellation,Requests[0].paymentId,bookingobj.Project_Name__r.Project_Email__c);
            SendSMSclass.SendSMS(Requests[0].bookingId,Requests[0].paymentId,System.Label.SMS_Cancellation_Booking_RTGS);
            //  SendSMS.sendSMSforPayment(Requests[0].bookingId,Requests[0].paymentId,System.Label.SMS_Cancellation_Booking_RTGS);
            SendWhatsappMsg.sendwhsmsForPayment(System.Label.WhatsApp_Rtgs_refund_cancellation,bookingobj.Id,Requests[0].paymentId);
        }
        else if(Requests[0].closedReason=='Terminated' && Requests[0].PaymentType=='Cheque')
        {
            refRnote =  page.Termination_Refund_Letter_Cheque;
            //refRnote.getParameters().put('id',Requests[0].bookingId);
            refRnote.getParameters().put('payid', Requests[0].paymentId);
            system.debug('acc.personcontactid=='+acc.personcontactid);
            system.debug('System.Label.Refund_Note_Cancellation=='+System.Label.Refund_Note_Cancellation);
            system.debug('Requests[0].paymentId=='+Requests[0].paymentId);
            SendEmailClass.SendEmail(acc.personcontactid ,System.Label.Refund_Note_Termination,Requests[0].paymentId,bookingobj.Project_Name__r.Project_Email__c);
            SendSMSclass.SendSMS(Requests[0].bookingId,Requests[0].paymentId,System.Label.SMS_Termination_Booking_Cheque); 
            //    SendSMS.sendSMSforPayment(Requests[0].bookingId,Requests[0].paymentId,System.Label.SMS_Termination_Booking_Cheque);
            SendWhatsappMsg.sendwhsmsForPayment(System.Label.Whatsapp_Cheque_Refund_Details_Terminati,bookingobj.Id,Requests[0].paymentId);
        }
        else if(Requests[0].closedReason=='Terminated' && Requests[0].PaymentType=='NEFT/ RTGS/ IMPS')
        {
            refRnote =  page.Termination_Refund_Letter_RTGS;
            // refRnote.getParameters().put('id',Requests[0].bookingId);
            refRnote.getParameters().put('payid', Requests[0].paymentId);
            system.debug('acc.personcontactid=='+acc.personcontactid);
            system.debug('System.Label.Refund_Note_Cancellation=='+System.Label.Refund_Note_Cancellation);
            system.debug('Requests[0].paymentId=='+Requests[0].paymentId);
            SendEmailClass.SendEmail(acc.personcontactid ,System.Label.Refund_Note_Termination,Requests[0].paymentId,bookingobj.Project_Name__r.Project_Email__c);  
            SendSMSclass.SendSMS(Requests[0].bookingId,Requests[0].paymentId,System.Label.SMS_Termination_Booking_RTGS); 
            //   SendSMS.sendSMSforPayment(Requests[0].bookingId,Requests[0].paymentId,System.Label.SMS_Termination_Booking_RTGS);
            SendWhatsappMsg.sendwhsmsForPayment(System.Label.WhatsApp_RTgs_refund_termina,bookingobj.Id,Requests[0].paymentId);
        }
        
        
        
        
        
        if(Test.isRunningTest()){
            bodyRnote = Blob.valueOf('Refund Note');
        }
        else{
            bodyRnote = refRnote.getContent();
        }
        
        conVerRnote = new ContentVersion();
        conVerRnote.ContentLocation = 'S'; // to use S specify this document is in Salesforce, to use E for external files
        conVerRnote.PathOnClient = 'Refund Note/'+String.valueof(bookingobj.Tower_Name__r.Name)+'/'+String.valueof(bookingobj.Property_Name__c)+'.pdf'; 
        conVerRnote.Title = 'Refund Note/'+String.valueof(bookingobj.Tower_Name__r.Name)+'/'+String.valueof(bookingobj.Property_Name__c)+'.pdf'; 
        conVerRnote.VersionData = bodyRnote;
        conVerRnote.SObjectType__c = 'Booking__c';
        conVerRnote.Document_Type__c = 'Flat Refund';
        insert conVerRnote;
        system.debug('===> conVerRnote '+ conVerRnote);
        list<ContentVersion> conVerList= [SELECT ContentDocumentId,CreatedDate FROM ContentVersion WHERE Id =: conVerRnote.Id order by CreatedDate desc];
        system.debug('===> conVerList'+ conVerList);
        If(conVerList.size()>0)
        {
            for(ContentVersion con :conVerList)
            {
                ContentDocumentLink conDocLink = New ContentDocumentLink();
                conDocLink.LinkedEntityId = Requests[0].bookingId; 
                conDocLink.ContentDocumentId = con.ContentDocumentId;  
                conDocLink.shareType = 'V';
                conDocList.add(conDocLink);
            }
        }    
        insert conDocList;
        system.debug('===> conDocList'+ conDocList);
        
        //For Send WhatsApp Message       
        communicat_o__Registered_Template__mdt regWhatEmailTemp=[Select Id,QualifiedApiName,label From communicat_o__Registered_Template__mdt Where label=:'WhatsApp Booking Refund' Limit 1];
        System.debug('regWhatEmailTemp:'+regWhatEmailTemp);
        if(regWhatEmailTemp!=null){
            String recipientAddress=bookingobj.Primary_Applicant__r.PersonMobilePhone;
            String recipientId=bookingobj.Primary_Applicant__c;
            String emailTemplateId=String.valueOf(regWhatEmailTemp.Id).substring(0, 15);
            String relatedToId=bookingobj.Id;
            System.debug('emailTemplateId:'+emailTemplateId);
            if(recipientAddress!=null && recipientId!=null && emailTemplateId!=null){
                SendWhatsAppMessageUtility.SendMessage(recipientAddress, recipientId, emailTemplateId,relatedToId);
            }
        }
        //for Send SMS
        EmailTemplate smsEmailTemp=[Select Id,Name,HtmlValue From EmailTemplate Where Name='SMS Booking Refund' Limit 1];
        if(smsEmailTemp!=null && bookingobj.Primary_Applicant__r.PersonMobilePhone!=null){
            String templateBody=smsEmailTemp.HtmlValue;
            templateBody=templateBody.stripHtmlTags();
            String mobileNumber=bookingobj.Primary_Applicant__r.PersonMobilePhone;
            templateBody = templateBody.replace('{{{Booking__c.Primary_Applicant_Name_Formulla__c}}}', bookingobj.Primary_Applicant_Name_Formulla__c);
            templateBody = templateBody.replace('{{{Booking__c.Name}}}', bookingobj.Name);
            templateBody = templateBody.replace('{{{Booking__c.Booking_Owner_Name__c}}}', bookingobj.Booking_Owner_Name__c);
            templateBody = templateBody.replace('{{{Booking__c.Booking_Owner_Email__c}}}', bookingobj.Booking_Owner_Email__c);
            SendSMSUtility.sendSMS(templateBody,mobileNumber,'DYMXGP');
        }
        return new List<String>{conVerList[0].ContentDocumentId};
           
            }
    
    public class Request {
        @InvocableVariable(label='Booking Id' required=true)
        public id bookingId;
        
        @InvocableVariable(label='Payment Id' required=true)
        public String paymentId;
        
        @InvocableVariable(label='closed Reson' required=true)
        public String closedReason;
        
        @InvocableVariable(label='Payment Type' required=true)
        public String PaymentType;
        
    }
}