dynamix/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Booking__c/fields/Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Booking__c/fields/Transferred_To_Booking__c.field-meta.xml
<CustomField>
    <fullName>Transferred_To_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transferred To Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Co_Applicant__c/Co_Applicant__c.object-meta.xml
<CustomObject>
    <label>Co-Applicant</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Applicant</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Co_Applicant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Co-Applicant</relationshipLabel>
    <relationshipName>Co_Applicant</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Co_Applicant__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Co-Applicant</relationshipLabel>
    <relationshipName>Co_Applicant</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>Pay-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

dynamix/force-app/main/default/objects/Payment__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payment</relationshipLabel>
    <relationshipName>Payment</relationshipName>
    <type>Lookup</type>
</CustomField>

dynamix/force-app/main/default/objects/Payment__c/fields/Primary_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant__c</fullName>
    <formula>IF( Booking__r.Primary_Applicant__r.FirstName &lt;&gt; null &amp;&amp; Booking__r.Primary_Applicant__r.FirstName &lt;&gt; &apos;&apos;,Booking__r.Primary_Applicant__r.FirstName+&apos; &apos;+Booking__r.Primary_Applicant__r.LastName , Booking__r.Primary_Applicant__r.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Applicant</label>
    <type>Text</type>
</CustomField>

dynamix/force-app/main/default/classes/SendWhatsappMsg.cls
public class SendWhatsappMsg {
    @InvocableMethod(label='Send WhatsappMsg class')
    public static void sendSms(List<sendSMSInvocableRequest> requests){
        
         String EmailTemplateID = requests[0].emailTemplateID;
         String bookingID = requests[0].bookingID;
         String OtherID = requests[0].recipientId;
        
         sendwhsms(EmailTemplateID,bookingID,OtherID);
        }
    
    @future(callout=true)
    public static void sendwhsms(string EmailTemplateID ,string bookingID ,string OtherID)
    {
        try{
                system.debug('EmailTemplateID '+EmailTemplateID+ ' bookingID '+bookingID+ ' OtherID '+ OtherID);
                List<booking__c> bookinglist = new list<booking__c>();
                List<Co_Applicant__c> coAppList = new List<Co_Applicant__c>();
                bookinglist =[select id,Primary_Applicant__r.personcontactid from booking__c where id=:bookingID];
                system.debug('bookinglist sms=='+bookinglist);
                coAppList = [select id,Account__c,Booking__c,Account__r.PersonEmail from Co_Applicant__c where Booking__c =:bookingID];  
                
                Set<ID> Accids = new Set<ID>();
                for(Co_Applicant__c coapp :coAppList)
                {
                    Accids.add(coapp.Account__c);
                } 
                system.debug('Accids '+Accids);
                List<Contact> cclist1 = [select id,MobilePhone,Phone,Email from Contact where AccountId IN : Accids];
        		List<account> cclist = [select id,PersonMobilePhone,Phone,PersonEmail from account where id IN : Accids];
                system.debug('cclist '+ cclist.size());
            	List<communicat_o.OutboundWrapper.OutboundActivity> liact = new List<communicat_o.OutboundWrapper.OutboundActivity>();
                  for(account cc : cclist)
                    {
                         if(cc.PersonMobilePhone!=null)
                         {
                            communicat_o.OutboundWrapper.OutboundActivity acti = new communicat_o.OutboundWrapper.OutboundActivity();
                            acti.recipientAddress = cc.PersonMobilePhone;
                            acti.recipientId = cc.Id;
                            acti.relatedToId = bookingID;
                            liact.add(acti);
                            
                        }
                 	}
            				communicat_o.OutboundWrapper out= new communicat_o.OutboundWrapper();
                            out.activities=liact;
                            out.sendDateTime=datetime.now();
                            out.templateId= EmailTemplateID;
                            out.senderAddress= 'Dynamix_919152915208';
            				if(!Test.isRunningTest()){
                            communicat_o.OSMS.sendSMS(out);
                            }
                            system.debug('Whatsapp send');
             }        
            Catch(Exception e)
            {
                system.debug('==> e'  + e.getMessage()+e.getLineNumber());
            }
    }
     @future(callout=true)
    public static void sendwhsmsForPayment(string EmailTemplateID ,string bookingID ,string OtherID)
    {
                system.debug('EmailTemplateID '+EmailTemplateID+ ' bookingID '+bookingID+ ' OtherID '+ OtherID);
                List<Payment__c > paymnetList = [select id,Booking__r.Primary_Applicant__c from payment__c where id =: OtherID];
                List<account> accList = [select id,PersonMobilePhone from account where id=: paymnetList[0].Booking__r.Primary_Applicant__c];
        
                         if(accList[0].PersonMobilePhone <> null)
                         {
                            communicat_o.OutboundWrapper.OutboundActivity acti = new communicat_o.OutboundWrapper.OutboundActivity();
                            acti.recipientAddress = accList[0].PersonMobilePhone;
                            acti.recipientId = accList[0].id;
                            acti.relatedToId = OtherID;
                            List<communicat_o.OutboundWrapper.OutboundActivity> liact = new List<communicat_o.OutboundWrapper.OutboundActivity>();
                            liact.add(acti);
                            communicat_o.OutboundWrapper out= new communicat_o.OutboundWrapper();
                            out.activities=liact;
                            out.sendDateTime=datetime.now();
                            out.templateId= EmailTemplateID;
                            out.senderAddress= 'Dynamix_919152915208';
                             if(!Test.isRunningTest()){
                                  communicat_o.OSMS.sendSMS(out);
                             }
                           
                            system.debug('Whatsapp send');
                        } 
    }
    public class sendSMSInvocableRequest
    {
        @InvocableVariable(required=true)
        public ID bookingID;
    
        @InvocableVariable(required=true)
        public String emailTemplateID;
        
        @InvocableVariable(required=true)
        public String recipientId;
    }

}