dynamix/force-app/main/default/objects/ReceiptNumber__c/ReceiptNumber__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payment Receipt Number</label>
</CustomObject>

dynamix/force-app/main/default/objects/ReceiptNumber__c/fields/LastReceiptNumber__c.field-meta.xml
<CustomField>
    <fullName>LastReceiptNumber__c</fullName>
    <defaultValue>40000</defaultValue>
    <label>LastReceiptNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/classes/PaymentReceiptNumber.cls
public class PaymentReceiptNumber {

    @InvocableMethod(label='Increment Receipt Number ')
    public static List<decimal> incrementNumber()
    {
        List<decimal> currentReceiptNumber = new List<decimal>();
        ReceiptNumber__c ct = ReceiptNumber__c.getOrgDefaults();
        currentReceiptNumber.add(ct.LastReceiptNumber__c);
        ct.LastReceiptNumber__c += 1;
        update ct;
        
        return currentReceiptNumber;
    }
}