dynamix/force-app/main/default/objects/ReceiptNumber__c/ReceiptNumber__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payment Receipt Number</label>
</CustomObject>

dynamix/force-app/main/default/objects/ReceiptNumber__c/fields/EOI_CA_Number__c.field-meta.xml
<CustomField>
    <fullName>EOI_CA_Number__c</fullName>
    <label>EOI/CA Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dynamix/force-app/main/default/classes/EOI_CA_Number.cls
public class EOI_CA_Number {
    @InvocableMethod(label='Increment EOI/CA Number')
    public static List<decimal> incrementNumber()
    {
        List<decimal> currentReceiptNumber = new List<decimal>();
        ReceiptNumber__c ct = ReceiptNumber__c.getOrgDefaults();
        currentReceiptNumber.add(ct.EOI_CA_Number__c);
        ct.EOI_CA_Number__c += 1;
        update ct;
        
        return currentReceiptNumber;
    }
    
}